// Code generated by gogen from fixture.json (module Main). DO NOT EDIT.

package fixture

type I_comparison struct {
	tag uint8
}

var C_Eq = &I_comparison{tag: 0}
var C_Lt = &I_comparison{tag: 1}
var C_Gt = &I_comparison{tag: 2}

// K_Eq builds the constructor Eq.
func K_Eq() *I_comparison {
	return &I_comparison{tag: 0}
}

// K_Lt builds the constructor Lt.
func K_Lt() *I_comparison {
	return &I_comparison{tag: 1}
}

// K_Gt builds the constructor Gt.
func K_Gt() *I_comparison {
	return &I_comparison{tag: 2}
}

type I_list[P_A any] struct {
	tag  uint8
	f1_0 P_A
	f1_1 *I_list[P_A]
}

// K_Nil builds the constructor Nil.
func K_Nil[P_A any]() *I_list[P_A] {
	return &I_list[P_A]{tag: 0}
}

// K_Cons builds the constructor Cons.
func K_Cons[P_A any](a0 P_A, a1 *I_list[P_A]) *I_list[P_A] {
	return &I_list[P_A]{tag: 1, f1_0: a0, f1_1: a1}
}

type I_prod[P_A any, P_B any] struct {
	tag  uint8
	f0_0 P_A
	f0_1 P_B
}

// K_Pair builds the constructor Pair.
func K_Pair[P_A any, P_B any](a0 P_A, a1 P_B) *I_prod[P_A, P_B] {
	return &I_prod[P_A, P_B]{tag: 0, f0_0: a0, f0_1: a1}
}

func F_fx_closures(n_in int64) *I_list[int64] {
	for {
		n_1 := n_in
		_ = n_1
		t_4 := func(f_2 func(int64) int64) int64 {
			_ = f_2
			t_3 := f_2(int64(0))
			return t_3
		}
		t_5 := &I_list[func(int64) int64]{tag: 0}
		t_6 := F_fx_mkfs(n_1, t_5)
		t_7 := F_map[func(int64) int64, int64](t_4, t_6)
		return t_7
	}
}

func F_fx_let(n_in int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		t_2 := zAdd(n_1, n_1)
		m_3 := t_2
		_ = m_3
		t_4 := zMul(m_3, m_3)
		t_5 := natSucc(t_4)
		return t_5
	}
}

func F_fx_list_wild(l_in *I_list[int64]) int64 {
	for {
		l_1 := l_in
		_ = l_1
		switch l_1.tag {
		case 0:
			return int64(0)
		case 1:
			return int64(1)
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_fx_mkfs(n_in int64, acc_in *I_list[func(int64) int64]) *I_list[func(int64) int64] {
	for {
		n_1 := n_in
		_ = n_1
		acc_2 := acc_in
		_ = acc_2
		if n_1 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case n_1 == 0:
			return acc_2
		case n_1 > 0:
			k_3 := n_1 - 1
			_ = k_3
			t_6 := func(x_4 int64) int64 {
				_ = x_4
				t_5 := zAdd(x_4, n_1)
				return t_5
			}
			t_7 := &I_list[func(int64) int64]{tag: 1, f1_0: t_6, f1_1: acc_2}
			n_in, acc_in = k_3, t_7
			continue
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_fx_nat_wild(n_in int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		if n_1 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case n_1 == 0:
			return int64(0)
		case n_1 > 0:
			n0_2 := n_1 - 1
			_ = n0_2
			if n0_2 < 0 {
				panic("gogen: not a nat")
			}
			switch {
			case n0_2 == 0:
				return int64(0)
			case n0_2 > 0:
				n1_3 := n0_2 - 1
				_ = n1_3
				if n1_3 < 0 {
					panic("gogen: not a nat")
				}
				switch {
				case n1_3 == 0:
					return int64(0)
				case n1_3 > 0:
					n2_4 := n1_3 - 1
					_ = n2_4
					if n2_4 < 0 {
						panic("gogen: not a nat")
					}
					switch {
					case n2_4 == 0:
						return int64(1)
					case n2_4 > 0:
						__5 := n2_4 - 1
						_ = __5
						return int64(0)
					default:
						panic("gogen: no case matches")
					}
				default:
					panic("gogen: no case matches")
				}
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_fx_over(n_in int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		t_2 := F_fx_pick(true, n_1)
		t_3 := F_fx_pick(false, n_1)
		t_4 := zAdd(t_2, t_3)
		return t_4
	}
}

func F_fx_partial(l_in *I_list[int64]) *I_list[*I_prod[int64, int64]] {
	for {
		l_1 := l_in
		_ = l_1
		t_4 := func(x_2 int64) *I_prod[int64, int64] {
			_ = x_2
			t_3 := &I_prod[int64, int64]{tag: 0, f0_0: int64(7), f0_1: x_2}
			return t_3
		}
		t_6 := func(a_5 int64) int64 {
			return zAdd(int64(2), a_5)
		}
		t_7 := F_map[int64, int64](t_6, l_1)
		t_8 := F_map[int64, *I_prod[int64, int64]](t_4, t_7)
		return t_8
	}
}

func F_fx_pick(b_in bool, x_in int64) int64 {
	for {
		b_1 := b_in
		_ = b_1
		x_2 := x_in
		_ = x_2
		switch {
		case b_1:
			t_3 := natSucc(x_2)
			return t_3
		case !b_1:
			return x_2
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_fx_pos_rel(p_in int64) int64 {
	for {
		p_1 := p_in
		_ = p_1
		if p_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case p_1 > 1 && p_1%2 == 1:
			__2 := p_1 / 2
			_ = __2
			t_3 := natSucc(p_1)
			return t_3
		case p_1 > 1 && p_1%2 == 0:
			__4 := p_1 / 2
			_ = __4
			t_5 := natSucc(p_1)
			return t_5
		case p_1 == 1:
			return int64(1)
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_fx_z_wild(z_in int64) int64 {
	for {
		z_1 := z_in
		_ = z_1
		switch {
		case z_1 == 0:
			return int64(0)
		case z_1 > 0:
			__2 := z_1
			_ = __2
			return int64(1)
		case z_1 < 0:
			__3 := zOpp(z_1)
			_ = __3
			return int64(2)
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_map[T1 any, T2 any](f_in func(T1) T2, l_in *I_list[T1]) *I_list[T2] {
	for {
		f_1 := f_in
		_ = f_1
		l_2 := l_in
		_ = l_2
		switch l_2.tag {
		case 0:
			t_3 := &I_list[T2]{tag: 0}
			return t_3
		case 1:
			a_4 := l_2.f1_0
			_ = a_4
			l0_5 := l_2.f1_1
			_ = l0_5
			t_6 := f_1(a_4)
			t_7 := F_map[T1, T2](f_1, l0_5)
			t_8 := &I_list[T2]{tag: 1, f1_0: t_6, f1_1: t_7}
			return t_8
		default:
			panic("gogen: no case matches")
		}
	}
}

// ===== the Go meaning of ExtrGo.v's symbols (gogen prims.go) =====

const minInt64 = -1 << 63

func zAdd(a, b int64) int64 {
	r := a + b
	if (a > 0 && b > 0 && r < 0) || (a < 0 && b < 0 && r >= 0) {
		panic("gogen: int64 overflow in add")
	}
	return r
}

func zSub(a, b int64) int64 {
	r := a - b
	if (b < 0 && r < a) || (b > 0 && r > a) {
		panic("gogen: int64 overflow in sub")
	}
	return r
}

func zMul(a, b int64) int64 {
	if a == 0 || b == 0 {
		return 0
	}
	r := a * b
	if r/b != a || (a == -1 && b == minInt64) || (b == -1 && a == minInt64) {
		panic("gogen: int64 overflow in mul")
	}
	return r
}

func zOpp(a int64) int64 {
	if a == minInt64 {
		panic("gogen: int64 overflow in opp")
	}
	return -a
}

func zAbs(a int64) int64 {
	if a < 0 {
		return zOpp(a)
	}
	return a
}

func zSucc(a int64) int64   { return zAdd(a, 1) }
func zPred(a int64) int64   { return zSub(a, 1) }
func natSucc(a int64) int64 { return zAdd(a, 1) }
func posXI(p int64) int64   { return zAdd(zMul(2, p), 1) }
func posXO(p int64) int64   { return zMul(2, p) }

func natSub(a, b int64) int64 {
	if a <= b {
		return 0
	}
	return a - b
}

func posSub(a, b int64) int64 {
	if a <= b {
		return 1
	}
	return a - b
}

func posPred(a int64) int64 {
	if a <= 1 {
		return 1
	}
	return a - 1
}

func nPred(a int64) int64 {
	if a <= 0 {
		return 0
	}
	return a - 1
}

func nDiv(a, b int64) int64 {
	if b == 0 {
		return 0
	}
	return a / b
}

func nModulo(a, b int64) int64 {
	if b == 0 {
		return a
	}
	return a % b
}

func natDiv2(a int64) int64 { return a / 2 }

func min64(a, b int64) int64 {
	if a < b {
		return a
	}
	return b
}

func max64(a, b int64) int64 {
	if a > b {
		return a
	}
	return b
}

func id64(a int64) int64 { return a }

func eqb(a, b int64) bool { return a == b }

func ltb(a, b int64) bool { return a < b }

func leb(a, b int64) bool { return a <= b }

func compare(a, b int64) *I_comparison {
	if a == b {
		return C_Eq
	}
	if a < b {
		return C_Lt
	}
	return C_Gt
}

func compareCont(c *I_comparison, a, b int64) *I_comparison {
	if a == b {
		return c
	}
	return compare(a, b)
}
