(* CohomologyGraph.v: the completion theorem and the cycle-basis criterion on an ARBITRARY finite
   group-labeled graph, mechanized axiom-free. Cohomology.v proves the single-cycle essence
   (a section exists iff the holonomy is trivial) and the bouquet form; CohomologyMin.v proves the
   S_3 theta-graph counts. This file lifts the completion to general graphs:

   - section_iff_coboundary (Thm 7.2, any graph, any group): a global section exists iff the edge
     labeling is a coboundary, g = h(v) h(u)^-1 on every edge.
   - tree_has_section (Prop 9.1, "coordinating a cycle basis suffices"): a spanning tree always
     carries a section, so deleting every non-tree edge always restores convergence.
   - tree_unique: on a tree grown from a root, sections are unique up to one right constant.
   - cycle_basis_criterion: for a spanning tree T plus extra (non-tree) edges X, the whole graph
     has a section iff every extra edge is balanced against the tree's section, that is, iff every
     fundamental cycle has trivial holonomy (sat_iff_trivial_holonomy). So the obstruction is
     generated by the fundamental cycles of any spanning tree.
   - keep_balanced_suffices / unbalanced_blocks: relative to a fixed spanning tree, the edges that
     must be coordinated are exactly the unbalanced fundamental edges.

   The group is abstract (associativity, identity, inverses as section hypotheses, the same style as
   Cohomology.v), and the group laws are discharged by a concrete Z/2 instance at the end, so the
   results are not vacuous. Choosing the spanning tree that minimizes the coordinated set is the
   group feedback edge set problem, whose complexity is a known result cited at the paper level. *)

From Coq Require Import List Arith Bool.
Import ListNotations.

Section GeneralGraph.
  Context {G : Type}.
  Variables (op : G -> G -> G) (e : G) (inv : G -> G).
  Hypothesis assoc : forall a b c, op a (op b c) = op (op a b) c.
  Hypothesis id_l  : forall a, op e a = a.
  Hypothesis id_r  : forall a, op a e = a.
  Hypothesis inv_r : forall a, op a (inv a) = e.
  Hypothesis inv_l : forall a, op (inv a) a = e.

  (* An edge u -> v carrying the transition g: it transports the fiber value at u to the one at v. *)
  Definition edge : Type := (nat * nat * G)%type.

  Definition sat (s : nat -> G) (x : edge) : Prop :=
    let '(u, v, g) := x in op g (s u) = s v.

  Definition is_section (s : nat -> G) (es : list edge) : Prop :=
    forall x, In x es -> sat s x.

  Definition has_section (es : list edge) : Prop := exists s, is_section s es.

  Definition coboundary (es : list edge) : Prop :=
    exists h : nat -> G, forall u v g, In (u, v, g) es -> g = op (h v) (inv (h u)).

  (* ----- small group facts ----- *)

  Lemma left_solve : forall g x y, op g x = y -> x = op (inv g) y.
  Proof. intros g x y H. rewrite <- H, assoc, inv_l, id_l. reflexivity. Qed.

  Lemma right_cancel : forall a b c, op a c = op b c -> a = b.
  Proof.
    intros a b c H.
    transitivity (op (op a c) (inv c)).
    - rewrite <- assoc, inv_r, id_r. reflexivity.
    - rewrite H, <- assoc, inv_r, id_r. reflexivity.
  Qed.

  (* An edge is balanced against s exactly when the holonomy s(v)^-1 g s(u) of its loop is trivial. *)
  Lemma sat_iff_trivial_holonomy :
    forall s u v g, sat s (u, v, g) <-> op (inv (s v)) (op g (s u)) = e.
  Proof.
    intros s u v g. unfold sat. split.
    - intro H. rewrite H. apply inv_l.
    - intro H.
      transitivity (op (op (s v) (inv (s v))) (op g (s u))).
      + rewrite inv_r, id_l. reflexivity.
      + rewrite <- assoc, H, id_r. reflexivity.
  Qed.

  (* ----- Thm 7.2 on an arbitrary graph ----- *)

  Theorem section_iff_coboundary : forall es, has_section es <-> coboundary es.
  Proof.
    intro es. split.
    - intros [s Hs]. exists s. intros u v g Hin.
      pose proof (Hs _ Hin) as E. unfold sat in E.
      rewrite <- E, <- assoc, inv_r, id_r. reflexivity.
    - intros [h Hh]. exists h. intros [[u v] g] Hin. unfold sat.
      rewrite (Hh u v g Hin), <- assoc, inv_l, id_r. reflexivity.
  Qed.

  (* ----- vertices, restriction, update ----- *)

  Fixpoint verts (es : list edge) : list nat :=
    match es with
    | [] => []
    | (u, v, _) :: t => u :: v :: verts t
    end.

  Lemma verts_app : forall a b, verts (a ++ b) = verts a ++ verts b.
  Proof.
    induction a as [| [[u v] g] t IH]; intro b; simpl; [reflexivity | rewrite IH; reflexivity].
  Qed.

  Lemma in_verts_edge :
    forall es u v g, In (u, v, g) es -> In u (verts es) /\ In v (verts es).
  Proof.
    induction es as [| [[a b] h] t IH]; intros u v g H; simpl in *; [contradiction |].
    destruct H as [H | H].
    - injection H as Ea Eb Eh. subst. split; [left | right; left]; reflexivity.
    - destruct (IH u v g H) as [Hu Hv]. split; right; right; assumption.
  Qed.

  Lemma section_app :
    forall s a b, is_section s (a ++ b) <-> is_section s a /\ is_section s b.
  Proof.
    intros s a b. unfold is_section. split.
    - intro H. split; intros x Hx; apply H; apply in_or_app; [left | right]; exact Hx.
    - intros [Ha Hb] x Hx. apply in_app_or in Hx. destruct Hx as [Hx | Hx];
        [apply Ha | apply Hb]; exact Hx.
  Qed.

  Definition upd (s : nat -> G) (w : nat) (x : G) : nat -> G :=
    fun z => if Nat.eq_dec z w then x else s z.

  Lemma upd_other : forall s w x z, z <> w -> upd s w x z = s z.
  Proof. intros s w x z H. unfold upd. destruct (Nat.eq_dec z w); [contradiction | reflexivity]. Qed.

  Lemma upd_same : forall s w x, upd s w x w = x.
  Proof. intros s w x. unfold upd. destruct (Nat.eq_dec w w); [reflexivity | contradiction]. Qed.

  Lemma section_upd_fresh :
    forall s es w x, is_section s es -> ~ In w (verts es) -> is_section (upd s w x) es.
  Proof.
    intros s es w x Hs Hw [[a b] h] Hin.
    destruct (in_verts_edge es a b h Hin) as [Ha Hb].
    assert (Na : a <> w) by (intro E; subst; contradiction).
    assert (Nb : b <> w) by (intro E; subst; contradiction).
    pose proof (Hs _ Hin) as E. unfold sat in *.
    rewrite (upd_other s w x a Na), (upd_other s w x b Nb). exact E.
  Qed.

  (* ----- spanning trees grown from a root ----- *)

  (* A tree rooted at r: each new edge attaches exactly one fresh vertex, in either direction. *)
  Inductive tree (r : nat) : list edge -> Prop :=
  | t_nil : tree r []
  | t_out : forall es u v g,
      tree r es -> In u (r :: verts es) -> ~ In v (r :: verts es) ->
      tree r (es ++ [(u, v, g)])
  | t_in : forall es u v g,
      tree r es -> In v (r :: verts es) -> ~ In u (r :: verts es) ->
      tree r (es ++ [(u, v, g)]).

  (* Prop 9.1: a tree always carries a section, so coordinating every non-tree edge suffices. *)
  Theorem tree_has_section : forall r es, tree r es -> has_section es.
  Proof.
    intros r es T. induction T as [| es u v g T IH Hu Hv | es u v g T IH Hv Hu].
    - exists (fun _ => e). intros x [].
    - destruct IH as [s Hs]. exists (upd s v (op g (s u))).
      apply section_app. split.
      + apply section_upd_fresh; [exact Hs |]. intro H. apply Hv. right. exact H.
      + intros x [<- | []]. unfold sat.
        rewrite upd_same, upd_other; [reflexivity |].
        intro E. subst. apply Hv. exact Hu.
    - destruct IH as [s Hs]. exists (upd s u (op (inv g) (s v))).
      apply section_app. split.
      + apply section_upd_fresh; [exact Hs |]. intro H. apply Hu. right. exact H.
      + intros x [<- | []]. unfold sat.
        rewrite upd_same, upd_other; [| intro E; subst; apply Hu; exact Hv].
        rewrite assoc, inv_r, id_l. reflexivity.
  Qed.

  (* Classify a vertex of an extended tree: old, or the freshly attached one. *)
  Lemma verts_snoc :
    forall r es u v g w, In w (r :: verts (es ++ [(u, v, g)])) ->
      In w (r :: verts es) \/ w = u \/ w = v.
  Proof.
    intros r es u v g w Hw. rewrite verts_app in Hw. simpl in Hw.
    destruct Hw as [Hw | Hw]; [left; left; exact Hw |].
    apply in_app_or in Hw. destruct Hw as [Hw | Hw]; [left; right; exact Hw |].
    destruct Hw as [Hw | [Hw | []]]; right; [left | right]; symmetry; exact Hw.
  Qed.

  (* Sections of a tree are unique up to a single right constant c = s(r)^-1 t(r). *)
  Theorem tree_unique :
    forall r es, tree r es ->
    forall s t, is_section s es -> is_section t es ->
    forall w, In w (r :: verts es) -> t w = op (s w) (op (inv (s r)) (t r)).
  Proof.
    intros r es T. induction T as [| es u v g T IH Hu Hv | es u v g T IH Hv Hu];
      intros s t Hs Ht w Hw.
    - simpl in Hw. destruct Hw as [<- | []]. rewrite assoc, inv_r, id_l. reflexivity.
    - destruct (proj1 (section_app _ _ _) Hs) as [Hs1 Hsx].
      destruct (proj1 (section_app _ _ _) Ht) as [Ht1 Htx].
      pose proof (Hsx (u, v, g) (or_introl eq_refl)) as Es.
      pose proof (Htx (u, v, g) (or_introl eq_refl)) as Et.
      unfold sat in Es, Et.
      destruct (verts_snoc r es u v g w Hw) as [Hold | [-> | ->]].
      + apply IH; assumption.
      + apply IH; assumption.
      + rewrite <- Et, <- Es, (IH s t Hs1 Ht1 u Hu). apply assoc.
    - destruct (proj1 (section_app _ _ _) Hs) as [Hs1 Hsx].
      destruct (proj1 (section_app _ _ _) Ht) as [Ht1 Htx].
      pose proof (Hsx (u, v, g) (or_introl eq_refl)) as Es.
      pose proof (Htx (u, v, g) (or_introl eq_refl)) as Et.
      unfold sat in Es, Et.
      destruct (verts_snoc r es u v g w Hw) as [Hold | [-> | ->]].
      + apply IH; assumption.
      + rewrite (left_solve _ _ _ Et), (left_solve _ _ _ Es), (IH s t Hs1 Ht1 v Hv).
        apply assoc.
      + apply IH; assumption.
  Qed.

  (* ----- the cycle-basis criterion ----- *)

  (* For a spanning tree T with section sT, plus extra edges X among T's vertices: the whole graph
     has a global section iff every extra edge is balanced against sT, i.e. iff every fundamental
     cycle (an extra edge closed through the tree) has trivial holonomy. *)
  Theorem cycle_basis_criterion :
    forall r T X sT,
      tree r T -> is_section sT T ->
      (forall u v g, In (u, v, g) X -> In u (r :: verts T) /\ In v (r :: verts T)) ->
      (has_section (T ++ X) <-> forall x, In x X -> sat sT x).
  Proof.
    intros r T X sT HT HsT Hspan. split.
    - intros [s Hs] [[u v] g] Hx.
      destruct (proj1 (section_app _ _ _) Hs) as [HsT' HsX].
      pose proof (HsX _ Hx) as E. unfold sat in E |- *.
      destruct (Hspan u v g Hx) as [Hu Hv].
      rewrite (tree_unique r T HT sT s HsT HsT' u Hu),
              (tree_unique r T HT sT s HsT HsT' v Hv) in E.
      rewrite (assoc g (sT u)) in E. exact (right_cancel _ _ _ E).
    - intro Hbal. exists sT. apply section_app. split; [exact HsT |].
      intros x Hx. exact (Hbal x Hx).
  Qed.

  (* Keeping only balanced fundamental edges always leaves a section. *)
  Corollary keep_balanced_suffices :
    forall T X sT, is_section sT T -> (forall x, In x X -> sat sT x) -> has_section (T ++ X).
  Proof.
    intros T X sT HsT Hbal. exists sT. apply section_app. split; [exact HsT |].
    intros x Hx. exact (Hbal x Hx).
  Qed.

  (* Keeping any unbalanced fundamental edge destroys every section: it must be coordinated. *)
  Corollary unbalanced_blocks :
    forall r T X sT x,
      tree r T -> is_section sT T ->
      (forall u v g, In (u, v, g) X -> In u (r :: verts T) /\ In v (r :: verts T)) ->
      In x X -> ~ sat sT x -> ~ has_section (T ++ X).
  Proof.
    intros r T X sT x HT HsT Hspan Hx Hnot H.
    apply Hnot. exact (proj1 (cycle_basis_criterion r T X sT HT HsT Hspan) H x Hx).
  Qed.
End GeneralGraph.

(* ============================================================
   Non-vacuity: the group Z/2 (bool, xor) discharges every group hypothesis, and a triangle shows
   the criterion firing both ways. Spanning tree 0 -> 1 -> 2 with identity labels; the closing edge
   2 -> 0 either carries the identity (balanced: a section exists) or the flip (unbalanced: no
   section, the minimal nonzero obstruction). Axiom-free.
   ============================================================ *)

Lemma xor_assoc : forall a b c, xorb a (xorb b c) = xorb (xorb a b) c.
Proof. destruct a, b, c; reflexivity. Qed.
Lemma xor_id_l : forall a, xorb false a = a. Proof. destruct a; reflexivity. Qed.
Lemma xor_id_r : forall a, xorb a false = a. Proof. destruct a; reflexivity. Qed.
Lemma xor_inv_r : forall a, xorb a a = false. Proof. destruct a; reflexivity. Qed.
Lemma xor_inv_l : forall a, xorb a a = false. Proof. destruct a; reflexivity. Qed.

Definition triT : list (@edge bool) := ([] ++ [(0, 1, false)]) ++ [(1, 2, false)].

Lemma triT_tree : tree 0 triT.
Proof.
  unfold triT. apply t_out.
  - apply t_out; [apply t_nil | left; reflexivity | simpl; intuition congruence].
  - simpl. right. right. left. reflexivity.
  - simpl. intuition congruence.
Qed.

Definition sT0 : nat -> bool := fun _ => false.

Lemma triT_section : is_section xorb sT0 triT.
Proof.
  unfold triT. intros [[u v] g] H. simpl in H.
  destruct H as [H | [H | []]]; injection H as Eu Ev Eg; subst; reflexivity.
Qed.

Lemma tri_span :
  forall (b : bool) (u v : nat) (g : bool),
    In (u, v, g) [(2, 0, b)] -> In u (0 :: verts triT) /\ In v (0 :: verts triT).
Proof.
  intros b u v g [H | []]. injection H as Eu Ev Eg. subst. simpl. split.
  - right. right. right. right. left. reflexivity.
  - left. reflexivity.
Qed.

(* Closing the triangle with the identity: balanced, so a global section exists. *)
Example tri_identity_has_section : has_section xorb (triT ++ [(2, 0, false)]).
Proof.
  apply (keep_balanced_suffices xorb triT [(2, 0, false)] sT0 triT_section).
  intros x [<- | []]. reflexivity.
Qed.

(* Closing it with the flip: unbalanced, so no global section, by the general criterion. *)
Example tri_flip_no_section : ~ has_section xorb (triT ++ [(2, 0, true)]).
Proof.
  apply (unbalanced_blocks xorb false (fun a => a) xor_assoc xor_id_l xor_id_r xor_inv_r xor_inv_l
           0 triT [(2, 0, true)] sT0 (2, 0, true)
           triT_tree triT_section (tri_span true)).
  - left. reflexivity.
  - unfold sat, sT0. simpl. discriminate.
Qed.
