(* CohomologyGraph.v: the completion theorem and the cycle-basis criterion on an ARBITRARY finite
   group-labeled graph, mechanized axiom-free. Cohomology.v proves the single-cycle essence
   (a section exists iff the holonomy is trivial) and the bouquet form; CohomologyMin.v proves the
   S_3 theta-graph counts. This file lifts the completion to general graphs:

   - section_iff_coboundary (Thm 7.2, any graph, any group): a global section exists iff the edge
     labeling is a coboundary, g = h(v) h(u)^-1 on every edge.
   - tree_has_section (Prop 9.1, "coordinating a cycle basis suffices"): a spanning tree always
     carries a section, so deleting every non-tree edge always restores convergence.
   - tree_unique: on a tree grown from a root, sections are unique up to one right constant.
   - cycle_basis_criterion: for a spanning tree T plus extra (non-tree) edges X, the whole graph
     has a section iff every extra edge is balanced against the tree's section, that is, iff every
     fundamental cycle has trivial holonomy (sat_iff_trivial_holonomy). So the obstruction is
     generated by the fundamental cycles of any spanning tree.
   - keep_balanced_suffices / unbalanced_blocks: relative to a fixed spanning tree, the edges that
     must be coordinated are exactly the unbalanced fundamental edges.

   The group is abstract (associativity, identity, inverses as section hypotheses, the same style as
   Cohomology.v), and the group laws are discharged by a concrete Z/2 instance at the end, so the
   results are not vacuous. Choosing the spanning tree that minimizes the coordinated set is the
   group feedback edge set problem, whose complexity is a known result cited at the paper level. *)

From Coq Require Import List Arith Bool Lia.
From Coq Require Import Sorting.Permutation.
Import ListNotations.

Section GeneralGraph.
  Context {G : Type}.
  Variables (op : G -> G -> G) (e : G) (inv : G -> G).
  Hypothesis assoc : forall a b c, op a (op b c) = op (op a b) c.
  Hypothesis id_l  : forall a, op e a = a.
  Hypothesis id_r  : forall a, op a e = a.
  Hypothesis inv_r : forall a, op a (inv a) = e.
  Hypothesis inv_l : forall a, op (inv a) a = e.

  (* An edge u -> v carrying the transition g: it transports the fiber value at u to the one at v. *)
  Definition edge : Type := (nat * nat * G)%type.

  Definition sat (s : nat -> G) (x : edge) : Prop :=
    let '(u, v, g) := x in op g (s u) = s v.

  Definition is_section (s : nat -> G) (es : list edge) : Prop :=
    forall x, In x es -> sat s x.

  Definition has_section (es : list edge) : Prop := exists s, is_section s es.

  Definition coboundary (es : list edge) : Prop :=
    exists h : nat -> G, forall u v g, In (u, v, g) es -> g = op (h v) (inv (h u)).

  (* ----- small group facts ----- *)

  Lemma left_solve : forall g x y, op g x = y -> x = op (inv g) y.
  Proof. intros g x y H. rewrite <- H, assoc, inv_l, id_l. reflexivity. Qed.

  Lemma right_cancel : forall a b c, op a c = op b c -> a = b.
  Proof.
    intros a b c H.
    transitivity (op (op a c) (inv c)).
    - rewrite <- assoc, inv_r, id_r. reflexivity.
    - rewrite H, <- assoc, inv_r, id_r. reflexivity.
  Qed.

  (* An edge is balanced against s exactly when the holonomy s(v)^-1 g s(u) of its loop is trivial. *)
  Lemma sat_iff_trivial_holonomy :
    forall s u v g, sat s (u, v, g) <-> op (inv (s v)) (op g (s u)) = e.
  Proof.
    intros s u v g. unfold sat. split.
    - intro H. rewrite H. apply inv_l.
    - intro H.
      transitivity (op (op (s v) (inv (s v))) (op g (s u))).
      + rewrite inv_r, id_l. reflexivity.
      + rewrite <- assoc, H, id_r. reflexivity.
  Qed.

  (* ----- Thm 7.2 on an arbitrary graph ----- *)

  Theorem section_iff_coboundary : forall es, has_section es <-> coboundary es.
  Proof.
    intro es. split.
    - intros [s Hs]. exists s. intros u v g Hin.
      pose proof (Hs _ Hin) as E. unfold sat in E.
      rewrite <- E, <- assoc, inv_r, id_r. reflexivity.
    - intros [h Hh]. exists h. intros [[u v] g] Hin. unfold sat.
      rewrite (Hh u v g Hin), <- assoc, inv_l, id_r. reflexivity.
  Qed.

  (* ----- vertices, restriction, update ----- *)

  Fixpoint verts (es : list edge) : list nat :=
    match es with
    | [] => []
    | (u, v, _) :: t => u :: v :: verts t
    end.

  Lemma verts_app : forall a b, verts (a ++ b) = verts a ++ verts b.
  Proof.
    induction a as [| [[u v] g] t IH]; intro b; simpl; [reflexivity | rewrite IH; reflexivity].
  Qed.

  Lemma in_verts_edge :
    forall es u v g, In (u, v, g) es -> In u (verts es) /\ In v (verts es).
  Proof.
    induction es as [| [[a b] h] t IH]; intros u v g H; simpl in *; [contradiction |].
    destruct H as [H | H].
    - injection H as Ea Eb Eh. subst. split; [left | right; left]; reflexivity.
    - destruct (IH u v g H) as [Hu Hv]. split; right; right; assumption.
  Qed.

  Lemma section_app :
    forall s a b, is_section s (a ++ b) <-> is_section s a /\ is_section s b.
  Proof.
    intros s a b. unfold is_section. split.
    - intro H. split; intros x Hx; apply H; apply in_or_app; [left | right]; exact Hx.
    - intros [Ha Hb] x Hx. apply in_app_or in Hx. destruct Hx as [Hx | Hx];
        [apply Ha | apply Hb]; exact Hx.
  Qed.

  Definition upd (s : nat -> G) (w : nat) (x : G) : nat -> G :=
    fun z => if Nat.eq_dec z w then x else s z.

  Lemma upd_other : forall s w x z, z <> w -> upd s w x z = s z.
  Proof. intros s w x z H. unfold upd. destruct (Nat.eq_dec z w); [contradiction | reflexivity]. Qed.

  Lemma upd_same : forall s w x, upd s w x w = x.
  Proof. intros s w x. unfold upd. destruct (Nat.eq_dec w w); [reflexivity | contradiction]. Qed.

  Lemma section_upd_fresh :
    forall s es w x, is_section s es -> ~ In w (verts es) -> is_section (upd s w x) es.
  Proof.
    intros s es w x Hs Hw [[a b] h] Hin.
    destruct (in_verts_edge es a b h Hin) as [Ha Hb].
    assert (Na : a <> w) by (intro E; subst; contradiction).
    assert (Nb : b <> w) by (intro E; subst; contradiction).
    pose proof (Hs _ Hin) as E. unfold sat in *.
    rewrite (upd_other s w x a Na), (upd_other s w x b Nb). exact E.
  Qed.

  (* ----- spanning trees grown from a root ----- *)

  (* A tree rooted at r: each new edge attaches exactly one fresh vertex, in either direction. *)
  Inductive tree (r : nat) : list edge -> Prop :=
  | t_nil : tree r []
  | t_out : forall es u v g,
      tree r es -> In u (r :: verts es) -> ~ In v (r :: verts es) ->
      tree r (es ++ [(u, v, g)])
  | t_in : forall es u v g,
      tree r es -> In v (r :: verts es) -> ~ In u (r :: verts es) ->
      tree r (es ++ [(u, v, g)]).

  (* Prop 9.1: a tree always carries a section, so coordinating every non-tree edge suffices. *)
  Theorem tree_has_section : forall r es, tree r es -> has_section es.
  Proof.
    intros r es T. induction T as [| es u v g T IH Hu Hv | es u v g T IH Hv Hu].
    - exists (fun _ => e). intros x [].
    - destruct IH as [s Hs]. exists (upd s v (op g (s u))).
      apply section_app. split.
      + apply section_upd_fresh; [exact Hs |]. intro H. apply Hv. right. exact H.
      + intros x [<- | []]. unfold sat.
        rewrite upd_same, upd_other; [reflexivity |].
        intro E. subst. apply Hv. exact Hu.
    - destruct IH as [s Hs]. exists (upd s u (op (inv g) (s v))).
      apply section_app. split.
      + apply section_upd_fresh; [exact Hs |]. intro H. apply Hu. right. exact H.
      + intros x [<- | []]. unfold sat.
        rewrite upd_same, upd_other; [| intro E; subst; apply Hu; exact Hv].
        rewrite assoc, inv_r, id_l. reflexivity.
  Qed.

  (* Classify a vertex of an extended tree: old, or the freshly attached one. *)
  Lemma verts_snoc :
    forall r es u v g w, In w (r :: verts (es ++ [(u, v, g)])) ->
      In w (r :: verts es) \/ w = u \/ w = v.
  Proof.
    intros r es u v g w Hw. rewrite verts_app in Hw. simpl in Hw.
    destruct Hw as [Hw | Hw]; [left; left; exact Hw |].
    apply in_app_or in Hw. destruct Hw as [Hw | Hw]; [left; right; exact Hw |].
    destruct Hw as [Hw | [Hw | []]]; right; [left | right]; symmetry; exact Hw.
  Qed.

  (* Sections of a tree are unique up to a single right constant c = s(r)^-1 t(r). *)
  Theorem tree_unique :
    forall r es, tree r es ->
    forall s t, is_section s es -> is_section t es ->
    forall w, In w (r :: verts es) -> t w = op (s w) (op (inv (s r)) (t r)).
  Proof.
    intros r es T. induction T as [| es u v g T IH Hu Hv | es u v g T IH Hv Hu];
      intros s t Hs Ht w Hw.
    - simpl in Hw. destruct Hw as [<- | []]. rewrite assoc, inv_r, id_l. reflexivity.
    - destruct (proj1 (section_app _ _ _) Hs) as [Hs1 Hsx].
      destruct (proj1 (section_app _ _ _) Ht) as [Ht1 Htx].
      pose proof (Hsx (u, v, g) (or_introl eq_refl)) as Es.
      pose proof (Htx (u, v, g) (or_introl eq_refl)) as Et.
      unfold sat in Es, Et.
      destruct (verts_snoc r es u v g w Hw) as [Hold | [-> | ->]].
      + apply IH; assumption.
      + apply IH; assumption.
      + rewrite <- Et, <- Es, (IH s t Hs1 Ht1 u Hu). apply assoc.
    - destruct (proj1 (section_app _ _ _) Hs) as [Hs1 Hsx].
      destruct (proj1 (section_app _ _ _) Ht) as [Ht1 Htx].
      pose proof (Hsx (u, v, g) (or_introl eq_refl)) as Es.
      pose proof (Htx (u, v, g) (or_introl eq_refl)) as Et.
      unfold sat in Es, Et.
      destruct (verts_snoc r es u v g w Hw) as [Hold | [-> | ->]].
      + apply IH; assumption.
      + rewrite (left_solve _ _ _ Et), (left_solve _ _ _ Es), (IH s t Hs1 Ht1 v Hv).
        apply assoc.
      + apply IH; assumption.
  Qed.

  (* ----- the cycle-basis criterion ----- *)

  (* For a spanning tree T with section sT, plus extra edges X among T's vertices: the whole graph
     has a global section iff every extra edge is balanced against sT, i.e. iff every fundamental
     cycle (an extra edge closed through the tree) has trivial holonomy. *)
  Theorem cycle_basis_criterion :
    forall r T X sT,
      tree r T -> is_section sT T ->
      (forall u v g, In (u, v, g) X -> In u (r :: verts T) /\ In v (r :: verts T)) ->
      (has_section (T ++ X) <-> forall x, In x X -> sat sT x).
  Proof.
    intros r T X sT HT HsT Hspan. split.
    - intros [s Hs] [[u v] g] Hx.
      destruct (proj1 (section_app _ _ _) Hs) as [HsT' HsX].
      pose proof (HsX _ Hx) as E. unfold sat in E |- *.
      destruct (Hspan u v g Hx) as [Hu Hv].
      rewrite (tree_unique r T HT sT s HsT HsT' u Hu),
              (tree_unique r T HT sT s HsT HsT' v Hv) in E.
      rewrite (assoc g (sT u)) in E. exact (right_cancel _ _ _ E).
    - intro Hbal. exists sT. apply section_app. split; [exact HsT |].
      intros x Hx. exact (Hbal x Hx).
  Qed.

  (* Keeping only balanced fundamental edges always leaves a section. *)
  Corollary keep_balanced_suffices :
    forall T X sT, is_section sT T -> (forall x, In x X -> sat sT x) -> has_section (T ++ X).
  Proof.
    intros T X sT HsT Hbal. exists sT. apply section_app. split; [exact HsT |].
    intros x Hx. exact (Hbal x Hx).
  Qed.

  (* Keeping any unbalanced fundamental edge destroys every section: it must be coordinated. *)
  Corollary unbalanced_blocks :
    forall r T X sT x,
      tree r T -> is_section sT T ->
      (forall u v g, In (u, v, g) X -> In u (r :: verts T) /\ In v (r :: verts T)) ->
      In x X -> ~ sat sT x -> ~ has_section (T ++ X).
  Proof.
    intros r T X sT x HT HsT Hspan Hx Hnot H.
    apply Hnot. exact (proj1 (cycle_basis_criterion r T X sT HT HsT Hspan) H x Hx).
  Qed.

  (* =====================================================================
     H^1 as a quotient, and its rank.

     A gauge h (a relabeling of every vertex's fiber) acts on a labeling by
     g |-> h(v) g h(u)^-1 on each edge u -> v; two labelings are cohomologous when one is the
     gauge transform of the other. This is the quotient defining H^1 on the graph (its
     1-skeleton, where every labeling is a cocycle). We prove:
     - gauge_fix: every labeling is cohomologous to one that is the identity on a spanning tree,
       and gauge_fixed_holonomy: its remaining labels are exactly the fundamental-cycle
       holonomies.
     - H1_classification: two tree-fixed labelings are cohomologous iff their non-tree labels are
       SIMULTANEOUSLY CONJUGATE, for any group (abelian or not). So H^1 is the tuples of
       fundamental holonomies modulo simultaneous conjugation.
     - betti_number: the number of those generators is |E| - |V| + 1, the first Betti number.
     ===================================================================== *)

  Definition gauge (h : nat -> G) (es : list edge) : list edge :=
    map (fun x => let '(u, v, g) := x in (u, v, op (h v) (op g (inv (h u))))) es.

  Definition cohomologous (L1 L2 : list edge) : Prop := exists h, L2 = gauge h L1.

  (* Identity labels on a set of edges (e.g. a gauge-fixed spanning tree). *)
  Definition idlab (es : list edge) : Prop := forall u v g, In (u, v, g) es -> g = e.

  Lemma gauge_app : forall h a b, gauge h (a ++ b) = gauge h a ++ gauge h b.
  Proof. intros h a b. unfold gauge. apply map_app. Qed.

  Lemma gauge_length : forall h l, length (gauge h l) = length l.
  Proof. intros h l. induction l as [| x l IH]; simpl; [reflexivity | rewrite IH; reflexivity]. Qed.

  Lemma inv_inv : forall a, inv (inv a) = a.
  Proof.
    intro a. transitivity (op (inv (inv a)) (op (inv a) a)).
    - rewrite inv_l, id_r. reflexivity.
    - rewrite assoc, inv_l, id_l. reflexivity.
  Qed.

  Lemma app_split_eq :
    forall (a b c d : list edge), length a = length c -> a ++ b = c ++ d -> a = c /\ b = d.
  Proof.
    induction a as [| x a IH]; intros b c d Hl E; destruct c as [| y c]; simpl in *;
      try discriminate.
    - split; [reflexivity | exact E].
    - injection E as Exy E'. injection Hl as Hl'.
      destruct (IH b c d Hl' E') as [-> ->]. subst. split; reflexivity.
  Qed.

  Lemma map_fixed_in :
    forall (f : edge -> edge) l, map f l = l -> forall x, In x l -> f x = x.
  Proof.
    intros f l. induction l as [| y l IH]; simpl; intros E x Hx; [contradiction |].
    injection E as E1 E2. destruct Hx as [<- | Hx]; [exact E1 | exact (IH E2 x Hx)].
  Qed.

  Lemma verts_gauge : forall h es, verts (gauge h es) = verts es.
  Proof.
    intros h es. induction es as [| [[u v] g] t IH]; [reflexivity |].
    simpl. rewrite IH. reflexivity.
  Qed.

  (* Gauge transformations preserve the tree structure (it depends only on the endpoints). *)
  Lemma tree_gauge : forall r es h, tree r es -> tree r (gauge h es).
  Proof.
    intros r es h T. induction T as [| es u v g T IH Hu Hv | es u v g T IH Hv Hu].
    - apply t_nil.
    - rewrite gauge_app.
      change (gauge h [(u, v, g)]) with [(u, v, op (h v) (op g (inv (h u))))].
      apply t_out; [exact IH | rewrite verts_gauge; exact Hu | rewrite verts_gauge; exact Hv].
    - rewrite gauge_app.
      change (gauge h [(u, v, g)]) with [(u, v, op (h v) (op g (inv (h u))))].
      apply t_in; [exact IH | rewrite verts_gauge; exact Hv | rewrite verts_gauge; exact Hu].
  Qed.

  (* A gauge that fixes the identity on every tree edge is constant on the tree. *)
  Lemma tree_const :
    forall r es, tree r es ->
    forall h : nat -> G, (forall u v g, In (u, v, g) es -> h u = h v) ->
    forall w, In w (r :: verts es) -> h w = h r.
  Proof.
    intros r es T. induction T as [| es u v g T IH Hu Hv | es u v g T IH Hv Hu];
      intros h Hh w Hw.
    - simpl in Hw. destruct Hw as [<- | []]. reflexivity.
    - assert (Hh' : forall a b c, In (a, b, c) es -> h a = h b)
        by (intros a b c Hin; apply (Hh a b c); apply in_or_app; left; exact Hin).
      assert (Huv : h u = h v)
        by (apply (Hh u v g); apply in_or_app; right; left; reflexivity).
      destruct (verts_snoc r es u v g w Hw) as [Hold | [-> | ->]].
      + exact (IH h Hh' w Hold).
      + exact (IH h Hh' u Hu).
      + rewrite <- Huv. exact (IH h Hh' u Hu).
    - assert (Hh' : forall a b c, In (a, b, c) es -> h a = h b)
        by (intros a b c Hin; apply (Hh a b c); apply in_or_app; left; exact Hin).
      assert (Huv : h u = h v)
        by (apply (Hh u v g); apply in_or_app; right; left; reflexivity).
      destruct (verts_snoc r es u v g w Hw) as [Hold | [-> | ->]].
      + exact (IH h Hh' w Hold).
      + rewrite Huv. exact (IH h Hh' v Hv).
      + exact (IH h Hh' v Hv).
  Qed.

  (* Gauge fixing: every labeling is cohomologous to one that is the identity on the tree. *)
  Theorem gauge_fix : forall r T, tree r T -> exists h, idlab (gauge h T).
  Proof.
    intros r T HT. destruct (tree_has_section r T HT) as [sT HsT].
    exists (fun w => inv (sT w)). intros u v g Hin.
    unfold gauge in Hin. apply in_map_iff in Hin. destruct Hin as [[[u0 v0] g0] [E Hin0]].
    simpl in E. injection E as Eu Ev Eg. subst.
    rewrite inv_inv. apply (proj1 (sat_iff_trivial_holonomy sT _ _ _)). exact (HsT _ Hin0).
  Qed.

  (* After gauge fixing by a tree section, each remaining label is that edge's fundamental-cycle
     holonomy s(v)^-1 g s(u). *)
  Theorem gauge_fixed_holonomy :
    forall sT X,
      gauge (fun w => inv (sT w)) X
      = map (fun x => let '(u, v, g) := x in (u, v, op (inv (sT v)) (op g (sT u)))) X.
  Proof.
    intros sT X. unfold gauge. apply map_ext_in. intros [[u v] g] _. simpl.
    rewrite inv_inv. reflexivity.
  Qed.

  (* H^1 classification: two tree-fixed labelings are cohomologous iff their non-tree labels are
     simultaneously conjugate by a single group element. *)
  Theorem H1_classification :
    forall r idT X1 X2,
      tree r idT -> idlab idT ->
      (forall u v g, In (u, v, g) X1 -> In u (r :: verts idT) /\ In v (r :: verts idT)) ->
      (cohomologous (idT ++ X1) (idT ++ X2) <-> exists c, X2 = gauge (fun _ => c) X1).
  Proof.
    intros r idT X1 X2 HT Hid Hspan. split.
    - intros [h E]. rewrite gauge_app in E.
      destruct (app_split_eq idT X2 (gauge h idT) (gauge h X1)
                  (eq_sym (gauge_length h idT)) E) as [Et EX].
      assert (Hc : forall u v g, In (u, v, g) idT -> h u = h v).
      { intros u v g Hin. unfold gauge in Et.
        pose proof (map_fixed_in _ idT (eq_sym Et) (u, v, g) Hin) as Hfix.
        simpl in Hfix. injection Hfix as Eg.
        rewrite (Hid u v g Hin) in Eg. rewrite id_l in Eg.
        symmetry. transitivity (op (op (h v) (inv (h u))) (h u)).
        - rewrite <- assoc, inv_l, id_r. reflexivity.
        - rewrite Eg, id_l. reflexivity. }
      exists (h r). rewrite EX. unfold gauge. apply map_ext_in.
      intros [[u v] g] Hin. destruct (Hspan u v g Hin) as [Hu Hv]. simpl.
      rewrite (tree_const r idT HT h Hc u Hu), (tree_const r idT HT h Hc v Hv). reflexivity.
    - intros [c ->]. exists (fun _ => c). rewrite gauge_app. f_equal.
      symmetry. transitivity (map (fun x : edge => x) idT); [| apply map_id].
      unfold gauge. apply map_ext_in. intros [[u v] g] Hin. simpl.
      rewrite (Hid u v g Hin), id_l, inv_r. reflexivity.
  Qed.

  (* ----- the rank: the first Betti number ----- *)

  Lemma len_snoc : forall (A : Type) (l : list A) x, length (l ++ [x]) = S (length l).
  Proof. intros A l x. induction l as [| y l IH]; simpl; [reflexivity | rewrite IH; reflexivity]. Qed.

  Lemma len_app : forall (A : Type) (a b : list A), length (a ++ b) = length a + length b.
  Proof. intros A a b. induction a as [| y a IH]; simpl; [reflexivity | rewrite IH; reflexivity]. Qed.

  Lemma verts_snoc_intro :
    forall r es u v g w, In w (r :: verts es) \/ w = u \/ w = v ->
      In w (r :: verts (es ++ [(u, v, g)])).
  Proof.
    intros r es u v g w H. rewrite verts_app. simpl.
    destruct H as [[H | H] | [-> | ->]].
    - left. exact H.
    - right. apply in_or_app. left. exact H.
    - right. apply in_or_app. right. left. reflexivity.
    - right. apply in_or_app. right. right. left. reflexivity.
  Qed.

  (* A tree with n edges has exactly n + 1 distinct vertices. *)
  Theorem tree_vertex_count :
    forall r es, tree r es ->
      exists vs, NoDup vs /\ (forall w, In w vs <-> In w (r :: verts es)) /\
                 length vs = S (length es).
  Proof.
    intros r es T. induction T as [| es u v g T IH Hu Hv | es u v g T IH Hv Hu].
    - exists [r]. split; [| split].
      + constructor; [intros [] | constructor].
      + intro w. simpl. tauto.
      + reflexivity.
    - destruct IH as [vs [Hnd [Hin Hlen]]]. exists (vs ++ [v]). split; [| split].
      + apply (Permutation_NoDup (Permutation_cons_append vs v)).
        constructor; [intro H; apply Hv; apply Hin; exact H | exact Hnd].
      + intro w. split; intro H.
        * apply in_app_or in H. apply verts_snoc_intro.
          destruct H as [H | [<- | []]]; [left; apply Hin; exact H | right; right; reflexivity].
        * apply verts_snoc in H. apply in_or_app.
          destruct H as [H | [-> | ->]];
            [left; apply Hin; exact H | left; apply Hin; exact Hu | right; left; reflexivity].
      + rewrite !len_snoc, Hlen. reflexivity.
    - destruct IH as [vs [Hnd [Hin Hlen]]]. exists (vs ++ [u]). split; [| split].
      + apply (Permutation_NoDup (Permutation_cons_append vs u)).
        constructor; [intro H; apply Hu; apply Hin; exact H | exact Hnd].
      + intro w. split; intro H.
        * apply in_app_or in H. apply verts_snoc_intro.
          destruct H as [H | [<- | []]]; [left; apply Hin; exact H | right; left; reflexivity].
        * apply verts_snoc in H. apply in_or_app.
          destruct H as [H | [-> | ->]];
            [left; apply Hin; exact H | right; left; reflexivity | left; apply Hin; exact Hv].
      + rewrite !len_snoc, Hlen. reflexivity.
  Qed.

  Lemma in_verts_exists :
    forall X w, In w (verts X) -> exists u v g, In (u, v, g) X /\ (w = u \/ w = v).
  Proof.
    induction X as [| [[a b] h] t IH]; intros w H; simpl in H; [contradiction |].
    destruct H as [<- | [<- | H]].
    - exists a, b, h. split; [left; reflexivity | left; reflexivity].
    - exists a, b, h. split; [left; reflexivity | right; reflexivity].
    - destruct (IH w H) as [u [v [g [Hin Hw]]]]. exists u, v, g. split; [right; exact Hin | exact Hw].
  Qed.

  (* The rank of H^1: for a connected graph given as a spanning tree T plus extra edges X, the
     number of independent fundamental cycles is |X| = |E| - |V| + 1 (stated without truncated
     subtraction as |X| + |V| = |E| + 1), the first Betti number. *)
  Theorem betti_number :
    forall r T X,
      tree r T ->
      (forall u v g, In (u, v, g) X -> In u (r :: verts T) /\ In v (r :: verts T)) ->
      exists vs, NoDup vs /\ (forall w, In w vs <-> In w (r :: verts (T ++ X))) /\
                 length X + length vs = length (T ++ X) + 1.
  Proof.
    intros r T X HT Hspan. destruct (tree_vertex_count r T HT) as [vs [Hnd [Hin Hlen]]].
    exists vs. split; [exact Hnd | split].
    - intro w. split; intro H.
      + apply Hin in H. destruct H as [H | H]; [left; exact H |].
        right. rewrite verts_app. apply in_or_app. left. exact H.
      + apply Hin. destruct H as [H | H]; [left; exact H |].
        rewrite verts_app in H. apply in_app_or in H. destruct H as [H | H]; [right; exact H |].
        destruct (in_verts_exists X w H) as [u [v [g [Hx [-> | ->]]]]];
          [exact (proj1 (Hspan u v g Hx)) | exact (proj2 (Hspan u v g Hx))].
    - rewrite len_app, Hlen. unfold edge in *. lia.
  Qed.
End GeneralGraph.

(* ============================================================
   Non-vacuity: the group Z/2 (bool, xor) discharges every group hypothesis, and a triangle shows
   the criterion firing both ways. Spanning tree 0 -> 1 -> 2 with identity labels; the closing edge
   2 -> 0 either carries the identity (balanced: a section exists) or the flip (unbalanced: no
   section, the minimal nonzero obstruction). Axiom-free.
   ============================================================ *)

Lemma xor_assoc : forall a b c, xorb a (xorb b c) = xorb (xorb a b) c.
Proof. destruct a, b, c; reflexivity. Qed.
Lemma xor_id_l : forall a, xorb false a = a. Proof. destruct a; reflexivity. Qed.
Lemma xor_id_r : forall a, xorb a false = a. Proof. destruct a; reflexivity. Qed.
Lemma xor_inv_r : forall a, xorb a a = false. Proof. destruct a; reflexivity. Qed.
Lemma xor_inv_l : forall a, xorb a a = false. Proof. destruct a; reflexivity. Qed.

Definition triT : list (@edge bool) := ([] ++ [(0, 1, false)]) ++ [(1, 2, false)].

Lemma triT_tree : tree 0 triT.
Proof.
  unfold triT. apply t_out.
  - apply t_out; [apply t_nil | left; reflexivity | simpl; intuition congruence].
  - simpl. right. right. left. reflexivity.
  - simpl. intuition congruence.
Qed.

Definition sT0 : nat -> bool := fun _ => false.

Lemma triT_section : is_section xorb sT0 triT.
Proof.
  unfold triT. intros [[u v] g] H. simpl in H.
  destruct H as [H | [H | []]]; injection H as Eu Ev Eg; subst; reflexivity.
Qed.

Lemma tri_span :
  forall (b : bool) (u v : nat) (g : bool),
    In (u, v, g) [(2, 0, b)] -> In u (0 :: verts triT) /\ In v (0 :: verts triT).
Proof.
  intros b u v g [H | []]. injection H as Eu Ev Eg. subst. simpl. split.
  - right. right. right. right. left. reflexivity.
  - left. reflexivity.
Qed.

(* Closing the triangle with the identity: balanced, so a global section exists. *)
Example tri_identity_has_section : has_section xorb (triT ++ [(2, 0, false)]).
Proof.
  apply (keep_balanced_suffices xorb triT [(2, 0, false)] sT0 triT_section).
  intros x [<- | []]. reflexivity.
Qed.

(* Closing it with the flip: unbalanced, so no global section, by the general criterion. *)
Example tri_flip_no_section : ~ has_section xorb (triT ++ [(2, 0, true)]).
Proof.
  apply (unbalanced_blocks xorb false (fun a => a) xor_assoc xor_id_l xor_id_r xor_inv_r xor_inv_l
           0 triT [(2, 0, true)] sT0 (2, 0, true)
           triT_tree triT_section (tri_span true)).
  - left. reflexivity.
  - unfold sat, sT0. simpl. discriminate.
Qed.

(* Non-vacuity of the H^1 classification: on the same triangle, the spanning tree is already
   identity-labeled, and closing it with the flip versus the identity gives two labelings in
   DIFFERENT cohomology classes. Every hypothesis of H1_classification is discharged. *)
Lemma triT_idlab : idlab false triT.
Proof.
  unfold triT. intros u v g H. simpl in H.
  destruct H as [H | [H | []]]; injection H as Eu Ev Eg; subst; reflexivity.
Qed.

Example tri_flip_not_cohomologous_to_identity :
  ~ cohomologous xorb (fun a => a) (triT ++ [(2, 0, true)]) (triT ++ [(2, 0, false)]).
Proof.
  intro H.
  apply (proj1 (H1_classification xorb false (fun a => a) xor_assoc xor_id_l xor_id_r xor_inv_r
                  xor_inv_l 0 triT [(2, 0, true)] [(2, 0, false)]
                  triT_tree triT_idlab (tri_span true))) in H.
  destruct H as [c E]. unfold gauge in E. simpl in E. injection E as Ec.
  destruct c; discriminate Ec.
Qed.
