(* CompositionBlocks.v: composition beyond acyclic collapse (REGIME-AUDIT section 14, gaps 19 and 5),
   mechanized axiom-free.

   Collapse.v proves compositional collapse for an ACYCLIC convex sub-federation J in the FedMachine
   model (collapse_c_exact: the contracted network N' converges iff N does, with the same exact
   condition). Two questions were open. (a) Networks whose strongly connected blocks use different
   engines (a monotone cycle, a rootless invertible cycle, an acyclic block, a non-monotone block):
   when does the composed network converge, and is its normal form the one computed block by block?
   (b) The distributed model, where J's internal propagation steps interleave with outer events.
   This file answers both, and closes gap 5 (a cyclic MONOTONE J) in the FedMachine model.

   PART A. The interface theorem (any engines). The condensation of a network into strongly
   connected blocks is acyclic, so a network is an acyclic composition of black boxes, and every
   finite DAG of blocks is built by repeatedly composing an upstream system A with one downstream
   block B (the composite is again a system of the same kind). A system is a state type with an
   equivalence (states are compared pointwise in the development), a type of actions with a
   predicate selecting the network's own actions, and a deterministic step per action; a schedule
   is a finite list of allowed actions. A is any system on X; B is a system on Y whose steps read A's
   CURRENT state x (its inputs; stepB x b y). The composite runs on X * Y and interleaves A's and B's
   actions freely. Quiet: every allowed action leaves the state unchanged (a normal form).
     Conv (convergence of a system): from every start some schedule reaches a quiet state, and every
     schedule that reaches a quiet state reaches the same one (up to the equivalence). This is the
     form of net_unique_normal_form_iff (RootlessNetworks.v).
     Lk xs: the equivalence on Y generated by B's steps taken at inputs x from which A reaches xs
     (the inputs A presents on its way to xs).
   compose_exact (exact, each conjunct necessary):
     Conv composite <-> Conv A
                        /\ (for every quiet xs of A, B at input xs reaches a quiet state from every y)
                        /\ (for every quiet xs of A, two quiet states of B at xs related by Lk xs are
                            equal).
   The third conjunct is the interleaving conjunct: B's settled output must not depend on the steps
   B took while A was still moving. It is not implied by each block converging in isolation:
   compose_isolated_refuted (the sticky block, y := input while y = 0: A converges, B converges at
   every fixed input, the composite reaches two normal forms). Each conjunct is necessary:
   compose_needs_A, compose_needs_wn, compose_isolated_refuted; and B is constrained only at A's
   quiet inputs: compose_transient_free (B has no normal form at a transient input, the composite
   converges).
   compose_collapse (the collapse): under the conjuncts, every normal form of the composite from
   (x, y) is (xs, ys) with xs A's normal form from x and ys B's normal form at input xs FROM THE
   ORIGINAL y. The composite's normal form is the collapsed, block-by-block one.
   The black-box interface. Give each block an equivalence K on its states that its steps preserve
   at every input (its own inputs: the locals, the values at its de facto roots; K = everything for
   a block whose normal form is unique), with eq included in K. Settles K: every start reaches a
   quiet state, and quiet states related by K are equal.
     settles_conv: Settles K -> Conv (a block meeting the interface converges).
     interface_closed: Settles (KA x KB) of the composite <-> Settles KA of A /\ Settles KB of B at
       every quiet input of A. The interface is closed under composition, exactly; by induction it
       holds for every finite DAG of blocks meeting it, whatever their engines.
     interface_lk: Settles KB of B at a quiet input gives compose_exact's interleaving conjunct.

   PART B. Engine instances.
     rootless_conv_iff: a rootless invertible network (RootlessNetworks.v), as a system whose
       actions are its edges, converges iff has_section and (authority_cover or the group is
       trivial): net_unique_normal_form_iff read as Conv (rootless_conv_lhs), so it is the exact
       A-conjunct for a rootless block feeding other blocks. mixed_rootless_exact: a rootless block
       feeding any block B converges iff that condition holds and B's two conjuncts hold at the
       rootless block's sections.
     mono_block_interface_iff: a monotone cycle (DistributedCycles.v, at fixed locals) meets the
       interface with K = every state exactly when its repair has one fixed point (through
       q1_unique_iff). mixed_mono_iff: a monotone block reading its locals from any upstream
       system A, with one fixed point at every quiet input of A, converges iff A does.
     Non-vacuity and the interleaving conjunct with real engines: mixed_instance (the rootless
       network of rootless_source_feeds_cycle, a source feeding a coherently oriented 2-cycle over
       Z/2, feeding a block that reads it), mixed_mono_instance (the same rootless block feeding a
       monotone 2-cycle with one fixed point at every local: the composite converges), and
       mixed_ghost_refuted (the same rootless block feeding the flag cycle of
       FederationEventsCycles.v: the rootless block converges, but a transient alarm, raised while
       it is still settling, lifts the cycle to its ghost fixed point, so the composite reaches two
       normal forms; compose_exact's third conjunct fails).

   PART C. Gap 5 in the FedMachine model: a cyclic MONOTONE J. The FedMachine of a monotone network
   computes the least fixed point of the repair (FederationEventsCycles.cyc_N_lfp). Split the
   shared values into an upstream block X and a downstream block Y (J is either; nesting the split
   gives any block decomposition along the condensation): the repair is triangular,
   F l (x, y) = (FA l x, FB l x y). bekic_lfp: if a is the least fixed point of FA l and b that of
   FB l a, then (a, b) is the least fixed point of F l (Bekic's principle for a triangular system;
   finite height on Y). mono_collapse_nf: a flattened normalizer computing lfp F (the form
   cyc_N_lfp gives for gsm's normalizeCyclic) equals the collapsed one, which normalizes J as one
   effective registry with its own least fixed point; mono_collapse_runs_agree,
   mono_collapse_converges_iff: N' converges iff N does, and mono_collapse_exact: both iff the
   global condition GC (gc_iff), the exact condition on cycles. Non-vacuity: mono_collapse_instance.

   PART D. The distributed model (FederationEvents.v, DistributedExact.v): a word of local events
   and propagation steps, compared after a final flush. In the collapsed distributed network N', J
   propagates as one effective registry: one action runs J's internal repair to completion (its
   block, in order), so no outer event sees J half-propagated. Words are lists of atoms.
     dist_atoms_exact: for any atom set containing every event, whose other atoms are propagation
       words and which contains a flush, convergence over its words is reachable XU over its words
       plus the FedMachine's C2 at states reachable from the flushed start (dist_exact's form).
       dist_exact is recovered as the singleton-atom case (dist_exact_recovered).
     dist_collapse_exact: N' converges iff XU at N'-reachable states and C2R.
     dist_collapse_sound: N converges -> N' converges.
     dist_collapse_iff: N converges <-> N' converges /\ XUR (XU at every state N reaches, J
       half-propagated included). The second conjunct is the settlement conjunct.
     dist_collapse_refuted: the plain collapse_c statement fails in the distributed model: a chain
       0 -> 1 -> 2, J = {1, 2}, Common, J convex, N' converges from the start, N does not (an event
       on 1 propagated to 2 before 1 is repaired is a combination no N' run produces).
     dist_collapse_needs_c2: XUR does not give N' convergence (C2 fails), so both conjuncts are
       needed.
     dist_collapse_xu: under static XU (gsm's ProjectionSafe check) N converges iff N' does.

   Literature. The composition of fixed points along an acyclic block decomposition is classical:
   Bekic's principle for least fixed points (H. Bekic, "Definable operations in general algebras,
   and the theory of automata and flowcharts", 1969, in LNCS 177, 1984); Robert's decomposition of
   discrete iterations along the strongly connected components of the interaction graph
   (F. Robert, "Discrete Iterations", Springer 1986); modular and SCC-based attractor computation for
   Boolean networks (for example Mizera, Pang, Qu, Yuan, "Taming asynchrony for attractor detection
   in large Boolean networks", IEEE/ACM TCBB 16(1), 2019, which detects attractors block by block
   along the SCC decomposition; Kadelka, Wheeler, Veliz-Cuba, Murrugarra,
   Laubenbacher, "Modularity of biological systems: a link between structure and function",
   J. R. Soc. Interface 20(207), 2023, where the attractors of a network are assembled from those of its
   modules driven by their upstream modules). Part A is in that line: a block driven by an upstream
   block. What is stated here is the exact condition for a unique reachable normal form in the
   asynchronous step model with arbitrary interleaving, its interleaving conjunct, and the
   interface closure; no claim beyond that is made.

   States are compared by a given equivalence; no functional extensionality is used. *)

From Coq Require Import List Arith Bool Lia.
Require Import NC.Trace NC.Federation NC.FederationEvents NC.FederationEventsConverse NC.FederationGRS
  NC.DistributedExact NC.Collapse NC.FederationEventsCycles NC.DistributedCycles NC.CohomologyGraph NC.RootlessCycles
  NC.RootlessNetworks.
Import ListNotations.

(* ========================================================================================= *)
(* PART A. Systems, composition, and the interface theorem.                                 *)
(* ========================================================================================= *)

Section Sys.
  Variable S Act : Type.
  Variable eqs : S -> S -> Prop.
  Variable ok : Act -> Prop.
  Variable step : Act -> S -> S.

  Definition run (w : list Act) (s : S) : S := fold_left (fun s a => step a s) w s.
  Definition Quiet (s : S) : Prop := forall a, ok a -> eqs (step a s) s.
  Definition WN (s : S) : Prop := exists w, Forall ok w /\ Quiet (run w s).
  Definition UN (s : S) : Prop :=
    forall w1 w2, Forall ok w1 -> Forall ok w2 -> Quiet (run w1 s) -> Quiet (run w2 s) ->
      eqs (run w1 s) (run w2 s).
  Definition Conv : Prop := forall s, WN s /\ UN s.

  Lemma run_app : forall w1 w2 s, run (w1 ++ w2) s = run w2 (run w1 s).
  Proof. intros. unfold run. apply fold_left_app. Qed.
End Sys.

Arguments run {S Act} step w s.
Arguments Quiet {S Act} eqs ok step s.
Arguments WN {S Act} eqs ok step s.
Arguments UN {S Act} eqs ok step s.
Arguments Conv {S Act} eqs ok step.

Section Compose.
  Variables X Y AA AB : Type.
  Variable eqX : X -> X -> Prop.
  Variable eqY : Y -> Y -> Prop.
  Hypothesis eqX_refl : forall x, eqX x x.
  Hypothesis eqX_sym : forall x y, eqX x y -> eqX y x.
  Hypothesis eqX_trans : forall x y z, eqX x y -> eqX y z -> eqX x z.
  Hypothesis eqY_refl : forall x, eqY x x.
  Hypothesis eqY_sym : forall x y, eqY x y -> eqY y x.
  Hypothesis eqY_trans : forall x y z, eqY x y -> eqY y z -> eqY x z.

  Variable okA : AA -> Prop.
  Variable stepA : AA -> X -> X.
  Variable okB : AB -> Prop.
  Variable stepB : X -> AB -> Y -> Y.
  Hypothesis stepA_ext : forall a x x', eqX x x' -> eqX (stepA a x) (stepA a x').
  Hypothesis stepB_ext : forall b x x' y y', eqX x x' -> eqY y y' -> eqY (stepB x b y) (stepB x' b y').
  Variable y_inh : Y.

  (* The composite. *)
  Definition eqC (p q : X * Y) : Prop := eqX (fst p) (fst q) /\ eqY (snd p) (snd q).
  Definition okC (c : AA + AB) : Prop := match c with inl a => okA a | inr b => okB b end.
  Definition stepC (c : AA + AB) (p : X * Y) : X * Y :=
    match c with inl a => (stepA a (fst p), snd p) | inr b => (fst p, stepB (fst p) b (snd p)) end.

  Local Notation runA := (run stepA).
  Local Notation runB x := (run (stepB x)).
  Local Notation runC := (run stepC).
  Local Notation QA := (Quiet eqX okA stepA).
  Local Notation QB x := (Quiet eqY okB (stepB x)).
  Local Notation QC := (Quiet eqC okC stepC).

  Fixpoint projA (w : list (AA + AB)) : list AA :=
    match w with [] => [] | inl a :: r => a :: projA r | inr _ :: r => projA r end.
  Fixpoint projB (w : list (AA + AB)) : list AB :=
    match w with [] => [] | inr b :: r => b :: projB r | inl _ :: r => projB r end.

  Lemma projA_ok : forall w, Forall okC w -> Forall okA (projA w).
  Proof.
    induction w as [| c w IH]; intros H; [constructor |]. inversion H; subst.
    destruct c; simpl; [constructor; [assumption |] |]; apply IH; assumption.
  Qed.

  Lemma projB_ok : forall w, Forall okC w -> Forall okB (projB w).
  Proof.
    induction w as [| c w IH]; intros H; [constructor |]. inversion H; subst.
    destruct c; simpl; [| constructor; [assumption |]]; apply IH; assumption.
  Qed.

  Lemma fst_runC : forall w p, fst (runC w p) = runA (projA w) (fst p).
  Proof. induction w as [| c w IH]; intros [x y]; [reflexivity |]. destruct c; simpl; apply IH. Qed.

  Lemma runC_inl : forall w x y, runC (map inl w) (x, y) = (runA w x, y).
  Proof. induction w as [| a w IH]; intros x y; [reflexivity |]. simpl. apply IH. Qed.

  Lemma runC_inr : forall w x y, runC (map inr w) (x, y) = (x, runB x w y).
  Proof. induction w as [| b w IH]; intros x y; [reflexivity |]. simpl. apply IH. Qed.

  Lemma ok_inl : forall w, Forall okA w -> Forall okC (map inl w).
  Proof. induction w; intros H; inversion H; subst; constructor; simpl; auto. Qed.

  Lemma ok_inr : forall w, Forall okB w -> Forall okC (map inr w).
  Proof. induction w; intros H; inversion H; subst; constructor; simpl; auto. Qed.

  Lemma ok_app' : forall {T} (P : T -> Prop) l1 l2, Forall P l1 -> Forall P l2 -> Forall P (l1 ++ l2).
  Proof. intros T P l1 l2 H1 H2. apply Forall_app. split; assumption. Qed.

  Lemma runA_ext : forall w x x', eqX x x' -> eqX (runA w x) (runA w x').
  Proof. induction w as [| a w IH]; intros x x' H; [exact H |]. simpl. apply IH, stepA_ext, H. Qed.

  Lemma runB_ext : forall w x x' y y', eqX x x' -> eqY y y' -> eqY (runB x w y) (runB x' w y').
  Proof. induction w as [| b w IH]; intros x x' y y' Hx Hy; [exact Hy |]. simpl. apply IH; [exact Hx | apply stepB_ext; assumption]. Qed.

  Lemma runC_ext : forall w p q, eqC p q -> eqC (runC w p) (runC w q).
  Proof.
    induction w as [| c w IH]; intros [x y] [x' y'] [Hx Hy]; [split; assumption |].
    simpl. apply IH. destruct c; split; simpl; auto.
  Qed.

  Lemma QA_run : forall w x, QA x -> Forall okA w -> eqX (runA w x) x.
  Proof.
    induction w as [| a w IH]; intros x Hq Hw; [apply eqX_refl |]. inversion Hw; subst. simpl.
    eapply eqX_trans; [apply runA_ext; apply Hq; assumption |]. apply IH; assumption.
  Qed.

  Lemma QA_eq : forall x x', QA x -> eqX x x' -> QA x'.
  Proof.
    intros x x' Hq H a Ha. eapply eqX_trans; [apply stepA_ext, eqX_sym, H |].
    eapply eqX_trans; [apply Hq, Ha | exact H].
  Qed.

  Lemma QB_eq : forall x x' y y', QB x y -> eqX x x' -> eqY y y' -> QB x' y'.
  Proof.
    intros x x' y y' Hq Hx Hy b Hb. eapply eqY_trans; [apply stepB_ext; [apply eqX_sym, Hx | apply eqY_sym, Hy] |].
    eapply eqY_trans; [apply Hq, Hb | exact Hy].
  Qed.

  Lemma QC_iff : forall x y, QC (x, y) <-> QA x /\ QB x y.
  Proof.
    intros x y. split.
    - intros H. split.
      + intros a Ha. exact (proj1 (H (inl a) Ha)).
      + intros b Hb. exact (proj2 (H (inr b) Hb)).
    - intros [Ha Hb] [a | b] Hc; split; simpl; auto.
  Qed.

  Lemma eqC_sym : forall p q, eqC p q -> eqC q p.
  Proof. intros p q [A B]. split; [apply eqX_sym, A | apply eqY_sym, B]. Qed.

  Lemma QC_eq : forall p q, QC p -> eqC p q -> QC q.
  Proof.
    intros [x y] [x' y'] H [Hx Hy]. apply QC_iff in H. apply QC_iff. simpl in *.
    split; [exact (QA_eq x x' (proj1 H) Hx) | exact (QB_eq x x' y y' (proj2 H) Hx Hy)].
  Qed.

  (* From a quiet input, the composite only runs B at that input. *)
  Lemma runC_quiet : forall xs w x y y', QA xs -> eqX x xs -> eqY y y' -> Forall okC w ->
    eqX (fst (runC w (x, y))) xs /\ eqY (snd (runC w (x, y))) (runB xs (projB w) y').
  Proof.
    intros xs. induction w as [| c w IH]; intros x y y' Hq Hx Hy Hw; [split; assumption |].
    inversion Hw; subst. destruct c as [a | b]; simpl.
    - apply IH; [exact Hq | | exact Hy | assumption].
      eapply eqX_trans; [apply stepA_ext, Hx |]. apply Hq. assumption.
    - apply IH; [exact Hq | exact Hx | | assumption]. apply stepB_ext; assumption.
  Qed.

  (* ----- the interleaving relation ----- *)
  Inductive Lk (xs : X) : Y -> Y -> Prop :=
  | lk_base : forall x w b y, Forall okA w -> eqX (runA w x) xs -> okB b -> Lk xs y (stepB x b y)
  | lk_eq : forall y y', eqY y y' -> Lk xs y y'
  | lk_sym : forall y y', Lk xs y y' -> Lk xs y' y
  | lk_trans : forall y y' y'', Lk xs y y' -> Lk xs y' y'' -> Lk xs y y''.

  Lemma lk_index : forall xs xs' y y', eqX xs xs' -> Lk xs y y' -> Lk xs' y y'.
  Proof.
    intros xs xs' y y' He H. induction H.
    - eapply lk_base; [eassumption | eapply eqX_trans; eassumption | assumption].
    - apply lk_eq; assumption.
    - apply lk_sym; assumption.
    - eapply lk_trans; eassumption.
  Qed.

  (* Every composite run from (x, y) moves y within Lk of A's final state. *)
  Lemma lk_run : forall w x y, Forall okC w -> Lk (runA (projA w) x) y (snd (runC w (x, y))).
  Proof.
    induction w as [| c w IH]; intros x y Hw; [apply lk_eq, eqY_refl |]. inversion Hw as [| ? ? Hc Hw']; subst.
    destruct c as [a | b]; simpl.
    - apply IH. exact Hw'.
    - eapply lk_trans; [| apply IH; exact Hw'].
      eapply lk_base; [apply projA_ok; exact Hw' | apply eqX_refl | exact Hc].
  Qed.

  Definition WNB (xs : X) : Prop := forall y, WN eqY okB (stepB xs) y.
  Definition LkUnique (xs : X) : Prop :=
    forall y1 y2, QB xs y1 -> QB xs y2 -> Lk xs y1 y2 -> eqY y1 y2.

  (* ----- necessity ----- *)

  Lemma conv_A : Conv eqC okC stepC -> Conv eqX okA stepA.
  Proof.
    intros H x. split.
    - destruct (proj1 (H (x, y_inh))) as [w [Hw Hq]].
      exists (projA w). split; [apply projA_ok; exact Hw |].
      destruct (runC w (x, y_inh)) as [x1 y1] eqn:E. apply QC_iff in Hq. pose proof (fst_runC w (x, y_inh)) as F. rewrite E in F. simpl in F. rewrite <- F. exact (proj1 Hq).
    - intros w1 w2 H1 H2 Q1 Q2.
      set (x1 := runA w1 x). set (x2 := runA w2 x).
      destruct (proj1 (H (x1, y_inh))) as [v1 [Hv1 R1]].
      destruct (proj1 (H (x2, y_inh))) as [v2 [Hv2 R2]].
      assert (U := proj2 (H (x, y_inh)) (map inl w1 ++ v1) (map inl w2 ++ v2)
                 (ok_app' _ _ _ (ok_inl _ H1) Hv1) (ok_app' _ _ _ (ok_inl _ H2) Hv2)).
      rewrite !run_app, !runC_inl in U. specialize (U R1 R2).
      destruct (runC_quiet x1 v1 x1 y_inh y_inh Q1 (eqX_refl _) (eqY_refl _) Hv1) as [F1 _].
      destruct (runC_quiet x2 v2 x2 y_inh y_inh Q2 (eqX_refl _) (eqY_refl _) Hv2) as [F2 _].
      eapply eqX_trans; [apply eqX_sym, F1 |]. eapply eqX_trans; [apply (proj1 U) | exact F2].
  Qed.

  Lemma conv_WNB : Conv eqC okC stepC -> forall xs, QA xs -> WNB xs.
  Proof.
    intros H xs Hq y. destruct (proj1 (H (xs, y))) as [w [Hw Q]].
    exists (projB w). split; [apply projB_ok; exact Hw |].
    destruct (runC_quiet xs w xs y y Hq (eqX_refl _) (eqY_refl _) Hw) as [F S].
    destruct (runC w (xs, y)) as [x1 y1] eqn:E. simpl in F, S. apply QC_iff in Q.
    exact (QB_eq x1 xs y1 _ (proj2 Q) F S).
  Qed.

  (* All quiet states reachable from (xs, y) and from (xs, y') agree. *)
  Definition Agree (xs : X) (y y' : Y) : Prop :=
    forall w1 w2, Forall okC w1 -> Forall okC w2 -> QC (runC w1 (xs, y)) -> QC (runC w2 (xs, y')) ->
      eqC (runC w1 (xs, y)) (runC w2 (xs, y')).

  Lemma conv_LkUnique : Conv eqC okC stepC -> forall xs, QA xs -> LkUnique xs.
  Proof.
    intros H xs Hq.
    assert (Hag : forall y y', Lk xs y y' -> Agree xs y y').
    { intros y y' L. induction L as [x w b y Hw Hr Hb | y y' He | y y' _ IH | y y' y'' _ IH1 _ IH2].
      - intros w1 w2 H1 H2 Q1 Q2.
        (* from (x, y): w, then w1 reaches the first; b, w, then w2 reaches the second *)
        assert (E1 : eqC (runC (map inl w ++ w1) (x, y)) (runC w1 (xs, y))).
        { rewrite run_app, runC_inl. apply runC_ext. split; [exact Hr | apply eqY_refl]. }
        assert (E2 : eqC (runC ((inr b :: map inl w) ++ w2) (x, y)) (runC w2 (xs, stepB x b y))).
        { rewrite run_app. simpl. rewrite runC_inl. apply runC_ext. split; [exact Hr | apply eqY_refl]. }
        assert (O1 : Forall okC (map inl w ++ w1)) by (apply ok_app'; [apply ok_inl; exact Hw | exact H1]).
        assert (O2 : Forall okC ((inr b :: map inl w) ++ w2))
          by (apply ok_app'; [constructor; [exact Hb | apply ok_inl; exact Hw] | exact H2]).
        pose proof (proj2 (H (x, y)) _ _ O1 O2 (QC_eq _ _ Q1 (eqC_sym _ _ E1))
                      (QC_eq _ _ Q2 (eqC_sym _ _ E2))) as U.
        destruct E1 as [A1 B1]. destruct E2 as [A2 B2]. destruct U as [A B].
        split; [eapply eqX_trans; [apply eqX_sym, A1 | eapply eqX_trans; [exact A | exact A2]] |].
        eapply eqY_trans; [apply eqY_sym, B1 | eapply eqY_trans; [exact B | exact B2]].
      - intros w1 w2 H1 H2 Q1 Q2.
        assert (E : eqC (runC w2 (xs, y)) (runC w2 (xs, y'))) by (apply runC_ext; split; [apply eqX_refl | exact He]).
        pose proof (proj2 (H (xs, y)) w1 w2 H1 H2 Q1 (QC_eq _ _ Q2 (eqC_sym _ _ E))) as [A B].
        destruct E as [A' B']. split; [eapply eqX_trans; eassumption | eapply eqY_trans; eassumption].
      - intros w1 w2 H1 H2 Q1 Q2. destruct (IH w2 w1 H2 H1 Q2 Q1) as [A B].
        split; [apply eqX_sym, A | apply eqY_sym, B].
      - intros w1 w2 H1 H2 Q1 Q2. destruct (proj1 (H (xs, y'))) as [v [Hv Qv]].
        destruct (IH1 w1 v H1 Hv Q1 Qv) as [A1 B1]. destruct (IH2 v w2 Hv H2 Qv Q2) as [A2 B2].
        split; [eapply eqX_trans; eassumption | eapply eqY_trans; eassumption]. }
    intros y1 y2 Q1 Q2 L.
    assert (C1 : QC (runC [] (xs, y1))) by (apply QC_iff; split; assumption).
    assert (C2 : QC (runC [] (xs, y2))) by (apply QC_iff; split; assumption).
    exact (proj2 (Hag y1 y2 L [] [] (Forall_nil _) (Forall_nil _) C1 C2)).
  Qed.

  (* ----- sufficiency ----- *)

  Lemma compose_suff : Conv eqX okA stepA -> (forall xs, QA xs -> WNB xs) ->
    (forall xs, QA xs -> LkUnique xs) -> Conv eqC okC stepC.
  Proof.
    intros HA HW HL [x y]. split.
    - destruct (proj1 (HA x)) as [wa [Ha Qa]]. destruct (HW _ Qa y) as [wb [Hb Qb]].
      exists (map inl wa ++ map inr wb). split; [apply ok_app'; [apply ok_inl | apply ok_inr]; assumption |].
      rewrite run_app, runC_inl, runC_inr. apply QC_iff. split; assumption.
    - intros w1 w2 H1 H2 Q1 Q2.
      pose proof (lk_run w1 x y H1) as L1. pose proof (lk_run w2 x y H2) as L2.
      pose proof (fst_runC w1 (x, y)) as F1. pose proof (fst_runC w2 (x, y)) as F2. simpl in F1, F2.
      destruct (runC w1 (x, y)) as [x1 y1]. destruct (runC w2 (x, y)) as [x2 y2]. simpl in *.
      apply QC_iff in Q1. apply QC_iff in Q2. subst x1 x2.
      assert (Ex : eqX (runA (projA w1) x) (runA (projA w2) x)).
      { apply (proj2 (HA x)); [apply projA_ok; exact H1 | apply projA_ok; exact H2 | apply Q1 | apply Q2]. }
      split; [exact Ex |]. simpl.
      apply (HL _ (proj1 Q1)); [apply Q1 | exact (QB_eq _ _ _ _ (proj2 Q2) (eqX_sym _ _ Ex) (eqY_refl _)) |].
      eapply lk_trans; [apply lk_sym; exact L1 |]. apply (lk_index _ _ _ _ (eqX_sym _ _ Ex)). exact L2.
  Qed.

  (* Headline (a): the exact condition for a composite of two blocks with any engines. *)
  Theorem compose_exact :
    Conv eqC okC stepC <->
    Conv eqX okA stepA /\ (forall xs, QA xs -> WNB xs) /\ (forall xs, QA xs -> LkUnique xs).
  Proof.
    split.
    - intros H. split; [apply conv_A; exact H |]. split; [apply conv_WNB; exact H | apply conv_LkUnique; exact H].
    - intros [HA [HW HL]]. apply compose_suff; assumption.
  Qed.

  (* The collapse: the composite's normal form is computed block by block, B started from the
     ORIGINAL y at A's normal form. *)
  Theorem compose_collapse :
    Conv eqX okA stepA -> (forall xs, QA xs -> WNB xs) -> (forall xs, QA xs -> LkUnique xs) ->
    forall x y wa wb w, Forall okA wa -> QA (runA wa x) -> Forall okB wb ->
      QB (runA wa x) (runB (runA wa x) wb y) -> Forall okC w -> QC (runC w (x, y)) ->
      eqC (runC w (x, y)) (runA wa x, runB (runA wa x) wb y).
  Proof.
    intros HA HW HL x y wa wb w Ha Qa Hb Qb Hw Qw.
    pose proof (compose_suff HA HW HL) as HC.
    assert (O : Forall okC (map inl wa ++ map inr wb)) by (apply ok_app'; [apply ok_inl | apply ok_inr]; assumption).
    assert (R : runC (map inl wa ++ map inr wb) (x, y) = (runA wa x, runB (runA wa x) wb y))
      by (rewrite run_app, runC_inl, runC_inr; reflexivity).
    pose proof (proj2 (HC (x, y)) w _ Hw O Qw) as U. rewrite R in U. apply U.
    apply QC_iff. split; assumption.
  Qed.

  (* ----- the black-box interface ----- *)

  Variable KA : X -> X -> Prop.
  Variable KB : Y -> Y -> Prop.
  Hypothesis KA_eq : forall x x', eqX x x' -> KA x x'.
  Hypothesis KB_eq : forall y y', eqY y y' -> KB y y'.
  Hypothesis KA_sym : forall x x', KA x x' -> KA x' x.
  Hypothesis KA_trans : forall x x' x'', KA x x' -> KA x' x'' -> KA x x''.
  Hypothesis KB_sym : forall y y', KB y y' -> KB y' y.
  Hypothesis KB_trans : forall y y' y'', KB y y' -> KB y' y'' -> KB y y''.
  Hypothesis KA_step : forall a x, okA a -> KA x (stepA a x).
  Hypothesis KB_step : forall b x y, okB b -> KB y (stepB x b y).

  Definition KC (p q : X * Y) : Prop := KA (fst p) (fst q) /\ KB (snd p) (snd q).

  Lemma KB_run : forall w x y, Forall okC w -> KB y (snd (runC w (x, y))).
  Proof.
    induction w as [| c w IH]; intros x y Hw; [apply KB_eq, eqY_refl |]. inversion Hw as [| ? ? Hc Hw']; subst.
    destruct c as [a | b]; simpl; [apply IH; exact Hw' |].
    eapply KB_trans; [apply KB_step; exact Hc | apply IH; exact Hw'].
  Qed.

  Lemma lk_KB : forall xs y y', Lk xs y y' -> KB y y'.
  Proof.
    intros xs y y' L. induction L; [apply KB_step; assumption | apply KB_eq; assumption |
                                    apply KB_sym; assumption | eapply KB_trans; eassumption].
  Qed.

  (* A quiet input of A at which B settles in the interface's sense satisfies the interleaving
     conjunct: the interface is a sufficient black-box form of compose_exact's third conjunct. *)
  Theorem interface_lk : forall xs,
    (forall y1 y2, QB xs y1 -> QB xs y2 -> KB y1 y2 -> eqY y1 y2) -> LkUnique xs.
  Proof. intros xs H y1 y2 Q1 Q2 L. apply H; [exact Q1 | exact Q2 | exact (lk_KB _ _ _ L)]. Qed.

  (* The composite's interface is exactly the conjunction of its blocks' interfaces. *)
  Theorem interface_closed :
    ((forall p, WN eqC okC stepC p) /\ (forall p q, QC p -> QC q -> KC p q -> eqC p q)) <->
    ((forall x, WN eqX okA stepA x) /\ (forall x1 x2, QA x1 -> QA x2 -> KA x1 x2 -> eqX x1 x2)) /\
    (forall xs, QA xs -> WNB xs /\ (forall y1 y2, QB xs y1 -> QB xs y2 -> KB y1 y2 -> eqY y1 y2)).
  Proof.
    split.
    - intros [W U].
      assert (WA : forall x, WN eqX okA stepA x).
      { intros x. destruct (W (x, y_inh)) as [w [Hw Hq]]. exists (projA w).
        split; [apply projA_ok; exact Hw |]. destruct (runC w (x, y_inh)) as [x1 y1] eqn:E.
        apply QC_iff in Hq. pose proof (fst_runC w (x, y_inh)) as F. rewrite E in F. simpl in F. rewrite <- F. exact (proj1 Hq). }
      split; [split; [exact WA |] |].
      + intros x1 x2 Q1 Q2 K12.
        destruct (W (x1, y_inh)) as [v1 [Hv1 R1]]. destruct (W (x2, y_inh)) as [v2 [Hv2 R2]].
        destruct (runC_quiet x1 v1 x1 y_inh y_inh Q1 (eqX_refl _) (eqY_refl _) Hv1) as [F1 _].
        destruct (runC_quiet x2 v2 x2 y_inh y_inh Q2 (eqX_refl _) (eqY_refl _) Hv2) as [F2 _].
        pose proof (KB_run v1 x1 y_inh Hv1) as K1. pose proof (KB_run v2 x2 y_inh Hv2) as K2.
        assert (Kc : KC (runC v1 (x1, y_inh)) (runC v2 (x2, y_inh))).
        { split.
          - eapply KA_trans; [apply KA_eq, F1 |]. eapply KA_trans; [exact K12 | apply KA_eq, eqX_sym, F2].
          - eapply KB_trans; [apply KB_sym, K1 | exact K2]. }
        destruct (U _ _ R1 R2 Kc) as [A _].
        eapply eqX_trans; [apply eqX_sym, F1 | eapply eqX_trans; [exact A | exact F2]].
      + intros xs Qs. split.
        * intros y. destruct (W (xs, y)) as [w [Hw Q]]. exists (projB w). split; [apply projB_ok; exact Hw |].
          destruct (runC_quiet xs w xs y y Qs (eqX_refl _) (eqY_refl _) Hw) as [F S].
          destruct (runC w (xs, y)) as [x1 y1] eqn:E. simpl in F, S. apply QC_iff in Q.
          exact (QB_eq x1 xs y1 _ (proj2 Q) F S).
        * intros y1 y2 Q1 Q2 K.
          assert (C1 : QC (xs, y1)) by (apply QC_iff; split; assumption).
          assert (C2 : QC (xs, y2)) by (apply QC_iff; split; assumption).
          exact (proj2 (U _ _ C1 C2 (conj (KA_eq _ _ (eqX_refl _)) K))).
    - intros [[WA UA] HB]. split.
      + intros [x y]. destruct (WA x) as [wa [Ha Qa]]. destruct (proj1 (HB _ Qa) y) as [wb [Hb Qb]].
        exists (map inl wa ++ map inr wb). split; [apply ok_app'; [apply ok_inl | apply ok_inr]; assumption |].
        rewrite run_app, runC_inl, runC_inr. apply QC_iff. split; assumption.
      + intros [x1 y1] [x2 y2] Q1 Q2 [K1 K2]. apply QC_iff in Q1. apply QC_iff in Q2. simpl in *.
        assert (Ex : eqX x1 x2) by (apply UA; [apply Q1 | apply Q2 | exact K1]).
        split; [exact Ex |]. simpl.
        apply (proj2 (HB _ (proj1 Q1))); [apply Q1 | exact (QB_eq _ _ _ _ (proj2 Q2) (eqX_sym _ _ Ex) (eqY_refl _)) | exact K2].
  Qed.
End Compose.

(* A block meeting the interface converges (with K preserved by its steps). *)
Section SettlesConv.
  Variables S Act : Type.
  Variable eqs : S -> S -> Prop.
  Hypothesis eq_refl' : forall x, eqs x x.
  Variable ok : Act -> Prop.
  Variable step : Act -> S -> S.
  Variable K : S -> S -> Prop.
  Hypothesis K_eq : forall x y, eqs x y -> K x y.
  Hypothesis K_sym : forall x y, K x y -> K y x.
  Hypothesis K_trans : forall x y z, K x y -> K y z -> K x z.
  Hypothesis K_step : forall a s, ok a -> K s (step a s).

  Lemma K_run : forall w s, Forall ok w -> K s (run step w s).
  Proof.
    induction w as [| a w IH]; intros s Hw; [apply K_eq, eq_refl' |]. inversion Hw; subst. simpl.
    eapply K_trans; [apply (K_step a s); assumption | apply IH; assumption].
  Qed.

  Theorem settles_conv :
    (forall s, WN eqs ok step s) -> (forall s t, Quiet eqs ok step s -> Quiet eqs ok step t -> K s t -> eqs s t) ->
    Conv eqs ok step.
  Proof.
    intros W U s. split; [apply W |]. intros w1 w2 H1 H2 Q1 Q2. apply U; [exact Q1 | exact Q2 |].
    eapply K_trans; [apply K_sym, K_run, H1 | apply K_run, H2].
  Qed.
End SettlesConv.

(* ----- Part A instances: each conjunct of compose_exact is necessary ----- *)

Definition okT {T : Type} (_ : T) : Prop := True.

Lemma okT_all : forall {T : Type} (l : list T), Forall okT l.
Proof. intros T l. induction l; constructor; [exact I | assumption]. Qed.

Lemma okC_all : forall {AA AB : Type} (l : list (AA + AB)), Forall (okC AA AB okT okT) l.
Proof. intros AA AB l. induction l as [| [a | b] l IH]; constructor; try exact I; exact IH. Qed.

(* A: a flag that rises once. *)
Definition flipA (_ : unit) (x : bool) : bool := true.

Lemma flip_run : forall w x, run flipA w x = match w with [] => x | _ => true end.
Proof.
  intros w x. destruct w as [| a w]; [reflexivity |]. simpl. change (flipA a x) with true.
  clear a x. induction w as [| a w IH]; [reflexivity | exact IH].
Qed.

Lemma flip_conv : Conv (@eq bool) okT flipA.
Proof.
  intros x. split.
  - exists [tt]. split; [apply okT_all |]. intros a _. reflexivity.
  - intros w1 w2 _ _ Q1 Q2. pose proof (Q1 tt I) as A. pose proof (Q2 tt I) as B.
    transitivity true; [exact (eq_sym A) | exact B].
Qed.

(* The sticky block: y takes the input's value (2 or 1) while y = 0, and then keeps it. *)
Definition stickyB (x : bool) (_ : unit) (y : nat) : nat :=
  if Nat.eqb y 0 then (if x then 2 else 1) else y.

Lemma sticky_idem : forall x z, stickyB x tt (stickyB x tt z) = stickyB x tt z.
Proof. intros x z; unfold stickyB; destruct (Nat.eqb z 0) eqn:E; [destruct x; reflexivity | rewrite E; reflexivity]. Qed.

Lemma sticky_run : forall x w y, run (stickyB x) w y = match w with [] => y | _ => stickyB x tt y end.
Proof.
  intros x w y. destruct w as [| [] w]; [reflexivity |]. simpl.
  revert y. induction w as [| [] w IH]; intros z; [reflexivity |].
  simpl. rewrite sticky_idem. apply IH.
Qed.

Lemma sticky_conv : forall x, Conv (@eq nat) okT (stickyB x).
Proof.
  intros x y. split.
  - exists [tt]. split; [apply okT_all |]. intros [] _. apply sticky_idem.
  - intros w1 w2 _ _ Q1 Q2. pose proof (Q1 tt I) as A. pose proof (Q2 tt I) as B.
    rewrite !sticky_run in *. destruct w1, w2; try reflexivity; [exact (eq_sym A) | exact B].
Qed.

Local Notation stickyC := (stepC bool nat unit unit flipA stickyB).

(* Headline counterexample: each block converges in isolation (A from every start, B at every
   fixed input from every start), and the composite does not: B's settled value depends on whether
   it moved before or after A. *)
Theorem compose_isolated_refuted :
  Conv (@eq bool) okT flipA /\ (forall x, Conv (@eq nat) okT (stickyB x)) /\
  run stickyC [inl tt; inr tt] (false, 0) = (true, 2) /\
  run stickyC [inr tt; inl tt] (false, 0) = (true, 1) /\
  ~ Conv (eqC bool nat (@eq bool) (@eq nat)) (okC unit unit okT okT) stickyC.
Proof.
  split; [exact flip_conv |]. split; [exact sticky_conv |]. split; [reflexivity |]. split; [reflexivity |].
  intros H. pose proof (proj2 (H (false, 0)) [inl tt; inr tt] [inr tt; inl tt] (okC_all _) (okC_all _)) as U.
  assert (Q : forall y, y <> 0 -> Quiet (eqC bool nat (@eq bool) (@eq nat)) (okC unit unit okT okT) stickyC (true, y)).
  { intros y Hy [[] | []] _; split; simpl; try reflexivity. unfold stickyB.
    destruct (Nat.eqb_spec y 0); [contradiction | reflexivity]. }
  destruct (U (Q 2 ltac:(discriminate)) (Q 1 ltac:(discriminate))) as [_ E]. discriminate E.
Qed.

(* The A conjunct: A with two normal forms from one start, B trivial. *)
Definition twoA (b : bool) (x : nat) : nat := if Nat.eqb x 0 then (if b then 1 else 2) else x.
Definition idB (_ : nat) (_ : unit) (y : unit) : unit := y.

Theorem compose_needs_A :
  (forall xs, Quiet (@eq nat) okT twoA xs -> WNB nat unit unit (@eq unit) okT idB xs) /\
  (forall xs, Quiet (@eq nat) okT twoA xs -> LkUnique nat unit bool unit (@eq nat) (@eq unit) okT twoA okT idB xs) /\
  ~ Conv (@eq nat) okT twoA /\
  ~ Conv (eqC nat unit (@eq nat) (@eq unit)) (okC bool unit okT okT) (stepC nat unit bool unit twoA idB).
Proof.
  assert (NA : ~ Conv (@eq nat) okT twoA).
  { intros H. pose proof (proj2 (H 0) [true] [false] (okT_all _) (okT_all _)) as U.
    assert (Q : forall x, x <> 0 -> Quiet (@eq nat) okT twoA x).
    { intros x Hx b _. unfold twoA. destruct (Nat.eqb_spec x 0); [contradiction | reflexivity]. }
    specialize (U (Q 1 ltac:(discriminate)) (Q 2 ltac:(discriminate))). discriminate U. }
  split; [intros xs _ y; exists []; split; [constructor | intros [] _; reflexivity] |].
  split; [intros xs _ [] [] _ _ _; reflexivity |].
  split; [exact NA |].
  intros H. apply NA. apply (conv_A nat unit bool unit (@eq nat) (@eq unit) (@eq_refl nat) (@eq_sym nat) (@eq_trans nat)
    (@eq_refl unit) (@eq_sym unit) okT twoA okT idB (fun a x x' H => f_equal _ H)
    (fun b x x' y y' Hx Hy => Hy) tt H).
Qed.

(* The existence conjunct: B never settles at A's normal form. *)
Definition unitA (_ : unit) (x : unit) : unit := x.
Definition incB (_ : unit) (_ : unit) (y : nat) : nat := S y.

Theorem compose_needs_wn :
  Conv (@eq unit) okT unitA /\
  (forall xs, Quiet (@eq unit) okT unitA xs -> LkUnique unit nat unit unit (@eq unit) (@eq nat) okT unitA okT incB xs) /\
  ~ Conv (eqC unit nat (@eq unit) (@eq nat)) (okC unit unit okT okT) (stepC unit nat unit unit unitA incB).
Proof.
  split.
  { intros [] . split; [exists []; split; [constructor | intros [] _; reflexivity] |].
    intros w1 w2 _ _ _ _. destruct (run unitA w1 tt), (run unitA w2 tt). reflexivity. }
  split; [intros xs _ y1 y2 Q _ _; pose proof (Q tt I) as A; unfold incB in A; lia |].
  intros H. destruct (proj1 (H (tt, 0))) as [w [_ Q]].
  destruct (run (stepC unit nat unit unit unitA incB) w (tt, 0)) as [x y].
  destruct (Q (inr tt) I) as [_ E]. simpl in E. unfold incB in E. lia.
Qed.

(* B is constrained only at A's normal forms: at the transient input false it never settles. *)
Definition transB (x : bool) (_ : unit) (y : nat) : nat := if x then 0 else S y.

Theorem compose_transient_free :
  ~ WN (@eq nat) okT (transB false) 0 /\
  Conv (eqC bool nat (@eq bool) (@eq nat)) (okC unit unit okT okT) (stepC bool nat unit unit flipA transB).
Proof.
  split.
  { intros [w [_ Q]]. pose proof (Q tt I) as A. unfold transB in A. lia. }
  apply (compose_exact bool nat unit unit (@eq bool) (@eq nat) (@eq_refl bool) (@eq_sym bool) (@eq_trans bool)
           (@eq_refl nat) (@eq_sym nat) (@eq_trans nat) okT flipA okT transB
           (fun a x x' H => f_equal _ H) (fun b x x' y y' Hx Hy => ltac:(subst; reflexivity)) 0).
  split; [exact flip_conv |]. split.
  - intros xs Qs y. pose proof (Qs tt I) as A. unfold flipA in A. subst xs.
    exists [tt]. split; [apply okT_all |]. intros [] _. reflexivity.
  - intros xs Qs y1 y2 Q1 Q2 _. pose proof (Qs tt I) as A. unfold flipA in A. subst xs.
    pose proof (Q1 tt I) as B1. pose proof (Q2 tt I) as B2. unfold transB in B1, B2. congruence.
Qed.

(* ========================================================================================= *)
(* PART B. Engine instances.                                                                 *)
(* ========================================================================================= *)

(* ----- rootless invertible networks (RootlessNetworks.v) as a block ----- *)

Section RootlessBlock.
  Context {G : Type}.
  Variable op : G -> G -> G.
  Variable es : list (@edge G).

  Definition rok (x : @edge G) : Prop := In x es.
  Definition rstep (x : @edge G) (t : nat -> G) : nat -> G := fire1 op t x.

  Lemma rrun_fire : forall w t, run rstep w t = fire op w t.
  Proof. reflexivity. Qed.

  Lemma rok_incl : forall w, Forall rok w <-> incl w es.
  Proof. intros w. unfold rok, incl. rewrite Forall_forall. tauto. Qed.

  Lemma rquiet_iff : forall t, Quiet (@peq G) rok rstep t <-> is_section op t es.
  Proof.
    intros t. split.
    - intros H [[u v] g] Hin. pose proof (H _ Hin v) as A. unfold rstep in A. simpl in A.
      destruct (Nat.eq_dec v v) as [_ | N]; [exact A | contradiction].
    - intros H [[u v] g] Hin k. pose proof (H _ Hin) as A. simpl in A. unfold rstep. simpl.
      destruct (Nat.eq_dec k v) as [-> | _]; [exact A | reflexivity].
  Qed.

  (* Conv for the rootless block is exactly the left side of net_unique_normal_form_iff. *)
  Lemma rootless_conv_lhs :
    Conv (@peq G) rok rstep <->
    (forall t0, exists p,
        incl p es /\ incl es p /\ is_section op (fire op p t0) es /\
        (forall q, incl q es -> is_section op (fire op q t0) es -> peq (fire op q t0) (fire op p t0))).
  Proof.
    split.
    - intros H t0. destruct (proj1 (H t0)) as [p [Hp Qp]].
      apply rok_incl in Hp. apply rquiet_iff in Qp. rewrite rrun_fire in Qp.
      destruct (extend_fair op es p t0 Hp Qp) as [A [B [C D]]].
      exists (p ++ es). split; [exact A | split; [exact B | split; [exact D |]]].
      intros q Hq Sq k. rewrite C.
      apply (proj2 (H t0) q p); [apply rok_incl; exact Hq | apply rok_incl; exact Hp | | ];
        apply rquiet_iff; rewrite rrun_fire; assumption.
    - intros H t0. destruct (H t0) as [p [Hp [_ [Sp U]]]]. split.
      + exists p. split; [apply rok_incl; exact Hp | apply rquiet_iff; exact Sp].
      + intros w1 w2 H1 H2 Q1 Q2 k. apply rquiet_iff in Q1. apply rquiet_iff in Q2.
        rewrite !rrun_fire in *. rewrite (U w1 (proj1 (rok_incl w1) H1) Q1 k), (U w2 (proj1 (rok_incl w2) H2) Q2 k).
        reflexivity.
  Qed.

  Variables (e : G) (inv : G -> G).
  Hypothesis assoc : forall a b c, op a (op b c) = op (op a b) c.
  Hypothesis id_l  : forall a, op e a = a.
  Hypothesis id_r  : forall a, op a e = a.
  Hypothesis inv_r : forall a, op a (inv a) = e.
  Hypothesis inv_l : forall a, op (inv a) a = e.

  (* The rootless engine's exact condition, as the A-conjunct of compose_exact. *)
  Theorem rootless_conv_iff :
    Conv (@peq G) rok rstep <-> has_section op es /\ (authority_cover es \/ @trivial_group G).
  Proof.
    rewrite rootless_conv_lhs. exact (net_unique_normal_form_iff op e inv assoc id_l id_r inv_r inv_l es).
  Qed.

  (* A rootless block feeding any block B. *)
  Variables (Y AB : Type) (eqY : Y -> Y -> Prop).
  Hypothesis eqY_refl : forall x, eqY x x.
  Hypothesis eqY_sym : forall x y, eqY x y -> eqY y x.
  Hypothesis eqY_trans : forall x y z, eqY x y -> eqY y z -> eqY x z.
  Variable okB : AB -> Prop.
  Variable stepB : (nat -> G) -> AB -> Y -> Y.
  Hypothesis stepB_ext : forall b x x' y y', peq x x' -> eqY y y' -> eqY (stepB x b y) (stepB x' b y').
  Variable y_inh : Y.

  Lemma peq_refl' : forall t : nat -> G, peq t t. Proof. intros t k. reflexivity. Qed.
  Lemma peq_sym' : forall s t : nat -> G, peq s t -> peq t s. Proof. intros s t H k. symmetry. apply H. Qed.
  Lemma peq_trans' : forall s t u : nat -> G, peq s t -> peq t u -> peq s u.
  Proof. intros s t u H1 H2 k. rewrite H1. apply H2. Qed.

  Theorem mixed_rootless_exact :
    Conv (eqC (nat -> G) Y (@peq G) eqY) (okC (@edge G) AB rok okB) (stepC (nat -> G) Y (@edge G) AB rstep stepB) <->
    (has_section op es /\ (authority_cover es \/ @trivial_group G)) /\
    (forall xs, is_section op xs es -> WNB (nat -> G) Y AB eqY okB stepB xs) /\
    (forall xs, is_section op xs es ->
       LkUnique (nat -> G) Y (@edge G) AB (@peq G) eqY rok rstep okB stepB xs).
  Proof.
    rewrite (compose_exact (nat -> G) Y (@edge G) AB (@peq G) eqY peq_refl' peq_sym' peq_trans'
               eqY_refl eqY_sym eqY_trans rok rstep okB stepB (fun x s t H => fire1_ext op x s t H)
               stepB_ext y_inh).
    rewrite rootless_conv_iff. split.
    - intros [A [B C]]. split; [exact A |].
      split; intros xs Hs; [apply B | apply C]; apply rquiet_iff; exact Hs.
    - intros [A [B C]]. split; [exact A |].
      split; intros xs Hs; [apply B | apply C]; apply rquiet_iff; exact Hs.
  Qed.
End RootlessBlock.

(* Non-vacuity: the network of rootless_source_feeds_cycle (registry 0 feeds the coherently
   oriented 2-cycle 1 <-> 2, over Z/2, with |G| = 2) feeding a block that reads registry 2. *)
Definition copy2 (x : nat -> bool) (_ : unit) (_ : bool) : bool := x 2.

Theorem mixed_instance :
  Conv (@peq bool) (rok sfc) (rstep xorb) /\
  Conv (eqC (nat -> bool) bool (@peq bool) (@eq bool)) (okC (@edge bool) unit (rok sfc) okT)
       (stepC (nat -> bool) bool (@edge bool) unit (rstep xorb) copy2).
Proof.
  assert (HA : Conv (@peq bool) (rok sfc) (rstep xorb)).
  { apply rootless_conv_lhs. destruct rootless_source_feeds_cycle as [_ [_ [_ [_ H]]]]. exact H. }
  split; [exact HA |].
  apply (compose_exact (nat -> bool) bool (@edge bool) unit (@peq bool) (@eq bool) peq_refl' peq_sym'
           peq_trans' (@eq_refl bool) (@eq_sym bool) (@eq_trans bool) (rok sfc) (rstep xorb) okT copy2
           (fun x s t H => fire1_ext xorb x s t H) (fun b x x' y y' Hx _ => Hx 2) false).
  split; [exact HA |]. split.
  - intros xs _ y. exists [tt]. split; [apply okT_all | intros [] _; reflexivity].
  - intros xs _ y1 y2 Q1 Q2 _. pose proof (Q1 tt I) as A. pose proof (Q2 tt I) as B.
    unfold copy2 in A, B. congruence.
Qed.

(* ----- monotone cycles (DistributedCycles.v) as a block ----- *)

Section MonoBlock.
  Variables Loc Sh : Type.
  Variable le : Sh -> Sh -> Prop.
  Hypothesis le_refl : forall x, le x x.
  Hypothesis le_trans : forall x y z, le x y -> le y z -> le x z.
  Hypothesis le_antisym : forall x y, le x y -> le y x -> x = y.
  Variable bot : Sh.
  Hypothesis bot_least : forall x, le bot x.
  Variable rank : Sh -> nat.
  Hypothesis rank_strict : forall x y, le x y -> x <> y -> rank x < rank y.
  Variable height : nat.
  Hypothesis rank_bound : forall x, rank x <= height.
  Variable sh_eq_dec : forall x y : Sh, {x = y} + {x <> y}.
  Variable F : Loc -> Sh -> Sh.
  Variable u : Loc -> nat -> Sh -> Sh.
  Hypothesis u_incr : forall l j x, sound Loc Sh le F l x -> le x (u l j x).
  Hypothesis u_sound : forall l j x, sound Loc Sh le F l x -> sound Loc Sh le F l (u l j x).
  Hypothesis u_mono : forall l j x y, le x y -> le (u l j x) (u l j y).
  Hypothesis u_fixed : forall l j x, F l x = x -> u l j x = x.
  Variable K : nat.
  Hypothesis K_big : height < K.
  Variable js : list nat.
  Hypothesis Hcov : Cover Loc Sh F u js.
  Variable top : Sh.
  Hypothesis top_greatest : forall x, le x top.
  Hypothesis u_decr : forall l j x, le (F l x) x -> le (u l j x) x.
  Hypothesis u_cosound : forall l j x, le (F l x) x -> le (F l (u l j x)) (u l j x).
  Variable sg : nat -> nat.
  Hypothesis Hf : Fair js sg.

  Definition mok (j : nat) : Prop := In j js.

  Local Notation LfpM := (Lfp Loc Sh bot sh_eq_dec u K js).

  Lemma prs_run : forall (up : nat -> Sh -> Sh) n h, prs Sh up sg n h = run up (map sg (seq 0 n)) h.
  Proof.
    intros up n. induction n as [| n IH]; intros h; [reflexivity |].
    rewrite seq_S, map_app, run_app. simpl. rewrite IH. reflexivity.
  Qed.

  Lemma sg_ok : forall n, Forall mok (map sg (seq 0 n)).
  Proof. intros n. apply Forall_forall. intros j Hj. apply in_map_iff in Hj. destruct Hj as [m [<- _]]. apply Hf. Qed.

  Lemma mquiet_iff : forall l h, Quiet (@eq Sh) mok (u l) h <-> F l h = h.
  Proof.
    intros l h. rewrite <- (qstable_iff Loc Sh F u u_fixed js Hcov l h). unfold QStable, Stable, Quiet, mok. tauto.
  Qed.

  (* The monotone engine meets the black-box interface with K = every state (its normal form a
     function of its locals alone) exactly when its repair has one fixed point. *)
  Theorem mono_block_interface_iff : forall l,
    ((forall h, WN (@eq Sh) mok (u l) h) /\
     (forall h1 h2, Quiet (@eq Sh) mok (u l) h1 -> Quiet (@eq Sh) mok (u l) h2 -> h1 = h2)) <->
    (forall p, F l p = p -> p = LfpM l).
  Proof.
    intros l. split.
    - intros [_ U] p Hp. apply U; apply mquiet_iff; [exact Hp |].
      exact (Lfp_fixed Loc Sh le le_refl le_trans bot bot_least rank rank_strict height rank_bound
               sh_eq_dec F u u_incr u_sound u_mono u_fixed K K_big js Hcov l).
    - intros Hu.
      pose proof (proj2 (q1_unique_iff Loc Sh le le_refl le_trans le_antisym bot bot_least rank rank_strict
                          height rank_bound sh_eq_dec F u u_incr u_sound u_mono u_fixed K K_big js Hcov top
                          top_greatest u_decr u_cosound l sg Hf) Hu) as HS.
      split.
      + intros h. destruct (HS h) as [N HN]. exists (map sg (seq 0 N)). split; [apply sg_ok |].
        rewrite <- prs_run, (HN N (le_n N)). apply mquiet_iff.
        exact (Lfp_fixed Loc Sh le le_refl le_trans bot bot_least rank rank_strict height rank_bound
                 sh_eq_dec F u u_incr u_sound u_mono u_fixed K K_big js Hcov l).
      + intros h1 h2 Q1 Q2. apply mquiet_iff in Q1. apply mquiet_iff in Q2.
        rewrite (Hu _ Q1), (Hu _ Q2). reflexivity.
  Qed.

  (* A monotone block fed by any upstream system A: its locals are read from A's state
     (loc x). With one fixed point at every quiet input of A, its two conjuncts of compose_exact
     hold, so the composite converges iff A does. *)
  Variables (X AA : Type) (eqX : X -> X -> Prop).
  Hypothesis eqX_refl : forall x, eqX x x.
  Hypothesis eqX_sym : forall x y, eqX x y -> eqX y x.
  Hypothesis eqX_trans : forall x y z, eqX x y -> eqX y z -> eqX x z.
  Variable okA : AA -> Prop.
  Variable stepA : AA -> X -> X.
  Hypothesis stepA_ext : forall a x x', eqX x x' -> eqX (stepA a x) (stepA a x').
  Variable loc : X -> Loc.
  Hypothesis loc_ext : forall x x', eqX x x' -> loc x = loc x'.

  Definition mstep (x : X) (j : nat) (h : Sh) : Sh := u (loc x) j h.

  Theorem mixed_mono_iff :
    (forall xs, Quiet eqX okA stepA xs -> forall p, F (loc xs) p = p -> p = LfpM (loc xs)) ->
    (Conv (eqC X Sh eqX (@eq Sh)) (okC AA nat okA mok) (stepC X Sh AA nat stepA mstep) <->
     Conv eqX okA stepA).
  Proof.
    intros Hu.
    rewrite (compose_exact X Sh AA nat eqX (@eq Sh) eqX_refl eqX_sym eqX_trans (@eq_refl Sh) (@eq_sym Sh)
               (@eq_trans Sh) okA stepA mok mstep stepA_ext
               (fun b x x' y y' Hx Hy => ltac:(subst y'; unfold mstep; rewrite (loc_ext x x' Hx); reflexivity)) bot).
    split; [intros [H _]; exact H |]. intros HA. split; [exact HA |].
    split; intros xs Qs; destruct (proj2 (mono_block_interface_iff (loc xs)) (Hu xs Qs)) as [W U].
    - exact W.
    - intros y1 y2 Q1 Q2 _. exact (U y1 y2 Q1 Q2).
  Qed.
End MonoBlock.

(* Instances on the two-flag lattice B2 of FederationEventsCycles.v. *)
Ltac bfc := repeat match goal with
  | x : B2 |- _ => destruct x
  | x : bool * bool |- _ => destruct x
  | b : bool |- _ => destruct b
  end.

(* A monotone 2-cycle with one fixed point at every local: sa := l && sb, sb := l || sa. *)
Definition aF (l : bool) (x : B2) : B2 := (l && snd x, l || fst x).
Definition au (l : bool) (j : nat) (x : B2) : B2 :=
  match j with 0 => (fst (aF l x), snd x) | 1 => (fst x, snd (aF l x)) | _ => x end.

Lemma au_incr : forall l j x, sound bool B2 cle aF l x -> cle x (au l j x).
Proof. intros l [| [| j]] x; bfc; unfold sound, cle, au, aF; simpl; intuition. Qed.
Lemma au_sound : forall l j x, sound bool B2 cle aF l x -> sound bool B2 cle aF l (au l j x).
Proof. intros l [| [| j]] x; bfc; unfold sound, cle, au, aF; simpl; intuition. Qed.
Lemma au_mono : forall l j x y, cle x y -> cle (au l j x) (au l j y).
Proof. intros l [| [| j]] x y; bfc; unfold cle, au, aF; simpl; intuition. Qed.
Lemma au_fixed : forall l j x, aF l x = x -> au l j x = x.
Proof. intros l [| [| j]] x; bfc; unfold au, aF; simpl; intro H; congruence. Qed.
Lemma au_cover : Cover bool B2 aF au cts.
Proof.
  intros l x H. pose proof (H 0 (or_introl eq_refl)) as H0. pose proof (H 1 (or_intror (or_introl eq_refl))) as H1.
  revert H0 H1. bfc; unfold au, aF; simpl; intros H0 H1; congruence.
Qed.
Lemma ctop : forall x, cle x (true, true). Proof. intros; bfc; split; reflexivity. Qed.
Lemma au_decr : forall l j x, cle (aF l x) x -> cle (au l j x) x.
Proof. intros l [| [| j]] x; bfc; unfold cle, au, aF; simpl; intuition. Qed.
Lemma au_cosound : forall l j x, cle (aF l x) x -> cle (aF l (au l j x)) (au l j x).
Proof. intros l [| [| j]] x; bfc; unfold cle, au, aF; simpl; intuition. Qed.
Lemma aF_unique : forall l p, aF l p = p -> p = Lfp bool B2 cbot ceq_dec au 3 cts l.
Proof. intros l p; bfc; unfold aF; simpl; intro H; try discriminate H; vm_compute; reflexivity. Qed.

(* The alternating schedule 0, 1, 0, 1, ... is fair for cts. *)
Fixpoint par (n : nat) : nat := match n with 0 => 0 | 1 => 1 | S (S k) => par k end.

Lemma par_add : forall n j, par (2 * n + j) = par j.
Proof. induction n as [| n IH]; intros j; [reflexivity |]. replace (2 * S n + j) with (S (S (2 * n + j))) by lia. apply IH. Qed.

Lemma par_fair : Fair cts par.
Proof.
  split.
  - intros n. induction n as [n IH] using (well_founded_induction lt_wf).
    destruct n as [| [| n]]; [left; reflexivity | right; left; reflexivity |]. exact (IH n ltac:(lia)).
  - intros j n Hj. exists (2 * n + j). split; [lia |]. rewrite par_add.
    destruct Hj as [<- | [<- | []]]; reflexivity.
Qed.

(* Rootless block feeding a monotone cycle: the rootless network of rootless_source_feeds_cycle,
   registry 2 read as the cycle's local; the cycle has one fixed point at every local, so the
   composite converges (mixed_mono_iff with the rootless engine's exact condition). *)
Definition loc2 (x : nat -> bool) : bool := x 2.

Theorem mixed_mono_instance :
  (forall l p, aF l p = p -> p = Lfp bool B2 cbot ceq_dec au 3 cts l) /\
  Conv (eqC (nat -> bool) B2 (@peq bool) (@eq B2)) (okC (@edge bool) nat (rok sfc) (mok cts))
       (stepC (nat -> bool) B2 (@edge bool) nat (rstep xorb) (mstep bool B2 au (nat -> bool) loc2)).
Proof.
  split; [exact aF_unique |].
  apply (mixed_mono_iff bool B2 cle cle_refl cle_trans cle_antisym cbot cbot_least crank crank_strict 2
           crank_bound ceq_dec aF au au_incr au_sound au_mono au_fixed 3 ltac:(lia) cts au_cover (true, true)
           ctop au_decr au_cosound par par_fair (nat -> bool) (@edge bool) (@peq bool) peq_refl' peq_sym'
           peq_trans' (rok sfc) (rstep xorb) (fun x s t H => fire1_ext xorb x s t H) loc2 (fun x x' H => H 2)).
  - intros xs _ p Hp. apply aF_unique. exact Hp.
  - exact (proj1 mixed_instance).
Qed.

(* The interleaving conjunct with real engines: the same rootless block feeding the flag cycle of
   FederationEventsCycles.v (sa := lb || sb, sb := la || sa), registry 2 read as the alarm la.
   With the alarm clear the cycle has two fixed points (the ghost of bottom_matters); a transient
   alarm, raised while the rootless block is still settling, lifts the cycle to the ghost, and the
   composite reaches two normal forms. *)
Definition flagloc (x : nat -> bool) : B2 := (x 2, false).
Definition gt0 (k : nat) : bool := Nat.eqb k 2.

Local Notation flagC := (stepC (nat -> bool) B2 (@edge bool) nat (rstep xorb) (mstep B2 B2 cu (nat -> bool) flagloc)).

Theorem mixed_ghost_refuted :
  Conv (@peq bool) (rok sfc) (rstep xorb) /\
  cF (false, false) (true, true) = (true, true) /\ cF (false, false) (false, false) = (false, false) /\
  ~ Conv (eqC (nat -> bool) B2 (@peq bool) (@eq B2)) (okC (@edge bool) nat (rok sfc) (mok cts)) flagC.
Proof.
  split; [exact (proj1 mixed_instance) |]. split; [reflexivity |]. split; [reflexivity |].
  intros H.
  set (w1 := [inr 1; inr 0; inl (1, 2, false)] : list (@edge bool + nat)).
  set (w2 := [inl (1, 2, false)] : list (@edge bool + nat)).
  assert (O1 : Forall (okC (@edge bool) nat (rok sfc) (mok cts)) w1).
  { repeat constructor; simpl; unfold mok, rok, cts, sfc; simpl; tauto. }
  assert (O2 : Forall (okC (@edge bool) nat (rok sfc) (mok cts)) w2).
  { repeat constructor; simpl; unfold rok, sfc; simpl; tauto. }
  assert (Qx : forall p, (forall k, fst p k = false) -> snd p = (true, true) \/ snd p = (false, false) ->
             Quiet (eqC (nat -> bool) B2 (@peq bool) (@eq B2)) (okC (@edge bool) nat (rok sfc) (mok cts)) flagC p).
  { intros [x y] Hx Hy. simpl in Hx, Hy.
    apply (proj2 (QC_iff (nat -> bool) B2 (@edge bool) nat (@peq bool) (@eq B2) peq_refl' peq_sym'
                    (@eq_refl B2) (@eq_sym B2) (rok sfc) (rstep xorb) (mok cts)
                    (mstep B2 B2 cu (nat -> bool) flagloc) x y)). split.
    - apply (proj2 (rquiet_iff xorb sfc x)). intros [[u v] g] Hin. simpl in Hin. unfold sat.
      destruct Hin as [E | [E | [E | []]]]; injection E as <- <- <-; rewrite !Hx; reflexivity.
    - intros j Hj. unfold mstep, flagloc. rewrite Hx. destruct Hj as [<- | [<- | []]];
        destruct Hy as [-> | ->]; reflexivity. }
  pose proof (proj2 (H (gt0, (false, false))) w1 w2 O1 O2) as U.
  assert (R1 : snd (run flagC w1 (gt0, (false, false))) = (true, true)) by reflexivity.
  assert (R2 : snd (run flagC w2 (gt0, (false, false))) = (false, false)) by reflexivity.
  assert (F1 : forall k, fst (run flagC w1 (gt0, (false, false))) k = false).
  { intros [| [| [| k]]]; reflexivity. }
  assert (F2 : forall k, fst (run flagC w2 (gt0, (false, false))) k = false).
  { intros [| [| [| k]]]; reflexivity. }
  destruct (U (Qx _ F1 (or_introl R1)) (Qx _ F2 (or_intror R2))) as [_ E].
  rewrite R1, R2 in E. discriminate E.
Qed.

(* ========================================================================================= *)
(* PART C. Gap 5: a cyclic MONOTONE J under collapse, FedMachine model.                      *)
(* ========================================================================================= *)

Section Bekic.
  Variables Loc X Y : Type.
  Variable leX : X -> X -> Prop.
  Variable leY : Y -> Y -> Prop.
  Hypothesis leX_refl : forall x, leX x x.
  Hypothesis leX_antisym : forall x y, leX x y -> leX y x -> x = y.
  Hypothesis leY_refl : forall y, leY y y.
  Hypothesis leY_trans : forall x y z, leY x y -> leY y z -> leY x z.
  Hypothesis leY_antisym : forall x y, leY x y -> leY y x -> x = y.
  Variable rankY : Y -> nat.
  Hypothesis rankY_strict : forall x y, leY x y -> x <> y -> rankY x < rankY y.
  Variable Ydec : forall x y : Y, {x = y} + {x <> y}.

  (* The triangular repair: the upstream block X does not read Y. *)
  Variable FA : Loc -> X -> X.
  Variable FB : Loc -> X -> Y -> Y.
  Hypothesis FB_mono : forall l x x' y y', leX x x' -> leY y y' -> leY (FB l x y) (FB l x' y').

  Definition leP (p q : X * Y) : Prop := leX (fst p) (fst q) /\ leY (snd p) (snd q).
  Definition FP (l : Loc) (p : X * Y) : X * Y := (FA l (fst p), FB l (fst p) (snd p)).

  Lemma leP_antisym : forall p q, leP p q -> leP q p -> p = q.
  Proof.
    intros [a b] [c d] [H1 H2] [H3 H4]. simpl in *. f_equal; [apply leX_antisym | apply leY_antisym]; assumption.
  Qed.

  (* Finite height: the least fixed point is below every pre-fixed point. *)
  Lemma lfp_below_prefixed : forall (g : Y -> Y) b, (forall y y', leY y y' -> leY (g y) (g y')) ->
    is_lfp leY g b -> forall y, leY (g y) y -> leY b y.
  Proof.
    intros g b Hg [Hb Hl] y. induction y as [y IH] using (well_founded_induction (well_founded_ltof Y rankY)).
    intros Hy. destruct (Ydec (g y) y) as [E | N].
    - apply Hl. exact E.
    - assert (Hr : rankY (g y) < rankY y) by (apply rankY_strict; assumption).
      eapply leY_trans; [apply (IH (g y) Hr); apply Hg; exact Hy | exact Hy].
  Qed.

  (* Bekic's principle for a triangular monotone system: the blockwise least fixed points form
     the least fixed point. *)
  Theorem bekic_lfp : forall l a b,
    is_lfp leX (FA l) a -> is_lfp leY (FB l a) b -> is_lfp leP (FP l) (a, b).
  Proof.
    intros l a b [Ha Hal] [Hb Hbl]. split.
    - unfold fixed_point, FP. simpl. unfold fixed_point in Ha, Hb. rewrite Ha, Hb. reflexivity.
    - intros [x y] Hxy. unfold fixed_point, FP in Hxy. simpl in Hxy. injection Hxy as Ex Ey.
      assert (Hax : leX a x) by (apply Hal; exact Ex).
      split; [exact Hax |]. simpl.
      apply (lfp_below_prefixed (FB l a) b (fun y y' H => FB_mono l a a y y' (leX_refl a) H) (conj Hb Hbl) y).
      rewrite <- Ey at 2. apply FB_mono; [exact Hax | apply leY_refl].
  Qed.

  (* ----- the collapsed and the flattened FedMachine ----- *)

  Variable rho1 : Loc * (X * Y) -> Loc * (X * Y).   (* phase 1 *)
  (* The flattened normalizer: the least fixed point of the whole repair (the form of
     FederationEventsCycles.cyc_N_lfp, which gsm's normalizeCyclic satisfies). *)
  Variable Nflat : Loc * (X * Y) -> Loc * (X * Y).
  Hypothesis HNf : forall t, fst (Nflat t) = fst (rho1 t) /\ is_lfp leP (FP (fst (rho1 t))) (snd (Nflat t)).
  (* The collapsed normalizer: each block normalized as one effective registry, J by its own least
     fixed point at its inputs. *)
  Variable NA : Loc -> X.
  Hypothesis HNA : forall l, is_lfp leX (FA l) (NA l).
  Variable NB : Loc -> X -> Y.
  Hypothesis HNB : forall l x, is_lfp leY (FB l x) (NB l x).

  Definition Ncol (t : Loc * (X * Y)) : Loc * (X * Y) :=
    (fst (rho1 t), (NA (fst (rho1 t)), NB (fst (rho1 t)) (NA (fst (rho1 t))))).

  Theorem mono_collapse_nf : forall t, Ncol t = Nflat t.
  Proof.
    intros t. destruct (HNf t) as [E L]. unfold Ncol. destruct (Nflat t) as [l' p]. simpl in E, L. subst l'.
    f_equal. apply (lfp_unique leP leP_antisym (FP (fst (rho1 t)))); [| exact L].
    apply bekic_lfp; [apply HNA | apply HNB].
  Qed.

  Theorem mono_collapse_runs_agree : forall (E : Type) (ev : E -> Loc * (X * Y) -> Loc * (X * Y)) es s,
    grun _ E Ncol ev es s = grun _ E Nflat ev es s.
  Proof.
    intros E ev es. unfold grun, runT. induction es as [| e es IH]; intros s; [reflexivity |].
    simpl. replace (gstep _ E Ncol ev e s) with (gstep _ E Nflat ev e s); [apply IH |].
    unfold gstep. symmetry. apply mono_collapse_nf.
  Qed.

  (* N' converges iff N does, and both exactly when the global condition holds. *)
  Theorem mono_collapse_converges_iff : forall (E : Type) ev reg (I : E -> E -> Prop) s0,
    Converges _ E Ncol ev reg I s0 <-> Converges _ E Nflat ev reg I s0.
  Proof.
    intros E ev reg I s0. unfold Converges. split; intros H es1 es2 Ht;
      [rewrite <- !mono_collapse_runs_agree | rewrite !mono_collapse_runs_agree]; apply H; exact Ht.
  Qed.

  Theorem mono_collapse_exact : forall (E : Type) ev reg (I : E -> E -> Prop) s0,
    (Converges _ E Ncol ev reg I s0 <-> GC _ E Nflat ev reg I s0) /\
    (GC _ E Ncol ev reg I s0 <-> GC _ E Nflat ev reg I s0).
  Proof.
    intros E ev reg I s0. rewrite mono_collapse_converges_iff, <- gc_iff. split; [tauto |].
    rewrite !gc_iff. apply mono_collapse_converges_iff.
  Qed.
End Bekic.

(* Non-vacuity: a root (registry 0, shared flag copying its local) feeding the flag cycle
   (registries 1 and 2, each one's flag fed by the other and by the root). The flattened
   normalizer is gsm's normalizeCyclic (Ncyc_with) on the three targets. *)
Definition ble (a b : bool) : Prop := implb a b = true.
Definition L3 : Type := (bool * B2)%type.
Definition gFA (l : L3) (_ : bool) : bool := fst l.
Definition gFB (l : L3) (x : bool) (y : B2) : B2 := (snd (snd l) || snd y || x, fst (snd l) || fst y).
Definition gle (p q : bool * B2) : Prop := leP bool B2 ble cle p q.
Definition gF (l : L3) (p : bool * B2) : bool * B2 := FP L3 bool B2 gFA gFB l p.
Definition gu (l : L3) (j : nat) (p : bool * B2) : bool * B2 :=
  match j with
  | 0 => (fst (gF l p), snd p)
  | 1 => (fst p, (fst (snd (gF l p)), snd (snd p)))
  | 2 => (fst p, (fst (snd p), snd (snd (gF l p))))
  | _ => p
  end.
Definition grank (p : bool * B2) : nat := (if fst p then 1 else 0) + crank (snd p).
Definition gbot : bool * B2 := (false, (false, false)).
Definition g_dec : forall x y : bool * B2, {x = y} + {x <> y}.
Proof. decide equality; [apply ceq_dec | apply bool_dec]. Defined.
Definition gts : list nat := [0; 1; 2].
Definition gN : L3 * (bool * B2) -> L3 * (bool * B2) := Ncyc_with L3 (bool * B2) gbot g_dec gu (fun s => s) 4 gts.
Definition gNA (l : L3) : bool := fst l.
Definition gNB (l : L3) (x : bool) : B2 := let c := fst (snd l) || snd (snd l) || x in (c, c).

Ltac bfg := repeat match goal with
  | x : L3 |- _ => destruct x
  | x : bool * B2 |- _ => destruct x
  | x : B2 |- _ => destruct x
  | b : bool |- _ => destruct b
  end.

Lemma gle_refl : forall x, gle x x. Proof. intros; bfg; unfold gle, leP, ble, cle; simpl; tauto. Qed.
Lemma gle_trans : forall x y z, gle x y -> gle y z -> gle x z.
Proof. intros x y z; bfg; unfold gle, leP, ble, cle; simpl; intuition congruence. Qed.
Lemma gbot_least : forall x, gle gbot x. Proof. intros; bfg; unfold gle, leP, ble, cle; simpl; tauto. Qed.
Lemma grank_strict : forall x y, gle x y -> x <> y -> grank x < grank y.
Proof. intros x y; bfg; unfold gle, leP, ble, cle, grank, crank; simpl; intuition (try congruence; try lia). Qed.
Lemma grank_bound : forall x, grank x <= 3. Proof. intros; bfg; unfold grank, crank; simpl; lia. Qed.
Lemma gu_incr : forall l j x, sound L3 (bool * B2) gle gF l x -> gle x (gu l j x).
Proof. intros l [| [| [| j]]] x; bfg; unfold sound, gle, leP, ble, cle, gu, gF, FP, gFA, gFB; simpl; intuition. Qed.
Lemma gu_sound : forall l j x, sound L3 (bool * B2) gle gF l x -> sound L3 (bool * B2) gle gF l (gu l j x).
Proof. intros l [| [| [| j]]] x; bfg; unfold sound, gle, leP, ble, cle, gu, gF, FP, gFA, gFB; simpl; intuition. Qed.
Lemma gu_mono : forall l j x y, gle x y -> gle (gu l j x) (gu l j y).
Proof. intros l [| [| [| j]]] x y; bfg; unfold gle, leP, ble, cle, gu, gF, FP, gFA, gFB; simpl; intuition. Qed.
Lemma gu_fixed : forall l j x, gF l x = x -> gu l j x = x.
Proof. intros l [| [| [| j]]] x; bfg; unfold gu, gF, FP, gFA, gFB; simpl; intro H; first [reflexivity | congruence]. Qed.
Lemma gts_cover : Cover L3 (bool * B2) gF gu gts.
Proof.
  intros l x H. pose proof (H 0 (or_introl eq_refl)) as H0. pose proof (H 1 (or_intror (or_introl eq_refl))) as H1.
  pose proof (H 2 (or_intror (or_intror (or_introl eq_refl)))) as H2.
  revert H0 H1 H2. bfg; unfold gu, gF, FP, gFA, gFB; simpl; intros H0 H1 H2; first [reflexivity | congruence].
Qed.

Theorem mono_collapse_instance :
  (forall t, Ncol L3 bool B2 (fun s => s) gNA gNB t = gN t) /\
  gN ((true, (false, false)), (false, (false, false))) = ((true, (false, false)), (true, (true, true))) /\
  gN ((false, (false, false)), (true, (true, true))) = ((false, (false, false)), (false, (false, false))).
Proof.
  split; [| split; reflexivity].
  apply (mono_collapse_nf L3 bool B2 ble cle (fun x => ltac:(destruct x; reflexivity))
           (fun x y => ltac:(destruct x, y; unfold ble; simpl; congruence)) cle_refl cle_trans cle_antisym
           crank crank_strict ceq_dec gFA gFB).
  - intros l x x' y y' Hx Hy. revert Hx Hy. bfg; unfold ble, cle, gFB; simpl; intuition.
  - intros t. exact (cyc_N_lfp L3 (bool * B2) gle gle_refl gle_trans gbot gbot_least grank grank_strict 3
                       grank_bound g_dec gF gu gu_incr gu_sound gu_mono gu_fixed (fun s => s) 4 ltac:(lia) gts
                       gts_cover t).
  - intros l. split; [reflexivity |]. intros x Hx. unfold fixed_point, gFA in Hx. subst x. unfold ble, gNA. destruct (fst l); reflexivity.
  - intros l x. split.
    + unfold fixed_point, gNB, gFB. bfg; reflexivity.
    + intros [a b] H. revert H. bfg; unfold fixed_point, gFB, gNB, cle; simpl; intro H;
        try discriminate H; split; reflexivity.
Qed.

(* ========================================================================================= *)
(* PART D. The distributed model: collapse when J's propagation interleaves with events.     *)
(* ========================================================================================= *)

Section DistAtoms.
  Variable V : Type.
  Variable src : nat -> list nat.
  Variable f : nat -> (nat -> V) -> V -> V.
  Variable valid : nat -> V -> Prop.
  Variable rho : nat -> V -> V.
  Variable E : Type.
  Variable reg : E -> nat.
  Variable sig : E -> V -> V.
  Variable I : E -> E -> Prop.
  Variable o : list nat.
  Hypothesis HC : Common V src f valid rho E reg sig o.

  Local Notation feqF := (feq V).
  Local Notation InvF := (Inv V valid).
  Local Notation nF := (N V f rho o).
  Local Notation frF := (frun V f).
  Local Notation rF := (runF V f rho E reg sig o).
  Local Notation aF := (applyF V f rho E reg sig o).
  Local Notation evF := (evstep V E reg sig).
  Local Notation dF := (drun V f E reg sig).
  Local Notation DE := (DEv E).
  Local Notation DP := (DProp E).
  Local Notation evsF := (evs E).
  Local Notation IfedF := (Ifed E reg I).
  Local Notation XUatF := (XUat V f rho E reg sig o).

  Lemma dA_app : forall p q t, dF (p ++ q) t = dF q (dF p t).
  Proof. induction p as [| a p IH]; intros q t; [reflexivity |]. simpl. apply IH. Qed.

  Lemma dA_props : forall l t, dF (map DP l) t = frF l t.
  Proof. induction l as [| a l IH]; intros t; [reflexivity |]. simpl. rewrite IH. reflexivity. Qed.

  Lemma evsA_app : forall p q, evsF (p ++ q) = evsF p ++ evsF q.
  Proof. induction p as [| a p IH]; intros q; [reflexivity |]. destruct a; simpl; rewrite IH; reflexivity. Qed.

  Lemma evsA_props : forall l, evsF (map DP l) = [].
  Proof. induction l as [| a l IH]; [reflexivity | exact IH]. Qed.

  Lemma props_flush : forall l t, InvF t -> incl l o -> feqF (nF (frF l t)) (nF t).
  Proof.
    induction l as [| a l IH]; intros t Ht Hl; [intro k; reflexivity |].
    change (frF (a :: l) t) with (frF l (fstep V f t a)).
    eapply feq_trans; [apply IH; [apply (fstep_inv _ _ _ _ _ _ _ _ _ HC); exact Ht | intros x Hx; apply Hl; right; exact Hx] |].
    apply (flush_prop _ _ _ _ _ _ _ _ _ HC); [exact Ht | apply Hl; left; reflexivity].
  Qed.

  (* ----- an atom set: every event, propagation words, and a flush ----- *)
  Variable At : list (act E) -> Prop.
  Hypothesis at_ev : forall e, At [DE e].
  Hypothesis at_shape : forall a, At a -> (exists e, a = [DE e]) \/ (exists l, a = map DP l /\ incl l o).
  Variable fl : list (list (act E)).
  Hypothesis fl_ok : Forall At fl.
  Variable lf : list nat.
  Hypothesis fl_word : concat fl = map DP lf.
  Hypothesis fl_flush : forall t, InvF t -> feqF (frF lf t) (frF o t).

  (* Convergence over the atom words, compared after the final flush, and XU at the states they
     reach. *)
  Definition DistConvA (s0 : nat -> V) : Prop :=
    forall ws1 ws2, Forall At ws1 -> Forall At ws2 -> tequiv IfedF (evsF (concat ws1)) (evsF (concat ws2)) ->
      feqF (nF (dF (concat ws1) s0)) (nF (dF (concat ws2) s0)).

  Definition XURA (s0 : nat -> V) : Prop :=
    forall ws e, Forall At ws -> XUatF (dF (concat ws) s0) e.

  Lemma flushA : forall s0, InvF s0 -> XURA s0 -> forall ws q, Forall At q -> Forall At ws ->
    feqF (nF (dF (concat ws) (dF (concat q) s0))) (rF (evsF (concat ws)) (nF (dF (concat q) s0))).
  Proof.
    intros s0 Hi Hx ws. induction ws as [| a ws IH]; intros q Hq Hw; [intro k; reflexivity |].
    inversion Hw as [| ? ? Ha Hw']; subst.
    assert (Hqa : Forall At (q ++ [a])) by (apply Forall_app; split; [exact Hq | constructor; [exact Ha | constructor]]).
    set (t := dF (concat q) s0).
    assert (It : InvF t) by (apply (drun_inv _ _ _ _ _ _ _ _ _ HC); exact Hi).
    assert (Ea : dF a t = dF (concat (q ++ [a])) s0) by (rewrite concat_app, dA_app; simpl; rewrite app_nil_r; reflexivity).
    simpl. rewrite dA_app, Ea.
    eapply feq_trans; [exact (IH (q ++ [a]) Hqa Hw') |]. rewrite <- Ea.
    rewrite evsA_app. destruct (at_shape a Ha) as [[e ->] | [l [-> Hl]]].
    - simpl. apply (runF_ext _ _ _ _ _ _ _ _ _ HC). apply (flush_ev_at _ _ _ _ _ _ _ _ _ HC); [exact It |].
      apply Hx. exact Hq.
    - rewrite evsA_props. simpl. apply (runF_ext _ _ _ _ _ _ _ _ _ HC). rewrite dA_props.
      apply props_flush; assumption.
  Qed.

  Lemma flushA0 : forall s0, InvF s0 -> XURA s0 -> forall ws, Forall At ws ->
    feqF (nF (dF (concat ws) s0)) (rF (evsF (concat ws)) (nF s0)).
  Proof. intros s0 Hi Hx ws Hw. exact (flushA s0 Hi Hx ws [] (Forall_nil _) Hw). Qed.

  Definition evatoms (es : list E) : list (list (act E)) := map (fun e => [DE e]) es.

  Lemma evatoms_ok : forall es, Forall At (evatoms es).
  Proof. induction es as [| e es IH]; constructor; [apply at_ev | exact IH]. Qed.

  Lemma evatoms_concat : forall es, concat (evatoms es) = map DE es.
  Proof. induction es as [| e es IH]; [reflexivity | simpl; rewrite IH; reflexivity]. Qed.

  Lemma evs_map : forall es, evsF (map DE es) = es.
  Proof. induction es as [| e es IH]; [reflexivity | simpl; rewrite IH; reflexivity]. Qed.

  (* The flush word, from a reachable state, lands on the flushed state. *)
  Lemma fl_lands : forall t, InvF t -> feqF (dF (concat fl) t) (nF t).
  Proof.
    intros t Ht. rewrite fl_word, dA_props. eapply feq_trans; [exact (fl_flush t Ht) |].
    apply feq_sym. exact (N_frun _ _ _ _ _ _ _ _ _ HC t Ht).
  Qed.

  Lemma xura_nec : forall s0, InvF s0 -> DistConvA s0 -> XURA s0.
  Proof.
    intros s0 Hi Hd ws e Hw. unfold XUat.
    set (t := dF (concat ws) s0).
    assert (It : InvF t) by (apply (drun_inv _ _ _ _ _ _ _ _ _ HC); exact Hi).
    assert (O1 : Forall At (ws ++ [[DE e]])) by (apply Forall_app; split; [exact Hw | repeat constructor; apply at_ev]).
    assert (O2 : Forall At (ws ++ fl ++ [[DE e]]))
      by (apply Forall_app; split; [exact Hw | apply Forall_app; split; [exact fl_ok | repeat constructor; apply at_ev]]).
    assert (Ev : evsF (concat (ws ++ [[DE e]])) = evsF (concat (ws ++ fl ++ [[DE e]]))).
    { rewrite !concat_app, !evsA_app, fl_word, evsA_props. reflexivity. }
    pose proof (Hd _ _ O1 O2 (eq_rect _ (fun l => tequiv IfedF (evsF (concat (ws ++ [[DE e]]))) l)
                                (teq_refl IfedF _) _ Ev) (reg e)) as H.
    rewrite !concat_app, !dA_app in H. simpl in H. rewrite ?app_nil_r in H. fold t in H.
    change (dF [DE e] t) with (evF e t) in H.
    set (u := dF (concat fl) t) in H.
    change (dF [DE e] u) with (evF e u) in H.
    assert (Hu : feqF u (nF t)) by (apply fl_lands; exact It).
    assert (Iu : InvF u) by (apply (drun_inv _ _ _ _ _ _ _ _ _ HC); exact It).
    assert (In_ : InvF (nF t)) by (apply (N_inv _ _ _ _ _ _ _ _ _ HC); exact It).
    assert (Nn : feqF (nF u) (nF t)).
    { eapply feq_trans; [apply (N_ext _ _ _ _ _ _ _ _ _ HC); exact Hu |].
      apply (N_self _ _ _ _ _ _ _ _ _ HC); [exact In_ | apply (N_cons _ _ _ _ _ _ _ _ _ HC); exact It]. }
    rewrite (N_ev_at _ _ _ _ _ _ _ _ _ HC e t It), (N_ev_at _ _ _ _ _ _ _ _ _ HC e u Iu) in H.
    rewrite (f_ext _ _ _ _ _ _ _ _ _ HC (reg e) _ _ _ Nn), (Hu (reg e)) in H.
    rewrite (N_at _ _ _ _ _ _ _ _ _ HC t (reg e) It (c_reg _ _ _ _ _ _ _ _ _ HC e)) in H.
    symmetry. exact H.
  Qed.

  Lemma tc_nec : forall s0, InvF s0 -> DistConvA s0 -> XURA s0 -> TraceConv V f rho E reg sig I o (nF s0).
  Proof.
    intros s0 Hi Hd Hx es1 es2 H.
    pose proof (flushA0 s0 Hi Hx _ (evatoms_ok es1)) as A1.
    pose proof (flushA0 s0 Hi Hx _ (evatoms_ok es2)) as A2.
    rewrite evatoms_concat, evs_map in A1, A2.
    assert (Ht : tequiv IfedF (evsF (concat (evatoms es1))) (evsF (concat (evatoms es2))))
      by (rewrite !evatoms_concat, !evs_map; exact H).
    pose proof (Hd _ _ (evatoms_ok es1) (evatoms_ok es2) Ht) as D. rewrite !evatoms_concat in D.
    eapply feq_trans; [apply feq_sym; exact A1 |]. eapply feq_trans; [exact D | exact A2].
  Qed.

  Lemma xura_c1r1 : forall s0, InvF s0 -> XURA s0 -> C1R1 V f rho E reg sig o (nF s0).
  Proof.
    intros s0 Hi Hx q e a Ne. unfold C1at.
    set (s := rF q (nF s0)).
    set (ws := evatoms q ++ fl).
    assert (Hws : Forall At ws) by (apply Forall_app; split; [apply evatoms_ok | exact fl_ok]).
    set (u := dF (concat ws) s0).
    assert (Hu : feqF u s).
    { unfold u, ws. rewrite concat_app, dA_app, evatoms_concat.
      assert (Iq : InvF (dF (map DE q) s0)) by (apply (drun_inv _ _ _ _ _ _ _ _ _ HC); exact Hi).
      eapply feq_trans; [apply fl_lands; exact Iq |].
      pose proof (flushA0 s0 Hi Hx _ (evatoms_ok q)) as A. rewrite evatoms_concat, evs_map in A. exact A. }
    pose proof (Hx (ws ++ [[DE a]]) e ltac:(apply Forall_app; split; [exact Hws | repeat constructor; apply at_ev])) as X.
    rewrite concat_app, dA_app in X. simpl in X. rewrite ?app_nil_r in X. fold u in X.
    change (dF [DE a] u) with (evF a u) in X. unfold XUat in X.
    assert (Na : feqF (nF (evF a u)) (aF a s)).
    { unfold applyF. apply (N_ext _ _ _ _ _ _ _ _ _ HC). apply (evstep_ext V E reg sig). exact Hu. }
    rewrite !(f_ext _ _ _ _ _ _ _ _ _ HC (reg e) _ _ _ Na) in X.
    rewrite (evstep_off V E reg sig a u (reg e) (fun H => Ne (eq_sym H))) in X.
    rewrite (Hu (reg e)) in X. exact X.
  Qed.

  (* Headline (b), generic form: over any atom set with every event and a flush, convergence is
     reachable XU over its words plus the FedMachine's C2 at states reachable from the flushed
     start. *)
  Theorem dist_atoms_exact : forall s0, InvF s0 ->
    (DistConvA s0 <-> XURA s0 /\ C2R V f rho E reg sig I o (nF s0)).
  Proof.
    intros s0 Hi.
    assert (In_ : InvF (nF s0)) by (apply (N_inv _ _ _ _ _ _ _ _ _ HC); exact Hi).
    assert (Cn : Cons V f o (nF s0)) by (apply (N_cons _ _ _ _ _ _ _ _ _ HC); exact Hi).
    split.
    - intros Hd. assert (Hx : XURA s0) by (apply xura_nec; assumption).
      split; [exact Hx |].
      exact (proj2 (proj1 (fed_exact _ _ _ _ _ _ _ _ _ _ HC (nF s0) In_ Cn) (tc_nec s0 Hi Hd Hx))).
    - intros [Hx H2] ws1 ws2 H1 H2' Hq.
      assert (Ht : TraceConv V f rho E reg sig I o (nF s0)).
      { apply (proj2 (fed_exact _ _ _ _ _ _ _ _ _ _ HC (nF s0) In_ Cn)). split; [apply xura_c1r1; assumption | exact H2]. }
      eapply feq_trans; [exact (flushA0 s0 Hi Hx ws1 H1) |].
      eapply feq_trans; [exact (Ht _ _ Hq) | apply feq_sym; exact (flushA0 s0 Hi Hx ws2 H2')].
  Qed.
End DistAtoms.

(* dist_exact recovered: N's own words are the singleton atoms. *)
Section DistRecovered.
  Variable V : Type.
  Variable src : nat -> list nat.
  Variable f : nat -> (nat -> V) -> V -> V.
  Variable valid : nat -> V -> Prop.
  Variable rho : nat -> V -> V.
  Variable E : Type.
  Variable reg : E -> nat.
  Variable sig : E -> V -> V.
  Variable I : E -> E -> Prop.
  Variable o : list nat.
  Hypothesis HC : Common V src f valid rho E reg sig o.

  Definition At1 (a : list (act E)) : Prop := exists x, a = [x] /\ okact E o x.

  Lemma single_concat : forall w : list (act E), concat (map (fun x => [x]) w) = w.
  Proof. induction w as [| x w IH]; [reflexivity | simpl; rewrite IH; reflexivity]. Qed.

  Lemma single_ok : forall w, Forall (okact E o) w -> Forall At1 (map (fun x => [x]) w).
  Proof.
    induction w as [| x w IH]; intros H; [constructor |]. inversion H; subst.
    constructor; [exists x; split; [reflexivity | assumption] | apply IH; assumption].
  Qed.

  Lemma At1_ok : forall ws, Forall At1 ws -> Forall (okact E o) (concat ws).
  Proof.
    induction ws as [| a ws IH]; intros H; [constructor |]. inversion H as [| ? ? [x [-> Hx]] Hw]; subst.
    simpl. constructor; [exact Hx | apply IH; exact Hw].
  Qed.

  Theorem dist_exact_recovered : forall s0, Inv V valid s0 ->
    (DistConv V f rho E reg sig I o s0 <-> XUR V f rho E reg sig o s0 /\ C2R V f rho E reg sig I o (N V f rho o s0)).
  Proof.
    intros s0 Hi.
    assert (Hd : DistConv V f rho E reg sig I o s0 <-> DistConvA V f rho E reg sig I o At1 s0).
    { split.
      - intros H ws1 ws2 H1 H2 Ht. apply H; [apply At1_ok; exact H1 | apply At1_ok; exact H2 | exact Ht].
      - intros H w1 w2 H1 H2 Ht. rewrite <- (single_concat w1), <- (single_concat w2).
        apply H; [apply single_ok; exact H1 | apply single_ok; exact H2 | rewrite !single_concat; exact Ht]. }
    assert (Hx : XUR V f rho E reg sig o s0 <-> XURA V f rho E reg sig o At1 s0).
    { split.
      - intros H ws e Hw. apply H. apply At1_ok. exact Hw.
      - intros H p e Hp. rewrite <- (single_concat p). apply H. apply single_ok. exact Hp. }
    rewrite Hd, Hx.
    apply (dist_atoms_exact V src f valid rho E reg sig I o HC At1) with (fl := map (fun x => [x]) (map (DProp E) o)) (lf := o).
    - intros e. exists (DEv E e). split; [reflexivity | exact Logic.I].
    - intros a [[e | j] [-> Hx']]; [left; exists e; reflexivity | right; exists [j]; split; [reflexivity |]].
      intros k [<- | []]. exact Hx'.
    - apply (single_ok (map (DProp E) o)). apply Forall_forall. intros x Hx'. apply in_map_iff in Hx'.
      destruct Hx' as [j [<- Hj]]. exact Hj.
    - apply single_concat.
    - intros t _ k. reflexivity.
    - exact Hi.
  Qed.
End DistRecovered.

(* ----- the collapsed distributed network N': J propagates as one atom ----- *)

Section DistCollapse.
  Variable V : Type.
  Variable src : nat -> list nat.
  Variable f : nat -> (nat -> V) -> V -> V.
  Variable valid : nat -> V -> Prop.
  Variable rho : nat -> V -> V.
  Variable E : Type.
  Variable reg : E -> nat.
  Variable sig : E -> V -> V.
  Variable I : E -> E -> Prop.
  Variable o : list nat.
  Hypothesis HC : Common V src f valid rho E reg sig o.
  Variable inJ : nat -> bool.
  Hypothesis Hconv : Convex src inJ.

  Local Notation DE := (DEv E).
  Local Notation DP := (DProp E).
  Local Notation B := (blk inJ o).

  (* N''s atoms: an event; a propagation step of a registry outside J; J's whole internal repair,
     its block in order, as one step. *)
  Definition AtC (a : list (act E)) : Prop :=
    (exists e, a = [DE e]) \/ (exists j, a = [DP j] /\ In j o /\ inJ j = false) \/ a = map DP B.

  Definition flC : list (list (act E)) :=
    map (fun j => [DP j]) (preJ src inJ o) ++ [map DP B] ++ map (fun j => [DP j]) (postJ src inJ o).

  Lemma concat_single : forall l, concat (map (fun j => [DP j]) l) = map DP l.
  Proof. induction l as [| a l IH]; [reflexivity | simpl; rewrite IH; reflexivity]. Qed.

  Lemma flC_word : concat flC = map DP (blockOrder src inJ o).
  Proof.
    unfold flC, blockOrder. rewrite !concat_app, !concat_single, !map_app. simpl. rewrite app_nil_r. reflexivity.
  Qed.

  Lemma htopo : topoF src o. Proof. exact (c_topo _ _ _ _ _ _ _ _ _ HC). Qed.

  Lemma flC_ok : Forall AtC flC.
  Proof.
    unfold flC. apply Forall_app. split; [| apply Forall_app; split].
    - apply Forall_forall. intros a Ha. apply in_map_iff in Ha. destruct Ha as [j [<- Hj]].
      apply in_preJ in Hj. right. left. exists j. split; [reflexivity | split; apply Hj].
    - constructor; [right; right; reflexivity | constructor].
    - apply Forall_forall. intros a Ha. apply in_map_iff in Ha. destruct Ha as [j [<- Hj]].
      apply in_postJ in Hj. right. left. exists j. split; [reflexivity | split; [apply Hj |]].
      apply (desc_notJ src inJ o htopo). apply Hj.
  Qed.

  Lemma AtC_shape : forall a, AtC a -> (exists e, a = [DE e]) \/ (exists l, a = map DP l /\ incl l o).
  Proof.
    intros a [H | [[j [-> [Hj _]]] | ->]]; [left; exact H | right | right].
    - exists [j]. split; [reflexivity | intros x [<- | []]; exact Hj].
    - exists B. split; [reflexivity |]. intros x Hx. apply in_blk in Hx. apply Hx.
  Qed.

  Lemma flC_flush : forall t, Inv V valid t -> feq V (frun V f (blockOrder src inJ o) t) (frun V f o t).
  Proof.
    intros t _. destruct (Hbo V src f valid rho E reg sig o HC inJ Hconv) as [T P].
    apply (frun_topo_eq V src f valid rho E reg sig o HC); [exact T | exact htopo |].
    intros k. split; apply Permutation.Permutation_in; [apply Permutation.Permutation_sym |]; exact P.
  Qed.

  Definition DistConvC (s0 : nat -> V) : Prop := DistConvA V f rho E reg sig I o AtC s0.
  Definition XURC (s0 : nat -> V) : Prop := XURA V f rho E reg sig o AtC s0.

  (* The exact condition for N'. *)
  Theorem dist_collapse_exact : forall s0, Inv V valid s0 ->
    (DistConvC s0 <-> XURC s0 /\ C2R V f rho E reg sig I o (N V f rho o s0)).
  Proof.
    intros s0 Hi.
    exact (dist_atoms_exact V src f valid rho E reg sig I o HC AtC (fun e => or_introl (ex_intro _ e eq_refl))
             AtC_shape flC flC_ok (blockOrder src inJ o) flC_word flC_flush s0 Hi).
  Qed.

  Lemma AtC_ok : forall ws, Forall AtC ws -> Forall (okact E o) (concat ws).
  Proof.
    induction ws as [| a ws IH]; intros H; [constructor |]. inversion H as [| ? ? Ha Hw]; subst.
    simpl. apply Forall_app. split; [| apply IH; exact Hw].
    destruct Ha as [[e ->] | [[j [-> [Hj _]]] | ->]]; [repeat constructor | repeat constructor; exact Hj |].
    apply Forall_forall. intros x Hx. apply in_map_iff in Hx. destruct Hx as [j [<- Hj]].
    apply in_blk in Hj. apply Hj.
  Qed.

  (* N converges -> N' converges: every N' word is an N word. *)
  Theorem dist_collapse_sound : forall s0, DistConv V f rho E reg sig I o s0 -> DistConvC s0.
  Proof. intros s0 H ws1 ws2 H1 H2 Ht. apply H; [apply AtC_ok; exact H1 | apply AtC_ok; exact H2 | exact Ht]. Qed.

  Lemma xur_xurc : forall s0, XUR V f rho E reg sig o s0 -> XURC s0.
  Proof. intros s0 H ws e Hw. apply H. apply AtC_ok. exact Hw. Qed.

  (* Headline (b): N converges iff N' does and XU holds at every state N reaches, J
     half-propagated included. *)
  Theorem dist_collapse_iff : forall s0, Inv V valid s0 ->
    (DistConv V f rho E reg sig I o s0 <-> DistConvC s0 /\ XUR V f rho E reg sig o s0).
  Proof.
    intros s0 Hi. rewrite (dist_exact V src f valid rho E reg sig I o HC s0 Hi). split.
    - intros [Hx H2]. split; [| exact Hx]. apply (proj2 (dist_collapse_exact s0 Hi)).
      split; [apply xur_xurc; exact Hx | exact H2].
    - intros [Hc Hx]. split; [exact Hx | exact (proj2 (proj1 (dist_collapse_exact s0 Hi) Hc))].
  Qed.

  (* Under static XU (gsm's ProjectionSafe check), collapse is preserved in the distributed model. *)
  Theorem dist_collapse_xu : XU V f valid E reg sig -> forall s0, Inv V valid s0 ->
    (DistConvC s0 <-> DistConv V f rho E reg sig I o s0).
  Proof.
    intros HX s0 Hi. rewrite (dist_collapse_iff s0 Hi).
    pose proof (xu_xur V src f valid rho E reg sig o HC HX s0 Hi). tauto.
  Qed.
End DistCollapse.

(* ----- counterexamples ----- *)

(* The chain 0 -> 1 -> 2 (Collapse.v's chain_src), J = {1, 2}. Values (shared, local). Registry 1
   copies 0's shared value, 2 copies 1's. Seven (on 1) writes 7 into 1's shared part; Bump (on 2)
   counts, but only at shared value 7. No N' run puts 7 into 2: J's atom repairs 1 before it
   copies 1 into 2. An N run can: Seven, then propagate 2 alone. *)
Definition ch_f (j : nat) (z : nat -> nat * nat) (x : nat * nat) : nat * nat :=
  match j with 1 => (fst (z 0), snd x) | 2 => (fst (z 1), snd x) | _ => x end.
Definition ch_valid (_ : nat) (_ : nat * nat) : Prop := True.
Definition ch_rho (_ : nat) (x : nat * nat) : nat * nat := x.
Inductive chev : Type := Seven | Bump.
Definition ch_reg (e : chev) : nat := match e with Seven => 1 | Bump => 2 end.
Definition ch_sig (e : chev) (x : nat * nat) : nat * nat :=
  match e with Seven => (7, snd x) | Bump => if Nat.eqb (fst x) 7 then (fst x, S (snd x)) else x end.
Definition ch_I (_ _ : chev) : Prop := True.
Definition ch_o : list nat := [0; 1; 2].
Definition j12 (v : nat) : bool := match v with 1 | 2 => true | _ => false end.
Definition ch_s0 (_ : nat) : nat * nat := (0, 0).

Lemma ch_common : Common (nat * nat) chain_src ch_f ch_valid ch_rho chev ch_reg ch_sig ch_o.
Proof.
  constructor.
  - intros [| [| [| j]]] z1 z2 x H; simpl; try reflexivity; rewrite H; simpl; auto.
  - simpl. intuition lia.
  - intros; exact I.
  - intros [| [| [| j]]] z z' x _ _ _; reflexivity.
  - intros; reflexivity.
  - intros; exact I.
  - intros []; simpl; tauto.
Qed.

Lemma ch_convex : Convex chain_src j12.
Proof.
  intros u m w _ _ Hm P _. destruct (path_last chain_src u m P) as [y Hy].
  destruct m as [| [| [| m]]]; simpl in Hy; try discriminate Hm; exact Hy.
Qed.

Local Notation chD := (drun (nat * nat) ch_f chev ch_reg ch_sig).

(* The invariant of N' runs from ch_s0: registries 0 and 2 hold shared value 0. *)
Lemma ch_inv : forall ws t, Forall (AtC chev ch_o j12) ws -> fst (t 0) = 0 -> fst (t 2) = 0 ->
  fst (chD (concat ws) t 0) = 0 /\ fst (chD (concat ws) t 2) = 0.
Proof.
  induction ws as [| a ws IH]; intros t Hw H0 H2; [split; assumption |].
  inversion Hw as [| ? ? Ha Hw']; subst. simpl. rewrite dA_app.
  destruct Ha as [[[] ->] | [[j [-> [Hj HjJ]]] | ->]].
  all: apply IH; [exact Hw' | |].
  all: unfold blk, ch_o; simpl; unfold evstep, fstep, FederationEvents.upd; simpl; try assumption.
  all: try (destruct (Nat.eqb (fst (t 2)) 7); simpl; assumption).
  all: destruct Hj as [<- | [<- | [<- | []]]]; try discriminate HjJ; simpl; assumption.
Qed.

Lemma ch_xurc : XURC (nat * nat) ch_f ch_rho chev ch_reg ch_sig ch_o j12 ch_s0.
Proof.
  intros ws e Hw. destruct (ch_inv ws ch_s0 Hw eq_refl eq_refl) as [H0 H2].
  set (t := chD (concat ws) ch_s0) in *. clearbody t. unfold XUat.
  destruct e; simpl.
  - destruct (t 1) as [a b]. reflexivity.
  - unfold N, frun, fstep, FederationEvents.upd, ch_rho; simpl. rewrite H0.
    destruct (t 2) as [a b] eqn:T2. simpl in H2. subst a. reflexivity.
Qed.

Lemma ch_c2r : forall s, C2R (nat * nat) ch_f ch_rho chev ch_reg ch_sig ch_I ch_o s.
Proof. intros s p [] [] E' _; simpl in E'; try discriminate E'; reflexivity. Qed.

(* Headline counterexample (b): the collapsed distributed network converges, the network does not;
   collapse_c's "N' converges iff N does" fails in the distributed model. *)
Theorem dist_collapse_refuted :
  Common (nat * nat) chain_src ch_f ch_valid ch_rho chev ch_reg ch_sig ch_o /\
  Convex chain_src j12 /\
  XURC (nat * nat) ch_f ch_rho chev ch_reg ch_sig ch_o j12 ch_s0 /\
  DistConvC (nat * nat) ch_f ch_rho chev ch_reg ch_sig ch_I ch_o j12 ch_s0 /\
  ~ XUR (nat * nat) ch_f ch_rho chev ch_reg ch_sig ch_o ch_s0 /\
  ~ DistConv (nat * nat) ch_f ch_rho chev ch_reg ch_sig ch_I ch_o ch_s0.
Proof.
  pose proof ch_common as HC. pose proof ch_convex as Hcv.
  assert (Hi : Inv (nat * nat) ch_valid ch_s0) by (intro k; exact I).
  assert (Nd : ~ DistConv (nat * nat) ch_f ch_rho chev ch_reg ch_sig ch_I ch_o ch_s0).
  { intro Hd.
    assert (Ok1 : Forall (okact chev ch_o) [DEv chev Seven; DProp chev 2; DEv chev Bump])
      by (repeat constructor; simpl; tauto).
    assert (Ok2 : Forall (okact chev ch_o) [DEv chev Seven; DEv chev Bump]) by (repeat constructor).
    pose proof (Hd _ _ Ok1 Ok2 (teq_refl _ [Seven; Bump]) 2) as H. vm_compute in H. discriminate H. }
  split; [exact HC |]. split; [exact Hcv |]. split; [exact ch_xurc |]. split.
  - apply (proj2 (dist_collapse_exact (nat * nat) chain_src ch_f ch_valid ch_rho chev ch_reg ch_sig ch_I ch_o
                    HC j12 Hcv ch_s0 Hi)).
    split; [exact ch_xurc | apply ch_c2r].
  - split; [| exact Nd].
    intro Hx. apply Nd. apply (proj2 (dist_exact _ _ _ _ _ _ _ _ _ _ HC ch_s0 Hi)). split; [exact Hx | apply ch_c2r].
Qed.

(* The other conjunct: XU everywhere does not give N' convergence (two events on registry 0, a
   root, declared independent and not commuting: C2 fails). *)
Inductive c2ev : Type := Inc | Dbl.
Definition c2_reg (_ : c2ev) : nat := 0.
Definition c2_sig (e : c2ev) (x : nat * nat) : nat * nat :=
  match e with Inc => (fst x, S (snd x)) | Dbl => (fst x, 2 * snd x) end.
Definition c2_I (_ _ : c2ev) : Prop := True.

Lemma c2_common : Common (nat * nat) chain_src ch_f ch_valid ch_rho c2ev c2_reg c2_sig ch_o.
Proof.
  constructor.
  - intros [| [| [| j]]] z1 z2 x H; simpl; try reflexivity; rewrite H; simpl; auto.
  - simpl. intuition lia.
  - intros; exact I.
  - intros [| [| [| j]]] z z' x _ _ _; reflexivity.
  - intros; reflexivity.
  - intros; exact I.
  - intros []; simpl; tauto.
Qed.

Theorem dist_collapse_needs_c2 :
  Common (nat * nat) chain_src ch_f ch_valid ch_rho c2ev c2_reg c2_sig ch_o /\
  XUR (nat * nat) ch_f ch_rho c2ev c2_reg c2_sig ch_o ch_s0 /\
  ~ DistConvC (nat * nat) ch_f ch_rho c2ev c2_reg c2_sig c2_I ch_o j12 ch_s0.
Proof.
  split; [exact c2_common |]. split; [intros p e _; destruct e; reflexivity |].
  intros H.
  assert (O : forall a b, Forall (AtC c2ev ch_o j12) [[DEv c2ev a]; [DEv c2ev b]])
    by (intros a b; constructor; [left; exists a; reflexivity | constructor; [left; exists b; reflexivity | constructor]]).
  assert (Ht : tequiv (Ifed c2ev c2_reg c2_I) (evs c2ev (concat [[DEv c2ev Inc]; [DEv c2ev Dbl]]))
                 (evs c2ev (concat [[DEv c2ev Dbl]; [DEv c2ev Inc]])))
    by (apply (teq_swap _ [] Inc Dbl []); right; exact I).
  pose proof (H _ _ (O Inc Dbl) (O Dbl Inc) Ht 0) as E. vm_compute in E. discriminate E.
Qed.
