(* PresentedExecution.v: layer A of the regime map, the execution algebra, as a presented
   admissible path system. Axiom-free.

   The question layer A answers: which executions count as the same, and when is the semantics
   invariant under that identification. Executions do not form a free monoid in general: only
   admissible words are executions (causal delivery, typed phases, legal duplicate landings), so
   the structure is an admissible path system. Here a path is a word of labels from a fixed start,
   admissibility is a predicate Adm on words (closed under prefixes where a theorem needs it), and
   the elementary alternative executions are generator pairs Gen p u v: at the point p (an
   admissible prefix) the fragments u and v are interchangeable. Examples: a swap of independent
   events u = [a; b], v = [b; a]; a legal duplicate landing u = [a; a], v = [a]; a switch square
   u = [a; sw], v = [sw; tau a] between typed phases. The generated equivalence PEq is the
   equivalence closure, with every vertex admissible, of the whiskered generators
     p ++ u ++ w  ~  p ++ v ++ w    (Gen p u v, both sides admissible)
   (pre-composition is the choice of the point p, post-composition the continuation w). It is
   CanonicalExecution.AC on the whiskered generators, so every intermediate execution is
   admissible. Free delivery is the degenerate case (Adm everything, Gen independent of the
   point): PEq is then the monoid congruence generated by the generator pairs (free_congruence),
   and with the adjacent swaps it is Permutation (swap_peq_perm).

   The semantics is a map sem from words to values compared by an equivalence eqv (for a state
   machine: sem t = obs (run t s0)). PInv: sem is constant, up to eqv, on PEq classes.

   1. Generic (section Presented).
      - PPC, the continuation closure of the generators: the seeds (p ++ u, p ++ v) with both
        sides admissible, closed under appending the same event to both sides when both stay
        admissible. ReconfigurationClosure.PC is the free instance (amodm_closure_recovered).
        ppc_least: PPC is contained in every relation that contains the seeds and is closed under
        admissible one-event continuation. ppc_iff_whisk: under prefix closure, PPC is exactly the
        set of whiskered generator pairs with both sides admissible.
      - (P2) closure_exact: AdmPrefix -> (PInv <-> PClosOK): invariance holds iff sem agrees on
        the continuation closure.
      - (P1) local_exact: if a predicate Q holds on both sides of every seed, is preserved by
        admissible one-event extension, and the semantics respects the future on Q (eqv-related
        Q-paths stay eqv-related after the same admissible event, RespOn), then
          PInv <-> PSeedOK,
        PSeedOK: every generator pair is observationally equal at its point. local_exact_all is
        Q = everything; seeds_necessary: PInv -> PSeedOK with no hypothesis.
      - Section StateMachine: sem t = obs (run t s0); resp_of_compat derives RespOn from
        compatibility of obs with the steps (the hypothesis of
        ReconfigurationClosure.perm_local_exact).
   2. The seeds alone do not suffice without RespOn (section HiddenWrite): writes to a hidden
      register and a reveal event. hw_seeds_ok: every swap seed is observationally equal at every
      point; hw_not_inv: invariance fails; hw_closure_witness: the closure pair that separates is
      a seed continued by the reveal event. So the continuation closure is needed in P2, and
      RespOn cannot be dropped from P1.
   3. The state side (section StateSide). State descent (CC2 in its all-events form,
      CanonicalExecution.state_descent_iff_cc2) compares the SAME word from a state and from its
      canonical form: it relates two states, not two parallel paths from one point, so it is not
      a generator. It enters through the semantics: state_side_transfer, under StateDescent the
      normalized raw semantics and the governed semantics from N s0 are the same function on
      words, so invariance of one under any path presentation is invariance of the other.
   4. Instances (each recovered statement is proved from P1 or P2).
      - history_descent_recovered: CanonicalExecution.history_descent_exact, through the one-step
        path system (executions as one-letter words; P1 with RespOn vacuous).
      - amodm_closure_recovered, amodm_swap_recovered: ReconfigurationClosure.amodm_closure_exact
        and amodm_swap_exact through P2 (free delivery, adjacent swaps, M not compatible).
      - causal_exact_recovered: GovernanceConverse.causal_exact through P1 (admissibility =
        causal consistency, generators = adjacent concurrent swaps at a causal point).
      - tconv_exact_recovered: AtLeastOnceDeclared.tconv_exact through P1 (declared pairs: the
        trace monoid of I, restricted to causal histories over Ev).
      - causal_alo_idem_recovered, alo_exact_recovered: AtLeastOnceExact.causal_alo_exact_idem
        and alo_exact through P1 (generators = concurrent swaps plus the legal duplicate landing
        [a; a] ~ [a] right after a first delivery).
      - det_live_recovered: Reconfiguration.det_live_exact through P1 with Q = "past the switch"
        (typed phases A, then B; generators = switch squares [LA a; LS] ~ [LS; LT a] and swaps
        after the switch). *)

From Coq Require Import List.
From Coq Require Import Sorting.Permutation.
Require Import NC.Newman NC.Trace NC.CanonicalExecution.
Require NC.CausalReplay NC.GovernanceConverse NC.ReconfigurationClosure NC.CanonicalInstances.
Require NC.AtLeastOnce NC.AtLeastOnceExact NC.AtLeastOnceDeclared NC.Reconfiguration.
Import ListNotations.

(* Every vertex of AC is admissible (stated with explicit arguments). *)
Lemma ac_adm' : forall {T : Type} (Adm : T -> Prop) (G : T -> T -> Prop) t u,
  AC Adm G t u -> Adm t /\ Adm u.
Proof.
  intros T Adm G t u H. induction H as [t Ht | t u Ht Hu _ | t u _ [A1 A2] | t u v _ [A1 _] _ [_ A3]];
    split; assumption.
Qed.

(* ============================================================================================ *)
(* 1. Generic: whiskered generators, the continuation closure, P1 and P2                        *)
(* ============================================================================================ *)

Section Presented.
  Context {L Y : Type}.
  Variable Adm : list L -> Prop.                       (* admissible executions *)
  Variable Gen : list L -> list L -> list L -> Prop.   (* Gen p u v: u, v interchangeable at p *)
  Variable sem : list L -> Y.
  Variable eqv : Y -> Y -> Prop.
  Hypothesis eqv_refl : forall y, eqv y y.
  Hypothesis eqv_sym : forall y z, eqv y z -> eqv z y.
  Hypothesis eqv_trans : forall x y z, eqv x y -> eqv y z -> eqv x z.

  (* Whiskered generators: the point p before, any continuation w after. *)
  Definition Whisk (t t' : list L) : Prop :=
    exists p u v w, Gen p u v /\ t = p ++ u ++ w /\ t' = p ++ v ++ w.

  (* The generated equivalence: every vertex admissible. *)
  Definition PEq : list L -> list L -> Prop := AC Adm Whisk.

  Definition PInv : Prop := forall t t', PEq t t' -> eqv (sem t) (sem t').

  Definition AdmPrefix : Prop := forall t w, Adm (t ++ w) -> Adm t.

  (* The continuation closure of the generators. *)
  Inductive PPC : list L -> list L -> Prop :=
  | ppc_seed : forall p u v, Gen p u v -> Adm (p ++ u) -> Adm (p ++ v) -> PPC (p ++ u) (p ++ v)
  | ppc_cont : forall t t' e, PPC t t' -> Adm (t ++ [e]) -> Adm (t' ++ [e]) ->
      PPC (t ++ [e]) (t' ++ [e]).

  Definition PClosOK : Prop := forall t t', PPC t t' -> eqv (sem t) (sem t').

  Definition PSeedOK : Prop := forall p u v, Gen p u v -> Adm (p ++ u) -> Adm (p ++ v) ->
    eqv (sem (p ++ u)) (sem (p ++ v)).

  Lemma ppc_whisk : forall t t', PPC t t' -> Adm t /\ Adm t' /\ Whisk t t'.
  Proof.
    intros t t' H. induction H as [p u v Hg Hu Hv | t t' e _ [_ [_ (p & u & v & w & Hg & -> & ->)]] H1 H2].
    - split; [exact Hu | split; [exact Hv |]]. exists p, u, v, []. rewrite !app_nil_r.
      split; [exact Hg | split; reflexivity].
    - split; [exact H1 | split; [exact H2 |]]. exists p, u, v, (w ++ [e]).
      split; [exact Hg |]. rewrite <- !app_assoc. split; reflexivity.
  Qed.

  Lemma whisk_ppc_w : AdmPrefix -> forall p u v, Gen p u v ->
    forall w, Adm (p ++ u ++ w) -> Adm (p ++ v ++ w) -> PPC (p ++ u ++ w) (p ++ v ++ w).
  Proof.
    intros HP p u v Hg w. induction w as [| e w IH] using rev_ind; intros Hu Hv.
    - rewrite !app_nil_r in *. apply ppc_seed; assumption.
    - replace (p ++ u ++ w ++ [e]) with ((p ++ u ++ w) ++ [e]) in Hu |- *
        by (rewrite <- !app_assoc; reflexivity).
      replace (p ++ v ++ w ++ [e]) with ((p ++ v ++ w) ++ [e]) in Hv |- *
        by (rewrite <- !app_assoc; reflexivity).
      apply ppc_cont; [| exact Hu | exact Hv].
      apply IH; [exact (HP _ [e] Hu) | exact (HP _ [e] Hv)].
  Qed.

  Theorem ppc_iff_whisk : AdmPrefix -> forall t t', PPC t t' <-> Adm t /\ Adm t' /\ Whisk t t'.
  Proof.
    intros HP t t'. split; [apply ppc_whisk |].
    intros [Ht [Ht' (p & u & v & w & Hg & -> & ->)]]. apply whisk_ppc_w; assumption.
  Qed.

  (* The closure is the least relation containing the seeds and closed under admissible
     one-event continuation. *)
  Theorem ppc_least : forall R : list L -> list L -> Prop,
    (forall p u v, Gen p u v -> Adm (p ++ u) -> Adm (p ++ v) -> R (p ++ u) (p ++ v)) ->
    (forall t t' e, R t t' -> Adm (t ++ [e]) -> Adm (t' ++ [e]) -> R (t ++ [e]) (t' ++ [e])) ->
    forall t t', PPC t t' -> R t t'.
  Proof.
    intros R Hs Hc t t' H. induction H as [p u v Hg Hu Hv | t t' e _ IH H1 H2].
    - apply Hs; assumption.
    - apply Hc; assumption.
  Qed.

  (* (P2) Invariance iff the semantics agrees on the continuation closure. *)
  Theorem closure_exact : AdmPrefix -> (PInv <-> PClosOK).
  Proof.
    intros HP. split.
    - intros H t t' Hc. apply H. destruct (ppc_whisk t t' Hc) as [Ht [Ht' Hw]].
      apply ac_gen; assumption.
    - intros H t t' He. induction He as [t _ | t t' Ht Ht' Hw | t t' _ IH | t t' t'' _ IH1 _ IH2].
      + apply eqv_refl.
      + apply H. apply (proj2 (ppc_iff_whisk HP t t')). tauto.
      + apply eqv_sym. exact IH.
      + exact (eqv_trans _ _ _ IH1 IH2).
  Qed.

  (* The seed condition is always necessary. *)
  Theorem seeds_necessary : PInv -> PSeedOK.
  Proof.
    intros H p u v Hg Hu Hv. apply H. apply ac_gen; [exact Hu | exact Hv |].
    exists p, u, v, []. rewrite !app_nil_r. split; [exact Hg | split; reflexivity].
  Qed.

  (* (P1) When the semantics respects the future on a predicate Q that covers the seeds and is
     preserved by admissible extension, the generators suffice locally. *)
  Variable Q : list L -> Prop.

  Definition RespOn : Prop := forall t t' e, Q t -> Q t' -> Adm (t ++ [e]) -> Adm (t' ++ [e]) ->
    eqv (sem t) (sem t') -> eqv (sem (t ++ [e])) (sem (t' ++ [e])).

  Definition QSeeds : Prop :=
    forall p u v, Gen p u v -> Adm (p ++ u) -> Adm (p ++ v) -> Q (p ++ u) /\ Q (p ++ v).

  Definition QExt : Prop := forall t e, Q t -> Adm (t ++ [e]) -> Q (t ++ [e]).

  Theorem local_closure : QSeeds -> QExt -> RespOn -> (PClosOK <-> PSeedOK).
  Proof.
    intros HQs HQe HR. split.
    - intros H p u v Hg Hu Hv. apply H. apply ppc_seed; assumption.
    - intros H t t' Hc.
      assert (K : Q t /\ Q t' /\ eqv (sem t) (sem t')).
      { induction Hc as [p u v Hg Hu Hv | t t' e _ [Q1 [Q2 IH]] H1 H2].
        - destruct (HQs p u v Hg Hu Hv) as [Q1 Q2]. split; [exact Q1 | split; [exact Q2 |]].
          apply H; assumption.
        - split; [apply HQe; assumption | split; [apply HQe; assumption |]].
          apply HR; assumption. }
      tauto.
  Qed.

  Theorem local_exact : AdmPrefix -> QSeeds -> QExt -> RespOn -> (PInv <-> PSeedOK).
  Proof.
    intros HP HQs HQe HR. rewrite (closure_exact HP). exact (local_closure HQs HQe HR).
  Qed.
End Presented.

(* P1 with Q everywhere. *)
Theorem local_exact_all : forall {L Y : Type} (Adm : list L -> Prop) Gen (sem : list L -> Y) eqv,
  (forall y, eqv y y) -> (forall y z, eqv y z -> eqv z y) ->
  (forall x y z, eqv x y -> eqv y z -> eqv x z) ->
  AdmPrefix Adm ->
  (forall t t' e, Adm (t ++ [e]) -> Adm (t' ++ [e]) -> eqv (sem t) (sem t') ->
     eqv (sem (t ++ [e])) (sem (t' ++ [e]))) ->
  (PInv Adm Gen sem eqv <-> PSeedOK Adm Gen sem eqv).
Proof.
  intros L Y Adm Gen sem eqv Hr Hs Ht HP HR.
  apply (local_exact Adm Gen sem eqv Hr Hs Ht (fun _ => True) HP).
  - intros p u v _ _ _. split; exact I.
  - intros t e _ _. exact I.
  - intros t t' e _ _. apply HR.
Qed.

(* Free delivery: admissibility trivial and generators independent of the point. The generated
   equivalence is then a monoid congruence. *)
Theorem free_congruence : forall {L : Type} (Adm : list L -> Prop) Gen,
  (forall t, Adm t) -> (forall p p' u v, Gen p u v -> Gen p' u v) ->
  forall t t', PEq Adm Gen t t' -> forall l r, PEq Adm Gen (l ++ t ++ r) (l ++ t' ++ r).
Proof.
  intros L Adm Gen HA HG t t' H. induction H as [t _ | t t' _ _ (p & u & v & w & Hg & -> & ->)
                                                 | t t' _ IH | t t' t'' _ IH1 _ IH2]; intros l r.
  - apply ac_refl. apply HA.
  - apply ac_gen; [apply HA | apply HA |]. exists (l ++ p), u, v, (w ++ r).
    split; [exact (HG p _ u v Hg) |]. rewrite <- !app_assoc. split; reflexivity.
  - apply ac_sym. apply IH.
  - eapply ac_trans; [apply IH1 | apply IH2].
Qed.

(* A state machine semantics: respect of the future follows from compatibility of obs with the
   steps, with no admissibility. *)
Section StateMachine.
  Context {L S O : Type}.
  Variable step : L -> S -> S.
  Variable obs : S -> O.
  Variable eqv : O -> O -> Prop.
  Variable s0 : S.

  Definition msem (t : list L) : O := obs (runT step t s0).

  Lemma msem_snoc : forall t e, msem (t ++ [e]) = obs (step e (runT step t s0)).
  Proof. intros t e. unfold msem. rewrite runT_app. reflexivity. Qed.

  Theorem resp_of_compat : forall (Adm : list L -> Prop) (Q : list L -> Prop),
    (forall e x y, eqv (obs x) (obs y) -> eqv (obs (step e x)) (obs (step e y))) ->
    RespOn Adm msem eqv Q.
  Proof.
    intros Adm Q Hc t t' e _ _ _ _ H. rewrite !msem_snoc. apply Hc. exact H.
  Qed.
End StateMachine.

(* ============================================================================================ *)
(* 2. Seeds alone do not suffice: a hidden write revealed later                                 *)
(* ============================================================================================ *)

(* State (hidden, visible). Some b writes the hidden register; None reveals it. The observation is
   the visible register; the generators swap two writes, at every point, with free delivery. *)
Definition hw_step (e : option bool) (s : bool * bool) : bool * bool :=
  match e with Some b => (b, snd s) | None => (fst s, fst s) end.
Definition hw_adm (_ : list (option bool)) : Prop := True.
Definition hw_gen (_ u v : list (option bool)) : Prop :=
  exists a b, u = [Some a; Some b] /\ v = [Some b; Some a].
Definition hw_sem : list (option bool) -> bool := msem hw_step snd (false, false).

(* Every swap seed is observationally equal, at every point. *)
Theorem hw_seeds_ok : PSeedOK hw_adm hw_gen hw_sem eq.
Proof.
  intros p u v (a & b & -> & ->) _ _. unfold hw_sem, msem. rewrite !runT_app. reflexivity.
Qed.

(* The seed continued by the reveal event separates. *)
Theorem hw_closure_witness :
  PPC hw_adm hw_gen [Some true; Some false; None] [Some false; Some true; None] /\
  hw_sem [Some true; Some false; None] <> hw_sem [Some false; Some true; None].
Proof.
  split; [| discriminate].
  apply (ppc_cont hw_adm hw_gen [Some true; Some false] [Some false; Some true] None);
    [| exact I | exact I].
  apply (ppc_seed hw_adm hw_gen [] [Some true; Some false] [Some false; Some true]);
    [exists true, false; split; reflexivity | exact I | exact I].
Qed.

Theorem hw_not_inv : ~ PInv hw_adm hw_gen hw_sem eq.
Proof.
  intros H. destruct hw_closure_witness as [P N]. apply N. apply H.
  destruct (ppc_whisk hw_adm hw_gen _ _ P) as [A1 [A2 W]]. apply ac_gen; assumption.
Qed.

(* The hypothesis of P1 is what fails: the observation does not respect the future. *)
Theorem hw_not_resp : ~ RespOn hw_adm hw_sem eq (fun _ => True).
Proof.
  intros H. specialize (H [Some true; Some false] [Some false; Some true] None I I I I eq_refl).
  discriminate H.
Qed.

(* Seeds checked at every reachable point, invariance still fails: P2 needs the closure. *)
Theorem hw_seeds_insufficient : PSeedOK hw_adm hw_gen hw_sem eq /\ ~ PInv hw_adm hw_gen hw_sem eq.
Proof. exact (conj hw_seeds_ok hw_not_inv). Qed.

(* ============================================================================================ *)
(* 3. The state side: state descent enters through the semantics, not as a generator            *)
(* ============================================================================================ *)

(* State descent N (act e s) = N (act e (N s)) compares one word run from two different states
   (s and N s). It is not a pair of parallel paths from one point, so it has no place in Gen. Its
   role: it makes the normalized raw semantics equal to the governed semantics from N s0, as
   functions on words, so any path presentation gives the same invariance question for both. *)
Theorem state_side_transfer : forall {X Ev : Type} (N : X -> X) (act : Ev -> X -> X) (s0 : X),
  StateDescent N act ->
  forall (Adm : list Ev -> Prop) Gen (eqv : X -> X -> Prop),
    PInv Adm Gen (fun t => N (rawrun act t s0)) eqv <->
    PInv Adm Gen (fun t => grun N act t (N s0)) eqv.
Proof.
  intros X Ev N act s0 HS Adm Gen eqv.
  assert (K : forall t, N (rawrun act t s0) = grun N act t (N s0))
    by (intros t; apply normalization_descent; exact HS).
  split; intros H t t' E; [rewrite <- !K | rewrite !K]; apply H; exact E.
Qed.

(* ============================================================================================ *)
(* 4a. history_descent_exact, through the one-step path system                                  *)
(* ============================================================================================ *)

Section OneStep.
  Context {T Y : Type}.
  Variable Adm : T -> Prop.
  Variable G : T -> T -> Prop.
  Variable SemEq : T -> T -> Prop.
  Variable sem : T -> Y.
  Variable eqY : Y -> Y -> Prop.
  Hypothesis eqY_refl : forall y, eqY y y.
  Hypothesis eqY_sym : forall y z, eqY y z -> eqY z y.
  Hypothesis eqY_trans : forall x y z, eqY x y -> eqY y z -> eqY x z.

  (* Executions are one-letter words; the empty word is the start. *)
  Definition os_adm (w : list T) : Prop :=
    match w with [] => True | [t] => Adm t | _ => False end.
  Definition os_gen (p u v : list T) : Prop :=
    p = [] /\ exists t t', u = [t] /\ v = [t'] /\ G t t'.
  Definition os_sem (w : list T) : option Y :=
    match w with [t] => Some (sem t) | _ => None end.
  Definition os_eqv (a b : option Y) : Prop :=
    match a, b with Some x, Some y => eqY x y | None, None => True | _, _ => False end.

  Lemma os_eqv_refl : forall a, os_eqv a a.
  Proof. intros [a |]; simpl; [apply eqY_refl | exact I]. Qed.
  Lemma os_eqv_sym : forall a b, os_eqv a b -> os_eqv b a.
  Proof. intros [a |] [b |]; simpl; try tauto. apply eqY_sym. Qed.
  Lemma os_eqv_trans : forall a b c, os_eqv a b -> os_eqv b c -> os_eqv a c.
  Proof. intros [a |] [b |] [c |]; simpl; try tauto. apply eqY_trans. Qed.

  Lemma os_prefix : AdmPrefix os_adm.
  Proof.
    intros t w H. destruct t as [| x [| y t]]; simpl; [exact I | | ].
    - destruct w; [exact H | destruct w; simpl in H; contradiction].
    - simpl in H. exact H.
  Qed.

  Lemma os_snoc : forall t e, os_adm (t ++ [e]) -> t = [].
  Proof.
    intros [| x t] e H; [reflexivity |]. destruct t; simpl in H; contradiction.
  Qed.

  Lemma os_whisk : forall a b, Whisk os_gen a b -> os_adm a ->
    exists t t', a = [t] /\ b = [t'] /\ G t t'.
  Proof.
    intros a b (p & u & v & w & [-> (t & t' & -> & -> & Hg)] & -> & ->) Ha.
    destruct w; [| simpl in Ha; contradiction]. exists t, t'. split; [reflexivity | split; [reflexivity | exact Hg]].
  Qed.

  Lemma os_peq : forall a b, PEq os_adm os_gen a b ->
    (a = [] /\ b = []) \/ exists t t', a = [t] /\ b = [t'] /\ AC Adm G t t'.
  Proof.
    intros a b H. induction H as [a Ha | a b Ha Hb Hw | a b _ IH | a b c _ IH1 _ IH2].
    - destruct a as [| t [| y a]]; [left; split; reflexivity | | contradiction].
      right. exists t, t. split; [reflexivity | split; [reflexivity |]]. apply ac_refl. exact Ha.
    - destruct (os_whisk a b Hw Ha) as (t & t' & -> & -> & Hg). right. exists t, t'.
      split; [reflexivity | split; [reflexivity |]]. apply ac_gen; assumption.
    - destruct IH as [[-> ->] | (t & t' & -> & -> & H)]; [left; split; reflexivity |].
      right. exists t', t. split; [reflexivity | split; [reflexivity |]]. apply ac_sym. exact H.
    - destruct IH1 as [[-> ->] | (t & t' & -> & -> & H1)];
        destruct IH2 as [[E ->] | (t2 & t3 & E & -> & H2)]; try discriminate.
      + left. split; reflexivity.
      + injection E as <-. right. exists t, t3. split; [reflexivity | split; [reflexivity |]].
        eapply ac_trans; eassumption.
  Qed.

  Lemma ac_os : forall t t', AC Adm G t t' -> PEq os_adm os_gen [t] [t'].
  Proof.
    intros t t' H. induction H as [t Ht | t t' Ht Ht' Hg | t t' _ IH | t t' t'' _ IH1 _ IH2].
    - apply ac_refl. exact Ht.
    - apply ac_gen; [exact Ht | exact Ht' |]. exists [], [t], [t'], [].
      split; [split; [reflexivity | exists t, t'; tauto] | split; reflexivity].
    - apply ac_sym. exact IH.
    - eapply ac_trans; eassumption.
  Qed.

  (* CanonicalExecution.history_descent_exact, recovered from P1. *)
  Theorem history_descent_recovered : Adequate Adm G SemEq ->
    (HistoryDescent Adm SemEq sem eqY <-> GenDescent Adm G sem eqY).
  Proof.
    intros HA.
    assert (S1 : HistoryDescent Adm SemEq sem eqY <-> PInv os_adm os_gen os_sem os_eqv).
    { split.
      - intros H a b E. destruct (os_peq a b E) as [[-> ->] | (t & t' & -> & -> & Hac)];
          [exact I |].
        destruct (ac_adm' Adm G t t' Hac) as [Ht Ht']. simpl.
        apply H; [exact Ht | exact Ht' |]. apply (proj2 (HA t t' Ht Ht')). exact Hac.
      - intros H t u Ht Hu Hs. apply (H [t] [u]). apply ac_os. exact (proj1 (HA t u Ht Hu) Hs). }
    assert (S2 : PInv os_adm os_gen os_sem os_eqv <-> PSeedOK os_adm os_gen os_sem os_eqv).
    { apply local_exact_all; [exact os_eqv_refl | exact os_eqv_sym | exact os_eqv_trans
                              | exact os_prefix |].
      intros t t' e H1 H2 _. rewrite (os_snoc t e H1), (os_snoc t' e H2). apply os_eqv_refl. }
    rewrite S1, S2. split.
    - intros H t t' Ht Ht' Hg.
      exact (H [] [t] [t'] (conj eq_refl (ex_intro _ t (ex_intro _ t' (conj eq_refl (conj eq_refl Hg)))))
               Ht Ht').
    - intros H p u v [-> (t & t' & -> & -> & Hg)] Ht Ht'. exact (H t t' Ht Ht' Hg).
  Qed.
End OneStep.

(* AC is monotone in the generators. *)
Lemma ac_impl : forall {T : Type} (Adm : T -> Prop) (G1 G2 : T -> T -> Prop),
  (forall t u, Adm t -> Adm u -> G1 t u -> G2 t u) -> forall t u, AC Adm G1 t u -> AC Adm G2 t u.
Proof.
  intros T Adm G1 G2 HG t u H. induction H as [t Ht | t u Ht Hu Hg | t u _ IH | t u v _ IH1 _ IH2].
  - apply ac_refl. exact Ht.
  - apply ac_gen; [exact Ht | exact Hu | apply HG; assumption].
  - apply ac_sym. exact IH.
  - eapply ac_trans; eassumption.
Qed.

(* Equality of a state machine run respects the future. *)
Lemma msem_eq_resp : forall {L S : Type} (step : L -> S -> S) (s0 : S) (t t' : list L) e,
  msem step (fun x => x) s0 t = msem step (fun x => x) s0 t' ->
  msem step (fun x => x) s0 (t ++ [e]) = msem step (fun x => x) s0 (t' ++ [e]).
Proof. intros L S step s0 t t' e H. rewrite !msem_snoc. unfold msem in H. rewrite H. reflexivity. Qed.

(* ============================================================================================ *)
(* 4b. Free delivery with adjacent swaps: ReconfigurationClosure's pair closure, through P2      *)
(* ============================================================================================ *)

Definition fs_adm {E : Type} (_ : list E) : Prop := True.
Definition fs_gen {E : Type} (_ u v : list E) : Prop := exists a b, u = [a; b] /\ v = [b; a].

Lemma fs_prefix : forall {E : Type}, AdmPrefix (@fs_adm E).
Proof. intros E t w _. exact I. Qed.

(* With free delivery and adjacent swaps the generated equivalence is Permutation. *)
Theorem swap_peq_perm : forall {E : Type} (t t' : list E),
  PEq fs_adm fs_gen t t' <-> Permutation t t'.
Proof.
  intros E t t'. split.
  - intros H. induction H as [t _ | t t' _ _ (p & u & v & w & (a & b & -> & ->) & -> & ->)
                             | t t' _ IH | t t' t'' _ IH1 _ IH2].
    + apply Permutation_refl.
    + apply Permutation_app_head. simpl. apply perm_swap.
    + apply Permutation_sym. exact IH.
    + eapply Permutation_trans; eassumption.
  - intros P.
    assert (K : forall l l' : list E, Permutation l l' -> forall p, PEq fs_adm fs_gen (p ++ l) (p ++ l')).
    { intros l l' Q. induction Q as [| x l l' Q IH | x y l | l l' l'' Q1 IH1 Q2 IH2]; intros p.
      - apply ac_refl. exact I.
      - replace (p ++ x :: l) with ((p ++ [x]) ++ l) by (rewrite <- app_assoc; reflexivity).
        replace (p ++ x :: l') with ((p ++ [x]) ++ l') by (rewrite <- app_assoc; reflexivity).
        apply IH.
      - apply ac_gen; [exact I | exact I |]. exists p, [y; x], [x; y], l.
        split; [exists y, x; split; reflexivity | split; reflexivity].
      - eapply ac_trans; [apply IH1 | apply IH2]. }
    exact (K t t' P (@nil E)).
Qed.

Section FreeSwap.
  Context {S E O : Type}.
  Variable step : E -> S -> S.
  Variable obs : S -> O.
  Variable eqv : O -> O -> Prop.
  Hypothesis eqv_refl : forall x, eqv x x.
  Hypothesis eqv_sym : forall x y, eqv x y -> eqv y x.
  Hypothesis eqv_trans : forall x y z, eqv x y -> eqv y z -> eqv x z.
  Variable s0 : S.

  Local Notation run := (runT step).
  Local Notation PC := (ReconfigurationClosure.PC step s0).

  Lemma fs_ppc_pc : forall t t', PPC (@fs_adm E) fs_gen t t' -> PC (run t s0) (run t' s0).
  Proof.
    intros t t' H. induction H as [p u v (a & b & -> & ->) _ _ | t t' e _ IH _ _].
    - rewrite !runT_app. exact (ReconfigurationClosure.pc_seed step s0 p a b).
    - rewrite !runT_app. exact (ReconfigurationClosure.pc_step step s0 e _ _ IH).
  Qed.

  Lemma fs_pc_ppc : forall x y, PC x y ->
    exists t t', PPC (@fs_adm E) fs_gen t t' /\ x = run t s0 /\ y = run t' s0.
  Proof.
    intros x y H. induction H as [u a b | e x y _ (t & t' & P & -> & ->)].
    - exists (u ++ [a; b]), (u ++ [b; a]). split; [| rewrite !runT_app; split; reflexivity].
      apply ppc_seed; [exists a, b; split; reflexivity | exact I | exact I].
    - exists (t ++ [e]), (t' ++ [e]). split; [| rewrite !runT_app; split; reflexivity].
      apply ppc_cont; [exact P | exact I | exact I].
  Qed.

  Theorem fs_closure_iff :
    PClosOK (@fs_adm E) fs_gen (msem step obs s0) eqv <->
    ReconfigurationClosure.ClosureOK step obs eqv s0.
  Proof.
    split.
    - intros H x y P. destruct (fs_pc_ppc x y P) as (t & t' & Q & -> & ->). exact (H t t' Q).
    - intros H t t' Q. exact (H _ _ (fs_ppc_pc t t' Q)).
  Qed.

  (* Permutation invariance of obs o run is P2's invariance for the adjacent-swap presentation. *)
  Lemma fs_perm_inv : (forall u u', Permutation u u' -> eqv (obs (run u s0)) (obs (run u' s0))) <->
    PInv (@fs_adm E) fs_gen (msem step obs s0) eqv.
  Proof.
    split.
    - intros H t t' Q. apply H. apply swap_peq_perm. exact Q.
    - intros H u u' P. apply H. apply swap_peq_perm. exact P.
  Qed.

  Theorem perm_closure_recovered :
    (forall u u', Permutation u u' -> eqv (obs (run u s0)) (obs (run u' s0))) <->
    ReconfigurationClosure.ClosureOK step obs eqv s0.
  Proof.
    rewrite fs_perm_inv, (closure_exact fs_adm fs_gen (msem step obs s0) eqv eqv_refl eqv_sym eqv_trans fs_prefix).
    exact fs_closure_iff.
  Qed.

  (* The closure pairs in whiskered form: the swap condition with a continuation. *)
  Theorem perm_swap_recovered :
    (forall u u', Permutation u u' -> eqv (obs (run u s0)) (obs (run u' s0))) <->
    forall u a b w, eqv (obs (run w (step b (step a (run u s0))))) (obs (run w (step a (step b (run u s0))))).
  Proof.
    rewrite fs_perm_inv, (closure_exact fs_adm fs_gen (msem step obs s0) eqv eqv_refl eqv_sym eqv_trans fs_prefix).
    split.
    - intros H u a b w.
      assert (P : PPC (@fs_adm E) fs_gen (u ++ [a; b] ++ w) (u ++ [b; a] ++ w))
        by (apply whisk_ppc_w; [exact fs_prefix | exists a, b; split; reflexivity | exact I | exact I]).
      pose proof (H _ _ P) as K. unfold msem in K. rewrite !runT_app in K. exact K.
    - intros H t t' P. destruct (ppc_whisk _ _ t t' P) as [_ [_ (p & u & v & w & (a & b & -> & ->) & -> & ->)]].
      unfold msem. rewrite !runT_app. apply H.
  Qed.
End FreeSwap.

(* ReconfigurationClosure.amodm_closure_exact and amodm_swap_exact, from P2. The migration M is
   the observation; it is not compatible with the A-steps in general, so P1 does not apply. *)
Theorem amodm_closure_recovered : forall {SA EA SB : Type} (stepA : EA -> SA -> SA)
  (eqvB : SB -> SB -> Prop), (forall x, eqvB x x) -> (forall x y, eqvB x y -> eqvB y x) ->
  (forall x y z, eqvB x y -> eqvB y z -> eqvB x z) -> forall (M : SA -> SB) s0,
  ReconfigurationClosure.AmodM stepA eqvB M s0 <-> ReconfigurationClosure.ClosureOK stepA M eqvB s0.
Proof.
  intros SA EA SB stepA eqvB Hr Hs Ht M s0. exact (perm_closure_recovered stepA M eqvB Hr Hs Ht s0).
Qed.

Theorem amodm_swap_recovered : forall {SA EA SB : Type} (stepA : EA -> SA -> SA)
  (eqvB : SB -> SB -> Prop), (forall x, eqvB x x) -> (forall x y, eqvB x y -> eqvB y x) ->
  (forall x y z, eqvB x y -> eqvB y z -> eqvB x z) -> forall (M : SA -> SB) s0,
  ReconfigurationClosure.AmodM stepA eqvB M s0 <->
  forall u a b w, eqvB (M (runT stepA w (stepA b (stepA a (runT stepA u s0)))))
                       (M (runT stepA w (stepA a (stepA b (runT stepA u s0))))).
Proof.
  intros SA EA SB stepA eqvB Hr Hs Ht M s0. exact (perm_swap_recovered stepA M eqvB Hr Hs Ht s0).
Qed.

(* ============================================================================================ *)
(* 4c. Causal delivery: GovernanceConverse.causal_exact, through P1                             *)
(* ============================================================================================ *)

Section CausalP.
  Context {S E : Type}.
  Variable step : E -> S -> S.
  Variable hb : E -> E -> Prop.
  Variable s0 : S.

  Local Notation causal := (CausalReplay.causal hb).
  Local Notation sem := (msem step (fun x => x) s0).

  (* The generator: an adjacent concurrent pair at a point after which it is causally deliverable. *)
  Definition cg_gen (p u v : list E) : Prop :=
    exists a b, CausalReplay.concurrent hb a b /\ causal (p ++ [a; b]) /\ u = [a; b] /\ v = [b; a].

  Lemma cg_prefix : AdmPrefix causal.
  Proof. intros t w H. exact (GovernanceConverse.causal_prefix hb t w H). Qed.

  Lemma cg_whisk_cswap : forall t t', Whisk cg_gen t t' <-> CanonicalInstances.cswap hb t t'.
  Proof.
    intros t t'. split.
    - intros (p & u & v & w & (a & b & Hab & Hc & -> & ->) & -> & ->).
      exists p, a, b, w. tauto.
    - intros (p & a & b & r & Hab & Hc & -> & ->). exists p, [a; b], [b; a], r.
      split; [exists a, b; tauto | split; reflexivity].
  Qed.

  Lemma cg_peq : forall t t', PEq causal cg_gen t t' <-> AC causal (CanonicalInstances.cswap hb) t t'.
  Proof.
    intros t t'. split; apply ac_impl; intros x y _ _ H; apply cg_whisk_cswap; exact H.
  Qed.

  Theorem causal_exact_recovered :
    GovernanceConverse.CausalConv step hb s0 <-> GovernanceConverse.CCR step hb s0.
  Proof.
    assert (S1 : GovernanceConverse.CausalConv step hb s0 <-> PInv causal cg_gen sem eq).
    { split.
      - intros H t t' Hq. apply cg_peq in Hq.
        destruct (ac_adm' causal (CanonicalInstances.cswap hb) t t' Hq)
          as [Ht Ht'].
        exact (H t t' Ht Ht' (proj2 (CanonicalInstances.causal_adequate hb t t' Ht Ht') Hq)).
      - intros H o1 o2 H1 H2 P. apply (H o1 o2). apply cg_peq.
        exact (proj1 (CanonicalInstances.causal_adequate hb o1 o2 H1 H2) P). }
    assert (S2 : PInv causal cg_gen sem eq <-> PSeedOK causal cg_gen sem eq).
    { apply local_exact_all; [exact (@eq_refl _) | exact (@eq_sym _) | exact (@eq_trans _)
                              | exact cg_prefix |].
      intros t t' e _ _. apply msem_eq_resp. }
    rewrite S1, S2. split.
    - intros H p a b Hab Hc.
      assert (Hc' : causal (p ++ [b; a]))
        by exact (GovernanceConverse.causal_swap hb p a b [] (proj1 (proj2 Hab)) Hc).
      pose proof (H p [a; b] [b; a] (ex_intro _ a (ex_intro _ b (conj Hab (conj Hc (conj eq_refl eq_refl)))))
                    Hc Hc') as K.
      unfold msem in K. rewrite !runT_app in K. exact K.
    - intros H p u v (a & b & Hab & Hc & -> & ->) _ _. unfold msem. rewrite !runT_app.
      exact (H p a b Hab Hc).
  Qed.
End CausalP.

(* ============================================================================================ *)
(* 4d. Declared pairs: AtLeastOnceDeclared.tconv_exact (a trace monoid), through P1             *)
(* ============================================================================================ *)

Section DeclaredP.
  Context {S E : Type}.
  Variable step : E -> S -> S.
  Variable Ev : E -> Prop.
  Variable hb I : E -> E -> Prop.
  Hypothesis I_sym : forall a b, I a b -> I b a.
  Hypothesis I_irrefl : forall a, ~ I a a.
  Hypothesis I_hb : forall a b, I a b -> ~ hb a b.
  Variable s0 : S.

  Local Notation causal := (CausalReplay.causal hb).
  Local Notation sem := (msem step (fun x => x) s0).

  (* Admissible: a history over Ev. Generator: a declared pair at a point where it is deliverable. *)
  Definition dg_adm (t : list E) : Prop := Forall Ev t /\ causal t.
  Definition dg_gen (p u v : list E) : Prop :=
    exists a b, I a b /\ Forall Ev (p ++ [a; b]) /\ causal (p ++ [a; b]) /\ u = [a; b] /\ v = [b; a].

  Lemma dg_prefix : AdmPrefix dg_adm.
  Proof.
    intros t w [Hf Hc]. split; [| exact (GovernanceConverse.causal_prefix hb t w Hc)].
    apply Forall_app in Hf. exact (proj1 Hf).
  Qed.

  Lemma dg_tequiv_peq : forall o1 o2, tequiv I o1 o2 -> dg_adm o1 -> PEq dg_adm dg_gen o1 o2.
  Proof.
    intros o1 o2 H. induction H as [l | l a b r Hab | l1 l2 H IH | l1 l2 l3 H1 IH1 H2 IH2]; intros Ha.
    - apply ac_refl. exact Ha.
    - destruct Ha as [Hf Hc].
      assert (Hb : dg_adm (l ++ b :: a :: r)).
      { split; [exact (Permutation_Forall (Permutation_app_head l (perm_swap b a r)) Hf) |].
        exact (AtLeastOnceDeclared.tequiv_I_causal hb I I_sym I_irrefl I_hb _ _ (teq_swap I l a b r Hab) Hc). }
      apply ac_gen; [split; assumption | exact Hb |]. exists l, [a; b], [b; a], r.
      split; [| split; reflexivity]. exists a, b. split; [exact Hab |].
      replace (l ++ a :: b :: r) with ((l ++ [a; b]) ++ r) in Hf, Hc by (rewrite <- app_assoc; reflexivity).
      split; [apply Forall_app in Hf; exact (proj1 Hf) |].
      split; [exact (GovernanceConverse.causal_prefix hb _ r Hc) | split; reflexivity].
    - apply ac_sym. apply IH. destruct Ha as [Hf Hc]. split.
      + exact (Permutation_Forall (Permutation_sym (tequiv_perm _ _ _ H)) Hf).
      + exact (AtLeastOnceDeclared.tequiv_I_causal hb I I_sym I_irrefl I_hb _ _ (teq_sym _ _ _ H) Hc).
    - eapply ac_trans; [apply IH1; exact Ha |]. apply IH2. destruct Ha as [Hf Hc]. split.
      + exact (Permutation_Forall (tequiv_perm _ _ _ H1) Hf).
      + exact (AtLeastOnceDeclared.tequiv_I_causal hb I I_sym I_irrefl I_hb _ _ H1 Hc).
  Qed.

  Lemma dg_peq_tequiv : forall o1 o2, PEq dg_adm dg_gen o1 o2 -> tequiv I o1 o2.
  Proof.
    intros o1 o2 H. induction H as [t _ | t t' _ _ (p & u & v & w & (a & b & Hab & _ & _ & -> & ->) & -> & ->)
                                   | t t' _ IH | t t' t'' _ IH1 _ IH2].
    - apply teq_refl.
    - apply teq_swap. exact Hab.
    - apply teq_sym. exact IH.
    - eapply teq_trans; eassumption.
  Qed.

  Theorem tconv_exact_recovered :
    AtLeastOnceDeclared.TConvI step Ev hb I s0 <-> AtLeastOnceDeclared.CommI step Ev hb I s0.
  Proof.
    assert (S1 : AtLeastOnceDeclared.TConvI step Ev hb I s0 <-> PInv dg_adm dg_gen sem eq).
    { split.
      - intros H t t' Hq. destruct (ac_adm' dg_adm (Whisk dg_gen) t t' Hq)
          as [[Hf Hc] _].
        exact (H t t' Hf Hc (dg_peq_tequiv t t' Hq)).
      - intros H o1 o2 Hf Hc T. apply H. apply dg_tequiv_peq; [exact T | split; assumption]. }
    assert (S2 : PInv dg_adm dg_gen sem eq <-> PSeedOK dg_adm dg_gen sem eq).
    { apply local_exact_all; [exact (@eq_refl _) | exact (@eq_sym _) | exact (@eq_trans _)
                              | exact dg_prefix |].
      intros t t' e _ _. apply msem_eq_resp. }
    rewrite S1, S2. split.
    - intros H p a b Hf Hc Hab.
      assert (Hb : dg_adm (p ++ [b; a])).
      { split; [exact (Permutation_Forall (Permutation_app_head p (perm_swap b a [])) Hf) |].
        exact (AtLeastOnceDeclared.tequiv_I_causal hb I I_sym I_irrefl I_hb _ _ (teq_swap I p a b [] Hab) Hc). }
      pose proof (H p [a; b] [b; a]
                    (ex_intro _ a (ex_intro _ b (conj Hab (conj Hf (conj Hc (conj eq_refl eq_refl))))))
                    (conj Hf Hc) Hb) as K.
      unfold msem in K. rewrite !runT_app in K. exact K.
    - intros H p u v (a & b & Hab & Hf & Hc & -> & ->) _ _. unfold msem. rewrite !runT_app.
      exact (H p a b Hf Hc Hab).
  Qed.
End DeclaredP.

(* ============================================================================================ *)
(* 4e. At-least-once delivery: legal duplicate landings, through P1                             *)
(* ============================================================================================ *)

Section ALOP.
  Context {S E : Type}.
  Variable dec : forall x y : E, {x = y} + {x <> y}.
  Variable step : E -> S -> S.
  Variable Ev : E -> Prop.
  Variable hb : E -> E -> Prop.
  Hypothesis hb_irrefl : forall x, ~ hb x x.
  Variable s0 : S.

  Local Notation causal := (CausalReplay.causal hb).
  Local Notation adm := (CanonicalInstances.alo_adm Ev hb).
  Local Notation sem := (msem step (fun x => x) s0).

  (* Generators: a concurrent swap at a causal point, and the legal duplicate landing: a second
     copy right after the first delivery, which ends an exactly-once causal prefix. *)
  Definition ag_gen (p u v : list E) : Prop :=
    (exists a b, CausalReplay.concurrent hb a b /\ causal (p ++ [a; b]) /\ u = [a; b] /\ v = [b; a]) \/
    (exists a, causal (p ++ [a]) /\ u = [a; a] /\ v = [a]).

  Lemma ag_prefix : AdmPrefix adm.
  Proof.
    intros t w [Hf Hc]. split; [apply Forall_app in Hf; exact (proj1 Hf) |].
    intros a b Hab l r Ed Hb Ha. apply (Hc a b Hab l (r ++ w)); [| exact Hb | apply in_or_app; left; exact Ha].
    rewrite Ed, app_assoc. reflexivity.
  Qed.

  Lemma ag_whisk : forall t t', Whisk ag_gen t t' <-> CanonicalInstances.G_idem hb t t'.
  Proof.
    intros t t'. split.
    - intros (p & u & v & w & [(a & b & Hab & Hc & -> & ->) | (a & Hc & -> & ->)] & -> & ->).
      + left. exists p, a, b, w. tauto.
      + right. exists p, a, w. split; [exact Hc | split; reflexivity].
    - intros [(p & a & b & r & Hab & Hc & -> & ->) | (p & a & r & Hc & -> & ->)].
      + exists p, [a; b], [b; a], r. split; [left; exists a, b; tauto | split; reflexivity].
      + exists p, [a; a], [a], r. split; [right; exists a; tauto | split; reflexivity].
  Qed.

  Lemma ag_peq : forall t t', PEq adm ag_gen t t' <-> AC adm (CanonicalInstances.G_idem hb) t t'.
  Proof. intros t t'. split; apply ac_impl; intros x y _ _ H; apply ag_whisk; exact H. Qed.

  Theorem causal_alo_idem_recovered :
    AtLeastOnceExact.CALOConv step Ev hb s0 <->
    AtLeastOnceExact.CCRon step Ev hb s0 /\ forall a, AtLeastOnceExact.IdemAt step Ev hb s0 a.
  Proof.
    pose proof (CanonicalInstances.alo_adequate_idem dec Ev hb hb_irrefl) as HA.
    assert (S1 : AtLeastOnceExact.CALOConv step Ev hb s0 <-> PInv adm ag_gen sem eq).
    { rewrite (CanonicalInstances.caloconv_hd dec step Ev hb hb_irrefl s0). split.
      - intros H t t' Hq. apply ag_peq in Hq.
        destruct (ac_adm' adm (CanonicalInstances.G_idem hb) t t' Hq) as [Ht Ht'].
        exact (H t t' Ht Ht' (proj2 (HA t t' Ht Ht') Hq)).
      - intros H t u Ht Hu Hs. apply (H t u). apply ag_peq. exact (proj1 (HA t u Ht Hu) Hs). }
    assert (S2 : PInv adm ag_gen sem eq <-> PSeedOK adm ag_gen sem eq).
    { apply local_exact_all; [exact (@eq_refl _) | exact (@eq_sym _) | exact (@eq_trans _)
                              | exact ag_prefix |].
      intros t t' e _ _. apply msem_eq_resp. }
    rewrite S1, S2. split.
    - intros H. split.
      + intros p a b Hev Hab Hc.
        assert (Hc' : causal (p ++ [b; a]))
          by exact (GovernanceConverse.causal_swap hb p a b [] (proj1 (proj2 Hab)) Hc).
        assert (Hev' : Forall Ev (p ++ [b; a]))
          by exact (Permutation_Forall (Permutation_app_head p (perm_swap b a [])) Hev).
        pose proof (H p [a; b] [b; a]
                      (or_introl (ex_intro _ a (ex_intro _ b (conj Hab (conj Hc (conj eq_refl eq_refl))))))
                      (CanonicalInstances.adm_causal Ev hb _ Hc Hev)
                      (CanonicalInstances.adm_causal Ev hb _ Hc' Hev')) as K.
        unfold msem in K. rewrite !runT_app in K. exact K.
      + intros a u Hev Hc.
        assert (Hx : Ev a) by (rewrite Forall_forall in Hev; apply Hev; apply in_or_app; right; left; reflexivity).
        assert (Hns : forall b, In b (u ++ [a]) -> ~ hb a b).
        { intros b Hb Hab. apply in_app_or in Hb. destruct Hb as [Hb | [<- | []]]; [| exact (hb_irrefl a Hab)].
          destruct Hc as [Hnd Hcc]. apply (CausalReplay.prec_before_contra u a [] b Hnd Hb).
          apply Hcc; [exact Hab | apply in_or_app; right; left; reflexivity | apply in_or_app; left; exact Hb]. }
        pose proof (CanonicalInstances.adm_snoc Ev hb (u ++ [a]) a Hc Hev Hx Hns) as A1.
        rewrite <- app_assoc in A1.
        pose proof (H u [a; a] [a] (or_intror (ex_intro _ a (conj Hc (conj eq_refl eq_refl))))
                      A1 (CanonicalInstances.adm_causal Ev hb _ Hc Hev)) as K.
        unfold msem in K. rewrite !runT_app in K. exact K.
    - intros [HC HI] p u v [(a & b & Hab & Hc & -> & ->) | (a & Hc & -> & ->)] [Hf _] _;
        unfold msem; rewrite !runT_app.
      + exact (HC p a b Hf Hab Hc).
      + apply HI; [| exact Hc].
        replace (p ++ [a; a]) with ((p ++ [a]) ++ [a]) in Hf by (rewrite <- app_assoc; reflexivity).
        apply Forall_app in Hf. exact (proj1 Hf).
  Qed.
End ALOP.

(* AtLeastOnceExact.alo_exact, the free instance (hb empty) of causal_alo_idem_recovered. *)
Theorem alo_exact_recovered : forall {S E : Type} (dec : forall x y : E, {x = y} + {x <> y})
  (step : E -> S -> S) (Ev : E -> Prop) (s0 : S),
  AtLeastOnceExact.ALOConv step Ev s0 <->
  AtLeastOnceExact.CommReach step Ev s0 /\ forall a, AtLeastOnceExact.IdemReach step Ev s0 a.
Proof.
  intros S E dec step Ev s0.
  rewrite AtLeastOnceExact.aloconv_iff,
    (causal_alo_idem_recovered dec step Ev AtLeastOnceExact.nohb AtLeastOnceExact.nohb_irrefl s0),
    AtLeastOnceExact.comm_iff.
  split; intros [HC H]; split; try exact HC; intros a; apply AtLeastOnceExact.idem_iff; exact (H a).
Qed.

(* ============================================================================================ *)
(* 4f. Typed phases: switch squares, Reconfiguration.det_live_exact through P1                  *)
(* ============================================================================================ *)

(* Labels of a live reconfiguration run: an A-event, the switch, an in-flight A-event applied after
   the switch (translated), a native B-event. *)
Inductive SwLab {EA EB : Type} : Type :=
| LA (a : EA) | LS | LT (a : EA) | LB (b : EB).
Arguments SwLab : clear implicits.

Definition isPost {EA EB : Type} (l : SwLab EA EB) : Prop :=
  match l with LT _ | LB _ => True | _ => False end.

(* Typed phases: A-events, then at most one switch, then only post-switch labels. *)
Fixpoint phA {EA EB : Type} (w : list (SwLab EA EB)) : Prop :=
  match w with
  | [] => True
  | LA _ :: w' => phA w'
  | LS :: w' => Forall isPost w'
  | _ => False
  end.

Lemma phA_prefix : forall {EA EB : Type}, AdmPrefix (@phA EA EB).
Proof.
  intros EA EB t. induction t as [| [a | | a | b] t IH]; intros w H; simpl in *; try tauto.
  - exact (IH w H).
  - apply Forall_app in H. exact (proj1 H).
Qed.

Lemma phA_mapA : forall {EA EB : Type} (u : list EA) (r : list (SwLab EA EB)),
  phA (map LA u ++ r) <-> phA r.
Proof. intros EA EB u r. induction u as [| a u IH]; simpl; tauto. Qed.

(* An admissible word is all A, or A, the switch, then post labels. *)
Lemma phA_shape : forall {EA EB : Type} (w : list (SwLab EA EB)), phA w ->
  (exists u, w = map LA u) \/ (exists u x, w = map LA u ++ LS :: x /\ Forall isPost x).
Proof.
  intros EA EB w. induction w as [| [a | | a | b] w IH]; intros H; simpl in H; try contradiction.
  - left. exists []. reflexivity.
  - destruct (IH H) as [[u ->] | (u & x & -> & Hx)].
    + left. exists (a :: u). reflexivity.
    + right. exists (a :: u), x. split; [reflexivity | exact Hx].
  - right. exists [], w. split; [reflexivity | exact H].
Qed.

(* A post label in an admissible word comes after the switch. *)
Lemma phA_post_LS : forall {EA EB : Type} (w : list (SwLab EA EB)) l, phA w -> In l w -> isPost l ->
  In LS w.
Proof.
  intros EA EB w l H Hl Hp. destruct (phA_shape w H) as [[u ->] | (u & x & -> & _)].
  - apply in_map_iff in Hl. destruct Hl as [a [<- _]]. simpl in Hp. contradiction.
  - apply in_or_app. right. left. reflexivity.
Qed.

Lemma phA_A_point : forall {EA EB : Type} (p r : list (SwLab EA EB)) a, phA (p ++ LA a :: r) ->
  exists u, p = map LA u.
Proof.
  intros EA EB p r a H. destruct (phA_shape p (phA_prefix p _ H)) as [[u ->] | (u & x & -> & Hx)].
  - exists u. reflexivity.
  - exfalso. rewrite <- app_assoc in H. apply phA_mapA in H. simpl in H.
    apply Forall_app in H. destruct H as [_ H]. inversion H as [| ? ? Hc _]. exact Hc.
Qed.

Lemma phA_post_point : forall {EA EB : Type} (p r : list (SwLab EA EB)) l, isPost l -> phA (p ++ l :: r) ->
  exists u x, p = map LA u ++ LS :: x /\ Forall isPost x.
Proof.
  intros EA EB p r l Hl H. destruct (phA_shape p (phA_prefix p _ H)) as [[u ->] | Hs]; [| exact Hs].
  exfalso. apply phA_mapA in H. destruct l; simpl in H, Hl; contradiction.
Qed.

(* The B-events a word contributes after the switch, the A-events and the native B-events. *)
Definition labo {EA EB : Type} (tau : EA -> EB) (l : SwLab EA EB) : list EB :=
  match l with LT a => [tau a] | LB b => [b] | _ => [] end.
Definition aOf {EA EB : Type} (w : list (SwLab EA EB)) : list EA :=
  flat_map (fun l => match l with LA a | LT a => [a] | _ => [] end) w.
Definition bOf {EA EB : Type} (w : list (SwLab EA EB)) : list EB :=
  flat_map (fun l => match l with LB b => [b] | _ => [] end) w.
Definition tOf {EA EB : Type} (w : list (SwLab EA EB)) : list EA :=
  flat_map (fun l => match l with LT a => [a] | _ => [] end) w.

Lemma labo_perm : forall {EA EB : Type} (tau : EA -> EB) (x : list (SwLab EA EB)),
  Permutation (flat_map (labo tau) x) (map tau (tOf x) ++ bOf x).
Proof.
  intros EA EB tau x. induction x as [| [a | | a | b] x IH]; simpl; try exact IH.
  - apply Permutation_refl.
  - apply perm_skip. exact IH.
  - apply (Permutation_trans (perm_skip b IH)). apply Permutation_middle.
Qed.

Section LiveP.
  Context {SA EA SB EB : Type}.
  Variable stepA : EA -> SA -> SA.
  Variable stepB : EB -> SB -> SB.
  Variable eqvB : SB -> SB -> Prop.
  Hypothesis eqvB_refl : forall x, eqvB x x.
  Hypothesis eqvB_sym : forall x y, eqvB x y -> eqvB y x.
  Hypothesis eqvB_trans : forall x y z, eqvB x y -> eqvB y z -> eqvB x z.
  Hypothesis stepB_ext : forall e x y, eqvB x y -> eqvB (stepB e x) (stepB e y).
  Variable M : SA -> SB.
  Variable tau : EA -> EB.
  Variable s0 : SA.

  Local Notation runA := (runT stepA).
  Local Notation runB := (runT stepB).
  Local Notation Lab := (SwLab EA EB).

  (* One state machine for both phases; ill-typed labels act as the identity (never admissible). *)
  Definition lv_step (l : Lab) (x : SA + SB) : SA + SB :=
    match l, x with
    | LA a, inl s => inl (stepA a s)
    | LS, inl s => inr (M s)
    | LT a, inr y => inr (stepB (tau a) y)
    | LB b, inr y => inr (stepB b y)
    | _, x => x
    end.
  Definition lv_obs (x : SA + SB) : SB := match x with inl s => M s | inr y => y end.
  Local Notation sem := (msem lv_step lv_obs (inl s0)).

  (* Generators: the switch square, and a swap of two post-switch labels. *)
  Definition lv_gen (_ u v : list Lab) : Prop :=
    (exists a, u = [LA a; LS] /\ v = [LS; LT a]) \/
    (exists x y, isPost x /\ isPost y /\ u = [x; y] /\ v = [y; x]).

  Lemma lv_run_A : forall u s, runT lv_step (map LA u) (inl s) = inl (runA u s).
  Proof.
    induction u as [| a u IH]; intros s; [reflexivity |].
    change (map LA (a :: u)) with (@LA EA EB a :: map LA u). rewrite !runT_cons. apply IH.
  Qed.

  Lemma lv_run_post : forall x y, runT lv_step x (inr y) = inr (runB (flat_map (labo tau) x) y).
  Proof.
    induction x as [| [a | | a | b] x IH]; intros y; [reflexivity | | | |]; rewrite runT_cons;
      cbn [lv_step]; rewrite IH; reflexivity.
  Qed.

  Lemma lv_sem_complete : forall u x,
    sem (map LA u ++ LS :: x) = runB (flat_map (labo tau) x) (M (runA u s0)).
  Proof.
    intros u x. unfold msem. rewrite runT_app, lv_run_A, runT_cons. simpl. rewrite lv_run_post.
    reflexivity.
  Qed.

  Lemma lv_sem_A : forall u, sem (map LA u) = M (runA u s0).
  Proof. intros u. unfold msem. rewrite lv_run_A. reflexivity. Qed.

  Lemma lv_run_inr : forall t y, exists y', runT lv_step t (inr y) = inr y'.
  Proof. intros t y. rewrite lv_run_post. eexists. reflexivity. Qed.

  Lemma lv_run_LS : forall t x, In LS t -> exists y, runT lv_step t x = inr y.
  Proof.
    induction t as [| l t IH]; intros x H; [destruct H |]. rewrite runT_cons.
    destruct H as [-> | H]; [| apply IH; exact H].
    destruct x as [s | y]; simpl; apply lv_run_inr.
  Qed.

  (* Past the switch the semantics respects the future. *)
  Lemma lv_resp : RespOn phA sem eqvB (fun t : list Lab => In LS t).
  Proof.
    intros t t' e Q1 Q2 _ _ H. unfold msem in *. rewrite !runT_app.
    destruct (lv_run_LS t (inl s0) Q1) as [y Hy]. destruct (lv_run_LS t' (inl s0) Q2) as [y' Hy'].
    rewrite Hy, Hy' in *. simpl in H. destruct e; simpl; auto.
  Qed.

  Lemma lv_qseeds : QSeeds phA lv_gen (fun t : list Lab => In LS t).
  Proof.
    intros p u v [(a & -> & ->) | (x & y & Hx & Hy & -> & ->)] Hu Hv; split.
    - apply in_or_app. right. right. left. reflexivity.
    - apply in_or_app. right. left. reflexivity.
    - apply (phA_post_LS _ x Hu); [apply in_or_app; right; left; reflexivity | exact Hx].
    - apply (phA_post_LS _ y Hv); [apply in_or_app; right; left; reflexivity | exact Hy].
  Qed.

  Lemma lv_qext : QExt phA (fun t : list Lab => In LS t).
  Proof. intros t e H _. apply in_or_app. left. exact H. Qed.

  (* P1: invariance iff the seeds. *)
  Lemma lv_local : PInv phA lv_gen sem eqvB <-> PSeedOK phA lv_gen sem eqvB.
  Proof.
    exact (local_exact phA lv_gen sem eqvB eqvB_refl eqvB_sym eqvB_trans (fun t : list Lab => In LS t)
             phA_prefix lv_qseeds lv_qext lv_resp).
  Qed.

  (* ----- the seeds are DS1 and the post-switch swaps ----- *)

  Definition SwapAll : Prop := forall u v a b,
    eqvB (stepB b (stepB a (runB v (M (runA u s0))))) (stepB a (stepB b (runB v (M (runA u s0))))).

  Lemma labo_LB : forall v, flat_map (labo tau) (map (@LB EA EB) v) = v.
  Proof. induction v as [| b v IH]; [reflexivity |]. simpl. rewrite IH. reflexivity. Qed.

  Lemma labo_LT_LB : forall r v, flat_map (labo tau) (map (@LT EA EB) r ++ map LB v) = map tau r ++ v.
  Proof.
    intros r v. rewrite flat_map_app, labo_LB. f_equal.
    induction r as [| a r IH]; [reflexivity |]. simpl. rewrite IH. reflexivity.
  Qed.

  Lemma lv_sem_post : forall u x l1 l2,
    sem ((map LA u ++ LS :: x) ++ [l1; l2]) =
    runB (flat_map (labo tau) [l1; l2]) (runB (flat_map (labo tau) x) (M (runA u s0))).
  Proof.
    intros u x l1 l2. rewrite <- app_assoc. change ((LS :: x) ++ [l1; l2]) with (LS :: (x ++ [l1; l2])).
    rewrite lv_sem_complete, flat_map_app, runT_app. reflexivity.
  Qed.

  Lemma forall_LB : forall v, Forall isPost (map (@LB EA EB) v).
  Proof.
    intros v. apply Forall_forall. intros l Hl. apply in_map_iff in Hl. destruct Hl as [b [<- _]]. exact I.
  Qed.

  Lemma lv_seeds_iff : PSeedOK phA lv_gen sem eqvB <-> Reconfiguration.DS1 stepA stepB eqvB M tau s0 /\ SwapAll.
  Proof.
    split.
    - intros H. split.
      + intros u e.
        assert (A1 : phA (map (@LA EA EB) u ++ [LA e; LS])) by (apply phA_mapA; simpl; apply Forall_nil).
        assert (A2 : phA (map (@LA EA EB) u ++ [LS; LT e])) by (apply phA_mapA; simpl; repeat constructor).
        pose proof (H (map LA u) [LA e; LS] [LS; LT e] (or_introl (ex_intro _ e (conj eq_refl eq_refl)))
                      A1 A2) as K.
        unfold msem in K. rewrite !runT_app, !lv_run_A in K. exact K.
      + intros u v a b.
        assert (A1 : phA ((map (@LA EA EB) u ++ LS :: map LB v) ++ [LB a; LB b])).
        { rewrite <- app_assoc. apply phA_mapA. simpl. apply Forall_app.
          split; [apply forall_LB | repeat constructor]. }
        assert (A2 : phA ((map (@LA EA EB) u ++ LS :: map LB v) ++ [LB b; LB a])).
        { rewrite <- app_assoc. apply phA_mapA. simpl. apply Forall_app.
          split; [apply forall_LB | repeat constructor]. }
        pose proof (H (map LA u ++ LS :: map LB v) [LB a; LB b] [LB b; LB a]
                      (or_intror (ex_intro _ (LB a) (ex_intro _ (LB b) (conj I (conj I (conj eq_refl eq_refl))))))
                      A1 A2) as K.
        rewrite !lv_sem_post, labo_LB in K. exact K.
    - intros [HD HS] p u v [(a & -> & ->) | (x & y & Hx & Hy & -> & ->)] Hu Hv.
      + destruct (phA_A_point p [LS] a Hu) as [u0 ->].
        unfold msem. rewrite !runT_app, !lv_run_A. exact (HD u0 a).
      + destruct (phA_post_point p [y] x Hx Hu) as (u0 & x0 & -> & _).
        rewrite !lv_sem_post.
        destruct x as [| | a1 | b1]; destruct y as [| | a2 | b2]; simpl in Hx, Hy; try contradiction;
          exact (HS u0 (flat_map (labo tau) x0) _ _).
  Qed.

  (* ----- DS1 and the swaps everywhere after a switch, versus PermB at the migrated start ----- *)

  Lemma lv_runB_ext : forall v x y, eqvB x y -> eqvB (runB v x) (runB v y).
  Proof.
    induction v as [| e v IH]; intros x y H; [exact H |]. rewrite !runT_cons. apply IH. apply stepB_ext. exact H.
  Qed.

  Lemma lv_M_run : Reconfiguration.DS1 stepA stepB eqvB M tau s0 ->
    forall u, eqvB (M (runA u s0)) (runB (map tau u) (M s0)).
  Proof.
    intros H u. induction u as [| e u IH] using rev_ind; [apply eqvB_refl |].
    rewrite runT_app, map_app, runT_app. simpl.
    apply (eqvB_trans _ _ _ (H u e)). apply stepB_ext. exact IH.
  Qed.

  (* PermB is local: P1 for free delivery, stepB respecting eqvB. *)
  Lemma lv_permB_local : forall x, Reconfiguration.PermB stepB eqvB x <->
    forall v a b, eqvB (stepB b (stepB a (runB v x))) (stepB a (stepB b (runB v x))).
  Proof.
    intros x. unfold Reconfiguration.PermB.
    assert (S1 : (forall v v', Permutation v v' -> eqvB (runB v x) (runB v' x)) <->
                 PInv (@fs_adm EB) fs_gen (msem stepB (fun y => y) x) eqvB).
    { split.
      - intros H t t' Hq. apply H. apply swap_peq_perm. exact Hq.
      - intros H v v' P. apply H. apply swap_peq_perm. exact P. }
    rewrite S1, (local_exact_all fs_adm fs_gen (msem stepB (fun y => y) x) eqvB eqvB_refl eqvB_sym eqvB_trans
                   fs_prefix).
    - split.
      + intros H v a b. pose proof (H v [a; b] [b; a] (ex_intro _ a (ex_intro _ b (conj eq_refl eq_refl))) I I) as K.
        unfold msem in K. rewrite !runT_app in K. exact K.
      + intros H p u v (a & b & -> & ->) _ _. unfold msem. rewrite !runT_app. apply H.
    - intros t t' e _ _ H. rewrite !msem_snoc. apply stepB_ext. exact H.
  Qed.

  Lemma lv_seeds_live : Reconfiguration.DS1 stepA stepB eqvB M tau s0 /\ SwapAll <->
    Reconfiguration.PermB stepB eqvB (M s0) /\ Reconfiguration.DS1 stepA stepB eqvB M tau s0.
  Proof.
    split.
    - intros [HD HS]. split; [| exact HD]. apply lv_permB_local. intros v a b. exact (HS [] v a b).
    - intros [HP HD]. split; [exact HD |]. intros u v a b.
      assert (HYZ : eqvB (runB v (M (runA u s0))) (runB (map tau u ++ v) (M s0))).
      { rewrite runT_app. apply lv_runB_ext. apply lv_M_run. exact HD. }
      pose proof (proj1 (lv_permB_local (M s0)) HP (map tau u ++ v) a b) as HL.
      apply (eqvB_trans _ _ _ (stepB_ext b _ _ (stepB_ext a _ _ HYZ))).
      apply (eqvB_trans _ _ _ HL). apply eqvB_sym. apply stepB_ext. apply stepB_ext. exact HYZ.
  Qed.

  (* ----- live runs and paths: DLive is invariance under the presentation ----- *)

  Lemma phA_complete : forall u (x : list Lab), phA (map LA u ++ LS :: x) <-> Forall isPost x.
  Proof. intros u x. rewrite phA_mapA. reflexivity. Qed.

  (* Post-switch labels can be permuted. *)
  Lemma lv_post_perm : forall l l' : list Lab, Permutation l l' -> forall u x0,
    Forall isPost (x0 ++ l) -> PEq phA lv_gen (map LA u ++ LS :: x0 ++ l) (map LA u ++ LS :: x0 ++ l').
  Proof.
    intros l l' Q. induction Q as [| x l l' Q IH | x y l | l l' l'' Q1 IH1 Q2 IH2]; intros u x0 H.
    - apply ac_refl. apply phA_complete. exact H.
    - replace (x0 ++ x :: l) with ((x0 ++ [x]) ++ l) by (rewrite <- app_assoc; reflexivity).
      replace (x0 ++ x :: l') with ((x0 ++ [x]) ++ l') by (rewrite <- app_assoc; reflexivity).
      apply IH. rewrite <- app_assoc. exact H.
    - assert (H' : Forall isPost (x0 ++ x :: y :: l))
        by exact (Permutation_Forall (Permutation_app_head x0 (perm_swap x y l)) H).
      pose proof H as Hc. apply Forall_app in Hc. destruct Hc as [_ Hc].
      inversion Hc as [| ? ? Hy Hc' E1]; subst. inversion Hc' as [| ? ? Hx _ E2]; subst.
      apply ac_gen; [apply phA_complete; exact H | apply phA_complete; exact H' |].
      exists (map LA u ++ LS :: x0), [y; x], [x; y], l.
      split; [right; exists y, x; tauto |]. rewrite <- !app_assoc. split; reflexivity.
    - eapply ac_trans; [apply IH1; exact H |]. apply IH2.
      exact (Permutation_Forall (Permutation_app_head x0 Q1) H).
  Qed.

  (* In-flight A-events cross the switch, one switch square at a time. *)
  Lemma lv_switch_front : forall u (x : list Lab), Forall isPost x ->
    PEq phA lv_gen (map LA u ++ LS :: x) (LS :: map LT u ++ x).
  Proof.
    intros u. induction u as [| a u IH] using rev_ind; intros x Hx.
    - apply ac_refl. exact Hx.
    - rewrite !map_app, <- !app_assoc. simpl.
      apply ac_trans with (map LA u ++ LS :: LT a :: x).
      + apply ac_gen; [apply phA_mapA; simpl; exact Hx | apply phA_complete; constructor; [exact I | exact Hx] |].
        exists (map LA u), [LA a; LS], [LS; LT a], x. split; [left; exists a; split; reflexivity |].
        split; reflexivity.
      + apply IH. constructor; [exact I | exact Hx].
  Qed.

  Lemma lv_aOf_complete : forall u (x : list Lab), Forall isPost x ->
    aOf (map LA u ++ LS :: x) = u ++ tOf x.
  Proof.
    intros u x Hx. unfold aOf, tOf. rewrite flat_map_app. f_equal.
    - induction u as [| a u IH]; [reflexivity |]. simpl. rewrite IH. reflexivity.
    - simpl. induction Hx as [| [a | | a | b] x Hl _ IH]; simpl in *; try contradiction; try rewrite IH; reflexivity.
  Qed.

  Lemma lv_bOf_complete : forall u (x : list Lab), bOf (map LA u ++ LS :: x) = bOf x.
  Proof.
    intros u x. unfold bOf. rewrite flat_map_app. simpl.
    induction u as [| a u IH]; [reflexivity |]. simpl. exact IH.
  Qed.

  Lemma lv_whisk_perm : forall t t', Whisk lv_gen t t' ->
    Permutation (aOf t) (aOf t') /\ Permutation (bOf t) (bOf t').
  Proof.
    intros t t' (p & u & v & w & Hg & -> & ->). unfold aOf, bOf. rewrite !flat_map_app.
    assert (FP : forall (B : Type) (f : Lab -> list B) x y, Permutation (flat_map f [x; y]) (flat_map f [y; x]))
      by (intros B f x y; simpl; rewrite !app_nil_r; apply Permutation_app_comm).
    destruct Hg as [(a & -> & ->) | (x & y & _ & _ & -> & ->)]; split.
    - apply Permutation_refl.
    - apply Permutation_refl.
    - apply Permutation_app_head, Permutation_app_tail, FP.
    - apply Permutation_app_head, Permutation_app_tail, FP.
  Qed.

  Lemma lv_peq_perm : forall t t', PEq phA lv_gen t t' ->
    Permutation (aOf t) (aOf t') /\ Permutation (bOf t) (bOf t').
  Proof.
    intros t t' H. induction H as [t _ | t t' _ _ Hw | t t' _ [IH1 IH2] | t t' t'' _ [A1 B1] _ [A2 B2]].
    - split; apply Permutation_refl.
    - exact (lv_whisk_perm t t' Hw).
    - split; apply Permutation_sym; assumption.
    - split; eapply Permutation_trans; eassumption.
  Qed.

  Lemma lv_whisk_LS : forall t t', phA t -> phA t' -> Whisk lv_gen t t' -> In LS t /\ In LS t'.
  Proof.
    intros t t' Ht Ht' (p & u & v & w & Hg & -> & ->).
    assert (Hu : phA (p ++ u)) by (apply (phA_prefix _ w); rewrite <- app_assoc; exact Ht).
    assert (Hv : phA (p ++ v)) by (apply (phA_prefix _ w); rewrite <- app_assoc; exact Ht').
    destruct (lv_qseeds p u v Hg Hu Hv) as [Q1 Q2].
    split; rewrite app_assoc; apply in_or_app; left; assumption.
  Qed.

  Lemma not_LS_A : forall u, ~ In LS (map (@LA EA EB) u).
  Proof. intros u H. apply in_map_iff in H. destruct H as [a [E _]]. discriminate E. Qed.

  Lemma lv_peq_LS : forall t t', PEq phA lv_gen t t' ->
    (In LS t <-> In LS t') /\ (~ In LS t -> t = t').
  Proof.
    intros t t' H. induction H as [t _ | t t' Ht Ht' Hw | t t' _ [IH1 IH2] | t t' t'' _ [A1 B1] _ [A2 B2]].
    - split; [reflexivity | reflexivity].
    - destruct (lv_whisk_LS t t' Ht Ht' Hw) as [Q1 Q2]. split; [tauto | intros N; contradiction].
    - split; [symmetry; exact IH1 |]. intros N. symmetry. apply IH2. rewrite IH1. exact N.
    - split; [rewrite A1; exact A2 |]. intros N. rewrite (B1 N). apply B2. rewrite <- A1. exact N.
  Qed.

  Lemma lv_out_path : forall t, phA t -> In LS t ->
    Reconfiguration.OutLive stepA stepB M tau s0 (aOf t) (bOf t) (sem t).
  Proof.
    intros t Ht HL. destruct (phA_shape t Ht) as [[u ->] | (u & x & -> & Hx)];
      [exfalso; exact (not_LS_A u HL) |].
    exists u, (tOf x), (flat_map (labo tau) x).
    rewrite (lv_aOf_complete u x Hx), lv_bOf_complete, lv_sem_complete.
    split; [apply Permutation_refl | split; [apply labo_perm | reflexivity]].
  Qed.

  Lemma lv_out_perm : forall Ea Ea' Eb Eb' y, Reconfiguration.OutLive stepA stepB M tau s0 Ea Eb y ->
    Permutation Ea Ea' -> Permutation Eb Eb' -> Reconfiguration.OutLive stepA stepB M tau s0 Ea' Eb' y.
  Proof.
    intros Ea Ea' Eb Eb' y (u & r & v & P1 & P2 & ->) Qa Qb. exists u, r, v.
    split; [exact (Permutation_trans P1 Qa) |].
    split; [exact (Permutation_trans P2 (Permutation_app_head _ Qb)) | reflexivity].
  Qed.

  (* Every live outcome is equivalent, under invariance, to the canonical path's semantics. *)
  Lemma lv_out_canon : PInv phA lv_gen sem eqvB -> forall Ea Eb y,
    Reconfiguration.OutLive stepA stepB M tau s0 Ea Eb y ->
    eqvB y (sem (LS :: map LT Ea ++ map LB Eb)).
  Proof.
    intros HI Ea Eb y (u & r & v & P1 & P2 & ->).
    assert (E1 : sem (map LA u ++ LS :: map LB v) = runB v (M (runA u s0)))
      by (rewrite lv_sem_complete, labo_LB; reflexivity).
    assert (E2 : sem (map LA u ++ LS :: map LB (map tau r ++ Eb)) =
                 sem (map LA u ++ LS :: (map LT r ++ map LB Eb)))
      by (rewrite !lv_sem_complete, labo_LB, labo_LT_LB; reflexivity).
    assert (C1 : PEq phA lv_gen (map LA u ++ LS :: map LB v) (map LA u ++ LS :: map LB (map tau r ++ Eb))).
    { exact (lv_post_perm _ _ (Permutation_map LB P2) u [] (forall_LB v)). }
    assert (Hx : Forall isPost (map (@LT EA EB) r ++ map LB Eb)).
    { apply Forall_app. split; [| apply forall_LB].
      apply Forall_forall. intros l Hl. apply in_map_iff in Hl. destruct Hl as [a [<- _]]. exact I. }
    assert (C2 : PEq phA lv_gen (map LA u ++ LS :: (map LT r ++ map LB Eb))
                   (LS :: map LT (u ++ r) ++ map LB Eb)).
    { rewrite map_app, <- app_assoc. exact (lv_switch_front u _ Hx). }
    assert (C3 : PEq phA lv_gen (LS :: map LT (u ++ r) ++ map LB Eb) (LS :: map LT Ea ++ map LB Eb)).
    { apply (lv_post_perm _ _ (Permutation_app_tail (map LB Eb) (Permutation_map LT P1)) [] []).
      simpl. apply Forall_app. split; [| apply forall_LB].
      apply Forall_forall. intros l Hl. apply in_map_iff in Hl. destruct Hl as [a [<- _]]. exact I. }
    rewrite <- E1. apply (eqvB_trans _ _ _ (HI _ _ C1)). rewrite E2.
    exact (HI _ _ (ac_trans _ _ _ _ _ C2 C3)).
  Qed.

  Lemma lv_dlive_inv : Reconfiguration.DLive stepA stepB eqvB M tau s0 <-> PInv phA lv_gen sem eqvB.
  Proof.
    split.
    - intros HD t t' Hq. destruct (ac_adm' phA (Whisk lv_gen) t t' Hq) as [Ht Ht'].
      destruct (lv_peq_LS t t' Hq) as [Hiff Heq].
      destruct (phA_shape t Ht) as [[u Eu] | (u & x & Eu & Hx)].
      + rewrite <- (Heq ltac:(rewrite Eu; apply not_LS_A)). apply eqvB_refl.
      + assert (HL : In LS t) by (rewrite Eu; apply in_or_app; right; left; reflexivity).
        destruct (lv_peq_perm t t' Hq) as [Pa Pb].
        apply (HD (aOf t) (bOf t)); [exact (lv_out_path t Ht HL) |].
        apply (lv_out_perm (aOf t') _ (bOf t')); [exact (lv_out_path t' Ht' (proj1 Hiff HL)) | |];
          apply Permutation_sym; assumption.
    - intros HI Ea Eb y1 y2 O1 O2. apply (eqvB_trans _ _ _ (lv_out_canon HI Ea Eb y1 O1)).
      apply eqvB_sym. exact (lv_out_canon HI Ea Eb y2 O2).
  Qed.

  (* Reconfiguration.det_live_exact, recovered from P1 with Q = past the switch. *)
  Theorem det_live_recovered : Reconfiguration.DLive stepA stepB eqvB M tau s0 <->
    Reconfiguration.PermB stepB eqvB (M s0) /\ Reconfiguration.DS1 stepA stepB eqvB M tau s0.
  Proof. rewrite lv_dlive_inv, lv_local, lv_seeds_iff. exact lv_seeds_live. Qed.
End LiveP.
