#!/usr/bin/env bash
# Build the mechanized proof and gate on it being axiom-free. Exits non-zero if any
# proof fails to compile OR if any key theorem depends on an axiom / admitted lemma.
# Run locally (needs coqc on PATH) or in CI; also the human one-command check.
set -euo pipefail
cd "$(dirname "$0")"

echo "== compiling =="
make clean >/dev/null 2>&1 || true
make

echo "== axiom-free gate (Print Assumptions) =="
cat > _audit.v <<'EOF'
Require Import NC.Newman NC.Governance NC.Defensibility NC.Gsm NC.Federation NC.Chaotic NC.Checker NC.Trace NC.TableCheck NC.TableFast NC.TableFn NC.AstChecker NC.AstTables NC.AstCompact NC.CRDT NC.Categorical NC.Cohomology NC.CohomologyMin NC.CohomologyGraph NC.FederationOrder NC.CausalReplay NC.GovernanceCausal NC.FederationEvents NC.GovernanceWF NC.ChaoticACC NC.FederationEventsCycles NC.FederationEventsConverse NC.GovernanceConverse.
Print Assumptions governance_confluent.
Print Assumptions governance_unique_normal_forms.
Print Assumptions example_confluent.
Print Assumptions disjoint_events_commute.
Print Assumptions repair_terminates.
Print Assumptions kleene_lfp.
Print Assumptions lfp_unique.
Print Assumptions chaotic_reaches_lfp.
Print Assumptions chaotic_limit_unique.
Print Assumptions checked_converges.
Print Assumptions check_sound_commute.
Print Assumptions check_sound_converges.
Print Assumptions check_no_overflow.
Print Assumptions check_binary_writes_exact.
Print Assumptions run_tequiv.
Print Assumptions perm_tequiv_total.
Print Assumptions tget_of_list.
Print Assumptions check_tables_nf_valid.
Print Assumptions check_tables_step_valid.
Print Assumptions check_tables_commute.
Print Assumptions check_tables_converges.
Print Assumptions check_tables_converges_all.
Print Assumptions check_tables_pairs_in_range.
Print Assumptions vlook_of_listV.
Print Assumptions bget_chunk.
Print Assumptions check_fast_eq.
Print Assumptions check_fast_converges.
Print Assumptions check_fn_converges.
Print Assumptions check_tables_fn.
Print Assumptions check_fast_fn.
Print Assumptions scan_cells_fn.
Print Assumptions stepG_valid_eq.
Print Assumptions checkBuild_normalize_valid.
Print Assumptions checkBuild_wfc_terminates.
Print Assumptions checkBuild_wfc_potential.
Print Assumptions checkBuild_step_valid.
Print Assumptions checkBuild_commute.
Print Assumptions checkBuild_converges.
Print Assumptions checkBuild_converges_all.
Print Assumptions checkBuild_no_overflow.
Print Assumptions checkBuild_binary_writes_exact.
Print Assumptions checkBuild_pairs_in_range.
Print Assumptions boxT_eq.
Print Assumptions enc_box.
Print Assumptions box_enc.
Print Assumptions cells_ok.
Print Assumptions tables_fn_eq.
Print Assumptions checkBuildT_eq.
Print Assumptions checkBuildT_converges.
Print Assumptions foldD_eq.
Print Assumptions foldB_eq.
Print Assumptions p2_inv.
Print Assumptions rdj_view.
Print Assumptions alignN_rdq.
Print Assumptions scanC_spec.
Print Assumptions checkBuildC_eq.
Print Assumptions checkBuildC_converges.
Print Assumptions compensationFree_step_no_repair.
Print Assumptions cmrdt_SEC.
Print Assumptions cmrdt_governed_SEC.
Print Assumptions cvrdt_SEC.
Print Assumptions witness_converges.
Print Assumptions witness_not_cmrdt.
Print Assumptions witness_leaves_valid_space.
Print Assumptions image_iff_fixed.
Print Assumptions retract_into_fixed.
Print Assumptions clamp3_retracts_into.
Print Assumptions consistent_iff_equalizer.
Print Assumptions rhoF_retraction.
Print Assumptions rhoF_image_iff_L2.
Print Assumptions updates_commute.
Print Assumptions rhoFold_retraction.
Print Assumptions rhoFold_image_iff_consistent.
Print Assumptions rhoFold_compositional.
Print Assumptions gluing_order_dependent.
Print Assumptions fixed_point_iff_trivial_holonomy.
Print Assumptions flip_no_section.
Print Assumptions identity_holonomy_has_section.
Print Assumptions simultaneous_section_iff.
Print Assumptions S3Sep.a_inv.
Print Assumptions S3Sep.del_e1_nontrivial.
Print Assumptions S3Sep.a_even.
Print Assumptions S3Sep.b_odd.
Print Assumptions sectionb_iff.
Print Assumptions sign_hom.
Print Assumptions section_G_implies_ab.
Print Assumptions min_G_lower.
Print Assumptions min_G_attained.
Print Assumptions min_ab_lower.
Print Assumptions min_ab_attained.
Print Assumptions theta_separation.
Print Assumptions section_iff_coboundary.
Print Assumptions sat_iff_trivial_holonomy.
Print Assumptions tree_has_section.
Print Assumptions tree_unique.
Print Assumptions cycle_basis_criterion.
Print Assumptions keep_balanced_suffices.
Print Assumptions unbalanced_blocks.
Print Assumptions tri_identity_has_section.
Print Assumptions tri_flip_no_section.
Print Assumptions gauge_fix.
Print Assumptions gauge_fixed_holonomy.
Print Assumptions tree_gauge.
Print Assumptions tree_const.
Print Assumptions H1_classification.
Print Assumptions tree_vertex_count.
Print Assumptions betti_number.
Print Assumptions tri_flip_not_cohomologous_to_identity.
Print Assumptions step_comm.
Print Assumptions bubble.
Print Assumptions order_independent.
Print Assumptions ex_orders_agree.
Print Assumptions causal_convergence.
Print Assumptions causal_cmrdt_SEC.
Print Assumptions compensation_free_exact.
Print Assumptions witness_causal_converges.
Print Assumptions witness_causal_not_cmrdt.
Print Assumptions witness_beyond_all_pairs.
Print Assumptions witness_orders_agree.
Print Assumptions tequiv_bubble.
Print Assumptions causal_tequiv.
Print Assumptions causal_governance_confluent.
Print Assumptions causal_governance_unique_normal_forms.
Print Assumptions cw_confluent.
Print Assumptions cw_violates_all_pairs_cc1.
Print Assumptions fed_events_commute.
Print Assumptions fed_interleavings_converge.
Print Assumptions fed_permutations_converge.
Print Assumptions propagation_flush.
Print Assumptions dist_interleavings_converge.
Print Assumptions xu_implies_c1_c2.
Print Assumptions supply_instance.
Print Assumptions supply_converges.
Print Assumptions audit_counterexample.
Print Assumptions c2_counterexample.
Print Assumptions wf_lex2.
Print Assumptions governance_wf_terminating.
Print Assumptions governance_wf_confluent.
Print Assumptions governance_wf_unique_normal_forms.
Print Assumptions causal_governance_wf_terminating.
Print Assumptions causal_governance_wf_confluent.
Print Assumptions causal_governance_wf_unique_normal_forms.
Print Assumptions governance_confluent_from_wf.
Print Assumptions causal_governance_confluent_from_wf.
Print Assumptions governance_comp_wf_confluent.
Print Assumptions governance_lex_confluent.
Print Assumptions zw_confluent.
Print Assumptions zw_unique_normal_forms.
Print Assumptions zw_any_overdraft_repairs.
Print Assumptions kleene_acc_not_forever.
Print Assumptions kleene_acc_lfp_nn.
Print Assumptions kleene_acc_stabilizes.
Print Assumptions kleene_acc_lfp.
Print Assumptions finite_height_acc.
Print Assumptions kleene_finite_height_lfp.
Print Assumptions chaotic_acc_terminates.
Print Assumptions chaotic_acc_reaches_lfp.
Print Assumptions chaotic_acc_from_bot.
Print Assumptions chaotic_reaches_lfp_from_acc.
Print Assumptions ole_acc.
Print Assumptions ole_no_rank.
Print Assumptions ple_acc.
Print Assumptions ple_no_rank.
Print Assumptions pl_chaotic_reaches_lfp.
Print Assumptions pl_chaotic_from_bot.
Print Assumptions pl_kleene_lfp_value.
Print Assumptions gc_sufficient.
Print Assumptions gc_necessary.
Print Assumptions gc_iff.
Print Assumptions gc_image.
Print Assumptions cyc_N_lfp.
Print Assumptions cyc_N_unique.
Print Assumptions cyc_sweep_order_independent.
Print Assumptions cyc_N_idem.
Print Assumptions cyc_events_converge_iff.
Print Assumptions cyc_instance.
Print Assumptions bottom_matters.
Print Assumptions cyc_counterexample.
Print Assumptions conv_c1_runs.
Print Assumptions conv_c2_runs.
Print Assumptions conv_c1_diverge.
Print Assumptions conv_c2_diverge.
Print Assumptions reach_commute_iff.
Print Assumptions acyclic_gc_iff.
Print Assumptions gc_iff_reach.
Print Assumptions fed_exact.
Print Assumptions fed_exact_full.
Print Assumptions static_c1_c2_gc.
Print Assumptions naive_converse_fails.
Require Import NC.AtLeastOnce.
Print Assumptions dedup_In.
Print Assumptions dedup_NoDup.
Print Assumptions alo_absorbed.
Print Assumptions alo_commuting_exactly_once.
Print Assumptions alo_commuting_converges.
Print Assumptions causal_alo_absorbs.
Print Assumptions causal_alo_dedup_causal.
Print Assumptions causal_alo_exactly_once.
Print Assumptions causal_alo_converges.
Print Assumptions non_idempotent_diverges.
Print Assumptions inc_not_idempotent.
Print Assumptions inc_duplicate_diverges.
Print Assumptions late_duplicate_diverges.
Print Assumptions mx_alo_converges.
Print Assumptions fl_not_all_commute.
Print Assumptions fl_causal_alo_converges.
Print Assumptions newman_on.
Print Assumptions CR_UN.
Print Assumptions jc_exact.
Print Assumptions jc_unique_normal_forms.
Print Assumptions cc_reach_jc.
Print Assumptions cc_reach_unique_normal_forms.
Print Assumptions cc1_runs.
Print Assumptions cc2_runs.
Print Assumptions cc1_fail_diverge.
Print Assumptions cc2_fail_diverge.
Print Assumptions reach_run.
Print Assumptions cc1_fail_diverge_from.
Print Assumptions cc2_fail_diverge_from.
Print Assumptions cc_exact_from.
Print Assumptions cc_exact.
Print Assumptions cc_exact_global.
Print Assumptions rho_star_qualifier.
Print Assumptions masked_cc1.
Print Assumptions causal_prefix.
Print Assumptions causal_swap.
Print Assumptions tequiv_causal.
Print Assumptions ccr_convergence.
Print Assumptions ccr_diverge.
Print Assumptions causal_exact.
Print Assumptions causal_convergence_exact.
Print Assumptions n_ccr.
Print Assumptions naive_causal_converse_fails.
Require Import NC.CoordinatedCycles.
Print Assumptions topo_topoF.
Print Assumptions frun_run.
Print Assumptions rule_some.
Print Assumptions root_none.
Print Assumptions driven.
Print Assumptions cons_section.
Print Assumptions drive_order_exists.
Print Assumptions drive_common.
Print Assumptions drive_consistent.
Print Assumptions balanced_any_section.
Print Assumptions kept_section.
Print Assumptions coordinated_sound.
Print Assumptions coordinated_unique_nf.
Print Assumptions coordination_needed.
Print Assumptions plan_exact.
Print Assumptions coordinated_events_converge.
Print Assumptions copyback_zero_coordination.
Print Assumptions negation_one_coordinated.
Print Assumptions copyback_without_authority.
Print Assumptions root_choice_matters.
Print Assumptions noninvertible_balance_not_static.
Print Assumptions nonfree_holonomy_counterexample.
Require NC.Calculus.
Print Assumptions NC.Calculus.calc_cc2_strong_absorption.
Print Assumptions NC.Calculus.calc_cc1_iff_commute_of_sa.
Print Assumptions NC.Calculus.calc_cc1_iff_commute_under_cc2.
Print Assumptions NC.Calculus.base_lem_repair_commute.
Print Assumptions NC.Calculus.base_lem_repair_idempotent.
Print Assumptions NC.Calculus.calc_decomp_normalizer.
Print Assumptions NC.Calculus.base_thm_footprint_cc1_refuted.
Print Assumptions NC.Calculus.base_thm_footprint_cc1_raw_refuted.
Print Assumptions NC.Calculus.calc_footprint_cc1_iff.
Print Assumptions NC.Calculus.calc_footprint_cc1_valid_iff.
Print Assumptions NC.Calculus.calc_footprint_cc1_valid.
Print Assumptions NC.Calculus.calc_fp_absorb_iff_sa.
Print Assumptions NC.Calculus.calc_footprint_cc1.
Print Assumptions NC.Calculus.calc_valid_needs_commute.
Print Assumptions NC.Calculus.calc_valid_needs_disjoint.
Print Assumptions NC.Calculus.calc_valid_needs_repair_local.
Print Assumptions NC.Calculus.calc_all_needs_commute.
Print Assumptions NC.Calculus.calc_all_needs_absorb.
Print Assumptions NC.Calculus.calc_all_needs_repair_local.
Print Assumptions NC.Calculus.calc_clamp_instance.
Print Assumptions NC.Calculus.calc_components_cc1_iff.
Print Assumptions NC.Calculus.calc_components_cc1_valid.
Print Assumptions NC.Calculus.calc_components_instance.
Print Assumptions NC.Calculus.base_rem_practical_import_refuted.
Print Assumptions NC.Calculus.calc_order_credit_repair_commute.
Print Assumptions NC.Calculus.calc_order_cc1.
Print Assumptions NC.Calculus.base_pattern1_cc1_refuted.
Print Assumptions NC.Calculus.base_pattern1_cc2_refuted.
Print Assumptions NC.Calculus.calc_canonical_cc2_iff.
Print Assumptions NC.Calculus.calc_canonical_pattern.
Print Assumptions NC.Calculus.calc_canonical_instance.
Print Assumptions NC.Calculus.base_thm_product.
Print Assumptions NC.Calculus.base_thm_product_decomposable.
Print Assumptions NC.Calculus.calc_product_instance.
Require Import NC.MonotoneFederation.
Print Assumptions finite_complete_nn.
Print Assumptions iter_below_prefixed.
Print Assumptions fed_def_lattice_shared_cyclic_hyps.
Print Assumptions net_sweep_valid.
Print Assumptions net_iter_valid.
Print Assumptions net_lfp_valid.
Print Assumptions net_Ncyc_correct.
Print Assumptions net_Ncyc_idem.
Print Assumptions net_events_converge_iff.
Print Assumptions b2_complete.
Print Assumptions b2r_complete.
Print Assumptions fed_thm_monotone_cycles_lfp_invalid.
Print Assumptions fed_valid_corrected_instance.
Print Assumptions fed_thm_monotone_cycles_events_refuted.
Print Assumptions fed_thm_monotone_cycles_events_corrected.
Print Assumptions negation_not_monotone.
Print Assumptions w_complete_nn.
Print Assumptions fed_thm_monotone_cycles_kleene_formula_fails.
Print Assumptions kleene_sup_lfp.
Print Assumptions kleene_sup_valid.
Print Assumptions kleene_sup_instance.
Print Assumptions widening_sound.
Print Assumptions widening_not_normal_form.
Print Assumptions fed_rem_convexity_refuted.
Print Assumptions lfp_mono_param.
Print Assumptions fed_rem_convexity_corrected.
Print Assumptions convexity_corrected_instance.
Require Import NC.CohomologyGeneral.
Print Assumptions cg_len_map.
Print Assumptions cg_len_seq.
Print Assumptions bounded_ex_dec.
Print Assumptions least_witness.
Print Assumptions nodup_map_inj.
Print Assumptions inj_bound.
Print Assumptions loop_cons.
Print Assumptions pre_succ.
Print Assumptions pre_all.
Print Assumptions section_pre.
Print Assumptions section_fixed.
Print Assumptions section_of_fixed.
Print Assumptions thm_obstruction_general.
Print Assumptions sections_are_fixed_points.
Print Assumptions orbit_stable.
Print Assumptions orbit_ext.
Print Assumptions reaches_fixed_iff_section.
Print Assumptions thm_obstruction_reachable.
Print Assumptions diagnose_bounded.
Print Assumptions diagnose_orbit_witness.
Print Assumptions diagnose_dichotomy.
Print Assumptions c15_exact_refuter.
Print Assumptions c15_free_definitive.
Print Assumptions c15_injective_reaches_iff_fixed.
Print Assumptions c15_convergent_result_sound.
Print Assumptions c15_regular_definitive.
Print Assumptions c15_regular_is_free.
Print Assumptions tri_full.
Print Assumptions swap_loop_g.
Print Assumptions tri_orbit01.
Print Assumptions c15_seed_orbits.
Print Assumptions c15_seed_settles.
Print Assumptions c15_tri_section.
Print Assumptions c15_definitive_claim_false.
Print Assumptions c15_convergent_result_not_global.
Print Assumptions prop_minimal_qualified_iff.
Print Assumptions prop_minimal_qualifiers_needed.
Print Assumptions meets_dec.
Print Assumptions must_hit.
Print Assumptions choose_hits.
Print Assumptions forall2_in.
Print Assumptions hits_nodup.
Print Assumptions edge_disjoint_lower_bound.
Print Assumptions edge_disjoint_min.
Print Assumptions bool_edge_eq_dec.
Print Assumptions bowtie_min_two.
Print Assumptions sat_push.
Print Assumptions section_pushforward.
Print Assumptions feasible_pushforward.
Print Assumptions min_G_ge_min_image.
Print Assumptions klein_hom.
Print Assumptions klein_min_ge_1.
Print Assumptions otree_tree.
Print Assumptions msection_app.
Print Assumptions msection_upd_fresh.
Print Assumptions out_tree_section.
Print Assumptions out_tree_unique.
Print Assumptions rooted_criterion.
Print Assumptions rooted_coordination_suffices.
Print Assumptions c22_cycle_basis_fails.
Print Assumptions c22_rooted_instance.
Print Assumptions c13_two_ways_not_exhaustive.
Require Import NC.Stream.
Print Assumptions stream_star_inv.
Print Assumptions stream_star_sub.
Print Assumptions stream_SN_sub.
Print Assumptions st_rm_head.
Print Assumptions st_rm_notin.
Print Assumptions st_rm_perm_cons.
Print Assumptions st_rm_perm.
Print Assumptions st_in_rm_neq.
Print Assumptions st_rm_app.
Print Assumptions prstep_cstep.
Print Assumptions star_prstep_cstep.
Print Assumptions nf_prstep_cstep.
Print Assumptions nf_cstep_prstep.
Print Assumptions st_SN_cstep.
Print Assumptions st_SN_prstep.
Print Assumptions st_cstep_unique_nf.
Print Assumptions st_cstep_perm.
Print Assumptions st_star_cstep_perm.
Print Assumptions st_nf_cstep_perm.
Print Assumptions st_find_enabled.
Print Assumptions st_nf_or_step.
Print Assumptions st_pnf_exists.
Print Assumptions st_nf_valid.
Print Assumptions comp_phase_terminates.
Print Assumptions comp_phase_done_valid.
Print Assumptions stream_validity.
Print Assumptions settled_empty_buffer.
Print Assumptions stream_order_independence.
Print Assumptions st_feasible_reach.
Print Assumptions st_feasible_nil_buffer.
Print Assumptions prun_valid.
Print Assumptions st_valid_empty_nf.
Print Assumptions stream_orders_agree.
Print Assumptions st_same_set_perm.
Print Assumptions stream_agreement.
Print Assumptions base_thm_convergence_c.
Print Assumptions stream_convergence.
Print Assumptions base_rem_set_function.
Print Assumptions stream_settle.
Print Assumptions stream_all_received.
Print Assumptions st_nodup_app_covered.
Print Assumptions base_cor_quiescent.
Print Assumptions star_prstep_app.
Print Assumptions incremental_computes.
Print Assumptions base_thm_convergence.
Print Assumptions base_cor_quiescent_nat.
Print Assumptions ct_registry.
Print Assumptions ct_nf_empty.
Print Assumptions ct_run.
Print Assumptions ct_one_step.
Print Assumptions base_thm_convergence_c_counterexample.
Print Assumptions ct_seq_snoc.
Print Assumptions ct_seq_len.
Print Assumptions base_thm_convergence_transient_counterexample.
Print Assumptions zc_rho_star_reach.
Print Assumptions zw_stream_registry.
Print Assumptions zc_apply.
Print Assumptions zc_comp.
Print Assumptions zc_rm1.
Print Assumptions zc_rm2.
Print Assumptions zc_nf_empty.
Print Assumptions zp_run12.
Print Assumptions zp_run21.
Print Assumptions zp_run1.
Print Assumptions zp_run2.
Print Assumptions zw_processors.
Print Assumptions zw_stream_agree.
Print Assumptions zw_stream_quiescent.
Print Assumptions zw_stream_quiescent_nat.
Print Assumptions zw_stream_convergence_nat.
Print Assumptions zw_incremental.
Print Assumptions base_cor_infinite.
Print Assumptions base_cor_infinite_quiescent.
Require Import NC.PaperInstances.
Print Assumptions rho_star_one_step.
Print Assumptions no_SN_of_total.
Print Assumptions cred_star.
Print Assumptions star_cred.
Print Assumptions of_registry.
Print Assumptions of_valid_paper.
Print Assumptions of_rho_star_iterated.
Print Assumptions of_cc1.
Print Assumptions of_cc2.
Print Assumptions of_paper_traces.
Print Assumptions of_unique_normal_forms.
Print Assumptions of_processors.
Print Assumptions naive_registry.
Print Assumptions naive_cc2_fails.
Print Assumptions naive_paper_witness_fails.
Print Assumptions naive_cc1_fails.
Print Assumptions naive_stream_diverges.
Print Assumptions ri_registry.
Print Assumptions ri_rho_star_iterated.
Print Assumptions ri_depth.
Print Assumptions thm_necessity.
Print Assumptions ri_depth_exact.
Print Assumptions ri_no_ubc.
Print Assumptions ri_cc_any_extension.
Print Assumptions ri_what_fails.
Print Assumptions four_registry.
Print Assumptions four_paths.
Print Assumptions prop_cc_necessary.
Print Assumptions cycle_paper_trace.
Print Assumptions prop_cycle_necessary.
Print Assumptions m1_paper_trace.
Print Assumptions prop_m1_necessary.
Print Assumptions m1_single_round_fails.
Print Assumptions r2_necessary.
Print Assumptions r1_necessary.
Print Assumptions ms_instance.
Print Assumptions ms_paper_traces.
Print Assumptions ms_converges.
Require Import NC.RhoStar.
Print Assumptions base_def_rhostar.
Print Assumptions base_def_rhostar_least_unique.
Print Assumptions rho_star_valid.
Print Assumptions rho_star_fix.
Print Assumptions rho_star_idem.
Print Assumptions rho_star_rho.
Print Assumptions rho_star_steps_le_measure.
Print Assumptions rho_star_canonical.
Print Assumptions rho_star_wf_valid.
Print Assumptions rho_star_wf_idem.
Print Assumptions cat_bg_rho_idempotent.
Print Assumptions cat_bg_valid_from_any_state.
Print Assumptions cat_bg_lemma_zero.
Print Assumptions cat_bg_nonempty_needs_a_state.
Print Assumptions base_rem_absorption.
Print Assumptions base_rem_absorption_enabled.
Print Assumptions base_thm_strong_absorption.
Print Assumptions strong_absorption_iff_cc2.
Print Assumptions termination_bound.
Print Assumptions comp_total_bound.
Print Assumptions comp_per_event_bound.
Print Assumptions base_lem_termination_bound.
Print Assumptions causal_lem_termination_bound.
Print Assumptions base_thm_complexity_comp_total.
Print Assumptions base_thm_complexity_per_event.
Print Assumptions base_lem_finite_implies_ubc.
Print Assumptions deps_enabled_after_remove.
Print Assumptions deps_enabled_after_comp.
Print Assumptions deps_causal_enabled_after_remove.
Print Assumptions deps_causal_enabled_after_comp.
Print Assumptions deps_coenabled_independent.
Print Assumptions wfc_governance_confluent.
Print Assumptions wfc_governance_unique_normal_forms.
Print Assumptions wfc_causal_governance_confluent.
Print Assumptions wfc_causal_governance_unique_normal_forms.
Print Assumptions paper_causal_governance_confluent.
Print Assumptions paper_causal_governance_unique_normal_forms.
Print Assumptions paper_governance_confluent.
Print Assumptions paper_governance_unique_normal_forms.
Print Assumptions wfc_cc_exact_from.
Print Assumptions wfc_governance_wf_confluent.
Print Assumptions wfc_causal_governance_wf_confluent.
Print Assumptions lv_ubc.
Print Assumptions lv_strong_absorption.
Print Assumptions lv_rho_star_caps.
Print Assumptions lv_paper_confluent.
Print Assumptions lv_paper_governance_confluent.
Print Assumptions lv_termination_bound.
Print Assumptions lv_termination_bound_tight.
Print Assumptions lv_def_rhostar.
Print Assumptions zw_rho_star_built.
Print Assumptions zw_confluent_built.
Print Assumptions crel_fun.
Print Assumptions crel_iter.
Print Assumptions iter_crel.
Print Assumptions rho_star_wf_crel.
Print Assumptions rho_star_crel.
Print Assumptions lv_wfc.
Print Assumptions lv_cc1.
Print Assumptions lv_cc2.
Print Assumptions zw_crel.
Require Import NC.CategoricalBridge.
Print Assumptions NC.Categorical.fixed_is_equalizer.
Print Assumptions NC.Categorical.retract_fixes_fixed.
Print Assumptions NC.Categorical.rhoL_idempotent.
Print Assumptions NC.Categorical.rhoL_image_iff_L.
Print Assumptions NC.Categorical.rhoL_L_iff_fixed.
Print Assumptions NC.Categorical.rhoFold_sound.
Print Assumptions NC.Categorical.rhoFold_complete.
Print Assumptions NC.Categorical.rhoF_from_app.
Print Assumptions NC.CategoricalBridge.map_split.
Print Assumptions NC.CategoricalBridge.prec_mid.
Print Assumptions NC.CategoricalBridge.stepN_local.
Print Assumptions NC.CategoricalBridge.isTarget_true.
Print Assumptions NC.CategoricalBridge.consistent_targets.
Print Assumptions NC.CategoricalBridge.cat_LF_split.
Print Assumptions NC.CategoricalBridge.cat_prop_one.
Print Assumptions NC.CategoricalBridge.cat_prop_one_product.
Print Assumptions NC.CategoricalBridge.cat_prop_one_limit.
Print Assumptions NC.CategoricalBridge.ovr_rho_idem.
Print Assumptions NC.CategoricalBridge.stepN_idem.
Print Assumptions NC.CategoricalBridge.stepN_fixed_iff.
Print Assumptions NC.CategoricalBridge.LF_pointwise.
Print Assumptions NC.CategoricalBridge.LF_ext.
Print Assumptions NC.CategoricalBridge.stepT_idem.
Print Assumptions NC.CategoricalBridge.look_tag_in.
Print Assumptions NC.CategoricalBridge.look_tag_out.
Print Assumptions NC.CategoricalBridge.look_agree.
Print Assumptions NC.CategoricalBridge.run_out.
Print Assumptions NC.CategoricalBridge.fold_run_gen.
Print Assumptions NC.CategoricalBridge.rhoFold_run.
Print Assumptions NC.CategoricalBridge.look_rhoFold.
Print Assumptions NC.CategoricalBridge.rhoFold_order_independent.
Print Assumptions NC.CategoricalBridge.rhoFold_order_perm.
Print Assumptions NC.CategoricalBridge.consistentList_iff_LF.
Print Assumptions NC.CategoricalBridge.cat_thm_one_sound.
Print Assumptions NC.CategoricalBridge.cat_thm_one_complete.
Print Assumptions NC.CategoricalBridge.cat_thm_one_idempotent.
Print Assumptions NC.CategoricalBridge.cat_thm_one_image.
Print Assumptions NC.CategoricalBridge.cat_thm_one_fixed.
Print Assumptions NC.CategoricalBridge.cat_thm_one_order_independent.
Print Assumptions NC.CategoricalBridge.cat_thm_one_fold_image.
Print Assumptions NC.CategoricalBridge.nv_idem.
Print Assumptions NC.CategoricalBridge.nv_putget.
Print Assumptions NC.CategoricalBridge.nv_sh_fixed.
Print Assumptions NC.CategoricalBridge.nv_run.
Print Assumptions NC.CategoricalBridge.nv_sound.
Print Assumptions NC.CategoricalBridge.nv_s0_not_LF.
Print Assumptions NC.CategoricalBridge.nv_orders_agree.
Print Assumptions NC.CategoricalBridge.nv_prop_one.
Print Assumptions NC.CategoricalBridge.cx_topo.
Print Assumptions NC.CategoricalBridge.cat_thm_one_m1_counterexample.
Require Import NC.FederationEventsCyclesCheck.
Print Assumptions lfp_commute_gc.
Print Assumptions footprint_c1.
Print Assumptions cyc_check_step.
Print Assumptions cyc_check_converges.
Print Assumptions cyc_check_gc.
Print Assumptions cyc_check_gc_lfp.
Print Assumptions cyc_check_instance.
Print Assumptions check_rejects_latch.
Print Assumptions monotone_c2_insufficient.
Print Assumptions c1_localcc_insufficient.
Require Import NC.FederationGRS.
Print Assumptions single_round.
Print Assumptions phase2_invariant.
Print Assumptions raw_ev.
Print Assumptions grho_valid.
Print Assumptions grho_id.
Print Assumptions gov_eq.
Print Assumptions gov_two_eq.
Print Assumptions grs_cc1_valid.
Print Assumptions fed_grs_exact.
Print Assumptions fed_grs_un_c1_c2.
Print Assumptions flush_raw.
Print Assumptions grs_cc1.
Print Assumptions grs_cc2.
Print Assumptions grs_unique_nf.
Print Assumptions grs_nf_exists.
Print Assumptions guarded_form.
Print Assumptions fed_guarded_exact.
Print Assumptions fed_guarded_c1_c2.
Print Assumptions source_projection.
Print Assumptions fed_authority_a_gen.
Print Assumptions perm_grp.
Print Assumptions grp_equations.
Print Assumptions topo_unique.
Print Assumptions fed_nf_constructive.
Print Assumptions fed_nf_recipe_xu.
Print Assumptions paper_rho_valid.
Print Assumptions fed_phase1_bound.
Print Assumptions paper_cc2_star.
Print Assumptions paper_common.
Print Assumptions paper_localcc.
Print Assumptions fed_lem_authority_b.
Print Assumptions fed_lem_authority_c_local.
Print Assumptions fed_lem_resolved_termination.
Print Assumptions fed_lem_fed_termination.
Print Assumptions fed_lem_authority_a.
Print Assumptions fed_resolved_cc_corrected.
Print Assumptions fed_thm_resolved_convergence_corrected.
Print Assumptions fed_thm_resolved_convergence_guarded.
Print Assumptions fed_thm_resolved_convergence_exact.
Print Assumptions fed_thm_fed_cc_corrected.
Print Assumptions fed_thm_fed_cc_corrected_machine.
Print Assumptions fed_thm_fed_convergence_corrected.
Print Assumptions fed_thm_fed_convergence_guarded.
Print Assumptions fed_thm_fed_convergence_exact.
Print Assumptions fed_lem_authority_c_corrected.
Print Assumptions fed_cor_resolved_nf_corrected.
Print Assumptions fed_cor_fed_nf_corrected.
Print Assumptions au_paper.
Print Assumptions fed_thm_fed_cc_refuted.
Print Assumptions fed_thm_fed_convergence_refuted.
Print Assumptions fed_thm_resolved_convergence_refuted.
Print Assumptions fed_lem_authority_c_refuted.
Print Assumptions su_paper.
Print Assumptions fed_supply_paper_instance.
Print Assumptions cw_paper.
Print Assumptions fed_c2_paper_counterexample.
Print Assumptions gg_paper.
Print Assumptions fed_grs_c1_c2_insufficient.
Print Assumptions fed_cor_fed_nf_refuted.
Print Assumptions fed_lem_authority_a_instance.
Require Import NC.Collapse.
Print Assumptions topoF_acyclic.
Print Assumptions collapse_block_order.
Print Assumptions collapse_contract_topo.
Print Assumptions collapse_contract_acyclic.
Print Assumptions collapse_every_order_refuted.
Print Assumptions collapse_convexity_needed.
Print Assumptions collapse_a_wfc.
Print Assumptions collapse_a_guarded.
Print Assumptions collapse_a_guarded_perm.
Print Assumptions collapse_a_guarded_exact.
Print Assumptions collapse_b_import_iff.
Print Assumptions collapse_b_export_iff.
Print Assumptions collapse_b_import_corrected.
Print Assumptions collapse_b_export_corrected.
Print Assumptions collapse_nf_agree.
Print Assumptions collapse_nf_factor.
Print Assumptions collapse_c_runs_agree.
Print Assumptions collapse_c_traceconv.
Print Assumptions collapse_c_exact.
Print Assumptions collapse_modular_c1.
Print Assumptions collapse_modular_c2.
Print Assumptions collapse_modular_converges.
Print Assumptions collapse_regroup.
Print Assumptions collapse_hierarchical.
Print Assumptions collapse_product_convex.
Print Assumptions collapse_c_guarded_iff.
Print Assumptions collapse_c_unguarded_iff.
Print Assumptions collapse_c_guarded_exact.
Print Assumptions collapse_c_guarded_c1_c2.
Print Assumptions collapse_a_refuted.
Print Assumptions collapse_b_import_refuted.
Print Assumptions collapse_b_export_refuted.
Print Assumptions port_c1_transfer.
Print Assumptions port_c2_transfer.
Print Assumptions port_interior_certificate.
Print Assumptions port_interior_invariant.
Print Assumptions port_sealed_write_refuted.
Print Assumptions chain_collapse_instance.
Print Assumptions chain_common.
Print Assumptions chain_c1.
Print Assumptions chain_c2.
Print Assumptions chain_convex.
Print Assumptions bi_common.
Print Assumptions sub_common.
Print Assumptions path_first.
Print Assumptions path_last.
Require Import NC.FederationEventsCyclesMulti.
Print Assumptions NC.FederationEventsCyclesMulti.upd_get_in.
Print Assumptions NC.FederationEventsCyclesMulti.upd_prod.
Print Assumptions NC.FederationEventsCyclesMulti.upd_full.
Print Assumptions NC.FederationEventsCyclesMulti.chainW.
Print Assumptions NC.FederationEventsCyclesMulti.multi_edge_c1.
Print Assumptions NC.FederationEventsCyclesMulti.multi_edge_c1_free.
Print Assumptions NC.FederationEventsCyclesMulti.m1_necessary.
Print Assumptions NC.FederationEventsCyclesMulti.resolver_joint_c1.
Print Assumptions NC.FederationEventsCyclesMulti.resolver_edge_insufficient.
Print Assumptions NC.FederationEventsCyclesMulti.resolver_instance.
Print Assumptions NC.FederationEventsCyclesMulti.prod_nf.
Print Assumptions NC.FederationEventsCyclesMulti.multi_edge_converges.
Print Assumptions NC.FederationEventsCyclesMulti.multi_edge_gc.
Print Assumptions NC.FederationEventsCyclesMulti.multi_edge_instance.
EOF
OUT=$(coqc -Q . NC _audit.v 2>/dev/null || true)
rm -f _audit.v _audit.vo .*.aux _audit.glob
echo "$OUT"

if echo "$OUT" | grep -qiE 'Axioms:|^Axiom|admit'; then
  echo "FAIL: an axiom or admitted lemma was detected"
  exit 1
fi
N=$(echo "$OUT" | grep -c 'Closed under the global context' || true)
if [ "$N" -lt 729 ]; then
  echo "FAIL: expected 729 axiom-free results, got $N"
  exit 1
fi
echo "PASS: all $N theorems are Closed under the global context (no axioms, no admits)"
