// Code generated by gogen from semantics.json (module Main). DO NOT EDIT.

package semantics

type I_big struct {
	tag  uint8
	f0_0 int64
	f0_1 int64
	f0_2 int64
	f0_3 int64
	f0_4 int64
	f0_5 int64
	f0_6 int64
	f0_7 int64
	f2_0 int64
}

var C_C0 = &I_big{tag: 1}
var C_C2 = &I_big{tag: 3}

// K_B builds the constructor B.
func K_B(a0 int64, a1 int64, a2 int64, a3 int64, a4 int64, a5 int64, a6 int64, a7 int64) *I_big {
	return &I_big{tag: 0, f0_0: a0, f0_1: a1, f0_2: a2, f0_3: a3, f0_4: a4, f0_5: a5, f0_6: a6, f0_7: a7}
}

// K_C0 builds the constructor C0.
func K_C0() *I_big {
	return &I_big{tag: 1}
}

// K_C1 builds the constructor C1.
func K_C1(a0 int64) *I_big {
	return &I_big{tag: 2, f2_0: a0}
}

// K_C2 builds the constructor C2.
func K_C2() *I_big {
	return &I_big{tag: 3}
}

type I_comparison struct {
	tag uint8
}

var C_Eq = &I_comparison{tag: 0}
var C_Lt = &I_comparison{tag: 1}
var C_Gt = &I_comparison{tag: 2}

// K_Eq builds the constructor Eq.
func K_Eq() *I_comparison {
	return &I_comparison{tag: 0}
}

// K_Lt builds the constructor Lt.
func K_Lt() *I_comparison {
	return &I_comparison{tag: 1}
}

// K_Gt builds the constructor Gt.
func K_Gt() *I_comparison {
	return &I_comparison{tag: 2}
}

type I_list[P_A any] struct {
	tag  uint8
	f1_0 P_A
	f1_1 *I_list[P_A]
}

// K_Nil builds the constructor Nil.
func K_Nil[P_A any]() *I_list[P_A] {
	return &I_list[P_A]{tag: 0}
}

// K_Cons builds the constructor Cons.
func K_Cons[P_A any](a0 P_A, a1 *I_list[P_A]) *I_list[P_A] {
	return &I_list[P_A]{tag: 1, f1_0: a0, f1_1: a1}
}

type I_mask struct {
	tag  uint8
	f1_0 int64
}

var C_IsNul = &I_mask{tag: 0}
var C_IsNeg = &I_mask{tag: 2}

// K_IsNul builds the constructor IsNul.
func K_IsNul() *I_mask {
	return &I_mask{tag: 0}
}

// K_IsPos builds the constructor IsPos.
func K_IsPos(a0 int64) *I_mask {
	return &I_mask{tag: 1, f1_0: a0}
}

// K_IsNeg builds the constructor IsNeg.
func K_IsNeg() *I_mask {
	return &I_mask{tag: 2}
}

type I_mask0 struct {
	tag  uint8
	f1_0 int64
}

var C_IsNul0 = &I_mask0{tag: 0}
var C_IsNeg0 = &I_mask0{tag: 2}

// K_IsNul0 builds the constructor IsNul0.
func K_IsNul0() *I_mask0 {
	return &I_mask0{tag: 0}
}

// K_IsPos0 builds the constructor IsPos0.
func K_IsPos0(a0 int64) *I_mask0 {
	return &I_mask0{tag: 1, f1_0: a0}
}

// K_IsNeg0 builds the constructor IsNeg0.
func K_IsNeg0() *I_mask0 {
	return &I_mask0{tag: 2}
}

type I_option[P_A any] struct {
	tag  uint8
	f0_0 P_A
}

// K_Some builds the constructor Some.
func K_Some[P_A any](a0 P_A) *I_option[P_A] {
	return &I_option[P_A]{tag: 0, f0_0: a0}
}

// K_None builds the constructor None.
func K_None[P_A any]() *I_option[P_A] {
	return &I_option[P_A]{tag: 1}
}

type I_prod[P_A any, P_B any] struct {
	tag  uint8
	f0_0 P_A
	f0_1 P_B
}

// K_Pair builds the constructor Pair.
func K_Pair[P_A any, P_B any](a0 P_A, a1 P_B) *I_prod[P_A, P_B] {
	return &I_prod[P_A, P_B]{tag: 0, f0_0: a0, f0_1: a1}
}

type I_r struct {
	tag  uint8
	f0_0 func(int64) int64
	f0_1 int64
}

// K_Build_R builds the constructor Build_R.
func K_Build_R(a0 func(int64) int64, a1 int64) *I_r {
	return &I_r{tag: 0, f0_0: a0, f0_1: a1}
}

func F_add(n_in int64, m_in int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		m_2 := m_in
		_ = m_2
		if n_1 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case n_1 == 0:
			return m_2
		case n_1 > 0:
			p_3 := n_1 - 1
			_ = p_3
			t_4 := F_add(p_3, m_2)
			t_5 := natSucc(t_4)
			return t_5
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_add0(x_in int64, y_in int64) int64 {
	for {
		x_1 := x_in
		_ = x_1
		y_2 := y_in
		_ = y_2
		if x_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case x_1 > 1 && x_1%2 == 1:
			p_3 := x_1 / 2
			_ = p_3
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				q_4 := y_2 / 2
				_ = q_4
				t_5 := F_add_carry(p_3, q_4)
				t_6 := posXO(t_5)
				return t_6
			case y_2 > 1 && y_2%2 == 0:
				q_7 := y_2 / 2
				_ = q_7
				t_8 := F_add0(p_3, q_7)
				t_9 := posXI(t_8)
				return t_9
			case y_2 == 1:
				t_10 := F_succ(p_3)
				t_11 := posXO(t_10)
				return t_11
			default:
				panic("gogen: no case matches")
			}
		case x_1 > 1 && x_1%2 == 0:
			p_12 := x_1 / 2
			_ = p_12
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				q_13 := y_2 / 2
				_ = q_13
				t_14 := F_add0(p_12, q_13)
				t_15 := posXI(t_14)
				return t_15
			case y_2 > 1 && y_2%2 == 0:
				q_16 := y_2 / 2
				_ = q_16
				t_17 := F_add0(p_12, q_16)
				t_18 := posXO(t_17)
				return t_18
			case y_2 == 1:
				t_19 := posXI(p_12)
				return t_19
			default:
				panic("gogen: no case matches")
			}
		case x_1 == 1:
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				q_20 := y_2 / 2
				_ = q_20
				t_21 := F_succ(q_20)
				t_22 := posXO(t_21)
				return t_22
			case y_2 > 1 && y_2%2 == 0:
				q_23 := y_2 / 2
				_ = q_23
				t_24 := posXI(q_23)
				return t_24
			case y_2 == 1:
				return int64(2)
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_add_carry(x_in int64, y_in int64) int64 {
	for {
		x_1 := x_in
		_ = x_1
		y_2 := y_in
		_ = y_2
		if x_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case x_1 > 1 && x_1%2 == 1:
			p_3 := x_1 / 2
			_ = p_3
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				q_4 := y_2 / 2
				_ = q_4
				t_5 := F_add_carry(p_3, q_4)
				t_6 := posXI(t_5)
				return t_6
			case y_2 > 1 && y_2%2 == 0:
				q_7 := y_2 / 2
				_ = q_7
				t_8 := F_add_carry(p_3, q_7)
				t_9 := posXO(t_8)
				return t_9
			case y_2 == 1:
				t_10 := F_succ(p_3)
				t_11 := posXI(t_10)
				return t_11
			default:
				panic("gogen: no case matches")
			}
		case x_1 > 1 && x_1%2 == 0:
			p_12 := x_1 / 2
			_ = p_12
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				q_13 := y_2 / 2
				_ = q_13
				t_14 := F_add_carry(p_12, q_13)
				t_15 := posXO(t_14)
				return t_15
			case y_2 > 1 && y_2%2 == 0:
				q_16 := y_2 / 2
				_ = q_16
				t_17 := F_add0(p_12, q_16)
				t_18 := posXI(t_17)
				return t_18
			case y_2 == 1:
				t_19 := F_succ(p_12)
				t_20 := posXO(t_19)
				return t_20
			default:
				panic("gogen: no case matches")
			}
		case x_1 == 1:
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				q_21 := y_2 / 2
				_ = q_21
				t_22 := F_succ(q_21)
				t_23 := posXI(t_22)
				return t_23
			case y_2 > 1 && y_2%2 == 0:
				q_24 := y_2 / 2
				_ = q_24
				t_25 := F_succ(q_24)
				t_26 := posXO(t_25)
				return t_26
			case y_2 == 1:
				return int64(3)
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_add_carry0(x_in int64, y_in int64) int64 {
	for {
		x_1 := x_in
		_ = x_1
		y_2 := y_in
		_ = y_2
		if x_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case x_1 > 1 && x_1%2 == 1:
			p_3 := x_1 / 2
			_ = p_3
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				q_4 := y_2 / 2
				_ = q_4
				t_5 := F_add_carry0(p_3, q_4)
				t_6 := posXI(t_5)
				return t_6
			case y_2 > 1 && y_2%2 == 0:
				q_7 := y_2 / 2
				_ = q_7
				t_8 := F_add_carry0(p_3, q_7)
				t_9 := posXO(t_8)
				return t_9
			case y_2 == 1:
				t_10 := natSucc(p_3)
				t_11 := posXI(t_10)
				return t_11
			default:
				panic("gogen: no case matches")
			}
		case x_1 > 1 && x_1%2 == 0:
			p_12 := x_1 / 2
			_ = p_12
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				q_13 := y_2 / 2
				_ = q_13
				t_14 := F_add_carry0(p_12, q_13)
				t_15 := posXO(t_14)
				return t_15
			case y_2 > 1 && y_2%2 == 0:
				q_16 := y_2 / 2
				_ = q_16
				t_17 := zAdd(p_12, q_16)
				t_18 := posXI(t_17)
				return t_18
			case y_2 == 1:
				t_19 := natSucc(p_12)
				t_20 := posXO(t_19)
				return t_20
			default:
				panic("gogen: no case matches")
			}
		case x_1 == 1:
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				q_21 := y_2 / 2
				_ = q_21
				t_22 := natSucc(q_21)
				t_23 := posXI(t_22)
				return t_23
			case y_2 > 1 && y_2%2 == 0:
				q_24 := y_2 / 2
				_ = q_24
				t_25 := natSucc(q_24)
				t_26 := posXO(t_25)
				return t_26
			case y_2 == 1:
				return int64(3)
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_allpos(l_in *I_list[int64]) bool {
	for {
		l_1 := l_in
		_ = l_1
		switch l_1.tag {
		case 0:
			return true
		case 1:
			x_2 := l_1.f1_0
			_ = x_2
			t_3 := l_1.f1_1
			_ = t_3
			t_4 := F_ltb1(int64(0), x_2)
			if !t_4 {
				return false
			}
			l_in = t_3
			continue
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_bigf(x_in *I_big) int64 {
	for {
		x_1 := x_in
		_ = x_1
		switch x_1.tag {
		case 0:
			a_2 := x_1.f0_0
			_ = a_2
			b_3 := x_1.f0_1
			_ = b_3
			c_4 := x_1.f0_2
			_ = c_4
			d_5 := x_1.f0_3
			_ = d_5
			e_6 := x_1.f0_4
			_ = e_6
			f_7 := x_1.f0_5
			_ = f_7
			g_8 := x_1.f0_6
			_ = g_8
			h_9 := x_1.f0_7
			_ = h_9
			t_10 := zAdd(a_2, b_3)
			t_11 := zAdd(t_10, c_4)
			t_12 := zAdd(t_11, d_5)
			t_13 := zAdd(t_12, e_6)
			t_14 := zAdd(t_13, f_7)
			t_15 := zAdd(t_14, g_8)
			t_16 := zAdd(t_15, h_9)
			return t_16
		case 2:
			x0_17 := x_1.f2_0
			_ = x0_17
			return x0_17
		default:
			return int64(99)
		}
	}
}

func F_compare() func(int64) func(int64) *I_comparison {
	for {
		t_3 := func(a_1 int64) func(int64) *I_comparison {
			return func(a_2 int64) *I_comparison {
				return F_compare_cont(C_Eq, a_1, a_2)
			}
		}
		return t_3
	}
}

func F_compare0(n_in int64, m_in int64) *I_comparison {
	for {
		n_1 := n_in
		_ = n_1
		m_2 := m_in
		_ = m_2
		if n_1 < 0 {
			panic("gogen: not a N")
		}
		switch {
		case n_1 == 0:
			if m_2 < 0 {
				panic("gogen: not a N")
			}
			switch {
			case m_2 == 0:
				return C_Eq
			case m_2 > 0:
				__3 := m_2
				_ = __3
				return C_Lt
			default:
				panic("gogen: no case matches")
			}
		case n_1 > 0:
			n_p_4 := n_1
			_ = n_p_4
			if m_2 < 0 {
				panic("gogen: not a N")
			}
			switch {
			case m_2 == 0:
				return C_Gt
			case m_2 > 0:
				m_p_5 := m_2
				_ = m_p_5
				t_6 := F_compare()(n_p_4)(m_p_5)
				return t_6
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_compare_cont(r0_in *I_comparison, x_in int64, y_in int64) *I_comparison {
	for {
		r0_1 := r0_in
		_ = r0_1
		x_2 := x_in
		_ = x_2
		y_3 := y_in
		_ = y_3
		if x_2 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case x_2 > 1 && x_2%2 == 1:
			p_4 := x_2 / 2
			_ = p_4
			if y_3 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_3 > 1 && y_3%2 == 1:
				q_5 := y_3 / 2
				_ = q_5
				r0_in, x_in, y_in = r0_1, p_4, q_5
				continue
			case y_3 > 1 && y_3%2 == 0:
				q_6 := y_3 / 2
				_ = q_6
				r0_in, x_in, y_in = C_Gt, p_4, q_6
				continue
			case y_3 == 1:
				return C_Gt
			default:
				panic("gogen: no case matches")
			}
		case x_2 > 1 && x_2%2 == 0:
			p_7 := x_2 / 2
			_ = p_7
			if y_3 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_3 > 1 && y_3%2 == 1:
				q_8 := y_3 / 2
				_ = q_8
				r0_in, x_in, y_in = C_Lt, p_7, q_8
				continue
			case y_3 > 1 && y_3%2 == 0:
				q_9 := y_3 / 2
				_ = q_9
				r0_in, x_in, y_in = r0_1, p_7, q_9
				continue
			case y_3 == 1:
				return C_Gt
			default:
				panic("gogen: no case matches")
			}
		case x_2 == 1:
			if y_3 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_3 > 1 && y_3%2 == 1:
				__10 := y_3 / 2
				_ = __10
				return C_Lt
			case y_3 > 1 && y_3%2 == 0:
				__11 := y_3 / 2
				_ = __11
				return C_Lt
			case y_3 == 1:
				return r0_1
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_compose_n(n_in int64, f_in func(int64) int64) func(int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		f_2 := f_in
		_ = f_2
		if n_1 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case n_1 == 0:
			return f_2
		case n_1 > 0:
			k_3 := n_1 - 1
			_ = k_3
			t_7 := func(x_4 int64) int64 {
				_ = x_4
				t_5 := zAdd(x_4, n_1)
				t_6 := f_2(t_5)
				return t_6
			}
			n_in, f_in = k_3, t_7
			continue
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_div(x_in int64, y_in int64) int64 {
	for {
		x_1 := x_in
		_ = x_1
		y_2 := y_in
		_ = y_2
		if y_2 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case y_2 == 0:
			return y_2
		case y_2 > 0:
			y_p_3 := y_2 - 1
			_ = y_p_3
			t_4 := F_divmod(x_1, y_p_3, int64(0), y_p_3)
			t_5 := F_fst[int64, int64](t_4)
			return t_5
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_div0(a_in int64, b_in int64) int64 {
	for {
		a_1 := a_in
		_ = a_1
		b_2 := b_in
		_ = b_2
		t_3 := F_div_eucl0(a_1, b_2)
		switch t_3.tag {
		case 0:
			q_4 := t_3.f0_0
			_ = q_4
			return q_4
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_div1(z_in int64) int64 {
	for {
		z_1 := z_in
		_ = z_1
		switch {
		case z_1 == 0:
			return int64(0)
		case z_1 > 0:
			p_2 := z_1
			_ = p_2
			if p_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case p_2 > 1 && p_2%2 == 1:
				__3 := p_2 / 2
				_ = __3
				t_4 := F_div2(p_2)
				t_5 := t_4
				return t_5
			case p_2 > 1 && p_2%2 == 0:
				__6 := p_2 / 2
				_ = __6
				t_7 := F_div2(p_2)
				t_8 := t_7
				return t_8
			case p_2 == 1:
				return int64(0)
			default:
				panic("gogen: no case matches")
			}
		case z_1 < 0:
			p_9 := zOpp(z_1)
			_ = p_9
			t_10 := F_div2_up(p_9)
			t_11 := zOpp(t_10)
			return t_11
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_div2(p_in int64) int64 {
	for {
		p_1 := p_in
		_ = p_1
		if p_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case p_1 > 1 && p_1%2 == 1:
			p0_2 := p_1 / 2
			_ = p0_2
			return p0_2
		case p_1 > 1 && p_1%2 == 0:
			p0_3 := p_1 / 2
			_ = p0_3
			return p0_3
		case p_1 == 1:
			return int64(1)
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_div2_up(p_in int64) int64 {
	for {
		p_1 := p_in
		_ = p_1
		if p_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case p_1 > 1 && p_1%2 == 1:
			p0_2 := p_1 / 2
			_ = p0_2
			t_3 := F_succ(p0_2)
			return t_3
		case p_1 > 1 && p_1%2 == 0:
			p0_4 := p_1 / 2
			_ = p0_4
			return p0_4
		case p_1 == 1:
			return int64(1)
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_div_eucl(a_in int64, b_in int64) *I_prod[int64, int64] {
	for {
		a_1 := a_in
		_ = a_1
		b_2 := b_in
		_ = b_2
		if a_1 < 0 {
			panic("gogen: not a N")
		}
		switch {
		case a_1 == 0:
			t_3 := &I_prod[int64, int64]{tag: 0, f0_0: int64(0), f0_1: int64(0)}
			return t_3
		case a_1 > 0:
			na_4 := a_1
			_ = na_4
			if b_2 < 0 {
				panic("gogen: not a N")
			}
			switch {
			case b_2 == 0:
				t_5 := &I_prod[int64, int64]{tag: 0, f0_0: int64(0), f0_1: a_1}
				return t_5
			case b_2 > 0:
				__6 := b_2
				_ = __6
				t_7 := F_pos_div_eucl0(na_4, b_2)
				return t_7
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_div_eucl0(a_in int64, b_in int64) *I_prod[int64, int64] {
	for {
		a_1 := a_in
		_ = a_1
		b_2 := b_in
		_ = b_2
		switch {
		case a_1 == 0:
			t_3 := &I_prod[int64, int64]{tag: 0, f0_0: int64(0), f0_1: int64(0)}
			return t_3
		case a_1 > 0:
			a_p_4 := a_1
			_ = a_p_4
			switch {
			case b_2 == 0:
				t_5 := &I_prod[int64, int64]{tag: 0, f0_0: int64(0), f0_1: a_1}
				return t_5
			case b_2 > 0:
				__6 := b_2
				_ = __6
				t_7 := F_pos_div_eucl1(a_p_4, b_2)
				return t_7
			case b_2 < 0:
				b_p_8 := zOpp(b_2)
				_ = b_p_8
				t_9 := b_p_8
				t_10 := F_pos_div_eucl1(a_p_4, t_9)
				switch t_10.tag {
				case 0:
					q_11 := t_10.f0_0
					_ = q_11
					r0_12 := t_10.f0_1
					_ = r0_12
					switch {
					case r0_12 == 0:
						t_13 := zOpp(q_11)
						t_14 := &I_prod[int64, int64]{tag: 0, f0_0: t_13, f0_1: int64(0)}
						return t_14
					case r0_12 > 0:
						__15 := r0_12
						_ = __15
						t_16 := zAdd(q_11, int64(1))
						t_17 := zOpp(t_16)
						t_18 := zAdd(b_2, r0_12)
						t_19 := &I_prod[int64, int64]{tag: 0, f0_0: t_17, f0_1: t_18}
						return t_19
					case r0_12 < 0:
						__20 := zOpp(r0_12)
						_ = __20
						t_21 := zAdd(q_11, int64(1))
						t_22 := zOpp(t_21)
						t_23 := zAdd(b_2, r0_12)
						t_24 := &I_prod[int64, int64]{tag: 0, f0_0: t_22, f0_1: t_23}
						return t_24
					default:
						panic("gogen: no case matches")
					}
				default:
					panic("gogen: no case matches")
				}
			default:
				panic("gogen: no case matches")
			}
		case a_1 < 0:
			a_p_25 := zOpp(a_1)
			_ = a_p_25
			switch {
			case b_2 == 0:
				t_26 := &I_prod[int64, int64]{tag: 0, f0_0: int64(0), f0_1: a_1}
				return t_26
			case b_2 > 0:
				__27 := b_2
				_ = __27
				t_28 := F_pos_div_eucl1(a_p_25, b_2)
				switch t_28.tag {
				case 0:
					q_29 := t_28.f0_0
					_ = q_29
					r0_30 := t_28.f0_1
					_ = r0_30
					switch {
					case r0_30 == 0:
						t_31 := zOpp(q_29)
						t_32 := &I_prod[int64, int64]{tag: 0, f0_0: t_31, f0_1: int64(0)}
						return t_32
					case r0_30 > 0:
						__33 := r0_30
						_ = __33
						t_34 := zAdd(q_29, int64(1))
						t_35 := zOpp(t_34)
						t_36 := zSub(b_2, r0_30)
						t_37 := &I_prod[int64, int64]{tag: 0, f0_0: t_35, f0_1: t_36}
						return t_37
					case r0_30 < 0:
						__38 := zOpp(r0_30)
						_ = __38
						t_39 := zAdd(q_29, int64(1))
						t_40 := zOpp(t_39)
						t_41 := zSub(b_2, r0_30)
						t_42 := &I_prod[int64, int64]{tag: 0, f0_0: t_40, f0_1: t_41}
						return t_42
					default:
						panic("gogen: no case matches")
					}
				default:
					panic("gogen: no case matches")
				}
			case b_2 < 0:
				b_p_43 := zOpp(b_2)
				_ = b_p_43
				t_44 := b_p_43
				t_45 := F_pos_div_eucl1(a_p_25, t_44)
				switch t_45.tag {
				case 0:
					q_46 := t_45.f0_0
					_ = q_46
					r0_47 := t_45.f0_1
					_ = r0_47
					t_48 := zOpp(r0_47)
					t_49 := &I_prod[int64, int64]{tag: 0, f0_0: q_46, f0_1: t_48}
					return t_49
				default:
					panic("gogen: no case matches")
				}
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_divmod(x_in int64, y_in int64, q_in int64, u_in int64) *I_prod[int64, int64] {
	for {
		x_1 := x_in
		_ = x_1
		y_2 := y_in
		_ = y_2
		q_3 := q_in
		_ = q_3
		u_4 := u_in
		_ = u_4
		if x_1 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case x_1 == 0:
			t_5 := &I_prod[int64, int64]{tag: 0, f0_0: q_3, f0_1: u_4}
			return t_5
		case x_1 > 0:
			x_p_6 := x_1 - 1
			_ = x_p_6
			if u_4 < 0 {
				panic("gogen: not a nat")
			}
			switch {
			case u_4 == 0:
				t_7 := natSucc(q_3)
				x_in, y_in, q_in, u_in = x_p_6, y_2, t_7, y_2
				continue
			case u_4 > 0:
				u_p_8 := u_4 - 1
				_ = u_p_8
				x_in, y_in, q_in, u_in = x_p_6, y_2, q_3, u_p_8
				continue
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_double(n_in int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		if n_1 < 0 {
			panic("gogen: not a N")
		}
		switch {
		case n_1 == 0:
			return int64(0)
		case n_1 > 0:
			p_2 := n_1
			_ = p_2
			t_3 := posXO(p_2)
			t_4 := t_3
			return t_4
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_double0(n_in int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		if n_1 < 0 {
			panic("gogen: not a N")
		}
		switch {
		case n_1 == 0:
			return int64(0)
		case n_1 > 0:
			p_2 := n_1
			_ = p_2
			t_3 := posXO(p_2)
			t_4 := t_3
			return t_4
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_double1(x_in int64) int64 {
	for {
		x_1 := x_in
		_ = x_1
		switch {
		case x_1 == 0:
			return int64(0)
		case x_1 > 0:
			p_2 := x_1
			_ = p_2
			t_3 := posXO(p_2)
			t_4 := t_3
			return t_4
		case x_1 < 0:
			p_5 := zOpp(x_1)
			_ = p_5
			t_6 := posXO(p_5)
			t_7 := zOpp(t_6)
			return t_7
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_double_mask(x_in *I_mask) *I_mask {
	for {
		x_1 := x_in
		_ = x_1
		switch x_1.tag {
		case 1:
			p_2 := x_1.f1_0
			_ = p_2
			t_3 := posXO(p_2)
			t_4 := &I_mask{tag: 1, f1_0: t_3}
			return t_4
		default:
			x0_5 := x_1
			_ = x0_5
			return x0_5
		}
	}
}

func F_double_mask0(x_in *I_mask0) *I_mask0 {
	for {
		x_1 := x_in
		_ = x_1
		switch x_1.tag {
		case 1:
			p_2 := x_1.f1_0
			_ = p_2
			t_3 := posXO(p_2)
			t_4 := &I_mask0{tag: 1, f1_0: t_3}
			return t_4
		default:
			x0_5 := x_1
			_ = x0_5
			return x0_5
		}
	}
}

func F_double_pred_mask(x_in int64) *I_mask {
	for {
		x_1 := x_in
		_ = x_1
		if x_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case x_1 > 1 && x_1%2 == 1:
			p_2 := x_1 / 2
			_ = p_2
			t_3 := posXO(p_2)
			t_4 := posXO(t_3)
			t_5 := &I_mask{tag: 1, f1_0: t_4}
			return t_5
		case x_1 > 1 && x_1%2 == 0:
			p_6 := x_1 / 2
			_ = p_6
			t_7 := F_pred_double(p_6)
			t_8 := posXO(t_7)
			t_9 := &I_mask{tag: 1, f1_0: t_8}
			return t_9
		case x_1 == 1:
			return C_IsNul
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_double_pred_mask0(x_in int64) *I_mask0 {
	for {
		x_1 := x_in
		_ = x_1
		if x_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case x_1 > 1 && x_1%2 == 1:
			p_2 := x_1 / 2
			_ = p_2
			t_3 := posXO(p_2)
			t_4 := posXO(t_3)
			t_5 := &I_mask0{tag: 1, f1_0: t_4}
			return t_5
		case x_1 > 1 && x_1%2 == 0:
			p_6 := x_1 / 2
			_ = p_6
			t_7 := F_pred_double0(p_6)
			t_8 := posXO(t_7)
			t_9 := &I_mask0{tag: 1, f1_0: t_8}
			return t_9
		case x_1 == 1:
			return C_IsNul0
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_eq_dec(p_in int64, x0_in int64) bool {
	for {
		p_1 := p_in
		_ = p_1
		x0_2 := x0_in
		_ = x0_2
		if p_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case p_1 > 1 && p_1%2 == 1:
			p0_3 := p_1 / 2
			_ = p0_3
			if x0_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case x0_2 > 1 && x0_2%2 == 1:
				p1_4 := x0_2 / 2
				_ = p1_4
				p_in, x0_in = p0_3, p1_4
				continue
			case x0_2 > 1 && x0_2%2 == 0:
				__5 := x0_2 / 2
				_ = __5
				return false
			case x0_2 == 1:
				return false
			default:
				panic("gogen: no case matches")
			}
		case p_1 > 1 && p_1%2 == 0:
			p0_6 := p_1 / 2
			_ = p0_6
			if x0_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case x0_2 > 1 && x0_2%2 == 1:
				__7 := x0_2 / 2
				_ = __7
				return false
			case x0_2 > 1 && x0_2%2 == 0:
				p1_8 := x0_2 / 2
				_ = p1_8
				p_in, x0_in = p0_6, p1_8
				continue
			case x0_2 == 1:
				return false
			default:
				panic("gogen: no case matches")
			}
		case p_1 == 1:
			if x0_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case x0_2 > 1 && x0_2%2 == 1:
				__9 := x0_2 / 2
				_ = __9
				return false
			case x0_2 > 1 && x0_2%2 == 0:
				__10 := x0_2 / 2
				_ = __10
				return false
			case x0_2 == 1:
				return true
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_eq_dec0(x_in int64, y_in int64) bool {
	for {
		x_1 := x_in
		_ = x_1
		y_2 := y_in
		_ = y_2
		switch {
		case x_1 == 0:
			switch {
			case y_2 == 0:
				return true
			case y_2 > 0:
				__3 := y_2
				_ = __3
				return false
			case y_2 < 0:
				__4 := zOpp(y_2)
				_ = __4
				return false
			default:
				panic("gogen: no case matches")
			}
		case x_1 > 0:
			p_5 := x_1
			_ = p_5
			switch {
			case y_2 == 0:
				return false
			case y_2 > 0:
				p0_6 := y_2
				_ = p0_6
				t_7 := F_eq_dec(p_5, p0_6)
				return t_7
			case y_2 < 0:
				__8 := zOpp(y_2)
				_ = __8
				return false
			default:
				panic("gogen: no case matches")
			}
		case x_1 < 0:
			p_9 := zOpp(x_1)
			_ = p_9
			switch {
			case y_2 == 0:
				return false
			case y_2 > 0:
				__10 := y_2
				_ = __10
				return false
			case y_2 < 0:
				p0_11 := zOpp(y_2)
				_ = p0_11
				t_12 := F_eq_dec(p_9, p0_11)
				return t_12
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_eqb(p_in int64, q_in int64) bool {
	for {
		p_1 := p_in
		_ = p_1
		q_2 := q_in
		_ = q_2
		if p_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case p_1 > 1 && p_1%2 == 1:
			p0_3 := p_1 / 2
			_ = p0_3
			if q_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case q_2 > 1 && q_2%2 == 1:
				q0_4 := q_2 / 2
				_ = q0_4
				p_in, q_in = p0_3, q0_4
				continue
			case q_2 > 1 && q_2%2 == 0:
				__5 := q_2 / 2
				_ = __5
				return false
			case q_2 == 1:
				return false
			default:
				panic("gogen: no case matches")
			}
		case p_1 > 1 && p_1%2 == 0:
			p0_6 := p_1 / 2
			_ = p0_6
			if q_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case q_2 > 1 && q_2%2 == 1:
				__7 := q_2 / 2
				_ = __7
				return false
			case q_2 > 1 && q_2%2 == 0:
				q0_8 := q_2 / 2
				_ = q0_8
				p_in, q_in = p0_6, q0_8
				continue
			case q_2 == 1:
				return false
			default:
				panic("gogen: no case matches")
			}
		case p_1 == 1:
			if q_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case q_2 > 1 && q_2%2 == 1:
				__9 := q_2 / 2
				_ = __9
				return false
			case q_2 > 1 && q_2%2 == 0:
				__10 := q_2 / 2
				_ = __10
				return false
			case q_2 == 1:
				return true
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_eqb0(p_in int64, q_in int64) bool {
	for {
		p_1 := p_in
		_ = p_1
		q_2 := q_in
		_ = q_2
		if p_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case p_1 > 1 && p_1%2 == 1:
			p0_3 := p_1 / 2
			_ = p0_3
			if q_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case q_2 > 1 && q_2%2 == 1:
				q0_4 := q_2 / 2
				_ = q0_4
				p_in, q_in = p0_3, q0_4
				continue
			case q_2 > 1 && q_2%2 == 0:
				__5 := q_2 / 2
				_ = __5
				return false
			case q_2 == 1:
				return false
			default:
				panic("gogen: no case matches")
			}
		case p_1 > 1 && p_1%2 == 0:
			p0_6 := p_1 / 2
			_ = p0_6
			if q_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case q_2 > 1 && q_2%2 == 1:
				__7 := q_2 / 2
				_ = __7
				return false
			case q_2 > 1 && q_2%2 == 0:
				q0_8 := q_2 / 2
				_ = q0_8
				p_in, q_in = p0_6, q0_8
				continue
			case q_2 == 1:
				return false
			default:
				panic("gogen: no case matches")
			}
		case p_1 == 1:
			if q_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case q_2 > 1 && q_2%2 == 1:
				__9 := q_2 / 2
				_ = __9
				return false
			case q_2 > 1 && q_2%2 == 0:
				__10 := q_2 / 2
				_ = __10
				return false
			case q_2 == 1:
				return true
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_eqb1(x_in int64, y_in int64) bool {
	for {
		x_1 := x_in
		_ = x_1
		y_2 := y_in
		_ = y_2
		switch {
		case x_1 == 0:
			switch {
			case y_2 == 0:
				return true
			case y_2 > 0:
				__3 := y_2
				_ = __3
				return false
			case y_2 < 0:
				__4 := zOpp(y_2)
				_ = __4
				return false
			default:
				panic("gogen: no case matches")
			}
		case x_1 > 0:
			p_5 := x_1
			_ = p_5
			switch {
			case y_2 == 0:
				return false
			case y_2 > 0:
				q_6 := y_2
				_ = q_6
				t_7 := F_eqb(p_5, q_6)
				return t_7
			case y_2 < 0:
				__8 := zOpp(y_2)
				_ = __8
				return false
			default:
				panic("gogen: no case matches")
			}
		case x_1 < 0:
			p_9 := zOpp(x_1)
			_ = p_9
			switch {
			case y_2 == 0:
				return false
			case y_2 > 0:
				__10 := y_2
				_ = __10
				return false
			case y_2 < 0:
				q_11 := zOpp(y_2)
				_ = q_11
				t_12 := F_eqb(p_9, q_11)
				return t_12
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_ev(n_in int64) bool {
	for {
		n_1 := n_in
		_ = n_1
		if n_1 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case n_1 == 0:
			return true
		case n_1 > 0:
			k_2 := n_1 - 1
			_ = k_2
			t_3 := F_od(k_2)
			return t_3
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_f3(a_in int64, b_in int64, c_in int64) int64 {
	for {
		a_1 := a_in
		_ = a_1
		b_2 := b_in
		_ = b_2
		c_3 := c_in
		_ = c_3
		t_4 := zMul(a_1, int64(100))
		t_5 := zMul(b_2, int64(10))
		t_6 := zAdd(t_4, t_5)
		t_7 := zAdd(t_6, c_3)
		return t_7
	}
}

func F_fold_left[T1 any, T2 any](f_in func(T1) func(T2) T1, l_in *I_list[T2], a0_in T1) T1 {
	for {
		f_1 := f_in
		_ = f_1
		l_2 := l_in
		_ = l_2
		a0_3 := a0_in
		_ = a0_3
		switch l_2.tag {
		case 0:
			return a0_3
		case 1:
			b_4 := l_2.f1_0
			_ = b_4
			l0_5 := l_2.f1_1
			_ = l0_5
			t_6 := f_1(a0_3)(b_4)
			f_in, l_in, a0_in = f_1, l0_5, t_6
			continue
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_fold_right[T1 any, T2 any](f_in func(T2) func(T1) T1, a0_in T1, l_in *I_list[T2]) T1 {
	for {
		f_1 := f_in
		_ = f_1
		a0_2 := a0_in
		_ = a0_2
		l_3 := l_in
		_ = l_3
		switch l_3.tag {
		case 0:
			return a0_2
		case 1:
			b_4 := l_3.f1_0
			_ = b_4
			l0_5 := l_3.f1_1
			_ = l0_5
			t_6 := F_fold_right[T1, T2](f_1, a0_2, l0_5)
			t_7 := f_1(b_4)(t_6)
			return t_7
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_fst[T1 any, T2 any](p_in *I_prod[T1, T2]) T1 {
	for {
		p_1 := p_in
		_ = p_1
		switch p_1.tag {
		case 0:
			x_2 := p_1.f0_0
			_ = x_2
			return x_2
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_gtb(x_in int64, y_in int64) bool {
	for {
		x_1 := x_in
		_ = x_1
		y_2 := y_in
		_ = y_2
		t_3 := compare(x_1, y_2)
		switch t_3.tag {
		case 2:
			return true
		default:
			return false
		}
	}
}

func F_hd_safe(l_in *I_list[int64]) int64 {
	for {
		l_1 := l_in
		_ = l_1
		switch l_1.tag {
		case 0:
			panic("gogen: extracted exception: absurd case")
		case 1:
			x_2 := l_1.f1_0
			_ = x_2
			return x_2
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_ins(x_in int64, l_in *I_list[int64]) *I_list[int64] {
	for {
		x_1 := x_in
		_ = x_1
		l_2 := l_in
		_ = l_2
		switch l_2.tag {
		case 0:
			t_3 := &I_list[int64]{tag: 0}
			t_4 := &I_list[int64]{tag: 1, f1_0: x_1, f1_1: t_3}
			return t_4
		case 1:
			y_5 := l_2.f1_0
			_ = y_5
			t_6 := l_2.f1_1
			_ = t_6
			t_7 := leb(x_1, y_5)
			switch {
			case t_7:
				t_8 := &I_list[int64]{tag: 1, f1_0: x_1, f1_1: l_2}
				return t_8
			case !t_7:
				t_9 := F_ins(x_1, t_6)
				t_10 := &I_list[int64]{tag: 1, f1_0: y_5, f1_1: t_9}
				return t_10
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_iter[T1 any](f_in func(T1) T1, x_in T1, n_in int64) T1 {
	for {
		f_1 := f_in
		_ = f_1
		x_2 := x_in
		_ = x_2
		n_3 := n_in
		_ = n_3
		if n_3 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case n_3 > 1 && n_3%2 == 1:
			n_p_4 := n_3 / 2
			_ = n_p_4
			t_5 := F_iter[T1](f_1, x_2, n_p_4)
			t_6 := F_iter[T1](f_1, t_5, n_p_4)
			t_7 := f_1(t_6)
			return t_7
		case n_3 > 1 && n_3%2 == 0:
			n_p_8 := n_3 / 2
			_ = n_p_8
			t_9 := F_iter[T1](f_1, x_2, n_p_8)
			f_in, x_in, n_in = f_1, t_9, n_p_8
			continue
		case n_3 == 1:
			t_10 := f_1(x_2)
			return t_10
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_iter0[T1 any](f_in func(T1) T1, x_in T1, n_in int64) T1 {
	for {
		f_1 := f_in
		_ = f_1
		x_2 := x_in
		_ = x_2
		n_3 := n_in
		_ = n_3
		if n_3 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case n_3 > 1 && n_3%2 == 1:
			n_p_4 := n_3 / 2
			_ = n_p_4
			t_5 := F_iter0[T1](f_1, x_2, n_p_4)
			t_6 := F_iter0[T1](f_1, t_5, n_p_4)
			t_7 := f_1(t_6)
			return t_7
		case n_3 > 1 && n_3%2 == 0:
			n_p_8 := n_3 / 2
			_ = n_p_8
			t_9 := F_iter0[T1](f_1, x_2, n_p_8)
			f_in, x_in, n_in = f_1, t_9, n_p_8
			continue
		case n_3 == 1:
			t_10 := f_1(x_2)
			return t_10
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_land(p_in int64, q_in int64) int64 {
	for {
		p_1 := p_in
		_ = p_1
		q_2 := q_in
		_ = q_2
		if p_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case p_1 > 1 && p_1%2 == 1:
			p0_3 := p_1 / 2
			_ = p0_3
			if q_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case q_2 > 1 && q_2%2 == 1:
				q0_4 := q_2 / 2
				_ = q0_4
				t_5 := F_land(p0_3, q0_4)
				t_6 := F_nsucc_double(t_5)
				return t_6
			case q_2 > 1 && q_2%2 == 0:
				q0_7 := q_2 / 2
				_ = q0_7
				t_8 := F_land(p0_3, q0_7)
				t_9 := F_ndouble(t_8)
				return t_9
			case q_2 == 1:
				return int64(1)
			default:
				panic("gogen: no case matches")
			}
		case p_1 > 1 && p_1%2 == 0:
			p0_10 := p_1 / 2
			_ = p0_10
			if q_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case q_2 > 1 && q_2%2 == 1:
				q0_11 := q_2 / 2
				_ = q0_11
				t_12 := F_land(p0_10, q0_11)
				t_13 := F_ndouble(t_12)
				return t_13
			case q_2 > 1 && q_2%2 == 0:
				q0_14 := q_2 / 2
				_ = q0_14
				t_15 := F_land(p0_10, q0_14)
				t_16 := F_ndouble(t_15)
				return t_16
			case q_2 == 1:
				return int64(0)
			default:
				panic("gogen: no case matches")
			}
		case p_1 == 1:
			if q_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case q_2 > 1 && q_2%2 == 1:
				__17 := q_2 / 2
				_ = __17
				return int64(1)
			case q_2 > 1 && q_2%2 == 0:
				__18 := q_2 / 2
				_ = __18
				return int64(0)
			case q_2 == 1:
				return int64(1)
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_land0(n_in int64, m_in int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		m_2 := m_in
		_ = m_2
		if n_1 < 0 {
			panic("gogen: not a N")
		}
		switch {
		case n_1 == 0:
			return int64(0)
		case n_1 > 0:
			p_3 := n_1
			_ = p_3
			if m_2 < 0 {
				panic("gogen: not a N")
			}
			switch {
			case m_2 == 0:
				return int64(0)
			case m_2 > 0:
				q_4 := m_2
				_ = q_4
				t_5 := F_land(p_3, q_4)
				return t_5
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_land1(a_in int64, b_in int64) int64 {
	for {
		a_1 := a_in
		_ = a_1
		b_2 := b_in
		_ = b_2
		switch {
		case a_1 == 0:
			return int64(0)
		case a_1 > 0:
			a0_3 := a_1
			_ = a0_3
			switch {
			case b_2 == 0:
				return int64(0)
			case b_2 > 0:
				b0_4 := b_2
				_ = b0_4
				t_5 := F_land(a0_3, b0_4)
				t_6 := id64(t_5)
				return t_6
			case b_2 < 0:
				b0_7 := zOpp(b_2)
				_ = b0_7
				t_8 := a0_3
				t_9 := F_pred_N(b0_7)
				t_10 := F_ldiff0(t_8, t_9)
				t_11 := id64(t_10)
				return t_11
			default:
				panic("gogen: no case matches")
			}
		case a_1 < 0:
			a0_12 := zOpp(a_1)
			_ = a0_12
			switch {
			case b_2 == 0:
				return int64(0)
			case b_2 > 0:
				b0_13 := b_2
				_ = b0_13
				t_14 := b0_13
				t_15 := F_pred_N(a0_12)
				t_16 := F_ldiff0(t_14, t_15)
				t_17 := id64(t_16)
				return t_17
			case b_2 < 0:
				b0_18 := zOpp(b_2)
				_ = b0_18
				t_19 := F_pred_N(a0_12)
				t_20 := F_pred_N(b0_18)
				t_21 := F_lor0(t_19, t_20)
				t_22 := F_succ_pos(t_21)
				t_23 := zOpp(t_22)
				return t_23
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_ldiff(p_in int64, q_in int64) int64 {
	for {
		p_1 := p_in
		_ = p_1
		q_2 := q_in
		_ = q_2
		if p_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case p_1 > 1 && p_1%2 == 1:
			p0_3 := p_1 / 2
			_ = p0_3
			if q_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case q_2 > 1 && q_2%2 == 1:
				q0_4 := q_2 / 2
				_ = q0_4
				t_5 := F_ldiff(p0_3, q0_4)
				t_6 := F_ndouble(t_5)
				return t_6
			case q_2 > 1 && q_2%2 == 0:
				q0_7 := q_2 / 2
				_ = q0_7
				t_8 := F_ldiff(p0_3, q0_7)
				t_9 := F_nsucc_double(t_8)
				return t_9
			case q_2 == 1:
				t_10 := posXO(p0_3)
				t_11 := t_10
				return t_11
			default:
				panic("gogen: no case matches")
			}
		case p_1 > 1 && p_1%2 == 0:
			p0_12 := p_1 / 2
			_ = p0_12
			if q_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case q_2 > 1 && q_2%2 == 1:
				q0_13 := q_2 / 2
				_ = q0_13
				t_14 := F_ldiff(p0_12, q0_13)
				t_15 := F_ndouble(t_14)
				return t_15
			case q_2 > 1 && q_2%2 == 0:
				q0_16 := q_2 / 2
				_ = q0_16
				t_17 := F_ldiff(p0_12, q0_16)
				t_18 := F_ndouble(t_17)
				return t_18
			case q_2 == 1:
				t_19 := p_1
				return t_19
			default:
				panic("gogen: no case matches")
			}
		case p_1 == 1:
			if q_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case q_2 > 1 && q_2%2 == 1:
				__20 := q_2 / 2
				_ = __20
				return int64(0)
			case q_2 > 1 && q_2%2 == 0:
				__21 := q_2 / 2
				_ = __21
				return int64(1)
			case q_2 == 1:
				return int64(0)
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_ldiff0(n_in int64, m_in int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		m_2 := m_in
		_ = m_2
		if n_1 < 0 {
			panic("gogen: not a N")
		}
		switch {
		case n_1 == 0:
			return int64(0)
		case n_1 > 0:
			p_3 := n_1
			_ = p_3
			if m_2 < 0 {
				panic("gogen: not a N")
			}
			switch {
			case m_2 == 0:
				return n_1
			case m_2 > 0:
				q_4 := m_2
				_ = q_4
				t_5 := F_ldiff(p_3, q_4)
				return t_5
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_leb(x_in int64, y_in int64) bool {
	for {
		x_1 := x_in
		_ = x_1
		y_2 := y_in
		_ = y_2
		t_3 := F_compare0(x_1, y_2)
		switch t_3.tag {
		case 2:
			return false
		default:
			return true
		}
	}
}

func F_leb0(x_in int64, y_in int64) bool {
	for {
		x_1 := x_in
		_ = x_1
		y_2 := y_in
		_ = y_2
		t_3 := compare(x_1, y_2)
		switch t_3.tag {
		case 2:
			return false
		default:
			return true
		}
	}
}

func F_leb1(x_in int64, y_in int64) bool {
	for {
		x_1 := x_in
		_ = x_1
		y_2 := y_in
		_ = y_2
		t_3 := compare(x_1, y_2)
		switch t_3.tag {
		case 2:
			return false
		default:
			return true
		}
	}
}

func F_length[T1 any](l_in *I_list[T1]) int64 {
	for {
		l_1 := l_in
		_ = l_1
		switch l_1.tag {
		case 0:
			return int64(0)
		case 1:
			l_p_2 := l_1.f1_1
			_ = l_p_2
			t_3 := F_length[T1](l_p_2)
			t_4 := natSucc(t_3)
			return t_4
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_log2(n_in int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		t_2 := F_pred(n_1)
		t_3 := F_log2_iter(t_2, int64(0), int64(1), int64(0))
		return t_3
	}
}

func F_log2_iter(k_in int64, p_in int64, q_in int64, r0_in int64) int64 {
	for {
		k_1 := k_in
		_ = k_1
		p_2 := p_in
		_ = p_2
		q_3 := q_in
		_ = q_3
		r0_4 := r0_in
		_ = r0_4
		if k_1 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case k_1 == 0:
			return p_2
		case k_1 > 0:
			k_p_5 := k_1 - 1
			_ = k_p_5
			if r0_4 < 0 {
				panic("gogen: not a nat")
			}
			switch {
			case r0_4 == 0:
				t_6 := natSucc(p_2)
				t_7 := natSucc(q_3)
				k_in, p_in, q_in, r0_in = k_p_5, t_6, t_7, q_3
				continue
			case r0_4 > 0:
				r_p_8 := r0_4 - 1
				_ = r_p_8
				t_9 := natSucc(q_3)
				k_in, p_in, q_in, r0_in = k_p_5, p_2, t_9, r_p_8
				continue
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_lor(p_in int64, q_in int64) int64 {
	for {
		p_1 := p_in
		_ = p_1
		q_2 := q_in
		_ = q_2
		if p_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case p_1 > 1 && p_1%2 == 1:
			p0_3 := p_1 / 2
			_ = p0_3
			if q_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case q_2 > 1 && q_2%2 == 1:
				q0_4 := q_2 / 2
				_ = q0_4
				t_5 := F_lor(p0_3, q0_4)
				t_6 := posXI(t_5)
				return t_6
			case q_2 > 1 && q_2%2 == 0:
				q0_7 := q_2 / 2
				_ = q0_7
				t_8 := F_lor(p0_3, q0_7)
				t_9 := posXI(t_8)
				return t_9
			case q_2 == 1:
				return p_1
			default:
				panic("gogen: no case matches")
			}
		case p_1 > 1 && p_1%2 == 0:
			p0_10 := p_1 / 2
			_ = p0_10
			if q_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case q_2 > 1 && q_2%2 == 1:
				q0_11 := q_2 / 2
				_ = q0_11
				t_12 := F_lor(p0_10, q0_11)
				t_13 := posXI(t_12)
				return t_13
			case q_2 > 1 && q_2%2 == 0:
				q0_14 := q_2 / 2
				_ = q0_14
				t_15 := F_lor(p0_10, q0_14)
				t_16 := posXO(t_15)
				return t_16
			case q_2 == 1:
				t_17 := posXI(p0_10)
				return t_17
			default:
				panic("gogen: no case matches")
			}
		case p_1 == 1:
			if q_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case q_2 > 1 && q_2%2 == 1:
				__18 := q_2 / 2
				_ = __18
				return q_2
			case q_2 > 1 && q_2%2 == 0:
				q0_19 := q_2 / 2
				_ = q0_19
				t_20 := posXI(q0_19)
				return t_20
			case q_2 == 1:
				return q_2
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_lor0(n_in int64, m_in int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		m_2 := m_in
		_ = m_2
		if n_1 < 0 {
			panic("gogen: not a N")
		}
		switch {
		case n_1 == 0:
			return m_2
		case n_1 > 0:
			p_3 := n_1
			_ = p_3
			if m_2 < 0 {
				panic("gogen: not a N")
			}
			switch {
			case m_2 == 0:
				return n_1
			case m_2 > 0:
				q_4 := m_2
				_ = q_4
				t_5 := F_lor(p_3, q_4)
				t_6 := t_5
				return t_6
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_lor1(a_in int64, b_in int64) int64 {
	for {
		a_1 := a_in
		_ = a_1
		b_2 := b_in
		_ = b_2
		switch {
		case a_1 == 0:
			return b_2
		case a_1 > 0:
			a0_3 := a_1
			_ = a0_3
			switch {
			case b_2 == 0:
				return a_1
			case b_2 > 0:
				b0_4 := b_2
				_ = b0_4
				t_5 := F_lor(a0_3, b0_4)
				t_6 := t_5
				return t_6
			case b_2 < 0:
				b0_7 := zOpp(b_2)
				_ = b0_7
				t_8 := F_pred_N(b0_7)
				t_9 := a0_3
				t_10 := F_ldiff0(t_8, t_9)
				t_11 := F_succ_pos(t_10)
				t_12 := zOpp(t_11)
				return t_12
			default:
				panic("gogen: no case matches")
			}
		case a_1 < 0:
			a0_13 := zOpp(a_1)
			_ = a0_13
			switch {
			case b_2 == 0:
				return a_1
			case b_2 > 0:
				b0_14 := b_2
				_ = b0_14
				t_15 := F_pred_N(a0_13)
				t_16 := b0_14
				t_17 := F_ldiff0(t_15, t_16)
				t_18 := F_succ_pos(t_17)
				t_19 := zOpp(t_18)
				return t_19
			case b_2 < 0:
				b0_20 := zOpp(b_2)
				_ = b0_20
				t_21 := F_pred_N(a0_13)
				t_22 := F_pred_N(b0_20)
				t_23 := F_land0(t_21, t_22)
				t_24 := F_succ_pos(t_23)
				t_25 := zOpp(t_24)
				return t_25
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_ltb(n_in int64, m_in int64) bool {
	for {
		n_1 := n_in
		_ = n_1
		m_2 := m_in
		_ = m_2
		t_3 := natSucc(n_1)
		t_4 := leb(t_3, m_2)
		return t_4
	}
}

func F_ltb0(x_in int64, y_in int64) bool {
	for {
		x_1 := x_in
		_ = x_1
		y_2 := y_in
		_ = y_2
		t_3 := compare(x_1, y_2)
		switch t_3.tag {
		case 1:
			return true
		default:
			return false
		}
	}
}

func F_ltb1(x_in int64, y_in int64) bool {
	for {
		x_1 := x_in
		_ = x_1
		y_2 := y_in
		_ = y_2
		t_3 := compare(x_1, y_2)
		switch t_3.tag {
		case 1:
			return true
		default:
			return false
		}
	}
}

func F_lxor(p_in int64, q_in int64) int64 {
	for {
		p_1 := p_in
		_ = p_1
		q_2 := q_in
		_ = q_2
		if p_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case p_1 > 1 && p_1%2 == 1:
			p0_3 := p_1 / 2
			_ = p0_3
			if q_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case q_2 > 1 && q_2%2 == 1:
				q0_4 := q_2 / 2
				_ = q0_4
				t_5 := F_lxor(p0_3, q0_4)
				t_6 := F_ndouble(t_5)
				return t_6
			case q_2 > 1 && q_2%2 == 0:
				q0_7 := q_2 / 2
				_ = q0_7
				t_8 := F_lxor(p0_3, q0_7)
				t_9 := F_nsucc_double(t_8)
				return t_9
			case q_2 == 1:
				t_10 := posXO(p0_3)
				t_11 := t_10
				return t_11
			default:
				panic("gogen: no case matches")
			}
		case p_1 > 1 && p_1%2 == 0:
			p0_12 := p_1 / 2
			_ = p0_12
			if q_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case q_2 > 1 && q_2%2 == 1:
				q0_13 := q_2 / 2
				_ = q0_13
				t_14 := F_lxor(p0_12, q0_13)
				t_15 := F_nsucc_double(t_14)
				return t_15
			case q_2 > 1 && q_2%2 == 0:
				q0_16 := q_2 / 2
				_ = q0_16
				t_17 := F_lxor(p0_12, q0_16)
				t_18 := F_ndouble(t_17)
				return t_18
			case q_2 == 1:
				t_19 := posXI(p0_12)
				t_20 := t_19
				return t_20
			default:
				panic("gogen: no case matches")
			}
		case p_1 == 1:
			if q_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case q_2 > 1 && q_2%2 == 1:
				q0_21 := q_2 / 2
				_ = q0_21
				t_22 := posXO(q0_21)
				t_23 := t_22
				return t_23
			case q_2 > 1 && q_2%2 == 0:
				q0_24 := q_2 / 2
				_ = q0_24
				t_25 := posXI(q0_24)
				t_26 := t_25
				return t_26
			case q_2 == 1:
				return int64(0)
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_lxor0(n_in int64, m_in int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		m_2 := m_in
		_ = m_2
		if n_1 < 0 {
			panic("gogen: not a N")
		}
		switch {
		case n_1 == 0:
			return m_2
		case n_1 > 0:
			p_3 := n_1
			_ = p_3
			if m_2 < 0 {
				panic("gogen: not a N")
			}
			switch {
			case m_2 == 0:
				return n_1
			case m_2 > 0:
				q_4 := m_2
				_ = q_4
				t_5 := F_lxor(p_3, q_4)
				return t_5
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_lxor1(a_in int64, b_in int64) int64 {
	for {
		a_1 := a_in
		_ = a_1
		b_2 := b_in
		_ = b_2
		switch {
		case a_1 == 0:
			return b_2
		case a_1 > 0:
			a0_3 := a_1
			_ = a0_3
			switch {
			case b_2 == 0:
				return a_1
			case b_2 > 0:
				b0_4 := b_2
				_ = b0_4
				t_5 := F_lxor(a0_3, b0_4)
				t_6 := id64(t_5)
				return t_6
			case b_2 < 0:
				b0_7 := zOpp(b_2)
				_ = b0_7
				t_8 := a0_3
				t_9 := F_pred_N(b0_7)
				t_10 := F_lxor0(t_8, t_9)
				t_11 := F_succ_pos(t_10)
				t_12 := zOpp(t_11)
				return t_12
			default:
				panic("gogen: no case matches")
			}
		case a_1 < 0:
			a0_13 := zOpp(a_1)
			_ = a0_13
			switch {
			case b_2 == 0:
				return a_1
			case b_2 > 0:
				b0_14 := b_2
				_ = b0_14
				t_15 := F_pred_N(a0_13)
				t_16 := b0_14
				t_17 := F_lxor0(t_15, t_16)
				t_18 := F_succ_pos(t_17)
				t_19 := zOpp(t_18)
				return t_19
			case b_2 < 0:
				b0_20 := zOpp(b_2)
				_ = b0_20
				t_21 := F_pred_N(a0_13)
				t_22 := F_pred_N(b0_20)
				t_23 := F_lxor0(t_21, t_22)
				t_24 := id64(t_23)
				return t_24
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_map[T1 any, T2 any](f_in func(T1) T2, l_in *I_list[T1]) *I_list[T2] {
	for {
		f_1 := f_in
		_ = f_1
		l_2 := l_in
		_ = l_2
		switch l_2.tag {
		case 0:
			t_3 := &I_list[T2]{tag: 0}
			return t_3
		case 1:
			a_4 := l_2.f1_0
			_ = a_4
			l0_5 := l_2.f1_1
			_ = l0_5
			t_6 := f_1(a_4)
			t_7 := F_map[T1, T2](f_1, l0_5)
			t_8 := &I_list[T2]{tag: 1, f1_0: t_6, f1_1: t_7}
			return t_8
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_mk(l_in *I_list[int64], acc_in *I_list[func(int64) int64]) *I_list[func(int64) int64] {
	for {
		l_1 := l_in
		_ = l_1
		acc_2 := acc_in
		_ = acc_2
		switch l_1.tag {
		case 0:
			return acc_2
		case 1:
			x_3 := l_1.f1_0
			_ = x_3
			t_4 := l_1.f1_1
			_ = t_4
			t_5 := zMul(x_3, int64(3))
			y_6 := t_5
			_ = y_6
			t_10 := func(z_7 int64) int64 {
				_ = z_7
				t_8 := zAdd(z_7, x_3)
				t_9 := zAdd(t_8, y_6)
				return t_9
			}
			t_11 := &I_list[func(int64) int64]{tag: 1, f1_0: t_10, f1_1: acc_2}
			l_in, acc_in = t_4, t_11
			continue
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_modulo(x_in int64, y_in int64) int64 {
	for {
		x_1 := x_in
		_ = x_1
		y_2 := y_in
		_ = y_2
		if y_2 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case y_2 == 0:
			return x_1
		case y_2 > 0:
			y_p_3 := y_2 - 1
			_ = y_p_3
			t_4 := F_divmod(x_1, y_p_3, int64(0), y_p_3)
			t_5 := F_snd[int64, int64](t_4)
			t_6 := F_sub(y_p_3, t_5)
			return t_6
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_modulo0(a_in int64, b_in int64) int64 {
	for {
		a_1 := a_in
		_ = a_1
		b_2 := b_in
		_ = b_2
		t_3 := F_div_eucl0(a_1, b_2)
		switch t_3.tag {
		case 0:
			r0_4 := t_3.f0_1
			_ = r0_4
			return r0_4
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_mul(n_in int64, m_in int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		m_2 := m_in
		_ = m_2
		if n_1 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case n_1 == 0:
			return int64(0)
		case n_1 > 0:
			p_3 := n_1 - 1
			_ = p_3
			t_4 := F_mul(p_3, m_2)
			t_5 := F_add(m_2, t_4)
			return t_5
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_mul0(x_in int64, y_in int64) int64 {
	for {
		x_1 := x_in
		_ = x_1
		y_2 := y_in
		_ = y_2
		if x_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case x_1 > 1 && x_1%2 == 1:
			p_3 := x_1 / 2
			_ = p_3
			t_4 := F_mul0(p_3, y_2)
			t_5 := posXO(t_4)
			t_6 := F_add0(y_2, t_5)
			return t_6
		case x_1 > 1 && x_1%2 == 0:
			p_7 := x_1 / 2
			_ = p_7
			t_8 := F_mul0(p_7, y_2)
			t_9 := posXO(t_8)
			return t_9
		case x_1 == 1:
			return y_2
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_ndouble(n_in int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		if n_1 < 0 {
			panic("gogen: not a N")
		}
		switch {
		case n_1 == 0:
			return int64(0)
		case n_1 > 0:
			p_2 := n_1
			_ = p_2
			t_3 := posXO(p_2)
			t_4 := t_3
			return t_4
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_negb(b_in bool) bool {
	for {
		b_1 := b_in
		_ = b_1
		switch {
		case b_1:
			return false
		case !b_1:
			return true
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_nsucc_double(x_in int64) int64 {
	for {
		x_1 := x_in
		_ = x_1
		if x_1 < 0 {
			panic("gogen: not a N")
		}
		switch {
		case x_1 == 0:
			return int64(1)
		case x_1 > 0:
			p_2 := x_1
			_ = p_2
			t_3 := posXI(p_2)
			t_4 := t_3
			return t_4
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_nth_err() func(*I_list[int64]) func(int64) *I_option[int64] {
	for {
		t_3 := func(a_1 *I_list[int64]) func(int64) *I_option[int64] {
			return func(a_2 int64) *I_option[int64] {
				return F_nth_error[int64](a_1, a_2)
			}
		}
		return t_3
	}
}

func F_nth_error[T1 any](l_in *I_list[T1], n_in int64) *I_option[T1] {
	for {
		l_1 := l_in
		_ = l_1
		n_2 := n_in
		_ = n_2
		if n_2 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case n_2 == 0:
			switch l_1.tag {
			case 0:
				t_3 := &I_option[T1]{tag: 1}
				return t_3
			case 1:
				x_4 := l_1.f1_0
				_ = x_4
				t_5 := &I_option[T1]{tag: 0, f0_0: x_4}
				return t_5
			default:
				panic("gogen: no case matches")
			}
		case n_2 > 0:
			n0_6 := n_2 - 1
			_ = n0_6
			switch l_1.tag {
			case 0:
				t_7 := &I_option[T1]{tag: 1}
				return t_7
			case 1:
				l_p_8 := l_1.f1_1
				_ = l_p_8
				l_in, n_in = l_p_8, n0_6
				continue
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_od(n_in int64) bool {
	for {
		n_1 := n_in
		_ = n_1
		if n_1 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case n_1 == 0:
			return false
		case n_1 > 0:
			k_2 := n_1 - 1
			_ = k_2
			t_3 := F_ev(k_2)
			return t_3
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_of_nat(n_in int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		if n_1 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case n_1 == 0:
			return int64(1)
		case n_1 > 0:
			x_2 := n_1 - 1
			_ = x_2
			if x_2 < 0 {
				panic("gogen: not a nat")
			}
			switch {
			case x_2 == 0:
				return int64(1)
			case x_2 > 0:
				__3 := x_2 - 1
				_ = __3
				t_4 := F_of_nat(x_2)
				t_5 := natSucc(t_4)
				return t_5
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_of_nat0(n_in int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		if n_1 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case n_1 == 0:
			return int64(0)
		case n_1 > 0:
			n_p_2 := n_1 - 1
			_ = n_p_2
			t_3 := F_of_succ_nat(n_p_2)
			t_4 := t_3
			return t_4
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_of_succ_nat(n_in int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		if n_1 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case n_1 == 0:
			return int64(1)
		case n_1 > 0:
			x_2 := n_1 - 1
			_ = x_2
			t_3 := F_of_succ_nat(x_2)
			t_4 := F_succ(t_3)
			return t_4
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_of_succ_nat0(n_in int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		if n_1 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case n_1 == 0:
			return int64(1)
		case n_1 > 0:
			x_2 := n_1 - 1
			_ = x_2
			t_3 := F_of_succ_nat0(x_2)
			t_4 := natSucc(t_3)
			return t_4
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_pa() func(int64) func(int64) int64 {
	for {
		t_3 := func(a_1 int64) func(int64) int64 {
			return func(a_2 int64) int64 {
				return F_f3(int64(1), a_1, a_2)
			}
		}
		return t_3
	}
}

func F_pos_div_eucl(a_in int64, b_in int64) *I_prod[int64, int64] {
	for {
		a_1 := a_in
		_ = a_1
		b_2 := b_in
		_ = b_2
		if a_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case a_1 > 1 && a_1%2 == 1:
			a_p_3 := a_1 / 2
			_ = a_p_3
			t_4 := F_pos_div_eucl(a_p_3, b_2)
			switch t_4.tag {
			case 0:
				q_5 := t_4.f0_0
				_ = q_5
				r0_6 := t_4.f0_1
				_ = r0_6
				t_7 := F_succ_double(r0_6)
				r_p_8 := t_7
				_ = r_p_8
				t_9 := F_leb(b_2, r_p_8)
				switch {
				case t_9:
					t_10 := F_succ_double(q_5)
					t_11 := F_sub0(r_p_8, b_2)
					t_12 := &I_prod[int64, int64]{tag: 0, f0_0: t_10, f0_1: t_11}
					return t_12
				case !t_9:
					t_13 := F_double(q_5)
					t_14 := &I_prod[int64, int64]{tag: 0, f0_0: t_13, f0_1: r_p_8}
					return t_14
				default:
					panic("gogen: no case matches")
				}
			default:
				panic("gogen: no case matches")
			}
		case a_1 > 1 && a_1%2 == 0:
			a_p_15 := a_1 / 2
			_ = a_p_15
			t_16 := F_pos_div_eucl(a_p_15, b_2)
			switch t_16.tag {
			case 0:
				q_17 := t_16.f0_0
				_ = q_17
				r0_18 := t_16.f0_1
				_ = r0_18
				t_19 := F_double(r0_18)
				r_p_20 := t_19
				_ = r_p_20
				t_21 := F_leb(b_2, r_p_20)
				switch {
				case t_21:
					t_22 := F_succ_double(q_17)
					t_23 := F_sub0(r_p_20, b_2)
					t_24 := &I_prod[int64, int64]{tag: 0, f0_0: t_22, f0_1: t_23}
					return t_24
				case !t_21:
					t_25 := F_double(q_17)
					t_26 := &I_prod[int64, int64]{tag: 0, f0_0: t_25, f0_1: r_p_20}
					return t_26
				default:
					panic("gogen: no case matches")
				}
			default:
				panic("gogen: no case matches")
			}
		case a_1 == 1:
			if b_2 < 0 {
				panic("gogen: not a N")
			}
			switch {
			case b_2 == 0:
				t_27 := &I_prod[int64, int64]{tag: 0, f0_0: int64(0), f0_1: int64(1)}
				return t_27
			case b_2 > 0:
				p_28 := b_2
				_ = p_28
				if p_28 < 1 {
					panic("gogen: not a positive")
				}
				switch {
				case p_28 > 1 && p_28%2 == 1:
					__29 := p_28 / 2
					_ = __29
					t_30 := &I_prod[int64, int64]{tag: 0, f0_0: int64(0), f0_1: int64(1)}
					return t_30
				case p_28 > 1 && p_28%2 == 0:
					__31 := p_28 / 2
					_ = __31
					t_32 := &I_prod[int64, int64]{tag: 0, f0_0: int64(0), f0_1: int64(1)}
					return t_32
				case p_28 == 1:
					t_33 := &I_prod[int64, int64]{tag: 0, f0_0: int64(1), f0_1: int64(0)}
					return t_33
				default:
					panic("gogen: no case matches")
				}
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_pos_div_eucl0(a_in int64, b_in int64) *I_prod[int64, int64] {
	for {
		a_1 := a_in
		_ = a_1
		b_2 := b_in
		_ = b_2
		if a_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case a_1 > 1 && a_1%2 == 1:
			a_p_3 := a_1 / 2
			_ = a_p_3
			t_4 := F_pos_div_eucl0(a_p_3, b_2)
			switch t_4.tag {
			case 0:
				q_5 := t_4.f0_0
				_ = q_5
				r0_6 := t_4.f0_1
				_ = r0_6
				t_7 := F_succ_double0(r0_6)
				r_p_8 := t_7
				_ = r_p_8
				t_9 := F_leb0(b_2, r_p_8)
				switch {
				case t_9:
					t_10 := F_succ_double0(q_5)
					t_11 := natSub(r_p_8, b_2)
					t_12 := &I_prod[int64, int64]{tag: 0, f0_0: t_10, f0_1: t_11}
					return t_12
				case !t_9:
					t_13 := F_double0(q_5)
					t_14 := &I_prod[int64, int64]{tag: 0, f0_0: t_13, f0_1: r_p_8}
					return t_14
				default:
					panic("gogen: no case matches")
				}
			default:
				panic("gogen: no case matches")
			}
		case a_1 > 1 && a_1%2 == 0:
			a_p_15 := a_1 / 2
			_ = a_p_15
			t_16 := F_pos_div_eucl0(a_p_15, b_2)
			switch t_16.tag {
			case 0:
				q_17 := t_16.f0_0
				_ = q_17
				r0_18 := t_16.f0_1
				_ = r0_18
				t_19 := F_double0(r0_18)
				r_p_20 := t_19
				_ = r_p_20
				t_21 := F_leb0(b_2, r_p_20)
				switch {
				case t_21:
					t_22 := F_succ_double0(q_17)
					t_23 := natSub(r_p_20, b_2)
					t_24 := &I_prod[int64, int64]{tag: 0, f0_0: t_22, f0_1: t_23}
					return t_24
				case !t_21:
					t_25 := F_double0(q_17)
					t_26 := &I_prod[int64, int64]{tag: 0, f0_0: t_25, f0_1: r_p_20}
					return t_26
				default:
					panic("gogen: no case matches")
				}
			default:
				panic("gogen: no case matches")
			}
		case a_1 == 1:
			if b_2 < 0 {
				panic("gogen: not a N")
			}
			switch {
			case b_2 == 0:
				t_27 := &I_prod[int64, int64]{tag: 0, f0_0: int64(0), f0_1: int64(1)}
				return t_27
			case b_2 > 0:
				p_28 := b_2
				_ = p_28
				if p_28 < 1 {
					panic("gogen: not a positive")
				}
				switch {
				case p_28 > 1 && p_28%2 == 1:
					__29 := p_28 / 2
					_ = __29
					t_30 := &I_prod[int64, int64]{tag: 0, f0_0: int64(0), f0_1: int64(1)}
					return t_30
				case p_28 > 1 && p_28%2 == 0:
					__31 := p_28 / 2
					_ = __31
					t_32 := &I_prod[int64, int64]{tag: 0, f0_0: int64(0), f0_1: int64(1)}
					return t_32
				case p_28 == 1:
					t_33 := &I_prod[int64, int64]{tag: 0, f0_0: int64(1), f0_1: int64(0)}
					return t_33
				default:
					panic("gogen: no case matches")
				}
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_pos_div_eucl1(a_in int64, b_in int64) *I_prod[int64, int64] {
	for {
		a_1 := a_in
		_ = a_1
		b_2 := b_in
		_ = b_2
		if a_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case a_1 > 1 && a_1%2 == 1:
			a_p_3 := a_1 / 2
			_ = a_p_3
			t_4 := F_pos_div_eucl1(a_p_3, b_2)
			switch t_4.tag {
			case 0:
				q_5 := t_4.f0_0
				_ = q_5
				r0_6 := t_4.f0_1
				_ = r0_6
				t_7 := zMul(int64(2), r0_6)
				t_8 := zAdd(t_7, int64(1))
				r_p_9 := t_8
				_ = r_p_9
				t_10 := F_ltb1(r_p_9, b_2)
				switch {
				case t_10:
					t_11 := zMul(int64(2), q_5)
					t_12 := &I_prod[int64, int64]{tag: 0, f0_0: t_11, f0_1: r_p_9}
					return t_12
				case !t_10:
					t_13 := zMul(int64(2), q_5)
					t_14 := zAdd(t_13, int64(1))
					t_15 := zSub(r_p_9, b_2)
					t_16 := &I_prod[int64, int64]{tag: 0, f0_0: t_14, f0_1: t_15}
					return t_16
				default:
					panic("gogen: no case matches")
				}
			default:
				panic("gogen: no case matches")
			}
		case a_1 > 1 && a_1%2 == 0:
			a_p_17 := a_1 / 2
			_ = a_p_17
			t_18 := F_pos_div_eucl1(a_p_17, b_2)
			switch t_18.tag {
			case 0:
				q_19 := t_18.f0_0
				_ = q_19
				r0_20 := t_18.f0_1
				_ = r0_20
				t_21 := zMul(int64(2), r0_20)
				r_p_22 := t_21
				_ = r_p_22
				t_23 := F_ltb1(r_p_22, b_2)
				switch {
				case t_23:
					t_24 := zMul(int64(2), q_19)
					t_25 := &I_prod[int64, int64]{tag: 0, f0_0: t_24, f0_1: r_p_22}
					return t_25
				case !t_23:
					t_26 := zMul(int64(2), q_19)
					t_27 := zAdd(t_26, int64(1))
					t_28 := zSub(r_p_22, b_2)
					t_29 := &I_prod[int64, int64]{tag: 0, f0_0: t_27, f0_1: t_28}
					return t_29
				default:
					panic("gogen: no case matches")
				}
			default:
				panic("gogen: no case matches")
			}
		case a_1 == 1:
			t_30 := F_leb1(int64(2), b_2)
			switch {
			case t_30:
				t_31 := &I_prod[int64, int64]{tag: 0, f0_0: int64(0), f0_1: int64(1)}
				return t_31
			case !t_30:
				t_32 := &I_prod[int64, int64]{tag: 0, f0_0: int64(1), f0_1: int64(0)}
				return t_32
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_pos_sub(x_in int64, y_in int64) int64 {
	for {
		x_1 := x_in
		_ = x_1
		y_2 := y_in
		_ = y_2
		if x_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case x_1 > 1 && x_1%2 == 1:
			p_3 := x_1 / 2
			_ = p_3
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				q_4 := y_2 / 2
				_ = q_4
				t_5 := F_pos_sub(p_3, q_4)
				t_6 := F_double1(t_5)
				return t_6
			case y_2 > 1 && y_2%2 == 0:
				q_7 := y_2 / 2
				_ = q_7
				t_8 := F_pos_sub(p_3, q_7)
				t_9 := F_succ_double1(t_8)
				return t_9
			case y_2 == 1:
				t_10 := posXO(p_3)
				t_11 := t_10
				return t_11
			default:
				panic("gogen: no case matches")
			}
		case x_1 > 1 && x_1%2 == 0:
			p_12 := x_1 / 2
			_ = p_12
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				q_13 := y_2 / 2
				_ = q_13
				t_14 := F_pos_sub(p_12, q_13)
				t_15 := F_pred_double1(t_14)
				return t_15
			case y_2 > 1 && y_2%2 == 0:
				q_16 := y_2 / 2
				_ = q_16
				t_17 := F_pos_sub(p_12, q_16)
				t_18 := F_double1(t_17)
				return t_18
			case y_2 == 1:
				t_19 := F_pred_double(p_12)
				t_20 := t_19
				return t_20
			default:
				panic("gogen: no case matches")
			}
		case x_1 == 1:
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				q_21 := y_2 / 2
				_ = q_21
				t_22 := posXO(q_21)
				t_23 := zOpp(t_22)
				return t_23
			case y_2 > 1 && y_2%2 == 0:
				q_24 := y_2 / 2
				_ = q_24
				t_25 := F_pred_double(q_24)
				t_26 := zOpp(t_25)
				return t_26
			case y_2 == 1:
				return int64(0)
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_pow(n_in int64, m_in int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		m_2 := m_in
		_ = m_2
		if m_2 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case m_2 == 0:
			return int64(1)
		case m_2 > 0:
			m0_3 := m_2 - 1
			_ = m0_3
			t_4 := F_pow(n_1, m0_3)
			t_5 := F_mul(n_1, t_4)
			return t_5
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_pow0(x_in int64) func(int64) int64 {
	for {
		x_1 := x_in
		_ = x_1
		t_3 := func(a_2 int64) int64 {
			return zMul(x_1, a_2)
		}
		t_5 := func(a_4 int64) int64 {
			return F_iter0[int64](t_3, int64(1), a_4)
		}
		return t_5
	}
}

func F_pow1(n_in int64, p_in int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		p_2 := p_in
		_ = p_2
		if p_2 < 0 {
			panic("gogen: not a N")
		}
		switch {
		case p_2 == 0:
			return int64(1)
		case p_2 > 0:
			p0_3 := p_2
			_ = p0_3
			if n_1 < 0 {
				panic("gogen: not a N")
			}
			switch {
			case n_1 == 0:
				return int64(0)
			case n_1 > 0:
				q_4 := n_1
				_ = q_4
				t_5 := F_pow0(q_4)(p0_3)
				t_6 := t_5
				return t_6
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_pow2(x_in int64, y_in int64) int64 {
	for {
		x_1 := x_in
		_ = x_1
		y_2 := y_in
		_ = y_2
		switch {
		case y_2 == 0:
			return int64(1)
		case y_2 > 0:
			p_3 := y_2
			_ = p_3
			t_4 := F_pow_pos(x_1)(p_3)
			return t_4
		case y_2 < 0:
			__5 := zOpp(y_2)
			_ = __5
			return int64(0)
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_pow_pos(z_in int64) func(int64) int64 {
	for {
		z_1 := z_in
		_ = z_1
		t_3 := func(a_2 int64) int64 {
			return zMul(z_1, a_2)
		}
		t_5 := func(a_4 int64) int64 {
			return F_iter[int64](t_3, int64(1), a_4)
		}
		return t_5
	}
}

func F_pred(n_in int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		if n_1 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case n_1 == 0:
			return n_1
		case n_1 > 0:
			u_2 := n_1 - 1
			_ = u_2
			return u_2
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_pred_N(x_in int64) int64 {
	for {
		x_1 := x_in
		_ = x_1
		if x_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case x_1 > 1 && x_1%2 == 1:
			p_2 := x_1 / 2
			_ = p_2
			t_3 := posXO(p_2)
			t_4 := t_3
			return t_4
		case x_1 > 1 && x_1%2 == 0:
			p_5 := x_1 / 2
			_ = p_5
			t_6 := F_pred_double(p_5)
			t_7 := t_6
			return t_7
		case x_1 == 1:
			return int64(0)
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_pred_double(x_in int64) int64 {
	for {
		x_1 := x_in
		_ = x_1
		if x_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case x_1 > 1 && x_1%2 == 1:
			p_2 := x_1 / 2
			_ = p_2
			t_3 := posXO(p_2)
			t_4 := posXI(t_3)
			return t_4
		case x_1 > 1 && x_1%2 == 0:
			p_5 := x_1 / 2
			_ = p_5
			t_6 := F_pred_double(p_5)
			t_7 := posXI(t_6)
			return t_7
		case x_1 == 1:
			return int64(1)
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_pred_double0(x_in int64) int64 {
	for {
		x_1 := x_in
		_ = x_1
		if x_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case x_1 > 1 && x_1%2 == 1:
			p_2 := x_1 / 2
			_ = p_2
			t_3 := posXO(p_2)
			t_4 := posXI(t_3)
			return t_4
		case x_1 > 1 && x_1%2 == 0:
			p_5 := x_1 / 2
			_ = p_5
			t_6 := F_pred_double0(p_5)
			t_7 := posXI(t_6)
			return t_7
		case x_1 == 1:
			return int64(1)
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_pred_double1(x_in int64) int64 {
	for {
		x_1 := x_in
		_ = x_1
		switch {
		case x_1 == 0:
			return int64(-1)
		case x_1 > 0:
			p_2 := x_1
			_ = p_2
			t_3 := F_pred_double(p_2)
			t_4 := t_3
			return t_4
		case x_1 < 0:
			p_5 := zOpp(x_1)
			_ = p_5
			t_6 := posXI(p_5)
			t_7 := zOpp(t_6)
			return t_7
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_quot(a_in int64, b_in int64) int64 {
	for {
		a_1 := a_in
		_ = a_1
		b_2 := b_in
		_ = b_2
		t_3 := F_quotrem(a_1, b_2)
		t_4 := F_fst[int64, int64](t_3)
		return t_4
	}
}

func F_quotrem(a_in int64, b_in int64) *I_prod[int64, int64] {
	for {
		a_1 := a_in
		_ = a_1
		b_2 := b_in
		_ = b_2
		switch {
		case a_1 == 0:
			t_3 := &I_prod[int64, int64]{tag: 0, f0_0: int64(0), f0_1: int64(0)}
			return t_3
		case a_1 > 0:
			a0_4 := a_1
			_ = a0_4
			switch {
			case b_2 == 0:
				t_5 := &I_prod[int64, int64]{tag: 0, f0_0: int64(0), f0_1: a_1}
				return t_5
			case b_2 > 0:
				b0_6 := b_2
				_ = b0_6
				t_7 := b0_6
				t_8 := F_pos_div_eucl(a0_4, t_7)
				switch t_8.tag {
				case 0:
					q_9 := t_8.f0_0
					_ = q_9
					r0_10 := t_8.f0_1
					_ = r0_10
					t_11 := id64(q_9)
					t_12 := id64(r0_10)
					t_13 := &I_prod[int64, int64]{tag: 0, f0_0: t_11, f0_1: t_12}
					return t_13
				default:
					panic("gogen: no case matches")
				}
			case b_2 < 0:
				b0_14 := zOpp(b_2)
				_ = b0_14
				t_15 := b0_14
				t_16 := F_pos_div_eucl(a0_4, t_15)
				switch t_16.tag {
				case 0:
					q_17 := t_16.f0_0
					_ = q_17
					r0_18 := t_16.f0_1
					_ = r0_18
					t_19 := id64(q_17)
					t_20 := zOpp(t_19)
					t_21 := id64(r0_18)
					t_22 := &I_prod[int64, int64]{tag: 0, f0_0: t_20, f0_1: t_21}
					return t_22
				default:
					panic("gogen: no case matches")
				}
			default:
				panic("gogen: no case matches")
			}
		case a_1 < 0:
			a0_23 := zOpp(a_1)
			_ = a0_23
			switch {
			case b_2 == 0:
				t_24 := &I_prod[int64, int64]{tag: 0, f0_0: int64(0), f0_1: a_1}
				return t_24
			case b_2 > 0:
				b0_25 := b_2
				_ = b0_25
				t_26 := b0_25
				t_27 := F_pos_div_eucl(a0_23, t_26)
				switch t_27.tag {
				case 0:
					q_28 := t_27.f0_0
					_ = q_28
					r0_29 := t_27.f0_1
					_ = r0_29
					t_30 := id64(q_28)
					t_31 := zOpp(t_30)
					t_32 := id64(r0_29)
					t_33 := zOpp(t_32)
					t_34 := &I_prod[int64, int64]{tag: 0, f0_0: t_31, f0_1: t_33}
					return t_34
				default:
					panic("gogen: no case matches")
				}
			case b_2 < 0:
				b0_35 := zOpp(b_2)
				_ = b0_35
				t_36 := b0_35
				t_37 := F_pos_div_eucl(a0_23, t_36)
				switch t_37.tag {
				case 0:
					q_38 := t_37.f0_0
					_ = q_38
					r0_39 := t_37.f0_1
					_ = r0_39
					t_40 := id64(q_38)
					t_41 := id64(r0_39)
					t_42 := zOpp(t_41)
					t_43 := &I_prod[int64, int64]{tag: 0, f0_0: t_40, f0_1: t_42}
					return t_43
				default:
					panic("gogen: no case matches")
				}
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_r_unused(_ int64, _ int64) int64 {
	for {
		return int64(7)
	}
}

func F_rem(a_in int64, b_in int64) int64 {
	for {
		a_1 := a_in
		_ = a_1
		b_2 := b_in
		_ = b_2
		t_3 := F_quotrem(a_1, b_2)
		t_4 := F_snd[int64, int64](t_3)
		return t_4
	}
}

func F_shadow(x_in int64) int64 {
	for {
		x_1 := x_in
		_ = x_1
		t_2 := zAdd(x_1, int64(1))
		x0_3 := t_2
		_ = x0_3
		t_4 := zAdd(x0_3, int64(10))
		x1_5 := t_4
		_ = x1_5
		t_6 := zMul(x1_5, int64(2))
		return t_6
	}
}

func F_shiftl(a_in int64, n_in int64) int64 {
	for {
		a_1 := a_in
		_ = a_1
		n_2 := n_in
		_ = n_2
		switch {
		case n_2 == 0:
			return a_1
		case n_2 > 0:
			p_3 := n_2
			_ = p_3
			t_5 := func(a_4 int64) int64 {
				return zMul(int64(2), a_4)
			}
			t_6 := F_iter[int64](t_5, a_1, p_3)
			return t_6
		case n_2 < 0:
			p_7 := zOpp(n_2)
			_ = p_7
			t_9 := func(a_8 int64) int64 {
				return F_div1(a_8)
			}
			t_10 := F_iter[int64](t_9, a_1, p_7)
			return t_10
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_snd[T1 any, T2 any](p_in *I_prod[T1, T2]) T2 {
	for {
		p_1 := p_in
		_ = p_1
		switch p_1.tag {
		case 0:
			y_2 := p_1.f0_1
			_ = y_2
			return y_2
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_sqrt(n_in int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		t_2 := F_sqrt_iter(n_1, int64(0), int64(0), int64(0))
		return t_2
	}
}

func F_sqrt_iter(k_in int64, p_in int64, q_in int64, r0_in int64) int64 {
	for {
		k_1 := k_in
		_ = k_1
		p_2 := p_in
		_ = p_2
		q_3 := q_in
		_ = q_3
		r0_4 := r0_in
		_ = r0_4
		if k_1 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case k_1 == 0:
			return p_2
		case k_1 > 0:
			k_p_5 := k_1 - 1
			_ = k_p_5
			if r0_4 < 0 {
				panic("gogen: not a nat")
			}
			switch {
			case r0_4 == 0:
				t_6 := natSucc(p_2)
				t_7 := natSucc(q_3)
				t_8 := natSucc(t_7)
				t_9 := natSucc(q_3)
				t_10 := natSucc(t_9)
				k_in, p_in, q_in, r0_in = k_p_5, t_6, t_8, t_10
				continue
			case r0_4 > 0:
				r_p_11 := r0_4 - 1
				_ = r_p_11
				k_in, p_in, q_in, r0_in = k_p_5, p_2, q_3, r_p_11
				continue
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_sub(n_in int64, m_in int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		m_2 := m_in
		_ = m_2
		if n_1 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case n_1 == 0:
			return n_1
		case n_1 > 0:
			k_3 := n_1 - 1
			_ = k_3
			if m_2 < 0 {
				panic("gogen: not a nat")
			}
			switch {
			case m_2 == 0:
				return n_1
			case m_2 > 0:
				l_4 := m_2 - 1
				_ = l_4
				n_in, m_in = k_3, l_4
				continue
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_sub0(n_in int64, m_in int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		m_2 := m_in
		_ = m_2
		if n_1 < 0 {
			panic("gogen: not a N")
		}
		switch {
		case n_1 == 0:
			return int64(0)
		case n_1 > 0:
			n_p_3 := n_1
			_ = n_p_3
			if m_2 < 0 {
				panic("gogen: not a N")
			}
			switch {
			case m_2 == 0:
				return n_1
			case m_2 > 0:
				m_p_4 := m_2
				_ = m_p_4
				t_5 := F_sub_mask(n_p_3, m_p_4)
				switch t_5.tag {
				case 1:
					p_6 := t_5.f1_0
					_ = p_6
					t_7 := p_6
					return t_7
				default:
					return int64(0)
				}
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_sub_mask(x_in int64, y_in int64) *I_mask {
	for {
		x_1 := x_in
		_ = x_1
		y_2 := y_in
		_ = y_2
		if x_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case x_1 > 1 && x_1%2 == 1:
			p_3 := x_1 / 2
			_ = p_3
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				q_4 := y_2 / 2
				_ = q_4
				t_5 := F_sub_mask(p_3, q_4)
				t_6 := F_double_mask(t_5)
				return t_6
			case y_2 > 1 && y_2%2 == 0:
				q_7 := y_2 / 2
				_ = q_7
				t_8 := F_sub_mask(p_3, q_7)
				t_9 := F_succ_double_mask(t_8)
				return t_9
			case y_2 == 1:
				t_10 := posXO(p_3)
				t_11 := &I_mask{tag: 1, f1_0: t_10}
				return t_11
			default:
				panic("gogen: no case matches")
			}
		case x_1 > 1 && x_1%2 == 0:
			p_12 := x_1 / 2
			_ = p_12
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				q_13 := y_2 / 2
				_ = q_13
				t_14 := F_sub_mask_carry(p_12, q_13)
				t_15 := F_succ_double_mask(t_14)
				return t_15
			case y_2 > 1 && y_2%2 == 0:
				q_16 := y_2 / 2
				_ = q_16
				t_17 := F_sub_mask(p_12, q_16)
				t_18 := F_double_mask(t_17)
				return t_18
			case y_2 == 1:
				t_19 := F_pred_double(p_12)
				t_20 := &I_mask{tag: 1, f1_0: t_19}
				return t_20
			default:
				panic("gogen: no case matches")
			}
		case x_1 == 1:
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				__21 := y_2 / 2
				_ = __21
				return C_IsNeg
			case y_2 > 1 && y_2%2 == 0:
				__22 := y_2 / 2
				_ = __22
				return C_IsNeg
			case y_2 == 1:
				return C_IsNul
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_sub_mask0(x_in int64, y_in int64) *I_mask0 {
	for {
		x_1 := x_in
		_ = x_1
		y_2 := y_in
		_ = y_2
		if x_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case x_1 > 1 && x_1%2 == 1:
			p_3 := x_1 / 2
			_ = p_3
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				q_4 := y_2 / 2
				_ = q_4
				t_5 := F_sub_mask0(p_3, q_4)
				t_6 := F_double_mask0(t_5)
				return t_6
			case y_2 > 1 && y_2%2 == 0:
				q_7 := y_2 / 2
				_ = q_7
				t_8 := F_sub_mask0(p_3, q_7)
				t_9 := F_succ_double_mask0(t_8)
				return t_9
			case y_2 == 1:
				t_10 := posXO(p_3)
				t_11 := &I_mask0{tag: 1, f1_0: t_10}
				return t_11
			default:
				panic("gogen: no case matches")
			}
		case x_1 > 1 && x_1%2 == 0:
			p_12 := x_1 / 2
			_ = p_12
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				q_13 := y_2 / 2
				_ = q_13
				t_14 := F_sub_mask_carry0(p_12, q_13)
				t_15 := F_succ_double_mask0(t_14)
				return t_15
			case y_2 > 1 && y_2%2 == 0:
				q_16 := y_2 / 2
				_ = q_16
				t_17 := F_sub_mask0(p_12, q_16)
				t_18 := F_double_mask0(t_17)
				return t_18
			case y_2 == 1:
				t_19 := F_pred_double0(p_12)
				t_20 := &I_mask0{tag: 1, f1_0: t_19}
				return t_20
			default:
				panic("gogen: no case matches")
			}
		case x_1 == 1:
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				__21 := y_2 / 2
				_ = __21
				return C_IsNeg0
			case y_2 > 1 && y_2%2 == 0:
				__22 := y_2 / 2
				_ = __22
				return C_IsNeg0
			case y_2 == 1:
				return C_IsNul0
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_sub_mask_carry(x_in int64, y_in int64) *I_mask {
	for {
		x_1 := x_in
		_ = x_1
		y_2 := y_in
		_ = y_2
		if x_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case x_1 > 1 && x_1%2 == 1:
			p_3 := x_1 / 2
			_ = p_3
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				q_4 := y_2 / 2
				_ = q_4
				t_5 := F_sub_mask_carry(p_3, q_4)
				t_6 := F_succ_double_mask(t_5)
				return t_6
			case y_2 > 1 && y_2%2 == 0:
				q_7 := y_2 / 2
				_ = q_7
				t_8 := F_sub_mask(p_3, q_7)
				t_9 := F_double_mask(t_8)
				return t_9
			case y_2 == 1:
				t_10 := F_pred_double(p_3)
				t_11 := &I_mask{tag: 1, f1_0: t_10}
				return t_11
			default:
				panic("gogen: no case matches")
			}
		case x_1 > 1 && x_1%2 == 0:
			p_12 := x_1 / 2
			_ = p_12
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				q_13 := y_2 / 2
				_ = q_13
				t_14 := F_sub_mask_carry(p_12, q_13)
				t_15 := F_double_mask(t_14)
				return t_15
			case y_2 > 1 && y_2%2 == 0:
				q_16 := y_2 / 2
				_ = q_16
				t_17 := F_sub_mask_carry(p_12, q_16)
				t_18 := F_succ_double_mask(t_17)
				return t_18
			case y_2 == 1:
				t_19 := F_double_pred_mask(p_12)
				return t_19
			default:
				panic("gogen: no case matches")
			}
		case x_1 == 1:
			return C_IsNeg
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_sub_mask_carry0(x_in int64, y_in int64) *I_mask0 {
	for {
		x_1 := x_in
		_ = x_1
		y_2 := y_in
		_ = y_2
		if x_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case x_1 > 1 && x_1%2 == 1:
			p_3 := x_1 / 2
			_ = p_3
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				q_4 := y_2 / 2
				_ = q_4
				t_5 := F_sub_mask_carry0(p_3, q_4)
				t_6 := F_succ_double_mask0(t_5)
				return t_6
			case y_2 > 1 && y_2%2 == 0:
				q_7 := y_2 / 2
				_ = q_7
				t_8 := F_sub_mask0(p_3, q_7)
				t_9 := F_double_mask0(t_8)
				return t_9
			case y_2 == 1:
				t_10 := F_pred_double0(p_3)
				t_11 := &I_mask0{tag: 1, f1_0: t_10}
				return t_11
			default:
				panic("gogen: no case matches")
			}
		case x_1 > 1 && x_1%2 == 0:
			p_12 := x_1 / 2
			_ = p_12
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				q_13 := y_2 / 2
				_ = q_13
				t_14 := F_sub_mask_carry0(p_12, q_13)
				t_15 := F_double_mask0(t_14)
				return t_15
			case y_2 > 1 && y_2%2 == 0:
				q_16 := y_2 / 2
				_ = q_16
				t_17 := F_sub_mask_carry0(p_12, q_16)
				t_18 := F_succ_double_mask0(t_17)
				return t_18
			case y_2 == 1:
				t_19 := F_double_pred_mask0(p_12)
				return t_19
			default:
				panic("gogen: no case matches")
			}
		case x_1 == 1:
			return C_IsNeg0
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_succ(x_in int64) int64 {
	for {
		x_1 := x_in
		_ = x_1
		if x_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case x_1 > 1 && x_1%2 == 1:
			p_2 := x_1 / 2
			_ = p_2
			t_3 := F_succ(p_2)
			t_4 := posXO(t_3)
			return t_4
		case x_1 > 1 && x_1%2 == 0:
			p_5 := x_1 / 2
			_ = p_5
			t_6 := posXI(p_5)
			return t_6
		case x_1 == 1:
			return int64(2)
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_succ_double(x_in int64) int64 {
	for {
		x_1 := x_in
		_ = x_1
		if x_1 < 0 {
			panic("gogen: not a N")
		}
		switch {
		case x_1 == 0:
			return int64(1)
		case x_1 > 0:
			p_2 := x_1
			_ = p_2
			t_3 := posXI(p_2)
			t_4 := t_3
			return t_4
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_succ_double0(x_in int64) int64 {
	for {
		x_1 := x_in
		_ = x_1
		if x_1 < 0 {
			panic("gogen: not a N")
		}
		switch {
		case x_1 == 0:
			return int64(1)
		case x_1 > 0:
			p_2 := x_1
			_ = p_2
			t_3 := posXI(p_2)
			t_4 := t_3
			return t_4
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_succ_double1(x_in int64) int64 {
	for {
		x_1 := x_in
		_ = x_1
		switch {
		case x_1 == 0:
			return int64(1)
		case x_1 > 0:
			p_2 := x_1
			_ = p_2
			t_3 := posXI(p_2)
			t_4 := t_3
			return t_4
		case x_1 < 0:
			p_5 := zOpp(x_1)
			_ = p_5
			t_6 := F_pred_double(p_5)
			t_7 := zOpp(t_6)
			return t_7
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_succ_double_mask(x_in *I_mask) *I_mask {
	for {
		x_1 := x_in
		_ = x_1
		switch x_1.tag {
		case 0:
			t_2 := &I_mask{tag: 1, f1_0: int64(1)}
			return t_2
		case 1:
			p_3 := x_1.f1_0
			_ = p_3
			t_4 := posXI(p_3)
			t_5 := &I_mask{tag: 1, f1_0: t_4}
			return t_5
		case 2:
			return C_IsNeg
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_succ_double_mask0(x_in *I_mask0) *I_mask0 {
	for {
		x_1 := x_in
		_ = x_1
		switch x_1.tag {
		case 0:
			t_2 := &I_mask0{tag: 1, f1_0: int64(1)}
			return t_2
		case 1:
			p_3 := x_1.f1_0
			_ = p_3
			t_4 := posXI(p_3)
			t_5 := &I_mask0{tag: 1, f1_0: t_4}
			return t_5
		case 2:
			return C_IsNeg0
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_succ_pos(n_in int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		if n_1 < 0 {
			panic("gogen: not a N")
		}
		switch {
		case n_1 == 0:
			return int64(1)
		case n_1 > 0:
			p_2 := n_1
			_ = p_2
			t_3 := F_succ(p_2)
			return t_3
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_swapper(n_in int64, a_in int64, b_in int64) *I_prod[int64, int64] {
	for {
		n_1 := n_in
		_ = n_1
		a_2 := a_in
		_ = a_2
		b_3 := b_in
		_ = b_3
		if n_1 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case n_1 == 0:
			t_4 := &I_prod[int64, int64]{tag: 0, f0_0: a_2, f0_1: b_3}
			return t_4
		case n_1 > 0:
			k_5 := n_1 - 1
			_ = k_5
			t_6 := zAdd(a_2, int64(1))
			n_in, a_in, b_in = k_5, b_3, t_6
			continue
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_t_and() *I_list[bool] {
	for {
		t_1 := &I_list[int64]{tag: 0}
		t_2 := &I_list[int64]{tag: 1, f1_0: int64(3), f1_1: t_1}
		t_3 := &I_list[int64]{tag: 1, f1_0: int64(2), f1_1: t_2}
		t_4 := &I_list[int64]{tag: 1, f1_0: int64(1), f1_1: t_3}
		t_5 := F_allpos(t_4)
		t_6 := &I_list[int64]{tag: 0}
		t_7 := &I_list[int64]{tag: 1, f1_0: int64(3), f1_1: t_6}
		t_8 := &I_list[int64]{tag: 1, f1_0: int64(-2), f1_1: t_7}
		t_9 := &I_list[int64]{tag: 1, f1_0: int64(1), f1_1: t_8}
		t_10 := F_allpos(t_9)
		b_11 := false
		if b_11 {
			t_12 := &I_list[int64]{tag: 0}
			t_13 := F_allpos(t_12)
			b_11 = t_13
		}
		t_14 := &I_list[bool]{tag: 0}
		t_15 := &I_list[bool]{tag: 1, f1_0: b_11, f1_1: t_14}
		t_16 := &I_list[bool]{tag: 1, f1_0: t_10, f1_1: t_15}
		t_17 := &I_list[bool]{tag: 1, f1_0: t_5, f1_1: t_16}
		return t_17
	}
}

func F_t_big() *I_list[int64] {
	for {
		t_1 := &I_big{tag: 0, f0_0: int64(1), f0_1: int64(2), f0_2: int64(3), f0_3: int64(4), f0_4: int64(5), f0_5: int64(6), f0_6: int64(7), f0_7: int64(8)}
		t_2 := F_bigf(t_1)
		t_3 := F_bigf(C_C0)
		t_4 := &I_big{tag: 2, f2_0: int64(4)}
		t_5 := F_bigf(t_4)
		t_6 := F_bigf(C_C2)
		t_7 := &I_list[int64]{tag: 0}
		t_8 := &I_list[int64]{tag: 1, f1_0: t_6, f1_1: t_7}
		t_9 := &I_list[int64]{tag: 1, f1_0: t_5, f1_1: t_8}
		t_10 := &I_list[int64]{tag: 1, f1_0: t_3, f1_1: t_9}
		t_11 := &I_list[int64]{tag: 1, f1_0: t_2, f1_1: t_10}
		return t_11
	}
}

func F_t_clos() *I_list[int64] {
	for {
		t_3 := func(f_1 func(int64) int64) int64 {
			_ = f_1
			t_2 := f_1(int64(100))
			return t_2
		}
		t_4 := &I_list[int64]{tag: 0}
		t_5 := &I_list[int64]{tag: 1, f1_0: int64(4), f1_1: t_4}
		t_6 := &I_list[int64]{tag: 1, f1_0: int64(3), f1_1: t_5}
		t_7 := &I_list[int64]{tag: 1, f1_0: int64(2), f1_1: t_6}
		t_8 := &I_list[int64]{tag: 1, f1_0: int64(1), f1_1: t_7}
		t_9 := &I_list[func(int64) int64]{tag: 0}
		t_10 := F_mk(t_8, t_9)
		t_11 := F_map[func(int64) int64, int64](t_3, t_10)
		return t_11
	}
}

func F_t_cmp() *I_list[bool] {
	for {
		t_1 := F_ltb(int64(3), int64(3))
		t_2 := leb(int64(3), int64(3))
		t_3 := F_leb1(int64(-1), int64(0))
		t_4 := F_eqb1(int64(5), int64(5))
		t_5 := F_eqb0(int64(4), int64(4))
		t_6 := F_ltb0(int64(2), int64(3))
		t_7 := F_gtb(int64(1), int64(2))
		t_8 := &I_list[bool]{tag: 0}
		t_9 := &I_list[bool]{tag: 1, f1_0: t_7, f1_1: t_8}
		t_10 := &I_list[bool]{tag: 1, f1_0: t_6, f1_1: t_9}
		t_11 := &I_list[bool]{tag: 1, f1_0: t_5, f1_1: t_10}
		t_12 := &I_list[bool]{tag: 1, f1_0: t_4, f1_1: t_11}
		t_13 := &I_list[bool]{tag: 1, f1_0: t_3, f1_1: t_12}
		t_14 := &I_list[bool]{tag: 1, f1_0: t_2, f1_1: t_13}
		t_15 := &I_list[bool]{tag: 1, f1_0: t_1, f1_1: t_14}
		return t_15
	}
}

func F_t_comp() *I_list[int64] {
	for {
		t_2 := func(x_1 int64) int64 {
			_ = x_1
			return x_1
		}
		t_3 := F_compose_n(int64(5), t_2)(int64(0))
		t_6 := func(x_4 int64) int64 {
			_ = x_4
			t_5 := natSucc(x_4)
			return t_5
		}
		t_7 := F_compose_n(int64(3), t_6)(int64(10))
		t_8 := &I_list[int64]{tag: 0}
		t_9 := &I_list[int64]{tag: 1, f1_0: t_7, f1_1: t_8}
		t_10 := &I_list[int64]{tag: 1, f1_0: t_3, f1_1: t_9}
		return t_10
	}
}

func F_t_dec() *I_list[int64] {
	for {
		var r_1 int64
		t_2 := eqb(int64(3), int64(3))
		switch {
		case t_2:
			r_1 = int64(1)
		case !t_2:
			r_1 = int64(0)
		default:
			panic("gogen: no case matches")
		}
		var r_3 int64
		t_4 := F_eq_dec0(int64(3), int64(4))
		switch {
		case t_4:
			r_3 = int64(1)
		case !t_4:
			r_3 = int64(0)
		default:
			panic("gogen: no case matches")
		}
		var r_5 int64
		t_6 := F_z_lt_dec(int64(-1), int64(0))
		switch {
		case t_6:
			r_5 = int64(1)
		case !t_6:
			r_5 = int64(0)
		default:
			panic("gogen: no case matches")
		}
		t_7 := &I_list[int64]{tag: 0}
		t_8 := &I_list[int64]{tag: 1, f1_0: r_5, f1_1: t_7}
		t_9 := &I_list[int64]{tag: 1, f1_0: r_3, f1_1: t_8}
		t_10 := &I_list[int64]{tag: 1, f1_0: r_1, f1_1: t_9}
		return t_10
	}
}

func F_t_exn() *I_list[int64] {
	for {
		t_1 := &I_list[int64]{tag: 0}
		t_2 := &I_list[int64]{tag: 1, f1_0: int64(4), f1_1: t_1}
		t_3 := F_hd_safe(t_2)
		t_4 := &I_list[int64]{tag: 0}
		t_5 := &I_list[int64]{tag: 1, f1_0: t_3, f1_1: t_4}
		return t_5
	}
}

func F_t_mut() *I_list[bool] {
	for {
		t_1 := F_ev(int64(10))
		t_2 := F_od(int64(10))
		t_3 := F_ev(int64(7))
		t_4 := F_od(int64(7))
		t_5 := &I_list[bool]{tag: 0}
		t_6 := &I_list[bool]{tag: 1, f1_0: t_4, f1_1: t_5}
		t_7 := &I_list[bool]{tag: 1, f1_0: t_3, f1_1: t_6}
		t_8 := &I_list[bool]{tag: 1, f1_0: t_2, f1_1: t_7}
		t_9 := &I_list[bool]{tag: 1, f1_0: t_1, f1_1: t_8}
		return t_9
	}
}

func F_t_n() *I_list[int64] {
	for {
		t_1 := natSub(int64(3), int64(5))
		t_2 := nDiv(int64(17), int64(0))
		t_3 := nModulo(int64(17), int64(0))
		t_4 := nPred(int64(0))
		t_5 := F_of_nat0(int64(9))
		t_6 := F_double0(int64(21))
		t_7 := F_pow1(int64(3), int64(4))
		t_8 := &I_list[int64]{tag: 0}
		t_9 := &I_list[int64]{tag: 1, f1_0: t_7, f1_1: t_8}
		t_10 := &I_list[int64]{tag: 1, f1_0: t_6, f1_1: t_9}
		t_11 := &I_list[int64]{tag: 1, f1_0: t_5, f1_1: t_10}
		t_12 := &I_list[int64]{tag: 1, f1_0: t_4, f1_1: t_11}
		t_13 := &I_list[int64]{tag: 1, f1_0: t_3, f1_1: t_12}
		t_14 := &I_list[int64]{tag: 1, f1_0: t_2, f1_1: t_13}
		t_15 := &I_list[int64]{tag: 1, f1_0: t_1, f1_1: t_14}
		return t_15
	}
}

func F_t_nat() *I_list[int64] {
	for {
		t_1 := natSub(int64(3), int64(5))
		t_2 := nPred(int64(0))
		t_3 := F_div(int64(7), int64(2))
		t_4 := F_modulo(int64(7), int64(0))
		t_5 := F_div(int64(7), int64(0))
		t_6 := F_pow(int64(2), int64(5))
		t_7 := F_sqrt(int64(17))
		t_8 := F_log2(int64(1000))
		t_9 := &I_list[int64]{tag: 0}
		t_10 := &I_list[int64]{tag: 1, f1_0: t_8, f1_1: t_9}
		t_11 := &I_list[int64]{tag: 1, f1_0: t_7, f1_1: t_10}
		t_12 := &I_list[int64]{tag: 1, f1_0: t_6, f1_1: t_11}
		t_13 := &I_list[int64]{tag: 1, f1_0: t_5, f1_1: t_12}
		t_14 := &I_list[int64]{tag: 1, f1_0: t_4, f1_1: t_13}
		t_15 := &I_list[int64]{tag: 1, f1_0: t_3, f1_1: t_14}
		t_16 := &I_list[int64]{tag: 1, f1_0: t_2, f1_1: t_15}
		t_17 := &I_list[int64]{tag: 1, f1_0: t_1, f1_1: t_16}
		return t_17
	}
}

func F_t_opt() *I_list[int64] {
	for {
		var r_1 int64
		t_2 := &I_list[int64]{tag: 0}
		t_3 := &I_list[int64]{tag: 1, f1_0: int64(7), f1_1: t_2}
		t_4 := &I_list[int64]{tag: 1, f1_0: int64(6), f1_1: t_3}
		t_5 := &I_list[int64]{tag: 1, f1_0: int64(5), f1_1: t_4}
		t_6 := F_nth_err()(t_5)(int64(2))
		switch t_6.tag {
		case 0:
			x_7 := t_6.f0_0
			_ = x_7
			r_1 = x_7
		case 1:
			r_1 = int64(0)
		default:
			panic("gogen: no case matches")
		}
		var r_8 int64
		t_9 := &I_list[int64]{tag: 0}
		t_10 := &I_list[int64]{tag: 1, f1_0: int64(5), f1_1: t_9}
		t_11 := F_nth_err()(t_10)(int64(4))
		switch t_11.tag {
		case 0:
			x_12 := t_11.f0_0
			_ = x_12
			r_8 = x_12
		case 1:
			r_8 = int64(42)
		default:
			panic("gogen: no case matches")
		}
		t_13 := &I_list[int64]{tag: 0}
		t_14 := &I_list[int64]{tag: 1, f1_0: r_8, f1_1: t_13}
		t_15 := &I_list[int64]{tag: 1, f1_0: r_1, f1_1: t_14}
		return t_15
	}
}

func F_t_pa() *I_list[int64] {
	for {
		t_1 := F_pa()(int64(2))(int64(3))
		t_2 := F_f3(int64(4), int64(5), int64(6))
		t_7 := func(acc_3 int64) func(func(int64) func(int64) int64) int64 {
			return func(g_4 func(int64) func(int64) int64) int64 {
				_ = acc_3
				_ = g_4
				t_5 := g_4(int64(1))(int64(2))
				t_6 := zAdd(acc_3, t_5)
				return t_6
			}
		}
		t_11 := func(a_8 int64) func(int64) func(int64) int64 {
			return func(a_9 int64) func(int64) int64 {
				return func(a_10 int64) int64 {
					return F_f3(a_8, a_9, a_10)
				}
			}
		}
		t_12 := &I_list[int64]{tag: 0}
		t_13 := &I_list[int64]{tag: 1, f1_0: int64(2), f1_1: t_12}
		t_14 := &I_list[int64]{tag: 1, f1_0: int64(1), f1_1: t_13}
		t_15 := F_map[int64, func(int64) func(int64) int64](t_11, t_14)
		t_16 := F_fold_left[int64, func(int64) func(int64) int64](t_7, t_15, int64(0))
		t_17 := &I_list[int64]{tag: 0}
		t_18 := &I_list[int64]{tag: 1, f1_0: t_16, f1_1: t_17}
		t_19 := &I_list[int64]{tag: 1, f1_0: t_2, f1_1: t_18}
		t_20 := &I_list[int64]{tag: 1, f1_0: t_1, f1_1: t_19}
		return t_20
	}
}

func F_t_poly() *I_list[int64] {
	for {
		t_3 := func(x_1 int64) int64 {
			_ = x_1
			t_2 := natSucc(x_1)
			return t_2
		}
		t_4 := F_twice[int64](t_3, int64(3))
		var r_5 int64
		t_7 := func(a_6 bool) bool {
			return F_negb(a_6)
		}
		t_8 := F_twice[bool](t_7, true)
		switch {
		case t_8:
			r_5 = int64(1)
		case !t_8:
			r_5 = int64(0)
		default:
			panic("gogen: no case matches")
		}
		t_11 := func(l_9 *I_list[int64]) *I_list[int64] {
			_ = l_9
			t_10 := &I_list[int64]{tag: 1, f1_0: int64(0), f1_1: l_9}
			return t_10
		}
		t_12 := &I_list[int64]{tag: 0}
		t_13 := F_twice[*I_list[int64]](t_11, t_12)
		t_14 := F_length[int64](t_13)
		t_15 := &I_list[int64]{tag: 0}
		t_16 := &I_list[int64]{tag: 1, f1_0: t_14, f1_1: t_15}
		t_17 := &I_list[int64]{tag: 1, f1_0: r_5, f1_1: t_16}
		t_18 := &I_list[int64]{tag: 1, f1_0: t_4, f1_1: t_17}
		return t_18
	}
}

func F_t_pos() *I_list[int64] {
	for {
		t_1 := posSub(int64(3), int64(5))
		t_2 := posPred(int64(1))
		t_3 := zAdd(int64(4), int64(5))
		t_4 := zMul(int64(6), int64(7))
		t_5 := F_of_nat(int64(0))
		t_6 := F_of_succ_nat0(int64(4))
		t_7 := F_pow0(int64(2))(int64(10))
		t_8 := &I_list[int64]{tag: 0}
		t_9 := &I_list[int64]{tag: 1, f1_0: t_7, f1_1: t_8}
		t_10 := &I_list[int64]{tag: 1, f1_0: t_6, f1_1: t_9}
		t_11 := &I_list[int64]{tag: 1, f1_0: t_5, f1_1: t_10}
		t_12 := &I_list[int64]{tag: 1, f1_0: t_4, f1_1: t_11}
		t_13 := &I_list[int64]{tag: 1, f1_0: t_3, f1_1: t_12}
		t_14 := &I_list[int64]{tag: 1, f1_0: t_2, f1_1: t_13}
		t_15 := &I_list[int64]{tag: 1, f1_0: t_1, f1_1: t_14}
		return t_15
	}
}

func F_t_rec() *I_list[int64] {
	for {
		t_3 := func(x_1 int64) int64 {
			_ = x_1
			t_2 := zMul(x_1, x_1)
			return t_2
		}
		t_4 := &I_r{tag: 0, f0_0: t_3, f0_1: int64(9)}
		t_5 := F_useR(t_4)
		t_6 := &I_list[int64]{tag: 0}
		t_7 := &I_list[int64]{tag: 1, f1_0: t_5, f1_1: t_6}
		return t_7
	}
}

func F_t_shadow() *I_list[int64] {
	for {
		t_1 := F_shadow(int64(5))
		t_2 := &I_list[int64]{tag: 0}
		t_3 := &I_list[int64]{tag: 1, f1_0: t_1, f1_1: t_2}
		return t_3
	}
}

func F_t_sort() *I_list[int64] {
	for {
		t_3 := func(a_1 int64) func(*I_list[int64]) *I_list[int64] {
			return func(a_2 *I_list[int64]) *I_list[int64] {
				return F_ins(a_1, a_2)
			}
		}
		t_4 := &I_list[int64]{tag: 0}
		t_5 := &I_list[int64]{tag: 0}
		t_6 := &I_list[int64]{tag: 1, f1_0: int64(7), f1_1: t_5}
		t_7 := &I_list[int64]{tag: 1, f1_0: int64(0), f1_1: t_6}
		t_8 := &I_list[int64]{tag: 1, f1_0: int64(3), f1_1: t_7}
		t_9 := &I_list[int64]{tag: 1, f1_0: int64(1), f1_1: t_8}
		t_10 := &I_list[int64]{tag: 1, f1_0: int64(9), f1_1: t_9}
		t_11 := &I_list[int64]{tag: 1, f1_0: int64(3), f1_1: t_10}
		t_12 := &I_list[int64]{tag: 1, f1_0: int64(5), f1_1: t_11}
		t_13 := F_fold_right[*I_list[int64], int64](t_3, t_4, t_12)
		return t_13
	}
}

func F_t_swap() *I_list[int64] {
	for {
		t_1 := F_swapper(int64(7), int64(1), int64(20))
		switch t_1.tag {
		case 0:
			a_2 := t_1.f0_0
			_ = a_2
			b_3 := t_1.f0_1
			_ = b_3
			t_4 := &I_list[int64]{tag: 0}
			t_5 := &I_list[int64]{tag: 1, f1_0: b_3, f1_1: t_4}
			t_6 := &I_list[int64]{tag: 1, f1_0: a_2, f1_1: t_5}
			return t_6
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_t_unused() *I_list[int64] {
	for {
		t_1 := F_r_unused(int64(1), int64(2))
		t_2 := &I_list[int64]{tag: 0}
		t_3 := &I_list[int64]{tag: 1, f1_0: t_1, f1_1: t_2}
		return t_3
	}
}

func F_t_z() *I_list[int64] {
	for {
		t_1 := zMul(int64(4611686018427387904), int64(1))
		t_2 := zSub(int64(-4611686018427387904), int64(4611686018427387904))
		t_3 := posXI(int64(4611686018427387903))
		t_4 := zOpp(t_3)
		t_5 := zAbs(t_4)
		t_6 := posXI(int64(4611686018427387903))
		t_7 := t_6
		t_8 := zOpp(t_7)
		t_9 := F_pow2(int64(2), int64(62))
		t_10 := F_shiftl(int64(1), int64(62))
		t_11 := F_land1(int64(12), int64(10))
		t_12 := F_lor1(int64(12), int64(10))
		t_13 := F_lxor1(int64(12), int64(10))
		t_14 := &I_list[int64]{tag: 0}
		t_15 := &I_list[int64]{tag: 1, f1_0: t_13, f1_1: t_14}
		t_16 := &I_list[int64]{tag: 1, f1_0: t_12, f1_1: t_15}
		t_17 := &I_list[int64]{tag: 1, f1_0: t_11, f1_1: t_16}
		t_18 := &I_list[int64]{tag: 1, f1_0: t_10, f1_1: t_17}
		t_19 := &I_list[int64]{tag: 1, f1_0: t_9, f1_1: t_18}
		t_20 := &I_list[int64]{tag: 1, f1_0: t_8, f1_1: t_19}
		t_21 := &I_list[int64]{tag: 1, f1_0: t_5, f1_1: t_20}
		t_22 := &I_list[int64]{tag: 1, f1_0: t_2, f1_1: t_21}
		t_23 := &I_list[int64]{tag: 1, f1_0: t_1, f1_1: t_22}
		return t_23
	}
}

func F_t_zdiv() *I_list[int64] {
	for {
		t_1 := F_div0(int64(-7), int64(2))
		t_2 := F_modulo0(int64(-7), int64(2))
		t_3 := F_div0(int64(7), int64(-2))
		t_4 := F_modulo0(int64(7), int64(-2))
		t_5 := F_quot(int64(-7), int64(2))
		t_6 := F_rem(int64(-7), int64(2))
		t_7 := F_div0(int64(-7), int64(0))
		t_8 := F_modulo0(int64(-7), int64(0))
		t_9 := &I_list[int64]{tag: 0}
		t_10 := &I_list[int64]{tag: 1, f1_0: t_8, f1_1: t_9}
		t_11 := &I_list[int64]{tag: 1, f1_0: t_7, f1_1: t_10}
		t_12 := &I_list[int64]{tag: 1, f1_0: t_6, f1_1: t_11}
		t_13 := &I_list[int64]{tag: 1, f1_0: t_5, f1_1: t_12}
		t_14 := &I_list[int64]{tag: 1, f1_0: t_4, f1_1: t_13}
		t_15 := &I_list[int64]{tag: 1, f1_0: t_3, f1_1: t_14}
		t_16 := &I_list[int64]{tag: 1, f1_0: t_2, f1_1: t_15}
		t_17 := &I_list[int64]{tag: 1, f1_0: t_1, f1_1: t_16}
		return t_17
	}
}

func F_twice[T1 any](f_in func(T1) T1, x_in T1) T1 {
	for {
		f_1 := f_in
		_ = f_1
		x_2 := x_in
		_ = x_2
		t_3 := f_1(x_2)
		t_4 := f_1(t_3)
		return t_4
	}
}

func F_useR(r0_in *I_r) int64 {
	for {
		r0_1 := r0_in
		_ = r0_1
		switch r0_1.tag {
		case 0:
			rf_2 := r0_1.f0_0
			_ = rf_2
			var r_3 int64
			switch r0_1.tag {
			case 0:
				rv_4 := r0_1.f0_1
				_ = rv_4
				r_3 = rv_4
			default:
				panic("gogen: no case matches")
			}
			t_5 := rf_2(r_3)
			return t_5
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_z_lt_dec(x_in int64, y_in int64) bool {
	for {
		x_1 := x_in
		_ = x_1
		y_2 := y_in
		_ = y_2
		t_3 := compare(x_1, y_2)
		switch t_3.tag {
		case 1:
			return true
		default:
			return false
		}
	}
}

// ===== the Go meaning of ExtrGo.v's symbols (gogen prims.go) =====

const minInt64 = -1 << 63

func zAdd(a, b int64) int64 {
	r := a + b
	if (a > 0 && b > 0 && r < 0) || (a < 0 && b < 0 && r >= 0) {
		panic("gogen: int64 overflow in add")
	}
	return r
}

func zSub(a, b int64) int64 {
	r := a - b
	if (b < 0 && r < a) || (b > 0 && r > a) {
		panic("gogen: int64 overflow in sub")
	}
	return r
}

func zMul(a, b int64) int64 {
	if a == 0 || b == 0 {
		return 0
	}
	r := a * b
	if r/b != a || (a == -1 && b == minInt64) || (b == -1 && a == minInt64) {
		panic("gogen: int64 overflow in mul")
	}
	return r
}

func zOpp(a int64) int64 {
	if a == minInt64 {
		panic("gogen: int64 overflow in opp")
	}
	return -a
}

func zAbs(a int64) int64 {
	if a < 0 {
		return zOpp(a)
	}
	return a
}

func zSucc(a int64) int64   { return zAdd(a, 1) }
func zPred(a int64) int64   { return zSub(a, 1) }
func natSucc(a int64) int64 { return zAdd(a, 1) }
func posXI(p int64) int64   { return zAdd(zMul(2, p), 1) }
func posXO(p int64) int64   { return zMul(2, p) }

func natSub(a, b int64) int64 {
	if a <= b {
		return 0
	}
	return a - b
}

func posSub(a, b int64) int64 {
	if a <= b {
		return 1
	}
	return a - b
}

func posPred(a int64) int64 {
	if a <= 1 {
		return 1
	}
	return a - 1
}

func nPred(a int64) int64 {
	if a <= 0 {
		return 0
	}
	return a - 1
}

func nDiv(a, b int64) int64 {
	if b == 0 {
		return 0
	}
	return a / b
}

func nModulo(a, b int64) int64 {
	if b == 0 {
		return a
	}
	return a % b
}

func natDiv2(a int64) int64 { return a / 2 }

func min64(a, b int64) int64 {
	if a < b {
		return a
	}
	return b
}

func max64(a, b int64) int64 {
	if a > b {
		return a
	}
	return b
}

func id64(a int64) int64 { return a }

func eqb(a, b int64) bool { return a == b }

func ltb(a, b int64) bool { return a < b }

func leb(a, b int64) bool { return a <= b }

func compare(a, b int64) *I_comparison {
	if a == b {
		return C_Eq
	}
	if a < b {
		return C_Lt
	}
	return C_Gt
}

func compareCont(c *I_comparison, a, b int64) *I_comparison {
	if a == b {
		return c
	}
	return compare(a, b)
}
