// Code generated by gogen from oracle_core.json (module Main). DO NOT EDIT.

package oracle

type I_comparison struct {
	tag uint8
}

var C_Eq = &I_comparison{tag: 0}
var C_Lt = &I_comparison{tag: 1}
var C_Gt = &I_comparison{tag: 2}

// K_Eq builds the constructor Eq.
func K_Eq() *I_comparison {
	return &I_comparison{tag: 0}
}

// K_Lt builds the constructor Lt.
func K_Lt() *I_comparison {
	return &I_comparison{tag: 1}
}

// K_Gt builds the constructor Gt.
func K_Gt() *I_comparison {
	return &I_comparison{tag: 2}
}

type I_expr struct {
	tag  uint8
	f0_0 int64
	f1_0 int64
	f2_0 *I_expr
	f2_1 *I_expr
	f3_0 *I_expr
	f3_1 *I_expr
}

// K_EVar builds the constructor EVar.
func K_EVar(a0 int64) *I_expr {
	return &I_expr{tag: 0, f0_0: a0}
}

// K_ELit builds the constructor ELit.
func K_ELit(a0 int64) *I_expr {
	return &I_expr{tag: 1, f1_0: a0}
}

// K_EAdd builds the constructor EAdd.
func K_EAdd(a0 *I_expr, a1 *I_expr) *I_expr {
	return &I_expr{tag: 2, f2_0: a0, f2_1: a1}
}

// K_ESub builds the constructor ESub.
func K_ESub(a0 *I_expr, a1 *I_expr) *I_expr {
	return &I_expr{tag: 3, f3_0: a0, f3_1: a1}
}

type I_list[P_A any] struct {
	tag  uint8
	f1_0 P_A
	f1_1 *I_list[P_A]
}

// K_Nil builds the constructor Nil.
func K_Nil[P_A any]() *I_list[P_A] {
	return &I_list[P_A]{tag: 0}
}

// K_Cons builds the constructor Cons.
func K_Cons[P_A any](a0 P_A, a1 *I_list[P_A]) *I_list[P_A] {
	return &I_list[P_A]{tag: 1, f1_0: a0, f1_1: a1}
}

type I_machine struct {
	tag  uint8
	f0_0 *I_list[int64]
	f0_1 *I_list[int64]
	f0_2 *I_list[*I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]]]
	f0_3 *I_list[*I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]]]
}

// K_Build_machine builds the constructor Build_machine.
func K_Build_machine(a0 *I_list[int64], a1 *I_list[int64], a2 *I_list[*I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]]], a3 *I_list[*I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]]]) *I_machine {
	return &I_machine{tag: 0, f0_0: a0, f0_1: a1, f0_2: a2, f0_3: a3}
}

type I_option[P_A any] struct {
	tag  uint8
	f0_0 P_A
}

// K_Some builds the constructor Some.
func K_Some[P_A any](a0 P_A) *I_option[P_A] {
	return &I_option[P_A]{tag: 0, f0_0: a0}
}

// K_None builds the constructor None.
func K_None[P_A any]() *I_option[P_A] {
	return &I_option[P_A]{tag: 1}
}

type I_pred struct {
	tag  uint8
	f0_0 *I_expr
	f0_1 *I_expr
	f1_0 *I_expr
	f1_1 *I_expr
	f2_0 *I_expr
	f2_1 *I_expr
	f3_0 *I_list[*I_pred]
	f4_0 *I_list[*I_pred]
	f5_0 *I_pred
}

// K_PLe builds the constructor PLe.
func K_PLe(a0 *I_expr, a1 *I_expr) *I_pred {
	return &I_pred{tag: 0, f0_0: a0, f0_1: a1}
}

// K_PLt builds the constructor PLt.
func K_PLt(a0 *I_expr, a1 *I_expr) *I_pred {
	return &I_pred{tag: 1, f1_0: a0, f1_1: a1}
}

// K_PEq builds the constructor PEq.
func K_PEq(a0 *I_expr, a1 *I_expr) *I_pred {
	return &I_pred{tag: 2, f2_0: a0, f2_1: a1}
}

// K_PAnd builds the constructor PAnd.
func K_PAnd(a0 *I_list[*I_pred]) *I_pred {
	return &I_pred{tag: 3, f3_0: a0}
}

// K_POr builds the constructor POr.
func K_POr(a0 *I_list[*I_pred]) *I_pred {
	return &I_pred{tag: 4, f4_0: a0}
}

// K_PNot builds the constructor PNot.
func K_PNot(a0 *I_pred) *I_pred {
	return &I_pred{tag: 5, f5_0: a0}
}

type I_prod[P_A any, P_B any] struct {
	tag  uint8
	f0_0 P_A
	f0_1 P_B
}

// K_Pair builds the constructor Pair.
func K_Pair[P_A any, P_B any](a0 P_A, a1 P_B) *I_prod[P_A, P_B] {
	return &I_prod[P_A, P_B]{tag: 0, f0_0: a0, f0_1: a1}
}

type I_w16 struct {
	tag   uint8
	f0_0  int64
	f0_1  int64
	f0_2  int64
	f0_3  int64
	f0_4  int64
	f0_5  int64
	f0_6  int64
	f0_7  int64
	f0_8  int64
	f0_9  int64
	f0_10 int64
	f0_11 int64
	f0_12 int64
	f0_13 int64
	f0_14 int64
	f0_15 int64
	f1_0  *I_w16
	f1_1  *I_w16
	f1_2  *I_w16
	f1_3  *I_w16
	f1_4  *I_w16
	f1_5  *I_w16
	f1_6  *I_w16
	f1_7  *I_w16
	f1_8  *I_w16
	f1_9  *I_w16
	f1_10 *I_w16
	f1_11 *I_w16
	f1_12 *I_w16
	f1_13 *I_w16
	f1_14 *I_w16
	f1_15 *I_w16
}

// K_WL builds the constructor WL.
func K_WL(a0 int64, a1 int64, a2 int64, a3 int64, a4 int64, a5 int64, a6 int64, a7 int64, a8 int64, a9 int64, a10 int64, a11 int64, a12 int64, a13 int64, a14 int64, a15 int64) *I_w16 {
	return &I_w16{tag: 0, f0_0: a0, f0_1: a1, f0_2: a2, f0_3: a3, f0_4: a4, f0_5: a5, f0_6: a6, f0_7: a7, f0_8: a8, f0_9: a9, f0_10: a10, f0_11: a11, f0_12: a12, f0_13: a13, f0_14: a14, f0_15: a15}
}

// K_WN builds the constructor WN.
func K_WN(a0 *I_w16, a1 *I_w16, a2 *I_w16, a3 *I_w16, a4 *I_w16, a5 *I_w16, a6 *I_w16, a7 *I_w16, a8 *I_w16, a9 *I_w16, a10 *I_w16, a11 *I_w16, a12 *I_w16, a13 *I_w16, a14 *I_w16, a15 *I_w16) *I_w16 {
	return &I_w16{tag: 1, f1_0: a0, f1_1: a1, f1_2: a2, f1_3: a3, f1_4: a4, f1_5: a5, f1_6: a6, f1_7: a7, f1_8: a8, f1_9: a9, f1_10: a10, f1_11: a11, f1_12: a12, f1_13: a13, f1_14: a14, f1_15: a15}
}

type I_wt struct {
	tag  uint8
	f0_0 int64
	f0_1 int64
	f0_2 *I_w16
}

// K_Build_wt builds the constructor Build_wt.
func K_Build_wt(a0 int64, a1 int64, a2 *I_w16) *I_wt {
	return &I_wt{tag: 0, f0_0: a0, f0_1: a1, f0_2: a2}
}

func F_add(n_in int64, m_in int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		m_2 := m_in
		_ = m_2
		if n_1 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case n_1 == 0:
			return m_2
		case n_1 > 0:
			p_3 := n_1 - 1
			_ = p_3
			t_4 := F_add(p_3, m_2)
			t_5 := natSucc(t_4)
			return t_5
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_add0(x_in int64, y_in int64) int64 {
	for {
		x_1 := x_in
		_ = x_1
		y_2 := y_in
		_ = y_2
		if x_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case x_1 > 1 && x_1%2 == 1:
			p_3 := x_1 / 2
			_ = p_3
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				q_4 := y_2 / 2
				_ = q_4
				t_5 := F_add_carry(p_3, q_4)
				t_6 := posXO(t_5)
				return t_6
			case y_2 > 1 && y_2%2 == 0:
				q_7 := y_2 / 2
				_ = q_7
				t_8 := F_add0(p_3, q_7)
				t_9 := posXI(t_8)
				return t_9
			case y_2 == 1:
				t_10 := F_succ(p_3)
				t_11 := posXO(t_10)
				return t_11
			default:
				panic("gogen: no case matches")
			}
		case x_1 > 1 && x_1%2 == 0:
			p_12 := x_1 / 2
			_ = p_12
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				q_13 := y_2 / 2
				_ = q_13
				t_14 := F_add0(p_12, q_13)
				t_15 := posXI(t_14)
				return t_15
			case y_2 > 1 && y_2%2 == 0:
				q_16 := y_2 / 2
				_ = q_16
				t_17 := F_add0(p_12, q_16)
				t_18 := posXO(t_17)
				return t_18
			case y_2 == 1:
				t_19 := posXI(p_12)
				return t_19
			default:
				panic("gogen: no case matches")
			}
		case x_1 == 1:
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				q_20 := y_2 / 2
				_ = q_20
				t_21 := F_succ(q_20)
				t_22 := posXO(t_21)
				return t_22
			case y_2 > 1 && y_2%2 == 0:
				q_23 := y_2 / 2
				_ = q_23
				t_24 := posXI(q_23)
				return t_24
			case y_2 == 1:
				return int64(2)
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_add_carry(x_in int64, y_in int64) int64 {
	for {
		x_1 := x_in
		_ = x_1
		y_2 := y_in
		_ = y_2
		if x_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case x_1 > 1 && x_1%2 == 1:
			p_3 := x_1 / 2
			_ = p_3
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				q_4 := y_2 / 2
				_ = q_4
				t_5 := F_add_carry(p_3, q_4)
				t_6 := posXI(t_5)
				return t_6
			case y_2 > 1 && y_2%2 == 0:
				q_7 := y_2 / 2
				_ = q_7
				t_8 := F_add_carry(p_3, q_7)
				t_9 := posXO(t_8)
				return t_9
			case y_2 == 1:
				t_10 := F_succ(p_3)
				t_11 := posXI(t_10)
				return t_11
			default:
				panic("gogen: no case matches")
			}
		case x_1 > 1 && x_1%2 == 0:
			p_12 := x_1 / 2
			_ = p_12
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				q_13 := y_2 / 2
				_ = q_13
				t_14 := F_add_carry(p_12, q_13)
				t_15 := posXO(t_14)
				return t_15
			case y_2 > 1 && y_2%2 == 0:
				q_16 := y_2 / 2
				_ = q_16
				t_17 := F_add0(p_12, q_16)
				t_18 := posXI(t_17)
				return t_18
			case y_2 == 1:
				t_19 := F_succ(p_12)
				t_20 := posXO(t_19)
				return t_20
			default:
				panic("gogen: no case matches")
			}
		case x_1 == 1:
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				q_21 := y_2 / 2
				_ = q_21
				t_22 := F_succ(q_21)
				t_23 := posXI(t_22)
				return t_23
			case y_2 > 1 && y_2%2 == 0:
				q_24 := y_2 / 2
				_ = q_24
				t_25 := F_succ(q_24)
				t_26 := posXO(t_25)
				return t_26
			case y_2 == 1:
				return int64(3)
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_allPairs(nE_in int64) *I_list[*I_prod[int64, int64]] {
	for {
		nE_1 := nE_in
		_ = nE_1
		t_11 := func(i_2 int64) *I_list[*I_prod[int64, int64]] {
			_ = i_2
			t_5 := func(j_3 int64) *I_prod[int64, int64] {
				_ = j_3
				t_4 := &I_prod[int64, int64]{tag: 0, f0_0: i_2, f0_1: j_3}
				return t_4
			}
			t_6 := natSucc(i_2)
			t_7 := natSucc(i_2)
			t_8 := natSub(nE_1, t_7)
			t_9 := F_seq(t_6, t_8)
			t_10 := F_map[int64, *I_prod[int64, int64]](t_5, t_9)
			return t_10
		}
		t_12 := F_seq(int64(0), nE_1)
		t_13 := F_flat_map[int64, *I_prod[int64, int64]](t_11, t_12)
		return t_13
	}
}

func F_allPairsT(nE_in int64) *I_list[*I_prod[int64, int64]] {
	for {
		nE_1 := nE_in
		_ = nE_1
		t_2 := &I_list[*I_prod[int64, int64]]{tag: 0}
		t_3 := F_pairsAll(nE_1, int64(0), nE_1, t_2)
		return t_3
	}
}

func F_allValid(m_in *I_machine, s_in *I_list[int64]) bool {
	for {
		m_1 := m_in
		_ = m_1
		s_2 := s_in
		_ = s_2
		t_8 := func(inv_3 *I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]]) bool {
			_ = inv_3
			var r_4 *I_list[int64]
			switch m_1.tag {
			case 0:
				mins_5 := m_1.f0_1
				_ = mins_5
				r_4 = mins_5
			default:
				panic("gogen: no case matches")
			}
			t_6 := F_fst[*I_pred, *I_list[*I_prod[int64, *I_expr]]](inv_3)
			t_7 := F_evalP(r_4, s_2, t_6)
			return t_7
		}
		var r_9 *I_list[*I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]]]
		switch m_1.tag {
		case 0:
			invs_10 := m_1.f0_2
			_ = invs_10
			r_9 = invs_10
		default:
			panic("gogen: no case matches")
		}
		t_11 := F_forallb[*I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]]](t_8, r_9)
		return t_11
	}
}

func F_app[T1 any](l_in *I_list[T1], m_in *I_list[T1]) *I_list[T1] {
	for {
		l_1 := l_in
		_ = l_1
		m_2 := m_in
		_ = m_2
		switch l_1.tag {
		case 0:
			return m_2
		case 1:
			a_3 := l_1.f1_0
			_ = a_3
			l1_4 := l_1.f1_1
			_ = l1_4
			t_5 := F_app[T1](l1_4, m_2)
			t_6 := &I_list[T1]{tag: 1, f1_0: a_3, f1_1: t_5}
			return t_6
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_applyT(m_in *I_machine, t_in *I_list[*I_prod[int64, *I_expr]], s_in *I_list[int64]) *I_list[int64] {
	for {
		m_1 := m_in
		_ = m_1
		t_2 := t_in
		_ = t_2
		s_3 := s_in
		_ = s_3
		switch t_2.tag {
		case 0:
			return s_3
		case 1:
			a_4 := t_2.f1_0
			_ = a_4
			rest_5 := t_2.f1_1
			_ = rest_5
			switch a_4.tag {
			case 0:
				i_6 := a_4.f0_0
				_ = i_6
				e_7 := a_4.f0_1
				_ = e_7
				var r_8 *I_list[int64]
				switch m_1.tag {
				case 0:
					mins_9 := m_1.f0_1
					_ = mins_9
					r_8 = mins_9
				default:
					panic("gogen: no case matches")
				}
				t_10 := F_evalE(r_8, s_3, e_7)
				t_11 := F_setClamped(m_1, i_6, t_10, s_3)
				m_in, t_in, s_in = m_1, rest_5, t_11
				continue
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_binaryVar(m_in *I_machine, i_in int64) bool {
	for {
		m_1 := m_in
		_ = m_1
		i_2 := i_in
		_ = i_2
		var r_3 *I_list[int64]
		switch m_1.tag {
		case 0:
			doms_4 := m_1.f0_0
			_ = doms_4
			r_3 = doms_4
		default:
			panic("gogen: no case matches")
		}
		t_5 := F_nth[int64](i_2, r_3, int64(0))
		t_6 := eqb(t_5, int64(2))
		if !t_6 {
			return false
		}
		var r_7 *I_list[int64]
		switch m_1.tag {
		case 0:
			mins_8 := m_1.f0_1
			_ = mins_8
			r_7 = mins_8
		default:
			panic("gogen: no case matches")
		}
		t_9 := F_nth[int64](i_2, r_7, int64(0))
		t_10 := F_eqb0(t_9, int64(0))
		return t_10
	}
}

func F_bnd(m_in *I_machine, e_in *I_expr) int64 {
	for {
		m_1 := m_in
		_ = m_1
		e_2 := e_in
		_ = e_2
		switch e_2.tag {
		case 0:
			i_3 := e_2.f0_0
			_ = i_3
			t_4 := F_varBound(m_1, i_3)
			return t_4
		case 1:
			n_5 := e_2.f1_0
			_ = n_5
			t_6 := zAbs(n_5)
			return t_6
		case 2:
			a_7 := e_2.f2_0
			_ = a_7
			b_8 := e_2.f2_1
			_ = b_8
			t_9 := F_bnd(m_1, a_7)
			t_10 := F_bnd(m_1, b_8)
			t_11 := zAdd(t_9, t_10)
			return t_11
		case 3:
			a_12 := e_2.f3_0
			_ = a_12
			b_13 := e_2.f3_1
			_ = b_13
			t_14 := F_bnd(m_1, a_12)
			t_15 := F_bnd(m_1, b_13)
			t_16 := zAdd(t_14, t_15)
			return t_16
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_bounded(m_in *I_machine) bool {
	for {
		m_1 := m_in
		_ = m_1
		t_6 := func(e_2 *I_expr) bool {
			_ = e_2
			t_3 := F_bnd(m_1, e_2)
			t_4 := F_maxAbs()
			t_5 := F_leb(t_3, t_4)
			return t_5
		}
		t_7 := F_exprsM(m_1)
		t_8 := F_forallb[*I_expr](t_6, t_7)
		return t_8
	}
}

func F_box(ds_in *I_list[int64]) *I_list[*I_list[int64]] {
	for {
		ds_1 := ds_in
		_ = ds_1
		switch ds_1.tag {
		case 0:
			t_2 := &I_list[int64]{tag: 0}
			t_3 := &I_list[*I_list[int64]]{tag: 0}
			t_4 := &I_list[*I_list[int64]]{tag: 1, f1_0: t_2, f1_1: t_3}
			return t_4
		case 1:
			d_5 := ds_1.f1_0
			_ = d_5
			rest_6 := ds_1.f1_1
			_ = rest_6
			t_13 := func(v_7 int64) *I_list[*I_list[int64]] {
				_ = v_7
				t_10 := func(x_8 *I_list[int64]) *I_list[int64] {
					_ = x_8
					t_9 := &I_list[int64]{tag: 1, f1_0: v_7, f1_1: x_8}
					return t_9
				}
				t_11 := F_box(rest_6)
				t_12 := F_map[*I_list[int64], *I_list[int64]](t_10, t_11)
				return t_12
			}
			t_14 := F_seq(int64(0), d_5)
			t_15 := F_flat_map[int64, *I_list[int64]](t_13, t_14)
			return t_15
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_ccA(m_in *I_machine, p_in *I_option[*I_list[*I_prod[int64, int64]]]) bool {
	for {
		m_1 := m_in
		_ = m_1
		p_2 := p_in
		_ = p_2
		t_19 := func(v_3 *I_list[int64]) bool {
			_ = v_3
			t_4 := F_inDA(m_1, v_3)
			t_15 := func(p0_5 *I_prod[int64, int64]) bool {
				_ = p0_5
				t_6 := F_fst[int64, int64](p0_5)
				t_7 := F_snd[int64, int64](p0_5)
				t_8 := F_stepI(m_1, t_7, v_3)
				t_9 := F_stepI(m_1, t_6, t_8)
				t_10 := F_snd[int64, int64](p0_5)
				t_11 := F_fst[int64, int64](p0_5)
				t_12 := F_stepI(m_1, t_11, v_3)
				t_13 := F_stepI(m_1, t_10, t_12)
				t_14 := F_valeqb(t_9, t_13)
				return t_14
			}
			t_16 := F_pairsA(m_1, p_2)
			t_17 := F_forallb[*I_prod[int64, int64]](t_15, t_16)
			t_18 := F_implb(t_4, t_17)
			return t_18
		}
		var r_20 *I_list[int64]
		switch m_1.tag {
		case 0:
			doms_21 := m_1.f0_0
			_ = doms_21
			r_20 = doms_21
		default:
			panic("gogen: no case matches")
		}
		t_22 := F_box(r_20)
		t_23 := F_forallb[*I_list[int64]](t_19, t_22)
		return t_23
	}
}

func F_checkBuild(m_in *I_machine, p_in *I_option[*I_list[*I_prod[int64, int64]]]) bool {
	for {
		m_1 := m_in
		_ = m_1
		p_2 := p_in
		_ = p_2
		t_6 := F_bounded(m_1)
		b_5 := t_6
		if b_5 {
			t_7 := F_signSafe(m_1)
			b_5 = t_7
		}
		b_4 := b_5
		if b_4 {
			t_8 := F_pairsOkA(m_1, p_2)
			b_4 = t_8
		}
		b_3 := b_4
		if b_3 {
			t_9 := F_wfc(m_1)
			b_3 = t_9
		}
		if !b_3 {
			return false
		}
		t_10 := F_ccA(m_1, p_2)
		return t_10
	}
}

func F_check_fast(n_in int64, nE_in int64, nFl_in *I_list[int64], tl0_in *I_list[*I_list[int64]], p_in *I_option[*I_list[*I_prod[int64, int64]]]) bool {
	for {
		n_1 := n_in
		_ = n_1
		nE_2 := nE_in
		_ = nE_2
		nFl_3 := nFl_in
		_ = nFl_3
		tl0_4 := tl0_in
		_ = tl0_4
		p_5 := p_in
		_ = p_5
		t_6 := F_of_list16(nFl_3)
		nfw_7 := t_6
		_ = nfw_7
		t_9 := func(a_8 *I_list[int64]) *I_wt {
			return F_of_list16(a_8)
		}
		t_10 := F_mapT[*I_list[int64], *I_wt](t_9, tl0_4)
		t_11 := F_rpairsW(nE_2, t_10, p_5)
		rp_12 := t_11
		_ = rp_12
		t_13 := F_pairs_okW(nE_2, p_5)
		if !t_13 {
			return false
		}
		t_14 := F_scanW(n_1, nfw_7, rp_12, int64(0), nFl_3, tl0_4)
		return t_14
	}
}

func F_chunk[T1 any, T2 any](mk_in func(T1) func(T1) func(T1) func(T1) func(T1) func(T1) func(T1) func(T1) func(T1) func(T1) func(T1) func(T1) func(T1) func(T1) func(T1) func(T1) T2, z_in T1, l_in *I_list[T1]) *I_list[T2] {
	for {
		mk_1 := mk_in
		_ = mk_1
		z_2 := z_in
		_ = z_2
		l_3 := l_in
		_ = l_3
		t_4 := F_lenT[T1](l_3, int64(0))
		t_5 := &I_list[T2]{tag: 0}
		t_6 := F_chunkT[T1, T2](t_4, mk_1, z_2, l_3, t_5)
		return t_6
	}
}

func F_chunkT[T1 any, T2 any](f_in int64, mk_in func(T1) func(T1) func(T1) func(T1) func(T1) func(T1) func(T1) func(T1) func(T1) func(T1) func(T1) func(T1) func(T1) func(T1) func(T1) func(T1) T2, z_in T1, l_in *I_list[T1], acc_in *I_list[T2]) *I_list[T2] {
	for {
		f_1 := f_in
		_ = f_1
		mk_2 := mk_in
		_ = mk_2
		z_3 := z_in
		_ = z_3
		l_4 := l_in
		_ = l_4
		acc_5 := acc_in
		_ = acc_5
		if f_1 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case f_1 == 0:
			t_6 := &I_list[T2]{tag: 0}
			t_7 := F_rev_append[T2](acc_5, t_6)
			return t_7
		case f_1 > 0:
			f_p_8 := f_1 - 1
			_ = f_p_8
			switch l_4.tag {
			case 0:
				t_9 := &I_list[T2]{tag: 0}
				t_10 := F_rev_append[T2](acc_5, t_9)
				return t_10
			case 1:
				t_11 := F_skipn[T1](int64(16), l_4)
				t_12 := F_nth[T1](int64(0), l_4, z_3)
				t_13 := F_nth[T1](int64(1), l_4, z_3)
				t_14 := F_nth[T1](int64(2), l_4, z_3)
				t_15 := F_nth[T1](int64(3), l_4, z_3)
				t_16 := F_nth[T1](int64(4), l_4, z_3)
				t_17 := F_nth[T1](int64(5), l_4, z_3)
				t_18 := F_nth[T1](int64(6), l_4, z_3)
				t_19 := F_nth[T1](int64(7), l_4, z_3)
				t_20 := F_nth[T1](int64(8), l_4, z_3)
				t_21 := F_nth[T1](int64(9), l_4, z_3)
				t_22 := F_nth[T1](int64(10), l_4, z_3)
				t_23 := F_nth[T1](int64(11), l_4, z_3)
				t_24 := F_nth[T1](int64(12), l_4, z_3)
				t_25 := F_nth[T1](int64(13), l_4, z_3)
				t_26 := F_nth[T1](int64(14), l_4, z_3)
				t_27 := F_nth[T1](int64(15), l_4, z_3)
				t_28 := mk_2(t_12)(t_13)(t_14)(t_15)(t_16)(t_17)(t_18)(t_19)(t_20)(t_21)(t_22)(t_23)(t_24)(t_25)(t_26)(t_27)
				t_29 := &I_list[T2]{tag: 1, f1_0: t_28, f1_1: acc_5}
				f_in, mk_in, z_in, l_in, acc_in = f_p_8, mk_2, z_3, t_11, t_29
				continue
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_compare() func(int64) func(int64) *I_comparison {
	for {
		t_3 := func(a_1 int64) func(int64) *I_comparison {
			return func(a_2 int64) *I_comparison {
				return F_compare_cont(C_Eq, a_1, a_2)
			}
		}
		return t_3
	}
}

func F_compare_cont(r_in *I_comparison, x_in int64, y_in int64) *I_comparison {
	for {
		r_1 := r_in
		_ = r_1
		x_2 := x_in
		_ = x_2
		y_3 := y_in
		_ = y_3
		if x_2 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case x_2 > 1 && x_2%2 == 1:
			p_4 := x_2 / 2
			_ = p_4
			if y_3 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_3 > 1 && y_3%2 == 1:
				q_5 := y_3 / 2
				_ = q_5
				r_in, x_in, y_in = r_1, p_4, q_5
				continue
			case y_3 > 1 && y_3%2 == 0:
				q_6 := y_3 / 2
				_ = q_6
				r_in, x_in, y_in = C_Gt, p_4, q_6
				continue
			case y_3 == 1:
				return C_Gt
			default:
				panic("gogen: no case matches")
			}
		case x_2 > 1 && x_2%2 == 0:
			p_7 := x_2 / 2
			_ = p_7
			if y_3 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_3 > 1 && y_3%2 == 1:
				q_8 := y_3 / 2
				_ = q_8
				r_in, x_in, y_in = C_Lt, p_7, q_8
				continue
			case y_3 > 1 && y_3%2 == 0:
				q_9 := y_3 / 2
				_ = q_9
				r_in, x_in, y_in = r_1, p_7, q_9
				continue
			case y_3 == 1:
				return C_Gt
			default:
				panic("gogen: no case matches")
			}
		case x_2 == 1:
			if y_3 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_3 > 1 && y_3%2 == 1:
				__10 := y_3 / 2
				_ = __10
				return C_Lt
			case y_3 > 1 && y_3%2 == 0:
				__11 := y_3 / 2
				_ = __11
				return C_Lt
			case y_3 == 1:
				return r_1
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_compensationFree(m_in *I_machine) bool {
	for {
		m_1 := m_in
		_ = m_1
		t_3 := func(a_2 *I_list[int64]) bool {
			return F_allValid(m_1, a_2)
		}
		var r_4 *I_list[int64]
		switch m_1.tag {
		case 0:
			doms_5 := m_1.f0_0
			_ = doms_5
			r_4 = doms_5
		default:
			panic("gogen: no case matches")
		}
		t_6 := F_box(r_4)
		t_7 := F_forallb[*I_list[int64]](t_3, t_6)
		return t_7
	}
}

func F_depthF(f_in int64, m_in int64, p_in int64) int64 {
	for {
		f_1 := f_in
		_ = f_1
		m_2 := m_in
		_ = m_2
		p_3 := p_in
		_ = p_3
		if f_1 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case f_1 == 0:
			return int64(0)
		case f_1 > 0:
			f_p_4 := f_1 - 1
			_ = f_p_4
			t_5 := zMul(int64(16), p_3)
			t_6 := ltb(t_5, m_2)
			switch {
			case t_6:
				t_7 := zMul(int64(16), p_3)
				t_8 := F_depthF(f_p_4, m_2, t_7)
				t_9 := natSucc(t_8)
				return t_9
			case !t_6:
				return int64(0)
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_double(x_in int64) int64 {
	for {
		x_1 := x_in
		_ = x_1
		switch {
		case x_1 == 0:
			return int64(0)
		case x_1 > 0:
			p_2 := x_1
			_ = p_2
			t_3 := posXO(p_2)
			t_4 := t_3
			return t_4
		case x_1 < 0:
			p_5 := zOpp(x_1)
			_ = p_5
			t_6 := posXO(p_5)
			t_7 := zOpp(t_6)
			return t_7
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_eqb(p_in int64, q_in int64) bool {
	for {
		p_1 := p_in
		_ = p_1
		q_2 := q_in
		_ = q_2
		if p_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case p_1 > 1 && p_1%2 == 1:
			p0_3 := p_1 / 2
			_ = p0_3
			if q_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case q_2 > 1 && q_2%2 == 1:
				q0_4 := q_2 / 2
				_ = q0_4
				p_in, q_in = p0_3, q0_4
				continue
			case q_2 > 1 && q_2%2 == 0:
				__5 := q_2 / 2
				_ = __5
				return false
			case q_2 == 1:
				return false
			default:
				panic("gogen: no case matches")
			}
		case p_1 > 1 && p_1%2 == 0:
			p0_6 := p_1 / 2
			_ = p0_6
			if q_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case q_2 > 1 && q_2%2 == 1:
				__7 := q_2 / 2
				_ = __7
				return false
			case q_2 > 1 && q_2%2 == 0:
				q0_8 := q_2 / 2
				_ = q0_8
				p_in, q_in = p0_6, q0_8
				continue
			case q_2 == 1:
				return false
			default:
				panic("gogen: no case matches")
			}
		case p_1 == 1:
			if q_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case q_2 > 1 && q_2%2 == 1:
				__9 := q_2 / 2
				_ = __9
				return false
			case q_2 > 1 && q_2%2 == 0:
				__10 := q_2 / 2
				_ = __10
				return false
			case q_2 == 1:
				return true
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_eqb0(x_in int64, y_in int64) bool {
	for {
		x_1 := x_in
		_ = x_1
		y_2 := y_in
		_ = y_2
		switch {
		case x_1 == 0:
			switch {
			case y_2 == 0:
				return true
			case y_2 > 0:
				__3 := y_2
				_ = __3
				return false
			case y_2 < 0:
				__4 := zOpp(y_2)
				_ = __4
				return false
			default:
				panic("gogen: no case matches")
			}
		case x_1 > 0:
			p_5 := x_1
			_ = p_5
			switch {
			case y_2 == 0:
				return false
			case y_2 > 0:
				q_6 := y_2
				_ = q_6
				t_7 := F_eqb(p_5, q_6)
				return t_7
			case y_2 < 0:
				__8 := zOpp(y_2)
				_ = __8
				return false
			default:
				panic("gogen: no case matches")
			}
		case x_1 < 0:
			p_9 := zOpp(x_1)
			_ = p_9
			switch {
			case y_2 == 0:
				return false
			case y_2 > 0:
				__10 := y_2
				_ = __10
				return false
			case y_2 < 0:
				q_11 := zOpp(y_2)
				_ = q_11
				t_12 := F_eqb(p_9, q_11)
				return t_12
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_evAt(m_in *I_machine, e_in int64) *I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]] {
	for {
		m_1 := m_in
		_ = m_1
		e_2 := e_in
		_ = e_2
		var r_3 *I_list[*I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]]]
		switch m_1.tag {
		case 0:
			evs_4 := m_1.f0_3
			_ = evs_4
			r_3 = evs_4
		default:
			panic("gogen: no case matches")
		}
		t_5 := F_noEvent()
		t_6 := F_nth[*I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]]](e_2, r_3, t_5)
		return t_6
	}
}

func F_evalE(mins_in *I_list[int64], s_in *I_list[int64], e_in *I_expr) int64 {
	for {
		mins_1 := mins_in
		_ = mins_1
		s_2 := s_in
		_ = s_2
		e_3 := e_in
		_ = e_3
		switch e_3.tag {
		case 0:
			i_4 := e_3.f0_0
			_ = i_4
			t_5 := F_nth[int64](i_4, mins_1, int64(0))
			t_6 := F_rd(i_4, s_2)
			t_7 := F_of_nat(t_6)
			t_8 := zAdd(t_5, t_7)
			return t_8
		case 1:
			n_9 := e_3.f1_0
			_ = n_9
			return n_9
		case 2:
			a_10 := e_3.f2_0
			_ = a_10
			b_11 := e_3.f2_1
			_ = b_11
			t_12 := F_evalE(mins_1, s_2, a_10)
			t_13 := F_evalE(mins_1, s_2, b_11)
			t_14 := zAdd(t_12, t_13)
			return t_14
		case 3:
			a_15 := e_3.f3_0
			_ = a_15
			b_16 := e_3.f3_1
			_ = b_16
			t_17 := F_evalE(mins_1, s_2, a_15)
			t_18 := F_evalE(mins_1, s_2, b_16)
			t_19 := zSub(t_17, t_18)
			return t_19
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_evalP(mins_in *I_list[int64], s_in *I_list[int64], p_in *I_pred) bool {
	for {
		mins_1 := mins_in
		_ = mins_1
		s_2 := s_in
		_ = s_2
		p_3 := p_in
		_ = p_3
		switch p_3.tag {
		case 0:
			a_4 := p_3.f0_0
			_ = a_4
			b_5 := p_3.f0_1
			_ = b_5
			t_6 := F_evalE(mins_1, s_2, a_4)
			t_7 := F_evalE(mins_1, s_2, b_5)
			t_8 := F_leb(t_6, t_7)
			return t_8
		case 1:
			a_9 := p_3.f1_0
			_ = a_9
			b_10 := p_3.f1_1
			_ = b_10
			t_11 := F_evalE(mins_1, s_2, a_9)
			t_12 := F_evalE(mins_1, s_2, b_10)
			t_13 := F_ltb(t_11, t_12)
			return t_13
		case 2:
			a_14 := p_3.f2_0
			_ = a_14
			b_15 := p_3.f2_1
			_ = b_15
			t_16 := F_evalE(mins_1, s_2, a_14)
			t_17 := F_evalE(mins_1, s_2, b_15)
			t_18 := F_eqb0(t_16, t_17)
			return t_18
		case 3:
			ps_19 := p_3.f3_0
			_ = ps_19
			t_21 := func(a_20 *I_pred) bool {
				return F_evalP(mins_1, s_2, a_20)
			}
			t_22 := F_forallb[*I_pred](t_21, ps_19)
			return t_22
		case 4:
			ps_23 := p_3.f4_0
			_ = ps_23
			t_25 := func(a_24 *I_pred) bool {
				return F_evalP(mins_1, s_2, a_24)
			}
			t_26 := F_existsb[*I_pred](t_25, ps_23)
			return t_26
		case 5:
			p0_27 := p_3.f5_0
			_ = p0_27
			t_28 := F_evalP(mins_1, s_2, p0_27)
			t_29 := F_negb(t_28)
			return t_29
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_existsb[T1 any](f_in func(T1) bool, l_in *I_list[T1]) bool {
	for {
		f_1 := f_in
		_ = f_1
		l_2 := l_in
		_ = l_2
		switch l_2.tag {
		case 0:
			return false
		case 1:
			a_3 := l_2.f1_0
			_ = a_3
			l0_4 := l_2.f1_1
			_ = l0_4
			t_5 := f_1(a_3)
			switch {
			case t_5:
				return true
			case !t_5:
				f_in, l_in = f_1, l0_4
				continue
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_exprsM(m_in *I_machine) *I_list[*I_expr] {
	for {
		m_1 := m_in
		_ = m_1
		t_8 := func(inv_2 *I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]]) *I_list[*I_expr] {
			_ = inv_2
			t_3 := F_fst[*I_pred, *I_list[*I_prod[int64, *I_expr]]](inv_2)
			t_4 := F_exprsP(t_3)
			t_5 := F_snd[*I_pred, *I_list[*I_prod[int64, *I_expr]]](inv_2)
			t_6 := F_exprsT(t_5)
			t_7 := F_app[*I_expr](t_4, t_6)
			return t_7
		}
		var r_9 *I_list[*I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]]]
		switch m_1.tag {
		case 0:
			invs_10 := m_1.f0_2
			_ = invs_10
			r_9 = invs_10
		default:
			panic("gogen: no case matches")
		}
		t_11 := F_flat_map[*I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]], *I_expr](t_8, r_9)
		t_18 := func(ge_12 *I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]]) *I_list[*I_expr] {
			_ = ge_12
			t_13 := F_fst[*I_pred, *I_list[*I_prod[int64, *I_expr]]](ge_12)
			t_14 := F_exprsP(t_13)
			t_15 := F_snd[*I_pred, *I_list[*I_prod[int64, *I_expr]]](ge_12)
			t_16 := F_exprsT(t_15)
			t_17 := F_app[*I_expr](t_14, t_16)
			return t_17
		}
		var r_19 *I_list[*I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]]]
		switch m_1.tag {
		case 0:
			evs_20 := m_1.f0_3
			_ = evs_20
			r_19 = evs_20
		default:
			panic("gogen: no case matches")
		}
		t_21 := F_flat_map[*I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]], *I_expr](t_18, r_19)
		t_22 := F_app[*I_expr](t_11, t_21)
		return t_22
	}
}

func F_exprsP(p_in *I_pred) *I_list[*I_expr] {
	for {
		p_1 := p_in
		_ = p_1
		switch p_1.tag {
		case 0:
			a_2 := p_1.f0_0
			_ = a_2
			b_3 := p_1.f0_1
			_ = b_3
			t_4 := &I_list[*I_expr]{tag: 0}
			t_5 := &I_list[*I_expr]{tag: 1, f1_0: b_3, f1_1: t_4}
			t_6 := &I_list[*I_expr]{tag: 1, f1_0: a_2, f1_1: t_5}
			return t_6
		case 1:
			a_7 := p_1.f1_0
			_ = a_7
			b_8 := p_1.f1_1
			_ = b_8
			t_9 := &I_list[*I_expr]{tag: 0}
			t_10 := &I_list[*I_expr]{tag: 1, f1_0: b_8, f1_1: t_9}
			t_11 := &I_list[*I_expr]{tag: 1, f1_0: a_7, f1_1: t_10}
			return t_11
		case 2:
			a_12 := p_1.f2_0
			_ = a_12
			b_13 := p_1.f2_1
			_ = b_13
			t_14 := &I_list[*I_expr]{tag: 0}
			t_15 := &I_list[*I_expr]{tag: 1, f1_0: b_13, f1_1: t_14}
			t_16 := &I_list[*I_expr]{tag: 1, f1_0: a_12, f1_1: t_15}
			return t_16
		case 3:
			ps_17 := p_1.f3_0
			_ = ps_17
			t_19 := func(a_18 *I_pred) *I_list[*I_expr] {
				return F_exprsP(a_18)
			}
			t_20 := F_flat_map[*I_pred, *I_expr](t_19, ps_17)
			return t_20
		case 4:
			ps_21 := p_1.f4_0
			_ = ps_21
			t_23 := func(a_22 *I_pred) *I_list[*I_expr] {
				return F_exprsP(a_22)
			}
			t_24 := F_flat_map[*I_pred, *I_expr](t_23, ps_21)
			return t_24
		case 5:
			q_25 := p_1.f5_0
			_ = q_25
			p_in = q_25
			continue
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_exprsT(t_in *I_list[*I_prod[int64, *I_expr]]) *I_list[*I_expr] {
	for {
		t_1 := t_in
		_ = t_1
		t_3 := func(a_2 *I_prod[int64, *I_expr]) *I_expr {
			return F_snd[int64, *I_expr](a_2)
		}
		t_4 := F_map[*I_prod[int64, *I_expr], *I_expr](t_3, t_1)
		return t_4
	}
}

func F_find[T1 any](f_in func(T1) bool, l_in *I_list[T1]) *I_option[T1] {
	for {
		f_1 := f_in
		_ = f_1
		l_2 := l_in
		_ = l_2
		switch l_2.tag {
		case 0:
			t_3 := &I_option[T1]{tag: 1}
			return t_3
		case 1:
			x_4 := l_2.f1_0
			_ = x_4
			tl0_5 := l_2.f1_1
			_ = tl0_5
			t_6 := f_1(x_4)
			switch {
			case t_6:
				t_7 := &I_option[T1]{tag: 0, f0_0: x_4}
				return t_7
			case !t_6:
				f_in, l_in = f_1, tl0_5
				continue
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_flat_map[T1 any, T2 any](f_in func(T1) *I_list[T2], l_in *I_list[T1]) *I_list[T2] {
	for {
		f_1 := f_in
		_ = f_1
		l_2 := l_in
		_ = l_2
		switch l_2.tag {
		case 0:
			t_3 := &I_list[T2]{tag: 0}
			return t_3
		case 1:
			x_4 := l_2.f1_0
			_ = x_4
			l0_5 := l_2.f1_1
			_ = l0_5
			t_6 := f_1(x_4)
			t_7 := F_flat_map[T1, T2](f_1, l0_5)
			t_8 := F_app[T2](t_6, t_7)
			return t_8
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_fold_left[T1 any, T2 any](f_in func(T1) func(T2) T1, l_in *I_list[T2], a0_in T1) T1 {
	for {
		f_1 := f_in
		_ = f_1
		l_2 := l_in
		_ = l_2
		a0_3 := a0_in
		_ = a0_3
		switch l_2.tag {
		case 0:
			return a0_3
		case 1:
			b_4 := l_2.f1_0
			_ = b_4
			l0_5 := l_2.f1_1
			_ = l0_5
			t_6 := f_1(a0_3)(b_4)
			f_in, l_in, a0_in = f_1, l0_5, t_6
			continue
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_forallb[T1 any](f_in func(T1) bool, l_in *I_list[T1]) bool {
	for {
		f_1 := f_in
		_ = f_1
		l_2 := l_in
		_ = l_2
		switch l_2.tag {
		case 0:
			return true
		case 1:
			a_3 := l_2.f1_0
			_ = a_3
			l0_4 := l_2.f1_1
			_ = l0_4
			t_5 := f_1(a_3)
			if !t_5 {
				return false
			}
			f_in, l_in = f_1, l0_4
			continue
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_fst[T1 any, T2 any](p_in *I_prod[T1, T2]) T1 {
	for {
		p_1 := p_in
		_ = p_1
		switch p_1.tag {
		case 0:
			x_2 := p_1.f0_0
			_ = x_2
			return x_2
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_fuelOf(m_in *I_machine) int64 {
	for {
		m_1 := m_in
		_ = m_1
		t_4 := func(a_2 int64) func(int64) int64 {
			return func(a_3 int64) int64 {
				return F_mul(a_2, a_3)
			}
		}
		var r_5 *I_list[int64]
		switch m_1.tag {
		case 0:
			doms_6 := m_1.f0_0
			_ = doms_6
			r_5 = doms_6
		default:
			panic("gogen: no case matches")
		}
		t_7 := F_fold_left[int64, int64](t_4, r_5, int64(1))
		return t_7
	}
}

func F_hd[T1 any](default_in T1, l_in *I_list[T1]) T1 {
	for {
		default_1 := default_in
		_ = default_1
		l_2 := l_in
		_ = l_2
		switch l_2.tag {
		case 0:
			return default_1
		case 1:
			x_3 := l_2.f1_0
			_ = x_3
			return x_3
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_hi(m_in *I_machine, e_in *I_expr) int64 {
	for {
		m_1 := m_in
		_ = m_1
		e_2 := e_in
		_ = e_2
		switch e_2.tag {
		case 0:
			i_3 := e_2.f0_0
			_ = i_3
			var r_4 *I_list[int64]
			switch m_1.tag {
			case 0:
				mins_5 := m_1.f0_1
				_ = mins_5
				r_4 = mins_5
			default:
				panic("gogen: no case matches")
			}
			t_6 := F_nth[int64](i_3, r_4, int64(0))
			var r_7 *I_list[int64]
			switch m_1.tag {
			case 0:
				doms_8 := m_1.f0_0
				_ = doms_8
				r_7 = doms_8
			default:
				panic("gogen: no case matches")
			}
			t_9 := F_nth[int64](i_3, r_7, int64(1))
			t_10 := F_of_nat(t_9)
			t_11 := zAdd(t_6, t_10)
			t_12 := zSub(t_11, int64(1))
			return t_12
		case 1:
			n_13 := e_2.f1_0
			_ = n_13
			return n_13
		case 2:
			a_14 := e_2.f2_0
			_ = a_14
			b_15 := e_2.f2_1
			_ = b_15
			t_16 := F_hi(m_1, a_14)
			t_17 := F_hi(m_1, b_15)
			t_18 := zAdd(t_16, t_17)
			return t_18
		case 3:
			a_19 := e_2.f3_0
			_ = a_19
			b_20 := e_2.f3_1
			_ = b_20
			t_21 := F_hi(m_1, a_19)
			t_22 := F_lo(m_1, b_20)
			t_23 := zSub(t_21, t_22)
			return t_23
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_implb(b1_in bool, b2_in bool) bool {
	for {
		b1_1 := b1_in
		_ = b1_1
		b2_2 := b2_in
		_ = b2_2
		switch {
		case b1_1:
			return b2_2
		case !b1_1:
			return true
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_inDA(m_in *I_machine, v_in *I_list[int64]) bool {
	for {
		m_1 := m_in
		_ = m_1
		v_2 := v_in
		_ = v_2
		t_3 := F_allValid(m_1, v_2)
		switch {
		case t_3:
			return true
		case !t_3:
			t_4 := F_zeroV(m_1)
			t_5 := F_valeqb(v_2, t_4)
			return t_5
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_inVw(n_in int64, nfw_in *I_wt, x_in int64) bool {
	for {
		n_1 := n_in
		_ = n_1
		nfw_2 := nfw_in
		_ = nfw_2
		x_3 := x_in
		_ = x_3
		var r_4 bool
		t_5 := ltb(x_3, n_1)
		switch {
		case t_5:
			r_4 = true
		case !t_5:
			r_4 = false
		default:
			panic("gogen: no case matches")
		}
		if !r_4 {
			return false
		}
		t_6 := F_wlook(nfw_2, x_3)
		t_7 := eqb(t_6, x_3)
		return t_7
	}
}

func F_iter_op[T1 any](op_in func(T1) func(T1) T1, p_in int64, a_in T1) T1 {
	for {
		op_1 := op_in
		_ = op_1
		p_2 := p_in
		_ = p_2
		a_3 := a_in
		_ = a_3
		if p_2 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case p_2 > 1 && p_2%2 == 1:
			p0_4 := p_2 / 2
			_ = p0_4
			t_5 := op_1(a_3)(a_3)
			t_6 := F_iter_op[T1](op_1, p0_4, t_5)
			t_7 := op_1(a_3)(t_6)
			return t_7
		case p_2 > 1 && p_2%2 == 0:
			p0_8 := p_2 / 2
			_ = p0_8
			t_9 := op_1(a_3)(a_3)
			op_in, p_in, a_in = op_1, p0_8, t_9
			continue
		case p_2 == 1:
			return a_3
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_leb(x_in int64, y_in int64) bool {
	for {
		x_1 := x_in
		_ = x_1
		y_2 := y_in
		_ = y_2
		t_3 := compare(x_1, y_2)
		switch t_3.tag {
		case 2:
			return false
		default:
			return true
		}
	}
}

func F_lenT[T1 any](l_in *I_list[T1], a_in int64) int64 {
	for {
		l_1 := l_in
		_ = l_1
		a_2 := a_in
		_ = a_2
		switch l_1.tag {
		case 0:
			return a_2
		case 1:
			t_3 := l_1.f1_1
			_ = t_3
			t_4 := natSucc(a_2)
			l_in, a_in = t_3, t_4
			continue
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_length[T1 any](l_in *I_list[T1]) int64 {
	for {
		l_1 := l_in
		_ = l_1
		switch l_1.tag {
		case 0:
			return int64(0)
		case 1:
			l_p_2 := l_1.f1_1
			_ = l_p_2
			t_3 := F_length[T1](l_p_2)
			t_4 := natSucc(t_3)
			return t_4
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_levels(l_in *I_list[int64], d_in int64) *I_list[*I_w16] {
	for {
		l_1 := l_in
		_ = l_1
		d_2 := d_in
		_ = d_2
		if d_2 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case d_2 == 0:
			t_20 := func(x_3 int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) *I_w16 {
				return func(x0_4 int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) *I_w16 {
					return func(x1_5 int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) *I_w16 {
						return func(x2_6 int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) *I_w16 {
							return func(x3_7 int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) *I_w16 {
								return func(x4_8 int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) *I_w16 {
									return func(x5_9 int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) *I_w16 {
										return func(x6_10 int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) *I_w16 {
											return func(x7_11 int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) *I_w16 {
												return func(x8_12 int64) func(int64) func(int64) func(int64) func(int64) func(int64) func(int64) *I_w16 {
													return func(x9_13 int64) func(int64) func(int64) func(int64) func(int64) func(int64) *I_w16 {
														return func(x10_14 int64) func(int64) func(int64) func(int64) func(int64) *I_w16 {
															return func(x11_15 int64) func(int64) func(int64) func(int64) *I_w16 {
																return func(x12_16 int64) func(int64) func(int64) *I_w16 {
																	return func(x13_17 int64) func(int64) *I_w16 {
																		return func(x14_18 int64) *I_w16 {
																			_ = x_3
																			_ = x0_4
																			_ = x1_5
																			_ = x2_6
																			_ = x3_7
																			_ = x4_8
																			_ = x5_9
																			_ = x6_10
																			_ = x7_11
																			_ = x8_12
																			_ = x9_13
																			_ = x10_14
																			_ = x11_15
																			_ = x12_16
																			_ = x13_17
																			_ = x14_18
																			t_19 := &I_w16{tag: 0, f0_0: x_3, f0_1: x0_4, f0_2: x1_5, f0_3: x2_6, f0_4: x3_7, f0_5: x4_8, f0_6: x5_9, f0_7: x6_10, f0_8: x7_11, f0_9: x8_12, f0_10: x9_13, f0_11: x10_14, f0_12: x11_15, f0_13: x12_16, f0_14: x13_17, f0_15: x14_18}
																			return t_19
																		}
																	}
																}
															}
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
			t_21 := F_chunk[int64, *I_w16](t_20, int64(0), l_1)
			return t_21
		case d_2 > 0:
			d_p_22 := d_2 - 1
			_ = d_p_22
			t_40 := func(x_23 *I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) *I_w16 {
				return func(x0_24 *I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) *I_w16 {
					return func(x1_25 *I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) *I_w16 {
						return func(x2_26 *I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) *I_w16 {
							return func(x3_27 *I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) *I_w16 {
								return func(x4_28 *I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) *I_w16 {
									return func(x5_29 *I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) *I_w16 {
										return func(x6_30 *I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) *I_w16 {
											return func(x7_31 *I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) *I_w16 {
												return func(x8_32 *I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) *I_w16 {
													return func(x9_33 *I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) *I_w16 {
														return func(x10_34 *I_w16) func(*I_w16) func(*I_w16) func(*I_w16) func(*I_w16) *I_w16 {
															return func(x11_35 *I_w16) func(*I_w16) func(*I_w16) func(*I_w16) *I_w16 {
																return func(x12_36 *I_w16) func(*I_w16) func(*I_w16) *I_w16 {
																	return func(x13_37 *I_w16) func(*I_w16) *I_w16 {
																		return func(x14_38 *I_w16) *I_w16 {
																			_ = x_23
																			_ = x0_24
																			_ = x1_25
																			_ = x2_26
																			_ = x3_27
																			_ = x4_28
																			_ = x5_29
																			_ = x6_30
																			_ = x7_31
																			_ = x8_32
																			_ = x9_33
																			_ = x10_34
																			_ = x11_35
																			_ = x12_36
																			_ = x13_37
																			_ = x14_38
																			t_39 := &I_w16{tag: 1, f1_0: x_23, f1_1: x0_24, f1_2: x1_25, f1_3: x2_26, f1_4: x3_27, f1_5: x4_28, f1_6: x5_29, f1_7: x6_30, f1_8: x7_31, f1_9: x8_32, f1_10: x9_33, f1_11: x10_34, f1_12: x11_35, f1_13: x12_36, f1_14: x13_37, f1_15: x14_38}
																			return t_39
																		}
																	}
																}
															}
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
			t_41 := F_zt(d_p_22)
			t_42 := F_levels(l_1, d_p_22)
			t_43 := F_chunk[*I_w16, *I_w16](t_40, t_41, t_42)
			return t_43
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_lo(m_in *I_machine, e_in *I_expr) int64 {
	for {
		m_1 := m_in
		_ = m_1
		e_2 := e_in
		_ = e_2
		switch e_2.tag {
		case 0:
			i_3 := e_2.f0_0
			_ = i_3
			var r_4 *I_list[int64]
			switch m_1.tag {
			case 0:
				mins_5 := m_1.f0_1
				_ = mins_5
				r_4 = mins_5
			default:
				panic("gogen: no case matches")
			}
			t_6 := F_nth[int64](i_3, r_4, int64(0))
			return t_6
		case 1:
			n_7 := e_2.f1_0
			_ = n_7
			return n_7
		case 2:
			a_8 := e_2.f2_0
			_ = a_8
			b_9 := e_2.f2_1
			_ = b_9
			t_10 := F_lo(m_1, a_8)
			t_11 := F_lo(m_1, b_9)
			t_12 := zAdd(t_10, t_11)
			return t_12
		case 3:
			a_13 := e_2.f3_0
			_ = a_13
			b_14 := e_2.f3_1
			_ = b_14
			t_15 := F_lo(m_1, a_13)
			t_16 := F_hi(m_1, b_14)
			t_17 := zSub(t_15, t_16)
			return t_17
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_ltb(x_in int64, y_in int64) bool {
	for {
		x_1 := x_in
		_ = x_1
		y_2 := y_in
		_ = y_2
		t_3 := compare(x_1, y_2)
		switch t_3.tag {
		case 1:
			return true
		default:
			return false
		}
	}
}

func F_ltn(a_in int64, b_in int64) bool {
	for {
		a_1 := a_in
		_ = a_1
		b_2 := b_in
		_ = b_2
		t_3 := compare(a_1, b_2)
		switch t_3.tag {
		case 1:
			return true
		default:
			return false
		}
	}
}

func F_map[T1 any, T2 any](f_in func(T1) T2, l_in *I_list[T1]) *I_list[T2] {
	for {
		f_1 := f_in
		_ = f_1
		l_2 := l_in
		_ = l_2
		switch l_2.tag {
		case 0:
			t_3 := &I_list[T2]{tag: 0}
			return t_3
		case 1:
			a_4 := l_2.f1_0
			_ = a_4
			l0_5 := l_2.f1_1
			_ = l0_5
			t_6 := f_1(a_4)
			t_7 := F_map[T1, T2](f_1, l0_5)
			t_8 := &I_list[T2]{tag: 1, f1_0: t_6, f1_1: t_7}
			return t_8
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_mapA[T1 any, T2 any](f_in func(T1) T2, l_in *I_list[T1], acc_in *I_list[T2]) *I_list[T2] {
	for {
		f_1 := f_in
		_ = f_1
		l_2 := l_in
		_ = l_2
		acc_3 := acc_in
		_ = acc_3
		switch l_2.tag {
		case 0:
			t_4 := &I_list[T2]{tag: 0}
			t_5 := F_rev_append[T2](acc_3, t_4)
			return t_5
		case 1:
			x_6 := l_2.f1_0
			_ = x_6
			t_7 := l_2.f1_1
			_ = t_7
			t_8 := f_1(x_6)
			t_9 := &I_list[T2]{tag: 1, f1_0: t_8, f1_1: acc_3}
			f_in, l_in, acc_in = f_1, t_7, t_9
			continue
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_mapT[T1 any, T2 any](f_in func(T1) T2, l_in *I_list[T1]) *I_list[T2] {
	for {
		f_1 := f_in
		_ = f_1
		l_2 := l_in
		_ = l_2
		t_3 := &I_list[T2]{tag: 0}
		t_4 := F_mapA[T1, T2](f_1, l_2, t_3)
		return t_4
	}
}

func F_maxAbs() int64 {
	for {
		return int64(2147483647)
	}
}

func F_min(n_in int64, m_in int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		m_2 := m_in
		_ = m_2
		if n_1 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case n_1 == 0:
			return int64(0)
		case n_1 > 0:
			n_p_3 := n_1 - 1
			_ = n_p_3
			if m_2 < 0 {
				panic("gogen: not a nat")
			}
			switch {
			case m_2 == 0:
				return int64(0)
			case m_2 > 0:
				m_p_4 := m_2 - 1
				_ = m_p_4
				t_5 := F_min(n_p_3, m_p_4)
				t_6 := natSucc(t_5)
				return t_6
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_mul(n_in int64, m_in int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		m_2 := m_in
		_ = m_2
		if n_1 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case n_1 == 0:
			return int64(0)
		case n_1 > 0:
			p_3 := n_1 - 1
			_ = p_3
			t_4 := F_mul(p_3, m_2)
			t_5 := F_add(m_2, t_4)
			return t_5
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_negb(b_in bool) bool {
	for {
		b_1 := b_in
		_ = b_1
		switch {
		case b_1:
			return false
		case !b_1:
			return true
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_noEvent() *I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]] {
	for {
		t_1 := &I_list[*I_pred]{tag: 0}
		t_2 := &I_pred{tag: 3, f3_0: t_1}
		t_3 := &I_list[*I_prod[int64, *I_expr]]{tag: 0}
		t_4 := &I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]]{tag: 0, f0_0: t_2, f0_1: t_3}
		return t_4
	}
}

func F_normalize(m_in *I_machine, fuel_in int64, s_in *I_list[int64]) *I_list[int64] {
	for {
		m_1 := m_in
		_ = m_1
		fuel_2 := fuel_in
		_ = fuel_2
		s_3 := s_in
		_ = s_3
		if fuel_2 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case fuel_2 == 0:
			return s_3
		case fuel_2 > 0:
			f_4 := fuel_2 - 1
			_ = f_4
			t_5 := F_allValid(m_1, s_3)
			switch {
			case t_5:
				return s_3
			case !t_5:
				t_6 := F_repair1(m_1, s_3)
				m_in, fuel_in, s_in = m_1, f_4, t_6
				continue
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_nth[T1 any](n_in int64, l_in *I_list[T1], default_in T1) T1 {
	for {
		n_1 := n_in
		_ = n_1
		l_2 := l_in
		_ = l_2
		default_3 := default_in
		_ = default_3
		if n_1 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case n_1 == 0:
			switch l_2.tag {
			case 0:
				return default_3
			case 1:
				x_4 := l_2.f1_0
				_ = x_4
				return x_4
			default:
				panic("gogen: no case matches")
			}
		case n_1 > 0:
			m_5 := n_1 - 1
			_ = m_5
			switch l_2.tag {
			case 0:
				return default_3
			case 1:
				l_p_6 := l_2.f1_1
				_ = l_p_6
				n_in, l_in, default_in = m_5, l_p_6, default_3
				continue
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_of_list16(l_in *I_list[int64]) *I_wt {
	for {
		l_1 := l_in
		_ = l_1
		t_2 := F_lenT[int64](l_1, int64(0))
		m_3 := t_2
		_ = m_3
		t_4 := F_depthF(m_3, m_3, int64(1))
		d_5 := t_4
		_ = d_5
		t_6 := F_powF(m_3, m_3, int64(1))
		t_7 := F_levels(l_1, d_5)
		t_8 := F_zt(d_5)
		t_9 := F_nth[*I_w16](int64(0), t_7, t_8)
		t_10 := &I_wt{tag: 0, f0_0: d_5, f0_1: t_6, f0_2: t_9}
		return t_10
	}
}

func F_of_nat(n_in int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		if n_1 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case n_1 == 0:
			return int64(0)
		case n_1 > 0:
			n0_2 := n_1 - 1
			_ = n0_2
			t_3 := F_of_succ_nat(n0_2)
			t_4 := t_3
			return t_4
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_of_succ_nat(n_in int64) int64 {
	for {
		n_1 := n_in
		_ = n_1
		if n_1 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case n_1 == 0:
			return int64(1)
		case n_1 > 0:
			x_2 := n_1 - 1
			_ = x_2
			t_3 := F_of_succ_nat(x_2)
			t_4 := F_succ(t_3)
			return t_4
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_pairsA(m_in *I_machine, p_in *I_option[*I_list[*I_prod[int64, int64]]]) *I_list[*I_prod[int64, int64]] {
	for {
		m_1 := m_in
		_ = m_1
		p_2 := p_in
		_ = p_2
		switch p_2.tag {
		case 0:
			l_3 := p_2.f0_0
			_ = l_3
			return l_3
		case 1:
			var r_4 *I_list[*I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]]]
			switch m_1.tag {
			case 0:
				evs_5 := m_1.f0_3
				_ = evs_5
				r_4 = evs_5
			default:
				panic("gogen: no case matches")
			}
			t_6 := F_length[*I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]]](r_4)
			t_7 := F_allPairs(t_6)
			return t_7
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_pairsAll(nE_in int64, i_in int64, k_in int64, acc_in *I_list[*I_prod[int64, int64]]) *I_list[*I_prod[int64, int64]] {
	for {
		nE_1 := nE_in
		_ = nE_1
		i_2 := i_in
		_ = i_2
		k_3 := k_in
		_ = k_3
		acc_4 := acc_in
		_ = acc_4
		if k_3 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case k_3 == 0:
			return acc_4
		case k_3 > 0:
			k_p_5 := k_3 - 1
			_ = k_p_5
			t_6 := natSucc(i_2)
			t_7 := natSucc(i_2)
			t_8 := natSucc(i_2)
			t_9 := natSub(nE_1, t_8)
			t_10 := F_pairsRow(i_2, t_7, t_9, acc_4)
			nE_in, i_in, k_in, acc_in = nE_1, t_6, k_p_5, t_10
			continue
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_pairsOfT(nE_in int64, p_in *I_option[*I_list[*I_prod[int64, int64]]]) *I_list[*I_prod[int64, int64]] {
	for {
		nE_1 := nE_in
		_ = nE_1
		p_2 := p_in
		_ = p_2
		switch p_2.tag {
		case 0:
			l_3 := p_2.f0_0
			_ = l_3
			return l_3
		case 1:
			t_4 := F_allPairsT(nE_1)
			return t_4
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_pairsOkA(m_in *I_machine, p_in *I_option[*I_list[*I_prod[int64, int64]]]) bool {
	for {
		m_1 := m_in
		_ = m_1
		p_2 := p_in
		_ = p_2
		t_14 := func(p0_3 *I_prod[int64, int64]) bool {
			_ = p0_3
			t_4 := F_fst[int64, int64](p0_3)
			var r_5 *I_list[*I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]]]
			switch m_1.tag {
			case 0:
				evs_6 := m_1.f0_3
				_ = evs_6
				r_5 = evs_6
			default:
				panic("gogen: no case matches")
			}
			t_7 := F_length[*I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]]](r_5)
			t_8 := F_ltn(t_4, t_7)
			if !t_8 {
				return false
			}
			t_9 := F_snd[int64, int64](p0_3)
			var r_10 *I_list[*I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]]]
			switch m_1.tag {
			case 0:
				evs_11 := m_1.f0_3
				_ = evs_11
				r_10 = evs_11
			default:
				panic("gogen: no case matches")
			}
			t_12 := F_length[*I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]]](r_10)
			t_13 := F_ltn(t_9, t_12)
			return t_13
		}
		t_15 := F_pairsA(m_1, p_2)
		t_16 := F_forallb[*I_prod[int64, int64]](t_14, t_15)
		return t_16
	}
}

func F_pairsRow(i_in int64, j_in int64, k_in int64, acc_in *I_list[*I_prod[int64, int64]]) *I_list[*I_prod[int64, int64]] {
	for {
		i_1 := i_in
		_ = i_1
		j_2 := j_in
		_ = j_2
		k_3 := k_in
		_ = k_3
		acc_4 := acc_in
		_ = acc_4
		if k_3 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case k_3 == 0:
			return acc_4
		case k_3 > 0:
			k_p_5 := k_3 - 1
			_ = k_p_5
			t_6 := natSucc(j_2)
			t_7 := &I_prod[int64, int64]{tag: 0, f0_0: i_1, f0_1: j_2}
			t_8 := &I_list[*I_prod[int64, int64]]{tag: 1, f1_0: t_7, f1_1: acc_4}
			i_in, j_in, k_in, acc_in = i_1, t_6, k_p_5, t_8
			continue
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_pairs_okW(nE_in int64, p_in *I_option[*I_list[*I_prod[int64, int64]]]) bool {
	for {
		nE_1 := nE_in
		_ = nE_1
		p_2 := p_in
		_ = p_2
		t_9 := func(p0_3 *I_prod[int64, int64]) bool {
			_ = p0_3
			var r_4 bool
			t_5 := F_fst[int64, int64](p0_3)
			t_6 := ltb(t_5, nE_1)
			switch {
			case t_6:
				r_4 = true
			case !t_6:
				r_4 = false
			default:
				panic("gogen: no case matches")
			}
			if !r_4 {
				return false
			}
			t_7 := F_snd[int64, int64](p0_3)
			t_8 := ltb(t_7, nE_1)
			switch {
			case t_8:
				return true
			case !t_8:
				return false
			default:
				panic("gogen: no case matches")
			}
		}
		t_10 := F_pairsOfT(nE_1, p_2)
		t_11 := F_forallb[*I_prod[int64, int64]](t_9, t_10)
		return t_11
	}
}

func F_pos_sub(x_in int64, y_in int64) int64 {
	for {
		x_1 := x_in
		_ = x_1
		y_2 := y_in
		_ = y_2
		if x_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case x_1 > 1 && x_1%2 == 1:
			p_3 := x_1 / 2
			_ = p_3
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				q_4 := y_2 / 2
				_ = q_4
				t_5 := F_pos_sub(p_3, q_4)
				t_6 := F_double(t_5)
				return t_6
			case y_2 > 1 && y_2%2 == 0:
				q_7 := y_2 / 2
				_ = q_7
				t_8 := F_pos_sub(p_3, q_7)
				t_9 := F_succ_double(t_8)
				return t_9
			case y_2 == 1:
				t_10 := posXO(p_3)
				t_11 := t_10
				return t_11
			default:
				panic("gogen: no case matches")
			}
		case x_1 > 1 && x_1%2 == 0:
			p_12 := x_1 / 2
			_ = p_12
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				q_13 := y_2 / 2
				_ = q_13
				t_14 := F_pos_sub(p_12, q_13)
				t_15 := F_pred_double0(t_14)
				return t_15
			case y_2 > 1 && y_2%2 == 0:
				q_16 := y_2 / 2
				_ = q_16
				t_17 := F_pos_sub(p_12, q_16)
				t_18 := F_double(t_17)
				return t_18
			case y_2 == 1:
				t_19 := F_pred_double(p_12)
				t_20 := t_19
				return t_20
			default:
				panic("gogen: no case matches")
			}
		case x_1 == 1:
			if y_2 < 1 {
				panic("gogen: not a positive")
			}
			switch {
			case y_2 > 1 && y_2%2 == 1:
				q_21 := y_2 / 2
				_ = q_21
				t_22 := posXO(q_21)
				t_23 := zOpp(t_22)
				return t_23
			case y_2 > 1 && y_2%2 == 0:
				q_24 := y_2 / 2
				_ = q_24
				t_25 := F_pred_double(q_24)
				t_26 := zOpp(t_25)
				return t_26
			case y_2 == 1:
				return int64(0)
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_powF(f_in int64, m_in int64, p_in int64) int64 {
	for {
		f_1 := f_in
		_ = f_1
		m_2 := m_in
		_ = m_2
		p_3 := p_in
		_ = p_3
		if f_1 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case f_1 == 0:
			return p_3
		case f_1 > 0:
			f_p_4 := f_1 - 1
			_ = f_p_4
			t_5 := zMul(int64(16), p_3)
			t_6 := ltb(t_5, m_2)
			switch {
			case t_6:
				t_7 := zMul(int64(16), p_3)
				f_in, m_in, p_in = f_p_4, m_2, t_7
				continue
			case !t_6:
				return p_3
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_pred_double(x_in int64) int64 {
	for {
		x_1 := x_in
		_ = x_1
		if x_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case x_1 > 1 && x_1%2 == 1:
			p_2 := x_1 / 2
			_ = p_2
			t_3 := posXO(p_2)
			t_4 := posXI(t_3)
			return t_4
		case x_1 > 1 && x_1%2 == 0:
			p_5 := x_1 / 2
			_ = p_5
			t_6 := F_pred_double(p_5)
			t_7 := posXI(t_6)
			return t_7
		case x_1 == 1:
			return int64(1)
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_pred_double0(x_in int64) int64 {
	for {
		x_1 := x_in
		_ = x_1
		switch {
		case x_1 == 0:
			return int64(-1)
		case x_1 > 0:
			p_2 := x_1
			_ = p_2
			t_3 := F_pred_double(p_2)
			t_4 := t_3
			return t_4
		case x_1 < 0:
			p_5 := zOpp(x_1)
			_ = p_5
			t_6 := posXI(p_5)
			t_7 := zOpp(t_6)
			return t_7
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_rd(i_in int64, s_in *I_list[int64]) int64 {
	for {
		i_1 := i_in
		_ = i_1
		s_2 := s_in
		_ = s_2
		switch s_2.tag {
		case 0:
			return int64(0)
		case 1:
			x_3 := s_2.f1_0
			_ = x_3
			t_4 := s_2.f1_1
			_ = t_4
			if i_1 < 0 {
				panic("gogen: not a nat")
			}
			switch {
			case i_1 == 0:
				return x_3
			case i_1 > 0:
				i_p_5 := i_1 - 1
				_ = i_p_5
				i_in, s_in = i_p_5, t_4
				continue
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_repair1(m_in *I_machine, s_in *I_list[int64]) *I_list[int64] {
	for {
		m_1 := m_in
		_ = m_1
		s_2 := s_in
		_ = s_2
		t_9 := func(inv_3 *I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]]) bool {
			_ = inv_3
			var r_4 *I_list[int64]
			switch m_1.tag {
			case 0:
				mins_5 := m_1.f0_1
				_ = mins_5
				r_4 = mins_5
			default:
				panic("gogen: no case matches")
			}
			t_6 := F_fst[*I_pred, *I_list[*I_prod[int64, *I_expr]]](inv_3)
			t_7 := F_evalP(r_4, s_2, t_6)
			t_8 := F_negb(t_7)
			return t_8
		}
		var r_10 *I_list[*I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]]]
		switch m_1.tag {
		case 0:
			invs_11 := m_1.f0_2
			_ = invs_11
			r_10 = invs_11
		default:
			panic("gogen: no case matches")
		}
		t_12 := F_find[*I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]]](t_9, r_10)
		switch t_12.tag {
		case 0:
			inv_13 := t_12.f0_0
			_ = inv_13
			t_14 := F_snd[*I_pred, *I_list[*I_prod[int64, *I_expr]]](inv_13)
			t_15 := F_applyT(m_1, t_14, s_2)
			return t_15
		case 1:
			return s_2
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_repeat[T1 any](x_in T1, n_in int64) *I_list[T1] {
	for {
		x_1 := x_in
		_ = x_1
		n_2 := n_in
		_ = n_2
		if n_2 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case n_2 == 0:
			t_3 := &I_list[T1]{tag: 0}
			return t_3
		case n_2 > 0:
			k_4 := n_2 - 1
			_ = k_4
			t_5 := F_repeat[T1](x_1, k_4)
			t_6 := &I_list[T1]{tag: 1, f1_0: x_1, f1_1: t_5}
			return t_6
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_rev_append[T1 any](l_in *I_list[T1], l_p_in *I_list[T1]) *I_list[T1] {
	for {
		l_1 := l_in
		_ = l_1
		l_p_2 := l_p_in
		_ = l_p_2
		switch l_1.tag {
		case 0:
			return l_p_2
		case 1:
			a_3 := l_1.f1_0
			_ = a_3
			l0_4 := l_1.f1_1
			_ = l0_4
			t_5 := &I_list[T1]{tag: 1, f1_0: a_3, f1_1: l_p_2}
			l_in, l_p_in = l0_4, t_5
			continue
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_rpairsW(nE_in int64, tw_in *I_list[*I_wt], p_in *I_option[*I_list[*I_prod[int64, int64]]]) *I_list[*I_prod[*I_prod[*I_prod[int64, int64], *I_wt], *I_wt]] {
	for {
		nE_1 := nE_in
		_ = nE_1
		tw_2 := tw_in
		_ = tw_2
		p_3 := p_in
		_ = p_3
		t_18 := func(p0_4 *I_prod[int64, int64]) *I_prod[*I_prod[*I_prod[int64, int64], *I_wt], *I_wt] {
			_ = p0_4
			t_5 := F_fst[int64, int64](p0_4)
			t_6 := F_snd[int64, int64](p0_4)
			t_7 := &I_prod[int64, int64]{tag: 0, f0_0: t_5, f0_1: t_6}
			t_8 := F_fst[int64, int64](p0_4)
			t_9 := &I_list[int64]{tag: 0}
			t_10 := F_of_list16(t_9)
			t_11 := F_nth[*I_wt](t_8, tw_2, t_10)
			t_12 := &I_prod[*I_prod[int64, int64], *I_wt]{tag: 0, f0_0: t_7, f0_1: t_11}
			t_13 := F_snd[int64, int64](p0_4)
			t_14 := &I_list[int64]{tag: 0}
			t_15 := F_of_list16(t_14)
			t_16 := F_nth[*I_wt](t_13, tw_2, t_15)
			t_17 := &I_prod[*I_prod[*I_prod[int64, int64], *I_wt], *I_wt]{tag: 0, f0_0: t_12, f0_1: t_16}
			return t_17
		}
		t_19 := F_pairsOfT(nE_1, p_3)
		t_20 := F_mapT[*I_prod[int64, int64], *I_prod[*I_prod[*I_prod[int64, int64], *I_wt], *I_wt]](t_18, t_19)
		return t_20
	}
}

func F_scanW(n_in int64, nfw_in *I_wt, rp_in *I_list[*I_prod[*I_prod[*I_prod[int64, int64], *I_wt], *I_wt]], s_in int64, nfl_in *I_list[int64], rows_in *I_list[*I_list[int64]]) bool {
	for {
		n_1 := n_in
		_ = n_1
		nfw_2 := nfw_in
		_ = nfw_2
		rp_3 := rp_in
		_ = rp_3
		s_4 := s_in
		_ = s_4
		nfl_5 := nfl_in
		_ = nfl_5
		rows_6 := rows_in
		_ = rows_6
		switch nfl_5.tag {
		case 0:
			return true
		case 1:
			x_7 := nfl_5.f1_0
			_ = x_7
			t_8 := nfl_5.f1_1
			_ = t_8
			t_10 := func(a_9 *I_list[int64]) int64 {
				return F_hd[int64](int64(0), a_9)
			}
			t_11 := F_mapT[*I_list[int64], int64](t_10, rows_6)
			t_12 := F_state_okW(n_1, nfw_2, rp_3, s_4, x_7, t_11)
			if !t_12 {
				return false
			}
			t_13 := natSucc(s_4)
			t_15 := func(a_14 *I_list[int64]) *I_list[int64] {
				return F_tl[int64](a_14)
			}
			t_16 := F_mapT[*I_list[int64], *I_list[int64]](t_15, rows_6)
			n_in, nfw_in, rp_in, s_in, nfl_in, rows_in = n_1, nfw_2, rp_3, t_13, t_8, t_16
			continue
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_seq(start_in int64, len_in int64) *I_list[int64] {
	for {
		start_1 := start_in
		_ = start_1
		len_2 := len_in
		_ = len_2
		if len_2 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case len_2 == 0:
			t_3 := &I_list[int64]{tag: 0}
			return t_3
		case len_2 > 0:
			len0_4 := len_2 - 1
			_ = len0_4
			t_5 := natSucc(start_1)
			t_6 := F_seq(t_5, len0_4)
			t_7 := &I_list[int64]{tag: 1, f1_0: start_1, f1_1: t_6}
			return t_7
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_setClamped(m_in *I_machine, i_in int64, v_in int64, s_in *I_list[int64]) *I_list[int64] {
	for {
		m_1 := m_in
		_ = m_1
		i_2 := i_in
		_ = i_2
		v_3 := v_in
		_ = v_3
		s_4 := s_in
		_ = s_4
		var r_5 *I_list[int64]
		switch m_1.tag {
		case 0:
			mins_6 := m_1.f0_1
			_ = mins_6
			r_5 = mins_6
		default:
			panic("gogen: no case matches")
		}
		t_7 := F_nth[int64](i_2, r_5, int64(0))
		t_8 := zSub(v_3, t_7)
		t_9 := F_to_nat0(t_8)
		var r_10 *I_list[int64]
		switch m_1.tag {
		case 0:
			doms_11 := m_1.f0_0
			_ = doms_11
			r_10 = doms_11
		default:
			panic("gogen: no case matches")
		}
		t_12 := F_nth[int64](i_2, r_10, int64(1))
		t_13 := natSub(t_12, int64(1))
		t_14 := F_min(t_9, t_13)
		t_15 := F_wr(i_2, t_14, s_4)
		return t_15
	}
}

func F_signSafe(m_in *I_machine) bool {
	for {
		m_1 := m_in
		_ = m_1
		t_3 := func(a_2 *I_list[*I_prod[int64, *I_expr]]) bool {
			return F_signSafeT(m_1, a_2)
		}
		t_4 := F_transformsM(m_1)
		t_5 := F_forallb[*I_list[*I_prod[int64, *I_expr]]](t_3, t_4)
		return t_5
	}
}

func F_signSafeT(m_in *I_machine, t_in *I_list[*I_prod[int64, *I_expr]]) bool {
	for {
		m_1 := m_in
		_ = m_1
		t_2 := t_in
		_ = t_2
		t_10 := func(a_3 *I_prod[int64, *I_expr]) bool {
			_ = a_3
			t_4 := F_fst[int64, *I_expr](a_3)
			t_5 := F_binaryVar(m_1, t_4)
			t_6 := F_snd[int64, *I_expr](a_3)
			t_7 := F_lo(m_1, t_6)
			t_8 := F_leb(int64(0), t_7)
			t_9 := F_implb(t_5, t_8)
			return t_9
		}
		t_11 := F_forallb[*I_prod[int64, *I_expr]](t_10, t_2)
		return t_11
	}
}

func F_skipn[T1 any](n_in int64, l_in *I_list[T1]) *I_list[T1] {
	for {
		n_1 := n_in
		_ = n_1
		l_2 := l_in
		_ = l_2
		if n_1 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case n_1 == 0:
			return l_2
		case n_1 > 0:
			n0_3 := n_1 - 1
			_ = n0_3
			switch l_2.tag {
			case 0:
				t_4 := &I_list[T1]{tag: 0}
				return t_4
			case 1:
				l0_5 := l_2.f1_1
				_ = l0_5
				n_in, l_in = n0_3, l0_5
				continue
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_snd[T1 any, T2 any](p_in *I_prod[T1, T2]) T2 {
	for {
		p_1 := p_in
		_ = p_1
		switch p_1.tag {
		case 0:
			y_2 := p_1.f0_1
			_ = y_2
			return y_2
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_state_okW(n_in int64, nfw_in *I_wt, rp_in *I_list[*I_prod[*I_prod[*I_prod[int64, int64], *I_wt], *I_wt]], s_in int64, nfs_in int64, col_in *I_list[int64]) bool {
	for {
		n_1 := n_in
		_ = n_1
		nfw_2 := nfw_in
		_ = nfw_2
		rp_3 := rp_in
		_ = rp_3
		s_4 := s_in
		_ = s_4
		nfs_5 := nfs_in
		_ = nfs_5
		col_6 := col_in
		_ = col_6
		t_8 := F_inVw(n_1, nfw_2, nfs_5)
		b_7 := t_8
		if b_7 {
			t_10 := func(a_9 int64) bool {
				return F_inVw(n_1, nfw_2, a_9)
			}
			t_11 := F_forallb[int64](t_10, col_6)
			b_7 = t_11
		}
		if !b_7 {
			return false
		}
		var r_13 bool
		t_14 := ltb(s_4, n_1)
		switch {
		case t_14:
			r_13 = true
		case !t_14:
			r_13 = false
		default:
			panic("gogen: no case matches")
		}
		b_12 := r_13
		if b_12 {
			var r_15 bool
			t_16 := eqb(nfs_5, s_4)
			switch {
			case t_16:
				r_15 = true
			case !t_16:
				t_17 := eqb(s_4, int64(0))
				r_15 = t_17
			default:
				panic("gogen: no case matches")
			}
			b_12 = r_15
		}
		t_30 := func(q_18 *I_prod[*I_prod[*I_prod[int64, int64], *I_wt], *I_wt]) bool {
			_ = q_18
			switch q_18.tag {
			case 0:
				y_19 := q_18.f0_0
				_ = y_19
				tb_20 := q_18.f0_1
				_ = tb_20
				switch y_19.tag {
				case 0:
					y0_21 := y_19.f0_0
					_ = y0_21
					ta_22 := y_19.f0_1
					_ = ta_22
					switch y0_21.tag {
					case 0:
						a_23 := y0_21.f0_0
						_ = a_23
						b_24 := y0_21.f0_1
						_ = b_24
						t_25 := F_nth[int64](b_24, col_6, int64(0))
						t_26 := F_wlook(ta_22, t_25)
						t_27 := F_nth[int64](a_23, col_6, int64(0))
						t_28 := F_wlook(tb_20, t_27)
						t_29 := eqb(t_26, t_28)
						return t_29
					default:
						panic("gogen: no case matches")
					}
				default:
					panic("gogen: no case matches")
				}
			default:
				panic("gogen: no case matches")
			}
		}
		t_31 := F_forallb[*I_prod[*I_prod[*I_prod[int64, int64], *I_wt], *I_wt]](t_30, rp_3)
		t_32 := F_implb(b_12, t_31)
		return t_32
	}
}

func F_stepG(m_in *I_machine, ge_in *I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]], s_in *I_list[int64]) *I_list[int64] {
	for {
		m_1 := m_in
		_ = m_1
		ge_2 := ge_in
		_ = ge_2
		s_3 := s_in
		_ = s_3
		t_4 := F_fuelOf(m_1)
		var r_5 *I_list[int64]
		var r_6 *I_list[int64]
		switch m_1.tag {
		case 0:
			mins_7 := m_1.f0_1
			_ = mins_7
			r_6 = mins_7
		default:
			panic("gogen: no case matches")
		}
		t_8 := F_fst[*I_pred, *I_list[*I_prod[int64, *I_expr]]](ge_2)
		t_9 := F_evalP(r_6, s_3, t_8)
		switch {
		case t_9:
			t_10 := F_snd[*I_pred, *I_list[*I_prod[int64, *I_expr]]](ge_2)
			t_11 := F_applyT(m_1, t_10, s_3)
			r_5 = t_11
		case !t_9:
			r_5 = s_3
		default:
			panic("gogen: no case matches")
		}
		t_12 := F_normalize(m_1, t_4, r_5)
		return t_12
	}
}

func F_stepI(m_in *I_machine, e_in int64, s_in *I_list[int64]) *I_list[int64] {
	for {
		m_1 := m_in
		_ = m_1
		e_2 := e_in
		_ = e_2
		s_3 := s_in
		_ = s_3
		t_4 := F_evAt(m_1, e_2)
		t_5 := F_stepG(m_1, t_4, s_3)
		return t_5
	}
}

func F_succ(x_in int64) int64 {
	for {
		x_1 := x_in
		_ = x_1
		if x_1 < 1 {
			panic("gogen: not a positive")
		}
		switch {
		case x_1 > 1 && x_1%2 == 1:
			p_2 := x_1 / 2
			_ = p_2
			t_3 := F_succ(p_2)
			t_4 := posXO(t_3)
			return t_4
		case x_1 > 1 && x_1%2 == 0:
			p_5 := x_1 / 2
			_ = p_5
			t_6 := posXI(p_5)
			return t_6
		case x_1 == 1:
			return int64(2)
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_succ_double(x_in int64) int64 {
	for {
		x_1 := x_in
		_ = x_1
		switch {
		case x_1 == 0:
			return int64(1)
		case x_1 > 0:
			p_2 := x_1
			_ = p_2
			t_3 := posXI(p_2)
			t_4 := t_3
			return t_4
		case x_1 < 0:
			p_5 := zOpp(x_1)
			_ = p_5
			t_6 := F_pred_double(p_5)
			t_7 := zOpp(t_6)
			return t_7
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_tl[T1 any](l_in *I_list[T1]) *I_list[T1] {
	for {
		l_1 := l_in
		_ = l_1
		switch l_1.tag {
		case 0:
			t_2 := &I_list[T1]{tag: 0}
			return t_2
		case 1:
			l_p_3 := l_1.f1_1
			_ = l_p_3
			return l_p_3
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_to_nat(x_in int64) int64 {
	for {
		x_1 := x_in
		_ = x_1
		t_4 := func(a_2 int64) func(int64) int64 {
			return func(a_3 int64) int64 {
				return zAdd(a_2, a_3)
			}
		}
		t_5 := F_iter_op[int64](t_4, x_1, int64(1))
		return t_5
	}
}

func F_to_nat0(z_in int64) int64 {
	for {
		z_1 := z_in
		_ = z_1
		switch {
		case z_1 == 0:
			return int64(0)
		case z_1 > 0:
			p_2 := z_1
			_ = p_2
			t_3 := F_to_nat(p_2)
			return t_3
		case z_1 < 0:
			__4 := zOpp(z_1)
			_ = __4
			return int64(0)
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_transformsM(m_in *I_machine) *I_list[*I_list[*I_prod[int64, *I_expr]]] {
	for {
		m_1 := m_in
		_ = m_1
		t_3 := func(a_2 *I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]]) *I_list[*I_prod[int64, *I_expr]] {
			return F_snd[*I_pred, *I_list[*I_prod[int64, *I_expr]]](a_2)
		}
		var r_4 *I_list[*I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]]]
		switch m_1.tag {
		case 0:
			invs_5 := m_1.f0_2
			_ = invs_5
			r_4 = invs_5
		default:
			panic("gogen: no case matches")
		}
		t_6 := F_map[*I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]], *I_list[*I_prod[int64, *I_expr]]](t_3, r_4)
		t_8 := func(a_7 *I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]]) *I_list[*I_prod[int64, *I_expr]] {
			return F_snd[*I_pred, *I_list[*I_prod[int64, *I_expr]]](a_7)
		}
		var r_9 *I_list[*I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]]]
		switch m_1.tag {
		case 0:
			evs_10 := m_1.f0_3
			_ = evs_10
			r_9 = evs_10
		default:
			panic("gogen: no case matches")
		}
		t_11 := F_map[*I_prod[*I_pred, *I_list[*I_prod[int64, *I_expr]]], *I_list[*I_prod[int64, *I_expr]]](t_8, r_9)
		t_12 := F_app[*I_list[*I_prod[int64, *I_expr]]](t_6, t_11)
		return t_12
	}
}

func F_valeqb(a_in *I_list[int64], b_in *I_list[int64]) bool {
	for {
		a_1 := a_in
		_ = a_1
		b_2 := b_in
		_ = b_2
		switch a_1.tag {
		case 0:
			switch b_2.tag {
			case 0:
				return true
			case 1:
				return false
			default:
				panic("gogen: no case matches")
			}
		case 1:
			x_3 := a_1.f1_0
			_ = x_3
			xs_4 := a_1.f1_1
			_ = xs_4
			switch b_2.tag {
			case 0:
				return false
			case 1:
				y_5 := b_2.f1_0
				_ = y_5
				ys_6 := b_2.f1_1
				_ = ys_6
				t_7 := eqb(x_3, y_5)
				if !t_7 {
					return false
				}
				a_in, b_in = xs_4, ys_6
				continue
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_varBound(m_in *I_machine, i_in int64) int64 {
	for {
		m_1 := m_in
		_ = m_1
		i_2 := i_in
		_ = i_2
		var r_3 *I_list[int64]
		switch m_1.tag {
		case 0:
			mins_4 := m_1.f0_1
			_ = mins_4
			r_3 = mins_4
		default:
			panic("gogen: no case matches")
		}
		t_5 := F_nth[int64](i_2, r_3, int64(0))
		t_6 := zAbs(t_5)
		var r_7 *I_list[int64]
		switch m_1.tag {
		case 0:
			mins_8 := m_1.f0_1
			_ = mins_8
			r_7 = mins_8
		default:
			panic("gogen: no case matches")
		}
		t_9 := F_nth[int64](i_2, r_7, int64(0))
		var r_10 *I_list[int64]
		switch m_1.tag {
		case 0:
			doms_11 := m_1.f0_0
			_ = doms_11
			r_10 = doms_11
		default:
			panic("gogen: no case matches")
		}
		t_12 := F_nth[int64](i_2, r_10, int64(0))
		t_13 := F_of_nat(t_12)
		t_14 := zAdd(t_9, t_13)
		t_15 := zSub(t_14, int64(1))
		t_16 := zAbs(t_15)
		t_17 := max64(t_6, t_16)
		return t_17
	}
}

func F_wfc(m_in *I_machine) bool {
	for {
		m_1 := m_in
		_ = m_1
		t_6 := func(v_2 *I_list[int64]) bool {
			_ = v_2
			t_3 := F_fuelOf(m_1)
			t_4 := F_normalize(m_1, t_3, v_2)
			t_5 := F_allValid(m_1, t_4)
			return t_5
		}
		var r_7 *I_list[int64]
		switch m_1.tag {
		case 0:
			doms_8 := m_1.f0_0
			_ = doms_8
			r_7 = doms_8
		default:
			panic("gogen: no case matches")
		}
		t_9 := F_box(r_7)
		t_10 := F_forallb[*I_list[int64]](t_6, t_9)
		return t_10
	}
}

func F_wget(p_in int64, b_in int64, t_in *I_w16, k_in int64) int64 {
	for {
		p_1 := p_in
		_ = p_1
		b_2 := b_in
		_ = b_2
		t_3 := t_in
		_ = t_3
		k_4 := k_in
		_ = k_4
		switch t_3.tag {
		case 0:
			x0_5 := t_3.f0_0
			_ = x0_5
			x1_6 := t_3.f0_1
			_ = x1_6
			x2_7 := t_3.f0_2
			_ = x2_7
			x3_8 := t_3.f0_3
			_ = x3_8
			x4_9 := t_3.f0_4
			_ = x4_9
			x5_10 := t_3.f0_5
			_ = x5_10
			x6_11 := t_3.f0_6
			_ = x6_11
			x7_12 := t_3.f0_7
			_ = x7_12
			x8_13 := t_3.f0_8
			_ = x8_13
			x9_14 := t_3.f0_9
			_ = x9_14
			x10_15 := t_3.f0_10
			_ = x10_15
			x11_16 := t_3.f0_11
			_ = x11_16
			x12_17 := t_3.f0_12
			_ = x12_17
			x13_18 := t_3.f0_13
			_ = x13_18
			x14_19 := t_3.f0_14
			_ = x14_19
			x15_20 := t_3.f0_15
			_ = x15_20
			t_21 := zMul(int64(8), int64(1))
			t_22 := zAdd(b_2, t_21)
			t_23 := ltb(k_4, t_22)
			switch {
			case t_23:
				t_24 := zMul(int64(4), int64(1))
				t_25 := zAdd(b_2, t_24)
				t_26 := ltb(k_4, t_25)
				switch {
				case t_26:
					t_27 := zMul(int64(2), int64(1))
					t_28 := zAdd(b_2, t_27)
					t_29 := ltb(k_4, t_28)
					switch {
					case t_29:
						t_30 := zMul(int64(1), int64(1))
						t_31 := zAdd(b_2, t_30)
						t_32 := ltb(k_4, t_31)
						switch {
						case t_32:
							return x0_5
						case !t_32:
							return x1_6
						default:
							panic("gogen: no case matches")
						}
					case !t_29:
						t_33 := zMul(int64(3), int64(1))
						t_34 := zAdd(b_2, t_33)
						t_35 := ltb(k_4, t_34)
						switch {
						case t_35:
							return x2_7
						case !t_35:
							return x3_8
						default:
							panic("gogen: no case matches")
						}
					default:
						panic("gogen: no case matches")
					}
				case !t_26:
					t_36 := zMul(int64(6), int64(1))
					t_37 := zAdd(b_2, t_36)
					t_38 := ltb(k_4, t_37)
					switch {
					case t_38:
						t_39 := zMul(int64(5), int64(1))
						t_40 := zAdd(b_2, t_39)
						t_41 := ltb(k_4, t_40)
						switch {
						case t_41:
							return x4_9
						case !t_41:
							return x5_10
						default:
							panic("gogen: no case matches")
						}
					case !t_38:
						t_42 := zMul(int64(7), int64(1))
						t_43 := zAdd(b_2, t_42)
						t_44 := ltb(k_4, t_43)
						switch {
						case t_44:
							return x6_11
						case !t_44:
							return x7_12
						default:
							panic("gogen: no case matches")
						}
					default:
						panic("gogen: no case matches")
					}
				default:
					panic("gogen: no case matches")
				}
			case !t_23:
				t_45 := zMul(int64(12), int64(1))
				t_46 := zAdd(b_2, t_45)
				t_47 := ltb(k_4, t_46)
				switch {
				case t_47:
					t_48 := zMul(int64(10), int64(1))
					t_49 := zAdd(b_2, t_48)
					t_50 := ltb(k_4, t_49)
					switch {
					case t_50:
						t_51 := zMul(int64(9), int64(1))
						t_52 := zAdd(b_2, t_51)
						t_53 := ltb(k_4, t_52)
						switch {
						case t_53:
							return x8_13
						case !t_53:
							return x9_14
						default:
							panic("gogen: no case matches")
						}
					case !t_50:
						t_54 := zMul(int64(11), int64(1))
						t_55 := zAdd(b_2, t_54)
						t_56 := ltb(k_4, t_55)
						switch {
						case t_56:
							return x10_15
						case !t_56:
							return x11_16
						default:
							panic("gogen: no case matches")
						}
					default:
						panic("gogen: no case matches")
					}
				case !t_47:
					t_57 := zMul(int64(14), int64(1))
					t_58 := zAdd(b_2, t_57)
					t_59 := ltb(k_4, t_58)
					switch {
					case t_59:
						t_60 := zMul(int64(13), int64(1))
						t_61 := zAdd(b_2, t_60)
						t_62 := ltb(k_4, t_61)
						switch {
						case t_62:
							return x12_17
						case !t_62:
							return x13_18
						default:
							panic("gogen: no case matches")
						}
					case !t_59:
						t_63 := zMul(int64(15), int64(1))
						t_64 := zAdd(b_2, t_63)
						t_65 := ltb(k_4, t_64)
						switch {
						case t_65:
							return x14_19
						case !t_65:
							return x15_20
						default:
							panic("gogen: no case matches")
						}
					default:
						panic("gogen: no case matches")
					}
				default:
					panic("gogen: no case matches")
				}
			default:
				panic("gogen: no case matches")
			}
		case 1:
			c0_66 := t_3.f1_0
			_ = c0_66
			c1_67 := t_3.f1_1
			_ = c1_67
			c2_68 := t_3.f1_2
			_ = c2_68
			c3_69 := t_3.f1_3
			_ = c3_69
			c4_70 := t_3.f1_4
			_ = c4_70
			c5_71 := t_3.f1_5
			_ = c5_71
			c6_72 := t_3.f1_6
			_ = c6_72
			c7_73 := t_3.f1_7
			_ = c7_73
			c8_74 := t_3.f1_8
			_ = c8_74
			c9_75 := t_3.f1_9
			_ = c9_75
			c10_76 := t_3.f1_10
			_ = c10_76
			c11_77 := t_3.f1_11
			_ = c11_77
			c12_78 := t_3.f1_12
			_ = c12_78
			c13_79 := t_3.f1_13
			_ = c13_79
			c14_80 := t_3.f1_14
			_ = c14_80
			c15_81 := t_3.f1_15
			_ = c15_81
			t_82 := zMul(int64(8), p_1)
			t_83 := zAdd(b_2, t_82)
			t_84 := ltb(k_4, t_83)
			switch {
			case t_84:
				t_85 := zMul(int64(4), p_1)
				t_86 := zAdd(b_2, t_85)
				t_87 := ltb(k_4, t_86)
				switch {
				case t_87:
					t_88 := zMul(int64(2), p_1)
					t_89 := zAdd(b_2, t_88)
					t_90 := ltb(k_4, t_89)
					switch {
					case t_90:
						t_91 := zMul(int64(1), p_1)
						t_92 := zAdd(b_2, t_91)
						t_93 := ltb(k_4, t_92)
						switch {
						case t_93:
							t_94 := natDiv2(p_1)
							t_95 := natDiv2(t_94)
							t_96 := natDiv2(t_95)
							t_97 := natDiv2(t_96)
							t_98 := zMul(int64(0), p_1)
							t_99 := zAdd(b_2, t_98)
							p_in, b_in, t_in, k_in = t_97, t_99, c0_66, k_4
							continue
						case !t_93:
							t_100 := natDiv2(p_1)
							t_101 := natDiv2(t_100)
							t_102 := natDiv2(t_101)
							t_103 := natDiv2(t_102)
							t_104 := zMul(int64(1), p_1)
							t_105 := zAdd(b_2, t_104)
							p_in, b_in, t_in, k_in = t_103, t_105, c1_67, k_4
							continue
						default:
							panic("gogen: no case matches")
						}
					case !t_90:
						t_106 := zMul(int64(3), p_1)
						t_107 := zAdd(b_2, t_106)
						t_108 := ltb(k_4, t_107)
						switch {
						case t_108:
							t_109 := natDiv2(p_1)
							t_110 := natDiv2(t_109)
							t_111 := natDiv2(t_110)
							t_112 := natDiv2(t_111)
							t_113 := zMul(int64(2), p_1)
							t_114 := zAdd(b_2, t_113)
							p_in, b_in, t_in, k_in = t_112, t_114, c2_68, k_4
							continue
						case !t_108:
							t_115 := natDiv2(p_1)
							t_116 := natDiv2(t_115)
							t_117 := natDiv2(t_116)
							t_118 := natDiv2(t_117)
							t_119 := zMul(int64(3), p_1)
							t_120 := zAdd(b_2, t_119)
							p_in, b_in, t_in, k_in = t_118, t_120, c3_69, k_4
							continue
						default:
							panic("gogen: no case matches")
						}
					default:
						panic("gogen: no case matches")
					}
				case !t_87:
					t_121 := zMul(int64(6), p_1)
					t_122 := zAdd(b_2, t_121)
					t_123 := ltb(k_4, t_122)
					switch {
					case t_123:
						t_124 := zMul(int64(5), p_1)
						t_125 := zAdd(b_2, t_124)
						t_126 := ltb(k_4, t_125)
						switch {
						case t_126:
							t_127 := natDiv2(p_1)
							t_128 := natDiv2(t_127)
							t_129 := natDiv2(t_128)
							t_130 := natDiv2(t_129)
							t_131 := zMul(int64(4), p_1)
							t_132 := zAdd(b_2, t_131)
							p_in, b_in, t_in, k_in = t_130, t_132, c4_70, k_4
							continue
						case !t_126:
							t_133 := natDiv2(p_1)
							t_134 := natDiv2(t_133)
							t_135 := natDiv2(t_134)
							t_136 := natDiv2(t_135)
							t_137 := zMul(int64(5), p_1)
							t_138 := zAdd(b_2, t_137)
							p_in, b_in, t_in, k_in = t_136, t_138, c5_71, k_4
							continue
						default:
							panic("gogen: no case matches")
						}
					case !t_123:
						t_139 := zMul(int64(7), p_1)
						t_140 := zAdd(b_2, t_139)
						t_141 := ltb(k_4, t_140)
						switch {
						case t_141:
							t_142 := natDiv2(p_1)
							t_143 := natDiv2(t_142)
							t_144 := natDiv2(t_143)
							t_145 := natDiv2(t_144)
							t_146 := zMul(int64(6), p_1)
							t_147 := zAdd(b_2, t_146)
							p_in, b_in, t_in, k_in = t_145, t_147, c6_72, k_4
							continue
						case !t_141:
							t_148 := natDiv2(p_1)
							t_149 := natDiv2(t_148)
							t_150 := natDiv2(t_149)
							t_151 := natDiv2(t_150)
							t_152 := zMul(int64(7), p_1)
							t_153 := zAdd(b_2, t_152)
							p_in, b_in, t_in, k_in = t_151, t_153, c7_73, k_4
							continue
						default:
							panic("gogen: no case matches")
						}
					default:
						panic("gogen: no case matches")
					}
				default:
					panic("gogen: no case matches")
				}
			case !t_84:
				t_154 := zMul(int64(12), p_1)
				t_155 := zAdd(b_2, t_154)
				t_156 := ltb(k_4, t_155)
				switch {
				case t_156:
					t_157 := zMul(int64(10), p_1)
					t_158 := zAdd(b_2, t_157)
					t_159 := ltb(k_4, t_158)
					switch {
					case t_159:
						t_160 := zMul(int64(9), p_1)
						t_161 := zAdd(b_2, t_160)
						t_162 := ltb(k_4, t_161)
						switch {
						case t_162:
							t_163 := natDiv2(p_1)
							t_164 := natDiv2(t_163)
							t_165 := natDiv2(t_164)
							t_166 := natDiv2(t_165)
							t_167 := zMul(int64(8), p_1)
							t_168 := zAdd(b_2, t_167)
							p_in, b_in, t_in, k_in = t_166, t_168, c8_74, k_4
							continue
						case !t_162:
							t_169 := natDiv2(p_1)
							t_170 := natDiv2(t_169)
							t_171 := natDiv2(t_170)
							t_172 := natDiv2(t_171)
							t_173 := zMul(int64(9), p_1)
							t_174 := zAdd(b_2, t_173)
							p_in, b_in, t_in, k_in = t_172, t_174, c9_75, k_4
							continue
						default:
							panic("gogen: no case matches")
						}
					case !t_159:
						t_175 := zMul(int64(11), p_1)
						t_176 := zAdd(b_2, t_175)
						t_177 := ltb(k_4, t_176)
						switch {
						case t_177:
							t_178 := natDiv2(p_1)
							t_179 := natDiv2(t_178)
							t_180 := natDiv2(t_179)
							t_181 := natDiv2(t_180)
							t_182 := zMul(int64(10), p_1)
							t_183 := zAdd(b_2, t_182)
							p_in, b_in, t_in, k_in = t_181, t_183, c10_76, k_4
							continue
						case !t_177:
							t_184 := natDiv2(p_1)
							t_185 := natDiv2(t_184)
							t_186 := natDiv2(t_185)
							t_187 := natDiv2(t_186)
							t_188 := zMul(int64(11), p_1)
							t_189 := zAdd(b_2, t_188)
							p_in, b_in, t_in, k_in = t_187, t_189, c11_77, k_4
							continue
						default:
							panic("gogen: no case matches")
						}
					default:
						panic("gogen: no case matches")
					}
				case !t_156:
					t_190 := zMul(int64(14), p_1)
					t_191 := zAdd(b_2, t_190)
					t_192 := ltb(k_4, t_191)
					switch {
					case t_192:
						t_193 := zMul(int64(13), p_1)
						t_194 := zAdd(b_2, t_193)
						t_195 := ltb(k_4, t_194)
						switch {
						case t_195:
							t_196 := natDiv2(p_1)
							t_197 := natDiv2(t_196)
							t_198 := natDiv2(t_197)
							t_199 := natDiv2(t_198)
							t_200 := zMul(int64(12), p_1)
							t_201 := zAdd(b_2, t_200)
							p_in, b_in, t_in, k_in = t_199, t_201, c12_78, k_4
							continue
						case !t_195:
							t_202 := natDiv2(p_1)
							t_203 := natDiv2(t_202)
							t_204 := natDiv2(t_203)
							t_205 := natDiv2(t_204)
							t_206 := zMul(int64(13), p_1)
							t_207 := zAdd(b_2, t_206)
							p_in, b_in, t_in, k_in = t_205, t_207, c13_79, k_4
							continue
						default:
							panic("gogen: no case matches")
						}
					case !t_192:
						t_208 := zMul(int64(15), p_1)
						t_209 := zAdd(b_2, t_208)
						t_210 := ltb(k_4, t_209)
						switch {
						case t_210:
							t_211 := natDiv2(p_1)
							t_212 := natDiv2(t_211)
							t_213 := natDiv2(t_212)
							t_214 := natDiv2(t_213)
							t_215 := zMul(int64(14), p_1)
							t_216 := zAdd(b_2, t_215)
							p_in, b_in, t_in, k_in = t_214, t_216, c14_80, k_4
							continue
						case !t_210:
							t_217 := natDiv2(p_1)
							t_218 := natDiv2(t_217)
							t_219 := natDiv2(t_218)
							t_220 := natDiv2(t_219)
							t_221 := zMul(int64(15), p_1)
							t_222 := zAdd(b_2, t_221)
							p_in, b_in, t_in, k_in = t_220, t_222, c15_81, k_4
							continue
						default:
							panic("gogen: no case matches")
						}
					default:
						panic("gogen: no case matches")
					}
				default:
					panic("gogen: no case matches")
				}
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_wlook(t_in *I_wt, k_in int64) int64 {
	for {
		t_1 := t_in
		_ = t_1
		k_2 := k_in
		_ = k_2
		var r_3 int64
		switch t_1.tag {
		case 0:
			wp_4 := t_1.f0_1
			_ = wp_4
			r_3 = wp_4
		default:
			panic("gogen: no case matches")
		}
		t_5 := zMul(int64(16), r_3)
		t_6 := ltb(k_2, t_5)
		switch {
		case t_6:
			var r_7 int64
			switch t_1.tag {
			case 0:
				wp_8 := t_1.f0_1
				_ = wp_8
				r_7 = wp_8
			default:
				panic("gogen: no case matches")
			}
			var r_9 *I_w16
			switch t_1.tag {
			case 0:
				wroot_10 := t_1.f0_2
				_ = wroot_10
				r_9 = wroot_10
			default:
				panic("gogen: no case matches")
			}
			t_11 := F_wget(r_7, int64(0), r_9, k_2)
			return t_11
		case !t_6:
			return int64(0)
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_wr(i_in int64, v_in int64, s_in *I_list[int64]) *I_list[int64] {
	for {
		i_1 := i_in
		_ = i_1
		v_2 := v_in
		_ = v_2
		s_3 := s_in
		_ = s_3
		switch s_3.tag {
		case 0:
			t_4 := &I_list[int64]{tag: 0}
			return t_4
		case 1:
			x_5 := s_3.f1_0
			_ = x_5
			t_6 := s_3.f1_1
			_ = t_6
			if i_1 < 0 {
				panic("gogen: not a nat")
			}
			switch {
			case i_1 == 0:
				t_7 := &I_list[int64]{tag: 1, f1_0: v_2, f1_1: t_6}
				return t_7
			case i_1 > 0:
				i_p_8 := i_1 - 1
				_ = i_p_8
				t_9 := F_wr(i_p_8, v_2, t_6)
				t_10 := &I_list[int64]{tag: 1, f1_0: x_5, f1_1: t_9}
				return t_10
			default:
				panic("gogen: no case matches")
			}
		default:
			panic("gogen: no case matches")
		}
	}
}

func F_zeroV(m_in *I_machine) *I_list[int64] {
	for {
		m_1 := m_in
		_ = m_1
		var r_2 *I_list[int64]
		switch m_1.tag {
		case 0:
			doms_3 := m_1.f0_0
			_ = doms_3
			r_2 = doms_3
		default:
			panic("gogen: no case matches")
		}
		t_4 := F_length[int64](r_2)
		t_5 := F_repeat[int64](int64(0), t_4)
		return t_5
	}
}

func F_zt(d_in int64) *I_w16 {
	for {
		d_1 := d_in
		_ = d_1
		if d_1 < 0 {
			panic("gogen: not a nat")
		}
		switch {
		case d_1 == 0:
			t_2 := &I_w16{tag: 0, f0_0: int64(0), f0_1: int64(0), f0_2: int64(0), f0_3: int64(0), f0_4: int64(0), f0_5: int64(0), f0_6: int64(0), f0_7: int64(0), f0_8: int64(0), f0_9: int64(0), f0_10: int64(0), f0_11: int64(0), f0_12: int64(0), f0_13: int64(0), f0_14: int64(0), f0_15: int64(0)}
			return t_2
		case d_1 > 0:
			d_p_3 := d_1 - 1
			_ = d_p_3
			t_4 := F_zt(d_p_3)
			z_5 := t_4
			_ = z_5
			t_6 := &I_w16{tag: 1, f1_0: z_5, f1_1: z_5, f1_2: z_5, f1_3: z_5, f1_4: z_5, f1_5: z_5, f1_6: z_5, f1_7: z_5, f1_8: z_5, f1_9: z_5, f1_10: z_5, f1_11: z_5, f1_12: z_5, f1_13: z_5, f1_14: z_5, f1_15: z_5}
			return t_6
		default:
			panic("gogen: no case matches")
		}
	}
}

// ===== the Go meaning of ExtrGo.v's symbols (gogen prims.go) =====

const minInt64 = -1 << 63

func zAdd(a, b int64) int64 {
	r := a + b
	if (a > 0 && b > 0 && r < 0) || (a < 0 && b < 0 && r >= 0) {
		panic("gogen: int64 overflow in add")
	}
	return r
}

func zSub(a, b int64) int64 {
	r := a - b
	if (b < 0 && r < a) || (b > 0 && r > a) {
		panic("gogen: int64 overflow in sub")
	}
	return r
}

func zMul(a, b int64) int64 {
	if a == 0 || b == 0 {
		return 0
	}
	r := a * b
	if r/b != a || (a == -1 && b == minInt64) || (b == -1 && a == minInt64) {
		panic("gogen: int64 overflow in mul")
	}
	return r
}

func zOpp(a int64) int64 {
	if a == minInt64 {
		panic("gogen: int64 overflow in opp")
	}
	return -a
}

func zAbs(a int64) int64 {
	if a < 0 {
		return zOpp(a)
	}
	return a
}

func zSucc(a int64) int64   { return zAdd(a, 1) }
func zPred(a int64) int64   { return zSub(a, 1) }
func natSucc(a int64) int64 { return zAdd(a, 1) }
func posXI(p int64) int64   { return zAdd(zMul(2, p), 1) }
func posXO(p int64) int64   { return zMul(2, p) }

func natSub(a, b int64) int64 {
	if a <= b {
		return 0
	}
	return a - b
}

func posSub(a, b int64) int64 {
	if a <= b {
		return 1
	}
	return a - b
}

func posPred(a int64) int64 {
	if a <= 1 {
		return 1
	}
	return a - 1
}

func nPred(a int64) int64 {
	if a <= 0 {
		return 0
	}
	return a - 1
}

func nDiv(a, b int64) int64 {
	if b == 0 {
		return 0
	}
	return a / b
}

func nModulo(a, b int64) int64 {
	if b == 0 {
		return a
	}
	return a % b
}

func natDiv2(a int64) int64 { return a / 2 }

func min64(a, b int64) int64 {
	if a < b {
		return a
	}
	return b
}

func max64(a, b int64) int64 {
	if a > b {
		return a
	}
	return b
}

func id64(a int64) int64 { return a }

func eqb(a, b int64) bool { return a == b }

func ltb(a, b int64) bool { return a < b }

func leb(a, b int64) bool { return a <= b }

func compare(a, b int64) *I_comparison {
	if a == b {
		return C_Eq
	}
	if a < b {
		return C_Lt
	}
	return C_Gt
}

func compareCont(c *I_comparison, a, b int64) *I_comparison {
	if a == b {
		return c
	}
	return compare(a, b)
}
